### ISSUE TITLE
error on make /usr install - ton of missing command errors

### ISSUE THREAD

**Issue by volumetricsteve** [bbidulock/icewm#100]
Crux 3.2 X86-64 linux 4.4.30

I got it built with your new version (thank you) and now i'm installing but a get a ton of errors on commands missing:

make[1]: sgml2html: Command not found
make[1]: [Makefile:647: icewm.html] Error 127 (ignored)
sgml2html icewm.sgml
make[1]: sgml2html: Command not found
make[1]: [Makefile:647: icewm-1.html] Error 127 (ignored)
sgml2html icewm.sgml
make[1]: sgml2html: Command not found
make[1]: [Makefile:647: icewm-2.html] Error 127 (ignored)
sgml2html icewm.sgml

...

this behavior continues through to the end:

make[2]: [Makefile:647: icewm-20.html] Error 127 (ignored)
 /bin/mkdir -p '/usr//usr/share/doc/icewm'
 /usr/bin/install -c -m 644 icewm.sgml techinfo.sgml ./icewm.html ./icewm-1.html ./icewm-2.html ./icewm-3.html ./icewm-4.html ./icewm-5.html ./icewm-6.html ./icewm-7.html ./icewm-8.html ./icewm-9.html ./icewm-10.html ./icewm-11.html ./icewm-12.html ./icewm-13.html ./icewm-14.html ./icewm-15.html ./icewm-16.html ./icewm-17.html ./icewm-18.html ./icewm-19.html ./icewm-20.html '/usr//usr/share/doc/icewm'
/usr/bin/install: cannot stat './icewm.html': No such file or directory
/usr/bin/install: cannot stat './icewm-1.html': No such file or directory
/usr/bin/install: cannot stat './icewm-2.html': No such file or directory
/usr/bin/install: cannot stat './icewm-3.html': No such file or directory
/usr/bin/install: cannot stat './icewm-4.html': No such file or directory
/usr/bin/install: cannot stat './icewm-5.html': No such file or directory
/usr/bin/install: cannot stat './icewm-6.html': No such file or directory
/usr/bin/install: cannot stat './icewm-7.html': No such file or directory
/usr/bin/install: cannot stat './icewm-8.html': No such file or directory
/usr/bin/install: cannot stat './icewm-9.html': No such file or directory
/usr/bin/install: cannot stat './icewm-10.html': No such file or directory
/usr/bin/install: cannot stat './icewm-11.html': No such file or directory
/usr/bin/install: cannot stat './icewm-12.html': No such file or directory
/usr/bin/install: cannot stat './icewm-13.html': No such file or directory
/usr/bin/install: cannot stat './icewm-14.html': No such file or directory
/usr/bin/install: cannot stat './icewm-15.html': No such file or directory
/usr/bin/install: cannot stat './icewm-16.html': No such file or directory
/usr/bin/install: cannot stat './icewm-17.html': No such file or directory
/usr/bin/install: cannot stat './icewm-18.html': No such file or directory
/usr/bin/install: cannot stat './icewm-19.html': No such file or directory
/usr/bin/install: cannot stat './icewm-20.html': No such file or directory
make[2]: *** [Makefile:465: install-dist_docDATA] Error 1
make[2]: Leaving directory '/root/sources/icewm-icewm-1-3-BRANCH/doc'
make[1]: *** [Makefile:534: install-am] Error 2
make[1]: Leaving directory '/root/sources/icewm-icewm-1-3-BRANCH/doc'
make: *** [Makefile:573: install-recursive] Error 1

It did look like some of the earlier stuff copied correctly, just not these items.
Anything else I should try?

**Comment by Code7R** [comment]
@bbidulock We cannot blame the user because INSTALL file is just a boilerplate and does not mention the actual requirements (like linuxdoc-tools here). Should I start writing a specific version?

**Comment by volumetricsteve** [comment]
I noticed that the INSTALL file was the same as 1.3.8's so I figured something was missing.

I should also mention, perhaps in another bug report, that what DID install seems to work, but it's glitchy.  My buttons in the upper right of each window look like fragmented chunks of whatever was left in vram from the cpu core monitor that's in the bar at the bottom of the screen by default.  I can proudly report, however, that this version of IceWM seems to have fixed the weird mouse/keyboard input issue I was having in some games.

**Comment by bbidulock** [comment]
@Code7R  I added dependencies to README.md.  You can go ahead and update the INSTALL and INSTALL.cmakebuild files.  The autoconf/automake version checks for the tools and libraries required to compile from the tarball; however, some additional tools are required to build from git.  One is linuxdoc-tools (for sgml2html).  The html help files are included in the tarball release so there is no need for ./configure to have it to install from tarball release.  Another one is xorg-mkfontdir which is required by the install-theme.sh script but unnecessary I believe for building from tarball, even though ./configure checks for the mkfondir command.  Not sure about cmake.  I suppose I could check for a .git directory and then invoke checks for sgml2html and markdown in configure.ac when it exists.

We are a bout 141 commits away from 1.3.12, so I was thinking of releaseing a 1.3.13 (but I don't like the 13 number, so I might skip to 1.3.14).  Is there anything outstanding that should be addressed before release?

**Comment by bbidulock** [comment]
With commit, above, autoconf build will complain more loudly about missing programs during the build but will only fail the build if they are invoked (such as sgml2html missing during a git build).  @Code7R is there an equivalent for cmake?

**Comment by bbidulock** [comment]
Now you will get an error like:

    make[1]: Leaving directory '/u2/custompkgs/ubs/icewm-git/working'
    /bin/sh /u2/custompkgs/ubs/icewm-git/working/scripts/missing sgml2thml icewm.sgml
    /u2/custompkgs/ubs/icewm-git/working/scripts/missing: line 81: sgml2thml: command not found
    WARNING: 'sgml2thml' is missing on your system.
             You might have modified some files without having the proper
             tools for further handling them.  Check the 'README' file, it
             often tells you about the needed prerequisites for installing
             this package.  You may also peek at any GNU archive site, in
             case some other package contains this missing 'sgml2thml' program.
    make: *** [Makefile:648: icewm.html] Error 127

Yes, I spelt sgml2html wrong on purpose to test this.

**Comment by bbidulock** [comment]
Has this resolved the issue?  Can we close it now?

**Comment by volumetricsteve** [comment]
It resolved that one issue I guess, I still get a boatload of errors, I just ignore them and install...and it mostly works, I still have the other bugs where it looks like it's grabbing garbage data and putting it into the 'icons' for the buttons that go into the upper right of each window.

**Comment by bbidulock** [comment]
Please report other issues under another issue number.
