### ISSUE TITLE
IceWM fresh install issues

### ISSUE THREAD

**Issue by volumetricsteve** [bbidulock/icewm#101]
On a fresh install of my OS (Crux linux x86_64) I compiled and installed your flavor of icewm before installing any other window manager.  It appears several icons are missing from the default install, including the icewm icon that usually goes in the lower left, the normal upper right window icons, and the default button that launches an xterm window.

**Comment by bbidulock** [comment]
It pretty much assumes that you have a basic freedesktop.org icon set (after all it uses gdk-pixbuf); but the start button on the taskbar (if that is what you are referring to) should be shipped with the theme.  Which theme are you using?

**Comment by volumetricsteve** [comment]
To answer "which theme am I using" I don't know.  All I'm doing is compiling from source and installing.  At no point do I select or configure a theme.  Maybe that is, itself, the issue?  I'm playing by old icewm rules of "make, make install, done" more or less.

**Comment by bbidulock** [comment]
Which version are you building?  What options are you giving to ./configure?  You should try 1.3.12 release.  Also, when I build for Arch Linux I use:

    ./configure --prefix=/usr --sysconfdir=/etc \
        --enable-shaped-decorations --enable-gradients \
        --enable-guievents  --with-icesound=ALSA,OSS \
        --disable-menus-gnome2
    make V=0

**Comment by volumetricsteve** [comment]
If that's what you have in the readme, that's what I configure with.  I believe I'm using the 1.3.12 version, I'm downloading the latest zip from github.

**Comment by volumetricsteve** [comment]
for experimentation's sake, i'm recompiling now with exactly the options you posted.

**Comment by volumetricsteve** [comment]
I just recompiled and reinstalled using your options, and I'm still seeing the same garbage data behavior.  I've noticed now that if I drag a window around and it intersects with the icons in question, it kinda "hall of mirrors" over the space of the buttons in the upper right of each window.

Edit:

I've confirmed I have gdk-pixbuf installed, so whatever icons it's supposed to dig up by default should be there I guess.

**Comment by volumetricsteve** [comment]
I still can't get screenshots to work, but this should actually be better to see it in action:
https://youtu.be/UMGwQb9rdxs

**Comment by bbidulock** [comment]
Perhaps the problems are with unstated dependencies: many distros provide base packages that are quite extensive.  Often those base dependencies can be missed and manifest some problems when minimalist distributions are used such as Crux.

**Comment by volumetricsteve** [comment]
i wondered if that was a possibility, though how can it compile and run
without some dependencies present, and past that, how could i try and
discover what those dependencies might be?

On Feb 13, 2017 11:00 AM, "Brian Bidulock" <notifications@github.com> wrote:

Perhaps the problems are with unstated dependencies: many distros provide
base packages that are quite extensive. Often those base dependencies can
be missed and manifest some problems when minimalist distributions are used
such as Crux.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bbidulock/icewm/issues/101#issuecomment-279434877>, or mute
the thread

**Comment by gijsbers** [comment]
It very much depends on the theme used. And especially the options missing in the default.theme file. Some older themes don't have the Look specified. In combination with the ShowMenuButtonIcon option (default is true) the above behavior is possible. Therefore either experiment with the Look option and try setting ShowMenuButtonIcon=0. It would be most relevant to learn the theme you used.

**Comment by bbidulock** [comment]
@volumetricsteve are you still having problems on Crux?

**Comment by bbidulock** [comment]
I assume this issue is resolved (or unresolvable).
