### ISSUE TITLE
Some english menu strings i would like to translate

### ISSUE THREAD

**Issue by scootergrisen** [bbidulock/icewm#106]
I am updating a translation for IceWM.

When click the desktop i get a menu with some english strings like:
```
_Applications
_System
_Utilities
_Toolbar
_Desktop Apps
```

I would like to translate them but i don't see them in the po file.

**Comment by bbidulock** [comment]
Those strings are part of the menu file.  There are utilities that will generate the menu file from .desktop files installed on the system (resplendent with the translations contained in those files).  I don't think that it is necessary to i18n the default menu file given the availability of those tools.

**Comment by scootergrisen** [comment]
Can you mention some of the utilities that can be used.

**Comment by Code7R** [comment]
@scootergrisen Are you using Debian or Ubuntu? There is a little gap in the chain of translations. Everything behind "Desktop Apps" and "_Programs" is covered either by XDG or Debian translation stuff. But the main menu is basically data file installed with icewm which is not translated at all.

Not sure how to resolve this on long term. We would need some trick to roll the upper part of 
/usr/share/icewm/menu as input into the translation process and then again have some method to splice the l10n-specific output with regular menu data. Not sure how to achieve this in a smooth way (yet).

**Comment by scootergrisen** [comment]
I use Debian but i work on making danish language better to use/better translated across all kinds of distributions.
Do you have link for where i can see translations for XDG and Debian stuff that can be translated?

**Comment by bbidulock** [comment]
I wrote [xde-menu](/bbidulock/xde-menu) that can be used to generate menus for icewm (and a dozen or so other light-weight window managers) from XDG .desktop files.  I use it with the menus and fallback .desktop files contained in the [xde-helpers](/bbidulock/xde-helpers) package.

**Comment by bbidulock** [comment]
If you are interested in those, also consider the [xdg-launch](/bbidulock/xdg-launch) program that the menu program can use to launch .desktop applications with proper startup notification.

**Comment by scootergrisen** [comment]
I can try the tools.
But my intension is to translate everything in the menus so that all users can have it translated in future releases not just for my self.

**Comment by bbidulock** [comment]
There is also the icewm-menu-fdo utility that ships with icewm.

**Comment by bbidulock** [comment]
Has this issue been resolved?

**Comment by bbidulock** [comment]
I assume that his issue is resolved.
