### ISSUE TITLE
Tell to translate the desktop files

### ISSUE THREAD

**Issue by scootergrisen** [bbidulock/icewm#110]
I see there are these two files that can be translated:
lib/icewm-session.desktop
lib/icewm.desktop

Perhaps these files could be mentioned in the Translation section so people know they have to translate them alone with the po file.
Or perhaps the strings could be but in the po file and the desktop files could be created by extracting strings from the po file?

**Comment by bbidulock** [comment]
Now mentioned in README

Not sure whether WebLate can handle .desktop files...

**Comment by scootergrisen** [comment]
Thanks.
