### ISSUE TITLE
autogen.sh fails on Xenial

### ISSUE THREAD

**Issue by exebook** [bbidulock/icewm#129]
```
$ ./autogen.sh 
fatal: No names found, cannot describe anything.
autoreconf: Entering directory `.'
autoreconf: running: autopoint
autoreconf: running: aclocal -I m4
configure.ac:23: error: AC_INIT should be called with package and version arguments
/usr/share/aclocal-1.15/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:23: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1

```

**Comment by exebook** [comment]
I found something on Internet, the issue is probably due to Ubuntu having a newer version of `autoreconf` that the one supported by the configure script.

**Comment by exebook** [comment]
OK, I recloned and it suddenly worked.

**Comment by bbidulock** [comment]
The
    fatal: No names found, cannot describe anything.
is being issued by this line from autogen.sh:
    git describe --tags
When you clone the git repository, make sure that you clone it with tags included and you won't have a problem.

Whoo.  You found it before I could send....
