### ISSUE TITLE
tint2 black background when using compositing

### ISSUE THREAD

**Issue by gensenio** [bbidulock/icewm#130]
i use icemw and compton if i start titn2 i get black background instead real transparency

**Comment by bbidulock** [comment]
icewm does not have compositor support.  See COMPLIANCE.

**Comment by bbidulock** [comment]
@gijsbers, do not close these until the original poster says its ok.

**Comment by gijsbers** [comment]
Thanks to this commit `urxvt -tr -sh 60` now does have transparency.
But there is a problem if I try

    urxvt -depth 32 -bg rgba:0000/0000/9999/4444 -fg "[80]pink"

It doesn't get a frame. And initially it has focus, but if I move the cursor elsewhere I cannot get focus back by moving the mouse inside.

**Comment by gijsbers** [comment]
Seems fixed now. Cool!

**Comment by gensenio** [comment]
Thank you very much!!! now tint2 is working very well.

**Comment by bbidulock** [comment]
I tested and still working well after recent commits.  Closing.
