### ISSUE TITLE
Building package on FreeBSD

### ISSUE THREAD

**Issue by bbidulock** [bbidulock/icewm#138]
Came across this thread concerning difficulties compiling IceWM on FreeBSD: https://forums.freebsd.org/threads/58498/

Are we still using this asprintf() (which is bad anyway) and glob_pattern_p?

**Comment by gijsbers** [comment]
There is this commit:

commit 759987111936515efbdbb4eaeb4d653805ea3fe1
Author: Eduard Bloch <blade@debian.org>
Date:   Sun Feb 22 17:01:22 2015 +0100

    globit.c makes use of GNUisms (asprintf, glob_pattern_p), make that code
    conditional and fix unsafe code

**Comment by gijsbers** [comment]
The use of asprintf was simple, so could easily be replaced everywhere.
glob_pattern_p is indeed a gnuism, so replaced it with our own my_glob_pattern_p.
BSDers should be happy now.
