### ISSUE TITLE
A full release is needed.

### ISSUE THREAD

**Issue by roarde** [bbidulock/icewm#139]
There are still many OS's that have IceWM in their official package repos, and are following this fork of it. Most of their package managers work better with serial-style versions. Trying to do the otherwise-sensible thing by adding numerical-order versioning to a commit hash, then editing (sed) the patchlevel-marker file so --version returns useful info results in absurd package filenames and unwieldy procedures.    
      
Please tag a new version and release. I suggest 3cd87d6fa98d924b637eaf7d81a36ca0a083bee8 . It avoids some later retrogressions of the long-standing focus issues, while keeping a lot of the useful, ready-to-use recent changes.

**Comment by bbidulock** [comment]
Yes, I have been avoiding releasing because I hate  the number 13.  I think maybe it will be 1.4 this time.  I don't like back-tagging a release, I would rather get all fixes in and let them soak for a month at least before a release. @gijsbers is still making changes and some are memory leaks which are important.  If there is a regression after 3cd87d6 lets get it fixed on HEAD now.

**Comment by roarde** [comment]
The late commits look promising.

In the meantime, if you would officially reserve "1.3.13[ . . . ]" for custom builds, that could at least provide some relief from longer version tags until a new release is offered here. It would also prevent you from using that version number when releasing. Two birds, one stone; and works whether the next version here is 1.3.14  or 1.4.

Given the changes, I'd go along with 1.4.

**Comment by bbidulock** [comment]
Please consider current HEAD as release candidate.  We will let it soak for 30 days and then release at 1.4.

**Comment by gijsbers** [comment]
1.4.0 is [available](https://github.com/bbidulock/icewm/releases/tag/1.4.0). It was 20 months since 1.3.12 with 488 commits. Would be good if we released much more often.

**Comment by Code7R** [comment]
@gijsbers ChangeLog of 1.4.1 is not uptodate, BTW

**Comment by bbidulock** [comment]
@roarde, is it possible to close this issue now?

**Comment by roarde** [comment]
Had no idea you'd wait on me. VectorLinux has packaged all three 1.4 releases so far into its test repo, and they are working well. IceWM (1.4.x) will be the default WM for the Light version of the OS once again.

Yes, please close the issue, of course!

Thank you all so very much for a lot of fine work, and congratulations.
