### ISSUE TITLE
Missing icons/apps from statusbar

### ISSUE THREAD

**Issue by bedna-KU** [bbidulock/icewm#140]
I now compiling IceWM from GitHub.

Disappeared thirdparty icons from status bar. IceWM icon network, memory, processor, email and time is OK, but not see other application for example, Wicd, pasystray, fbxkb and hexchat.

**Comment by gijsbers** [comment]
Where on your system can those missing icons be found?
The new icewm has a --directories option which gives you a list of icewm resource directories.

**Comment by bedna-KU** [comment]
I have set path for icons in file .icewm/preferences -> **IconPath**. In toolbar are displayed icons OK, this will not be a problem.
For example I have in winoptions: **xchat.Xchat.tray: Exclusive** but xchat no register to statusbar (tray).  Same for wicd, pasystray, fbxkb.
Before it worked OK.
I now compile previous installed version:
git describe 
1.3.8-226-gd490895
and all works fine.

**Comment by gijsbers** [comment]
Is icewmtray running? If I start pasystray then I see no tray icon, but if I also start icewmtray then i do.

**Comment by bedna-KU** [comment]
Yes, here's the problem, icewmtray not running.
I try compile 1.3.8-492-g1ff726a and here tray is running.

Where is problem, new configure options?

**Comment by gijsbers** [comment]
It was a bug. Commit 25cbfb76b85edeb9625fd9152cf45f81cfc79f8d fixes this. Start icewmtray always.

**Comment by bedna-KU** [comment]
Yes, now it is working properly.

**Comment by gijsbers** [comment]
Thanks for reporting this issue!
