### ISSUE TITLE
replace/update themes

### ISSUE THREAD

**Issue by gijsbers** [bbidulock/icewm#142]
Could we maybe consider updating the current theme set with something more modern?
The current set is about 15 years old and wasn't made by people who specialize in design.
box-look.org hosts a very nice set of themes to choose from, 420 of them:
https://www.box-look.org/browse/cat/142/ord/latest/
Which ones to choose? Ideally we would prefer to have themes which are not so big.
Preferably rather small even. Otherwise the github repo would explode in size and slow us down.
My current rating of the old themes is:

> Infadel2        OK, best of the oldies?
> default         OK, but as the default???
> gtk2            Less OK than 'default', poor.
> icedesert       No improvement over 'default'.
> metal2          Poor
> motif           OK
> nice            Poor
> nice2           Poor
> warp3           Poor
> warp4           Poor
> win95           Poor
> yellowmotif     Poor

My current personal favorite of box-look.org is "CrystalBlue".
Which ones do you like best/worst? 
Ideas/opinions?

**Comment by gijsbers** [comment]
fixed by commit fbd0a796f714781a70f9c825c2cfae5eb31ad762

**Comment by volth** [comment]
Hopefully they way the classical themes are removed do not prevent to use them.
Anyway, please consider keeping them.
There are 100500 WMs with "non-poor" themes and this "poorness" has been making IceWM unique and irreplaceable during 20 years. Those users would just keep the last version with the old themes and stop upgrading IceWM.

**Comment by bbidulock** [comment]
@Code7R might be willing to move the old classical themes into the Debian "icewm-themes" package.  Are you loading the "icewm-themes" package on NixOS.  It is quite easy to unpack the debian package and install to any distro.  There is a PKGBUILD for Arch Linux [here](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/icewm-themes).

**Comment by bbidulock** [comment]
Or, I can put them back if it is really causing problems.

**Comment by volth** [comment]
On NixOS, if IceWM ```1.4.2``` is compiled from git, it has all themes.
So no special support is required (unless all mentions of ```warp3```,etc are not removed from .cpp files)

**Comment by Code7R** [comment]
@bbidulock Actually I just requested the removal of this package from the distribution, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=869982 for details. If somebody wants to say something, feel free to comment there.

In case there is a requirement to blacklist old themes somehow, an alternative solution would be needed.

**Comment by bbidulock** [comment]
I created a https://github.com/bbidulock/icewm-extra-themes package that contains initially the contents of the icewm-themes debian package.  I don't know that the licensing issues are all that great: the majority appear to be clearly GPL2.  We could move antiquated themes out into that package.

**Comment by bbidulock** [comment]
Or, maybe we could pull them into IceWM itself and make deciding which themes to install as part of the installation process.

**Comment by gijsbers** [comment]
Thx for the themes repo. More ideas:
- the install process could use curl or wget to download them from this repo?
- an icewemtheme app could do list/load/delete themes, also from box-look.org?
- maybe this can be integrated in the icewm GUI?

**Comment by gijsbers** [comment]
How about sounds? No sounds are currently distributed. Add some to the distro? Add a sounds repository?

**Comment by AndersonTorres** [comment]
These themes can be installed in an arbitrarily-located local directory? If positive, then it's better to decouple them anyway.
