### ISSUE TITLE
Natural theme conflicts with themes package.

### ISSUE THREAD

**Issue by bbidulock** [bbidulock/icewm#143]
Including the "Natural" theme causes a conflict with the icewm-themes package provided by a number of distros (Arch, Debian).  Solution is to remove again the "Natural" theme from IceWM.

**Comment by gijsbers** [comment]
Removed theme Natural from the installation, like suggested. Another solution would be to rename Natural to something else, like _Naturally_ or _Wood_. This would make this theme available to everyone who doesn't have an _icewm-themes_ package installed. Eventually icewm-themes packages would then remove Natural, expecting _Naturally_ or _Wood_ to be present.
