### ISSUE TITLE
Theme glitches with 1.4.0

### ISSUE THREAD

**Issue by zaza42** [bbidulock/icewm#144]
I've been using IceWM for several years, and this update made 2 major visual changes on my theme. 
One is in window title: 
1.4.0 ![windowtitle-1 4 0](https://user-images.githubusercontent.com/16356124/28649858-277f8154-7278-11e7-904b-8306ae5f4da5.png)
1.3.12 ![windowtitle-1 3 12](https://user-images.githubusercontent.com/16356124/28649870-48a054b2-7278-11e7-8a4e-8f538e9210c5.png)
and the another one is in workspace indicator:
1.4.0 ![panel-1 4 0](https://user-images.githubusercontent.com/16356124/28649911-81e18c6e-7278-11e7-8709-bc7f3ee7805b.png)
1.3.12 ![panel-1 3 12](https://user-images.githubusercontent.com/16356124/28649918-88a2bab4-7278-11e7-846f-6c04fd0e3a71.png)

These are very old standard xpms. One is from jim-mac theme, and the other from ElbergGreen theme: [2xpms.zip](https://github.com/bbidulock/icewm/files/1178458/2xpms.zip)

**Comment by gijsbers** [comment]
Thanks for the very helpful and complete report
which include theme names, screendumps and images!

This behavior was unfortunately introduced by
commit 8caa2e9082f3207b121e316851c6bfd97df654b4.

The titlebar theme is not replicated as it should, but stretched.
This is strange. If I disable gradients then everything works fine.
The jim-mac theme file doesn't define any gradients.
So it looks as if gradients are being applied where they should not.

The commit before this one only loads a gradient if its filename
appears in the "gradients" theme option. While now it is always loaded.
So if we restore the previous behavior then we should be OK again.

Yes that seems to work.
The jim-mac theme again shows the replicated titlebar and
ElbergGreen has the original non-green workspace indicator again.

Thanks for reporting this issue!

**Comment by bbidulock** [comment]
Maybe cut a 1.4.1 with that fix?

**Comment by gijsbers** [comment]
My thinking.

**Comment by LoneFox78** [comment]
Workspace and toolbar buttons still look incorrect in version 1.4.1. Also, menu button icons on the top left corner of each window are missing. I'm using dusk from the icewm-themes package.

**Comment by gijsbers** [comment]
Thanks! What do you mean by "incorrect" ? What distro? My distro doesn't have dusk in icewm-themes.

**Comment by LoneFox78** [comment]
> What do you mean by "incorrect" ?

Compare:
http://lonefox.kapsi.fi/icewm-1.3.12.png
http://lonefox.kapsi.fi/icewm-1.4.1.png

> My distro doesn't have dusk in icewm-themes.

The themes are from this tarball, which AFAIK is the last "official" release of them:
http://ftp.debian.org/debian/pool/main/i/icewm-themes/icewm-themes_1.2.26.orig.tar.gz

**Comment by martintxoz** [comment]
For the "icons on the top left corner of each window missing" bug:
- If the theme HAVE the files menuButtonA.xpm AND menuButtonI.xpm, the window icon DON'T shows.
- If the theme DON'T have these files, the window icon appears...

I arrive to this conclusion at view that with an old theme with few image files the window icon is shown, like in the win95 theme... Then I made some test and voila!! :-D

I think that this is a grave regression. The window icon is important to window identify.

Many thanks for your work. Greetings. Martintxo.

**Comment by martintxoz** [comment]
My computer uses Debian Testing, and get the new version 1.4.1 from the experimental repo: https://packages.debian.org/experimental/icewm

Thanks too to the Debian maintainer!!

**Comment by gijsbers** [comment]
[1.4.2](https://github.com/bbidulock/icewm/releases) should fix all above issues.

**Comment by zaza42** [comment]
Thanx for fast reply + code! 1.4.2 has fixed these 2 gitches, so now everthing seems to be perfect.
