### ISSUE TITLE
icewm.html not installed by CMake

### ISSUE THREAD

**Issue by Code7R** [bbidulock/icewm#145]
So here is the thing:

I am upgrading the Debian packages of icewm right now and I see a little
glitch there. When doing out-of-sourcetree build, icewm.html is not
built at the right location (i.e. the "-o icewm.html" option is missing
in CMakeLists.txt). Therefore, the file is not installed.

I am wondering how it was supposed to work. If upgrading the file is a
release time task then it should be somehow kept track in release
automation. But I cannot find the location where it's executed.

But if the HTML rebuilding shall be done in user compiler runs then
the file should be build correctly even in OOT builds.

What's the plan? Please advise.

**Comment by gijsbers** [comment]
The plan sofar was that we provide the icewm.html in the distribution file.
I have added -o icewm.html to CMakeLists.txt, thanks for your suggestion.
I have uploaded a new icewm-1.4.1.tar.bz2 which includes this + an updated ChangeLog.
We provide the CMakeLists.txt but we note in the INSTALL-cmakebuild that it is experimental.
We usually use the autoconf/automake build setup.

**Comment by bbidulock** [comment]
@gijsbers, I always let the original issue poster close.

**Comment by bbidulock** [comment]
@Code7R, has this been fixed?

**Comment by Code7R** [comment]
Yes, it install the correct file now (generated or existing). Thanks @gijsbers et al.
