### ISSUE TITLE
icewm.html lacks TOC and text style in icewm help browser

### ISSUE THREAD

**Issue by Code7R** [bbidulock/icewm#146]
Hello,
unlike the old SGML documentation, the new version is not shown completely in icewm's own HTML help browser.

I.e. instead of TOC you see the message:
JavaScript must be enabled in your browser to display the table of contents.

Also the nice text format from sgml tools is now lost since asciidoc uses mostly CSS styles which are not supported by icewmhelp.

From my POV this is a clear regression WRT the old documentation. Please reconsider the change, or find a solution.

**Comment by gijsbers** [comment]
The provided icewm.html does not have this problem. 
![icewm-html-toc](https://user-images.githubusercontent.com/4169687/28727918-e7b9cd40-73c6-11e7-8350-3cdb4f945857.png)

The missing TOC occurs as a result of using asciidoc. But the output of asciidoctor should be fine. We recommend asciidoctor over asciidoc when processing icewm.adoc.

The drawback of SGML is that it is old and impopular. Having a more modern friendly markup language like asciidoc may make it less of a burden to update the manual.

**Comment by Code7R** [comment]
Alright. But then please document this recommendation in more visible fashion.

**Comment by bbidulock** [comment]
Again, I always let the original poster close.

**Comment by Code7R** [comment]
It looks ok, thank you.
