### ISSUE TITLE
Last icon in icewmsystray is half-sized

### ISSUE THREAD

**Issue by Code7R** [bbidulock/icewm#147]
In version 1.4.1, something happened to the systray container.

While the icons for tray apps are added, the most right icon appears small. I.e. it appears scaled down by half in each dimension and occupies only a quarter of the screen space. The remaining space is just background color.

When the next icons are added, the small icon is shifted to left and is then displayed normally, full size.

**Comment by gijsbers** [comment]
Does this occur regardless of which tray apps are used? Could you mention the ones you use for this purpose? A screendump would be appreciated. Thanks for reporting this.

**Comment by Code7R** [comment]
That's with Helix theme, pasystray and nm-applet, both should have the same size.

![mini_icon_systray](https://user-images.githubusercontent.com/10660264/28731838-cf38bd26-73d5-11e7-999f-40e147d8c102.png)

**Comment by Code7R** [comment]
PS: Something weird is going on here. After a reboot, I see this effects only sometimes, and only for a split-second after login. This makes it hard to bisect the issue :-( .

I still it's worth investigation but doesn't have high priority for me ATM.

**Comment by gijsbers** [comment]
What I found helpful in bisecting is using Xephyr.

**Comment by gijsbers** [comment]
Unfortunately I can't reproduce it. See image. 
![tray3](https://user-images.githubusercontent.com/4169687/28750383-4a737936-74e9-11e7-90ae-3223631c73a3.png)
If you add more tray icons, like from vlc and hexchat, does that work for you?

**Comment by bbidulock** [comment]
I could not recreate either, but I have had problems like this with nm-applet before on other window managers.  Check to see that you have the correct sizes of the correct file type.  Might be related to looking for xpm first.

**Comment by roarde** [comment]
I've not seen exactly this, but something similar. Questions you might probe:      
Does this happen, ever, when nm-applet is not loaded at all?      
Does it happen if no applets which use python are loaded?        
Does it still happen, ever,  if you follow your nm-applet line in startup with this line?:       
until xwininfo -name 'NetworkManager Applet' >/dev/null; do sleep 1; done
(Not a suitable fix, but a decent probe I think.)               

I think the main fault is with NM, probably with the Python implementation used. Whether it's proper for the WM to allow for this, or whether there's an expected standard not quite met, is beyond my ken.      

I do get something very, very close (but not quite) when I stop then restart the NM daemon from within an IceWM session. While changing between the "connected", "disconnected", and "connecting" icons, a noticeable line appears in the icons about 1/3 the way from the left, but it disappears and the icon "reassembles".

**Comment by bbidulock** [comment]
Might be related to the old issue #54.

**Comment by Code7R** [comment]
It hasn't happened again, at least since 1.4.2. Closing.
