### ISSUE TITLE
Black hole in a tray

### ISSUE THREAD

**Issue by arsonoff** [bbidulock/icewm#152]
Test:
Start icewm without applications in a tray.
Restart icewm (killall -SIGHUP icewm).
OK.
Start the application placed in a tray (for example: osmo)
Close the application placed in a tray (in a tray there should not be applications)
Restart icewm.
Black hole in a tray.
[![icewm_tray.png](https://s4.postimg.org/5xc7nt9d9/icewm_tray.png)](https://postimg.org/image/pry99xokp/)
If in a tray there is at least one application, then everything is normal.

**Comment by gijsbers** [comment]
bug confirmed

**Comment by gijsbers** [comment]
also confirmed for 1.3.12

**Comment by gijsbers** [comment]
@arsonoff commit 61c65d5 fixes all tray problems for me. No more black holes to be found and all icons are always shown no matter how often I restart IceWM. Agree? anything else?

**Comment by arsonoff** [comment]
Problem at compilation (CentOS7.4, gcc-4.8.5):
<pre><code>  CXX      yapp.lo
In file included from yapp.cc:9:0:
ytimer.h: In function 'timeval zerotime()':
ytimer.h:42:44: error: expected primary-expression before ')' token
 inline timeval zerotime() { return (timeval) {}; }
                                            ^
ytimer.h:42:46: error: expected ';' before '{' token
 inline timeval zerotime() { return (timeval) {}; }
                                              ^
make[2]: *** [yapp.lo] Error 1
</code></pre>

**Comment by arsonoff** [comment]
OK
