### ISSUE TITLE
What does icewmbg in RAM?

### ISSUE THREAD

**Issue by arsonoff** [bbidulock/icewm#153]
Why icewmbg remains in memory after installation of a background?
- change of a config (preferences) at restart he does not monitor, 
- change the image file too (only after restart manually),
- if kill process, the background remains.

Why it borrows 1Mb? :)

**Comment by gijsbers** [comment]
It also responds to changes in screen resolution, add/removal of monitors, it monitors switching workspaces because it supports separate background colors / images per workspace. When background images change on filesystem after 10 seconds it updates when switching workspaces.

**Comment by arsonoff** [comment]
>it updates when switching workspaces.

Only thus?
I expected that it will be updated at change of the file :(
>When background images change on filesystem after 10 seconds 

Changes without delay, but only after switching to other workspace.
