### ISSUE TITLE
Starting icewm-session without icewmtray

### ISSUE THREAD

**Issue by onli** [bbidulock/icewm#154]
I recently got an update for icewm making my system use this fork, and I'm running into an edge case.

It seems to be not possible anymore to start icewm-session when icewmtray is not present in `PATH`. It would be good if icewmtray would not be a hard dependency, or if it could be disabled completely in the preferences (maybe that's already possible?).

Context: I'm using icewm without the taskbar, with a dock and conky and stalonetray (which broke with the icewm update as well, thus currently I run trayer). The problem is that when icewm-session is called, it starts icewmtray, which paints a very unpractical window to catch tray icons, blocking stalonetray/trayer from working. My solution in prior icewm versions was to rename the icewmtray binary. That's not possible anymore, icewm-session refuses to start with a "File not found" error message in the terminal.

**Comment by gijsbers** [comment]
Could you clarify "not possible anymore to start icewm-session when icewmtray is not present in PATH" ? It reads as if your shell refuses to start icewm-session if it cannot find icewmtray. (Then get a better shell... ;-)) What is the real problem?

On startup icewmtray notifies icewm-session by sending it a SIGUSR1 signal.
You could mimic this by replacing icewmtray with the following script:

    #!/bin/bash
    kill -USR1 $PPID

Does that help your problem?

What you mean with "stalonetray broke"? Makes it hard to fix this way... :-)
How can we replicate this problem and what do you expect from a fix?
Thanks for your help!

**Comment by onli** [comment]
Hey, thanks for the response. I'm really hoping I'm getting this right. Is it correct that `icewm --version` is not printing 1.4, or is something warped on my system? My package system states I have 1.4 installed, and the ebuild is pointing to this github page.

I will report the stalonetray issue as a separate issue when I'm sure this one is described properly :) It's a separate thing.

I'll assume I'm in the right place, and structure the report a bit better.

## Summary

`icewm-session` does not work anymore as wanted when the `icewmtray` binary is not present.

## Steps to reproduce:

 1. Install icewm
 1. Delete /usr/bin/icewmtray
 1. Add something to execute to **~/.icewm/startup**
 1. Execute `icewm-session`

### What should happen: 

`icewm-session` starts icewm without starting icewmtray, but executes **~/.icewm/startup**

### What actually happens: 

icewm starts, but does not execute **~/.icewm/startup**. In the tty there is is one error message, which makes me believe icewm-session stopped there:

    icewm-session: Warning: icewmtray: No such file or directory


## Proposed solution:

 * Add an option in preferences that completely prohibits loading of icewmtray
 * Or make icewm-session continue as normal when icewmtray is not present

## PS:

Yes, replacing the binary with

    #!/bin/bash
    kill -USR1 $PPID

works. Sorry, I thought you had misunderstood the issue. However, I hope you can fix this in icewm itself - removing the binary worked in older versions, though I was always hoping there would be an option in preferences instead.

**Comment by gijsbers** [comment]
That is a very clear problem report! :-)
My --version output is:

    $ icewm --version
    IceWM 1.4.2.81, Copyright 1997-2003 Marko Macek, 2001 Mathias Hasselmann.

But what is yours then?
Having an option in preferences is a bit ugly, because currently icewm-session doesn't read any preferences file. Icewm-session is rather small and simple. We could easily add an argv flag and make it more robust against a missing icewmtray.

**Comment by onli** [comment]
Your commit looks very good. That should work for me when it arrives at my system, and till then the workaround you showed me is fine. Thanks. I hope it is okay if I close here with this comment.

> But what is yours then?

    onli@Fallout:~$ icewm --version
    IceWM 1.3.12.288, Copyright 1997-2003 Marko Macek, 2001 Mathias Hasselmann.

But:

```
onli@Fallout:~$ equery list -po icewm
 * Searching for icewm ...
[-P-] [  ] x11-wm/icewm-1.3.8:0
[-P-] [  ] x11-wm/icewm-1.3.12-r1:0
[IP-] [  ] x11-wm/icewm-1.4.0:0
```
Which is to say that 1.4.0 is installed. Also, I got the directory **/usr/share/doc/icewm-1.4.0**, I really think the version string is wrong.

Anyway, before I report the stalonetray bug I'll compile the git head to be sure it is relevant for you.

PS: I'm very happy to see an active development of this WM. Thank you!
