### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by ghost** [bbidulock/icewm#156]
Is this really what it looks like?

http://upload.wikimedia.org/wikipedia/commons/2/27/Icewm-default.jpg

If not, it would be nice to see some more current screenshots

**Comment by bbidulock** [comment]
There are 421 screenshots at [box-look.org](https://www.box-look.org/browse/cat/142/ord/latest/).

**Comment by gijsbers** [comment]
# This is the IceWM screenshots collection

![screen03](https://user-images.githubusercontent.com/15175058/31690477-d4a6bab8-b360-11e7-9dd3-30324c8cb020.png)

![cairo-clock-icewm1](https://cloud.githubusercontent.com/assets/3276068/7817583/3718e62c-03d6-11e5-95ef-589210a60c44.jpeg)

![odd](https://user-images.githubusercontent.com/7656607/32042698-002e773c-ba6b-11e7-8e6a-29da6f910ec2.png)

![Haiku](https://user-images.githubusercontent.com/367181/33675642-899b7340-dab3-11e7-9bdb-43606c5d4d58.png)

![Ater-ice](https://user-images.githubusercontent.com/15175058/34381016-c61d9ab6-ead3-11e7-835b-fa366dce8c68.png)

![maim-2018-03-05_18](https://user-images.githubusercontent.com/16356124/36989539-47c464f6-20a2-11e8-9eea-fde078593466.png)

![ryanrms](https://user-images.githubusercontent.com/2936638/44629544-3e05bd80-a90e-11e8-8a55-27a8a3f0d185.png)
