### ISSUE TITLE
Versioned releases?

### ISSUE THREAD

**Issue by ghost** [bbidulock/icewm#157]
Hello,

Not sure if this is worth to bother for you guys but I will report just in case; feel free to close at any time.

Old icewm releases were at sourceforge and had a release scheme URL such as:

https://downloads.sourceforge.net/icewm/icewm-1.4.2.tar.gz

At github, this becomes https://github.com/bbidulock/icewm/archive/1.4.3.tar.gz

Would it be possible to use icewm-1.4.3 on github rather than the 1.4.3 variant? It would help me a bit in regards to automatically fetching the latest source via scripts.

I do not know how this is done on github but other projects show that this is possible for example:

  https://github.com/apple/cups/releases/download/v2.2.4/cups-2.2.4-source.tar.gz
  https://github.com/libfuse/libfuse/releases/download/fuse-3.1.1/fuse-3.1.1.tar.gz
  https://github.com/libass/libass/releases/download/0.13.6/libass-0.13.6.tar.xz

**Comment by bbidulock** [comment]
In fact the download path is: https://github.com/bbidulock/icewm/releases/download/1.4.2/icewm-1.4.2.tar.bz2

You are just using the wrong path.
