### ISSUE TITLE
The menu icons could be nicer

### ISSUE THREAD

**Issue by onli** [bbidulock/icewm#160]
I hope it is okay to make a request like this.

The icons in the menu are really a good idea, but imho they could look a bit better. For reference, that's how they look right now for me (I hope that's still the current state):

![icewm-menu](https://user-images.githubusercontent.com/900380/29454334-0e8253f6-840d-11e7-9952-e8f44338e97b.png)

Imho the two on the top, which are set manually by me, show how the icons at the bottom (coming from icewm) should look like. Not necessarily the style, but the quality.

My feedback:

 1. The windows menu should not use the old Microsoft Windows icon. That's even a copyright problem, and it transports the wrong message.
 1. See the white border around the icon for about and focus? That's problematic, and misses anti-aliasing.
 1. The themes icon should have contours, or maybe a different motive (that's a hard one)
 1. Logout is more or less okay, just pixely and inset

My suggestion would be to rework the icons, and I might be able to help a bit with that. But you could also use existing icons. There are a number of free (FOSS) icons usually used in web development that could work very well here. The most popular set is font awesome. http://fontawesome.io/icons/ shows a number of icons that could work well here, and that project will see an influx of new icons soon. 

I could also try to look up from where the icons I use at the top stem from, and if they have a free license, that set might work well for IceWM in general.

**Comment by LoneFox78** [comment]
> 1. The windows menu should not use the old Microsoft Windows icon. That's even a copyright problem, and it transports the wrong message.

That is not the default icon that comes with icewm. It is from the old icewm-icons package, and looks like someone has resolved the naming conflict between them incorrectly.

**Comment by onli** [comment]
Could you show me what would be the correct icon, and where its location is? If that is a packaging bug I should report it in the gentoo bug tracker.

But the other icons are the current default icons?

*Edit:* No, that was my mistake. Seems like I years ago installed an icewm icon pack under ~/.icewm/icons. Please ignore the windows icon remark, but the feedback to the other icons still stands.

**Comment by gijsbers** [comment]
Makes sense. Also see issue https://github.com/bbidulock/icewm/issues/149. This could perhaps be done by you or others who may not program source code but who do have a knack for graphics and design. The key is perhaps that the license for the icons should allow it to be distributed by Linux distros.

**Comment by onli** [comment]
Great :)

Some initial remarks: 

 1. We should not use .xpm, but .png. It's impossible (for me?) to get proper quality icons in .xpm format. 
 1. SVG support would be even better! Do we have that already?
 1. I currently play with https://feathericons.com/. All icons are there. But: They don't have an outline, and I think that would destroy their style. Any chance of having dark and light icon sets, and giving themes the job to switch to the proper style? Think it would be worth it.
![icewm-menu-feather](https://user-images.githubusercontent.com/900380/29672603-02bbf7a4-88ed-11e7-808a-fcac72a3a00a.png)

**Comment by gijsbers** [comment]
1. Doesn't [convert](https://www.imagemagick.org/script/convert.php) work for you?
2. Support for PNG/SVG could be added with little effort I think.
3. What is an "outline"? These are monochromatic icons? No colored icons anymore???
4. dark/light/etc styles requires more thought. Where would they go? What if a theme doesn't specify that?

**Comment by onli** [comment]
1. Seems to work a bit better than the gimp import. I'll play with that a bit and report back.
 1. Great :) PNG support we have already, at least optionally (active in my build)
 1. The old windows and focus icon had a white outline/border around it, despite itself being monochromatic as well. In https://github.com/bbidulock/icewm/issues/149#issuecomment-319164625 you mentioned that as a good thing :) But I don't think it would be a good solution here.
 1. Yes, certainly. But it could be as simple as having `icon_16x16.xpm`,  `icon-light_16x16.xpm` under the normal icon path, and a themes/preferences setting to switch between the two, default to non-light. But I might miss some complications.

**Comment by gijsbers** [comment]
2. PNG/SVG should both already work for any icon in a `icons` directory.

**Comment by onli** [comment]
> 2. PNG/SVG should both already work for any icon in a icons directory.

Nice! And yes, it does! But the quality of an .svg is a lot worse than having a png in there :/ 

But if png is a baseline feature then we should just use png instead of .xpm for now, imho.

**Comment by bbidulock** [comment]
Now the order is .png .svg .xpm

Light and dark is kind of unnecessary when a style can specify its own icons.

**Comment by Code7R** [comment]
The current icons are nice enough, closing.
