### ISSUE TITLE
The firefox icon does not appear in the toolbar

### ISSUE THREAD

**Issue by ghost** [bbidulock/icewm#163]
My system arch linux.
Here is a screenshot of the problem: http://screenshot.ru/upload/image/ShZY
The pix map images are in the ~/.icewm/icons folder and everything should work.

**Comment by gijsbers** [comment]
So you have icons like these ?

~/.icewm/icons/firefox_16x16.xpm
~/.icewm/icons/firefox_32x32.xpm
~/.icewm/icons/firefox_48x48.xpm

**Comment by ghost** [comment]
> So you have icons like these ?
>
>~/.icewm/icons/firefox_16x16.xpm
>~/.icewm/icons/firefox_32x32.xpm
>~/.icewm/icons/firefox_48x48.xpm

There are only two files associated with mozilla: .icewm/icons/mozilla_16x16.xpm  .icewm/icons/mozilla_32x32.xpm

**Comment by ghost** [comment]
I figured out by examining the toolbar file, I had to change the second line to mozilla and it all worked.
