### ISSUE TITLE
How to remove this annoying warning

### ISSUE THREAD

**Issue by ghost** [bbidulock/icewm#165]
Every day I read logs and this is what prevents me:
```
 icewm-session: Warning: File still open: fd=3, target='/var/log/slim.log' (missing FD_CLOEXEC?)
```

Such an inscription is highlighted 132 times. How can I remove it without recompiling the sources?

**Comment by gijsbers** [comment]
There is this nifty tool called `sed` which allows you to remove unwanted lines like this:

    sed -i /FD_CLOEXEC/d     /path/to/your/file.log

The problem seems to originate from SLIM. They open an extra logfile and pass it on to icewm, even though icewm doesn't know how to handle such unexpected presents.

**Comment by bbidulock** [comment]
Sliipped warning inside of DEBUG.  Not an icewm issue: slim should close its files or set close on exec file control flag.  Please report to slim.

**Comment by ghost** [comment]
Then I will reply to the developers
