### ISSUE TITLE
RFC: drop libxft 1.x support

### ISSUE THREAD

**Issue by Code7R** [bbidulock/icewm#168]
Hi,
I was reviewing some code (trying to figure my preferred font from the list in Xft spec is not used although fc-match buys that just fine).

While doing that, I realized that we still support the first generation of libxft library. But libxft 2 has been released almost 15 years ago. I don't think there are many (if any) systems not having it nowadays (unless they want to use corefont anyway).

So I would drop that code bits and always assume libxft>=2.0. Anyone saying veto?

**Comment by bbidulock** [comment]
I always get:

    checking for xft >= 2.0.0... yes

So, what is the problem exactly?

**Comment by Code7R** [comment]
Not a  problem yet. Just extra code rotting in ypaint.cc which probably hasn't been enabled on real world systems for over a decade. I will prepare a PR for this proposal.
