### ISSUE TITLE
Config inheritance order is probably wrong

### ISSUE THREAD

**Issue by scarabeusiv** [bbidulock/icewm#179]
If the user has theme and config the theme values take precedence. 

When built with --cfgdir=/etc/icewm/ DesktopBackgroundImage value set in /usr/share/icewm/themes/default/default.theme takes place instead of the user provided values from /etc/icewm/preferences

The behaviour should be rather overlapping. Load the theme, and then load user configs from the path, or provided on the command line and overlap from them.

I think the full inheritance order should be priority wise like:
theme -> configdir -> user xdg/home -> commandline

**Comment by bbidulock** [comment]
See prefoverride in icewm(1) manual page.  These are loaded after the theme.  preferences is loaded before the theme.

**Comment by scarabeusiv** [comment]
Yea but that is behaviour change compared to 1.3 which I bet many people counted to be the same and are already complaining about :)

I can of course patch it locally but I would like to avoid that.

**Comment by bbidulock** [comment]
No, prefoverride was there in 1.3.

**Comment by scarabeusiv** [comment]
Oh, I didn't understand you. I mean perfoverride was there in 1.3 but simple preferences worked fine and replaced the values. Now you really need to use perfoverride and regular preferences do not work.

For me, it means I have to patch it because users are used for it to work even if it was not by documentation :(

**Comment by gijsbers** [comment]
Hello @scarabeusiv ! Which 1.3 do you refer to? 
I just tried it out with IceWM 1.3.12. If I create a new user and add DesktopBackgroundImage to its ~/.icewm/preferences, but a theme like Korilla or BerryXP has its own background defined then the theme background takes precedence.
This seems correct to me. 
Maybe your 1.3 was already patched?

**Comment by scarabeusiv** [comment]
https://build.opensuse.org/package/show/openSUSE:Leap:42.2/icewm

This is the package with 1.3.12 that does work, there is no patch.
Does it take precedence even if it is in the defined configdir rather than userdir. We define during build it to be /etc/icewm/ and then it did override everything.

Here is the test output confirming it works on 1.3 (will be pruned in a couple of days):
https://openqa.opensuse.org/tests/502780#step/first_boot/4

**Comment by bbidulock** [comment]
Well, 1.3.12 used icedesert as the default theme.  The data/themes/icedesert/default.theme file does not define DesktopBackgroundImage.  For releases after 1.3.12 the default theme is data/themes/default/default.theme, which does define DesktopBackgroundImage.  The SUSE icewm-preferences.patch file patches DesktopBackgroundImage="BRANDING_IMAGE" into the system preferences file.  It did not override anything: the old default theme just did not provide a background image; the new one does.  This approach does not override the background image for any theme that provides one at all.  If you want to override the background image for all themes, by default, add a file /etc/icewm/prefoverride and place your background image definitions (scaling, etc.) there.  If you want to override the background image for just the default theme, patch /etc/icewm/themes/default/default.theme with the background image definitions you want.

**Comment by scarabeusiv** [comment]
Ah good, I didn't notice it was not set to anything before, so we are not breaking anything for the user :)

For the package I can use the prefoverride and as such we can close this. Thanks for the help.

**Comment by gijsbers** [comment]
@scarabeusiv Maybe consider that IceWM now supports one background per workspace. See icewmbg(1). Could be nice to have 4 backgrounds in a theme, like moon phases, or dusk to dawn, or seasons.
