### ISSUE TITLE
Multimonitor control as quickswitch

### ISSUE THREAD

**Issue by Code7R** [bbidulock/icewm#181]
Hi,
(I am sorry for not helping out with the real bugs here but with the limited spare time I have, I decided to work on something which makes more fun at the moment...)

So, there is something I have always envied the Windows 7 users for: the ability to switch turn off and on the additional monitors with simply a few clicks. This also comes handy in meetings and conferences - it's sometimes embarrassing to see Linux users fiddling around with arandr or opening xrandr manpage as the first action on the stage.

So I wanted to integrate something handy into icewm which should not require many resources or additional packages like arandr. I came up with a menu generator first. This is written in perl and uses xrandr and also sysfs on LInux to find out the real monitor names (can also be fetched via xrandr but it blocks the call for a second). See attached screenshot.

The next thing I had in mind is creating a way to use the QuickSwitch functionality but feed it with the menu data! (i.e. titles, icons, action to run a program). Just imagine pressing Win-P instead of Alt-Tab and you see a similar menu which contains the monitor options. I have already started refactoring the wmswitch stuff, separating the content control bits from the main class so it can be replaced as needed (even using the same class, kinda strategy pattern).

Questions? Opinions? Objections?

**Comment by Code7R** [comment]
![monitor_control_menu_sample](https://user-images.githubusercontent.com/10660264/31575961-bb73cd68-b0f1-11e7-8064-a1372f1b02d5.png)

**Comment by bbidulock** [comment]
arandr uses python so I hate it.  I use grandr (an xorg tool, so the same people that wrote xrandr), which has a nice intuitive gtk2 interface so no need to read man pages.  I maintain the xorg-grandr and xorg-grandr-git packages on the AUR.

**Comment by Code7R** [comment]
Works good enough now.
