### ISSUE TITLE
NetworkStatusDevice="<sys>" not detecting anything

### ISSUE THREAD

**Issue by jidanni** [bbidulock/icewm#182]
Thinking #42 might be fixed, I read file:///usr/share/doc/icewm-common/html/icewm.html
so in ~/.icewm/preferences I tried
```NetworkStatusDevice=<sys>```
and restarted icewm, also
```NetworkStatusDevice="<sys>"```
(Please give the whole line in the document, so we know how it should look.)
same problem. It doesn't work. You don't detect anything.

There they are, plain as day
```
$ ls /sys/class/net
enp0s31f6  lo  wlx0011a30acb8a
$ /sbin/ifconfig | grep -P ^\\S
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
wlx0011a30acb8a: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
```
but icewm cannot detect them.
```
$ uname -a
Linux jidanni7 4.13.0-1-amd64 #1 SMP Debian 4.13.4-2 (2017-10-15) x86_64 GNU/Linux
```

**Comment by jidanni** [comment]
Yes they are detected if I hardwire them into the file.
```NetworkStatusDevice="wlx0011a30acb8a eth0 enp0s31f6"```

**Comment by Code7R** [comment]
@jidanni I am preparing a Debian build soon, please retest with glob patterns.

**Comment by jidanni** [comment]
OK I replaced
```
NetworkStatusDevice="enp1s0"
```
with
```
NetworkStatusDevice=<sys>
```
and clicked restart icewm, and....
lost my status icon!
IceWM 1.4.3.0~pre-20180822

**Comment by gijsbers** [comment]
Where in the current docs do you find `<sys>`?
Can't you just use `*` or `e*` or `[ew]*` or some other regular expression?

**Comment by jidanni** [comment]
OK.
