### ISSUE TITLE
TrayDrawBevel not recalculating when switching themes.

### ISSUE THREAD

**Issue by SolisX** [bbidulock/icewm#184]
Hello Everyone,

When one starts with Dark-Ice (the only theme that has TrayDrawBevel=1), the geometry of the tray is being calculated to exclude the bevel. When the theme changes (to one with TrayDrawBevel=0), the geometries are not being recalculated so there is a gap where the bevel would be.

**Comment by bbidulock** [comment]
Well that wasn't the problem at all, icewmtray was only reading configuration at startup, and I think it was reading configuration from the wrong location.  Nevertheless, I made the internal tray calculate the difference and apply the border.  TrayMaxIconHeight is now just that (not the max height of the tray, but the icons in it).  If you have TrayDrawBevel=1 and TrayMaxIconHeight=24, then the tray will by 26 pixels high to accommodate the border.  This should get rid of some problems with tray icons hating to be resized to 24x22 when there is a bevel.  Now they will be 24x24.  Also configured the icon itself, so toolkits will now be told when they are resized.  Give it a try.  I think that it is all fixed.

**Comment by SolisX** [comment]
Got a compile error. Catalan.
ca.po:1366 needs %s.

Okay i got to compile.  When i switch between the two themes it seems fixed but if i keep
switching the themes the tray icon disappear. I can see a vertical black line but no icons.
The patch you added is causing the taskbar to add an extra line on some pixmap themes.
For example ultrablack theme.

**Comment by SolisX** [comment]
Here is a video of the problem.
https://www.sendspace.com/file/snqooy

**Comment by gijsbers** [comment]
Since yesterday there is a rather noticable white line at bottom of CrystalBlue and a dark vertical line at the end of the tasks before the netmonitor, which both look ugly. 
See this image:
![crystalblue](https://user-images.githubusercontent.com/4169687/31707297-2836cebc-b3ec-11e7-9f2f-311f454f7f89.png)

**Comment by bbidulock** [comment]
@SolisX Fixed that po file.  You can try it now.

@gijsbers The dark vertical line is probably my fault: it is likely the tray with nothing in it.  Open another issue, I have a fix for it I think.

**Comment by bbidulock** [comment]
The white line is really the taskbar pixmap repeated.  TrayIconMaxHeight is now the maximum height of the icons in the tray, not the maximum height of the tray as it was before.  When you have a bevel it makes the tray 2 pixels taller than before.  Try setting TrayIconMaxHeight to 22 in prefoverrides or in the theme.  I won't change the default because 24x24 icons are easier for toolkits to render.  Another solution would be to extend the taskbar pixmap for that theme by two pixels so that it does not repeat.

**Comment by bbidulock** [comment]
Maybe I spoke too soon.  The taskbar is 27 pixels high, but everything inside it is 26 pixels high.  Somewhere in the calculations of the height of the overall taskbar, one is getting added.

**Comment by SolisX** [comment]
Hello Bbidulock,

The orginal theme was 25 pixels high for the taskbar. I had to change it to 26 pixels. I had mentioned
in the issue below near the end of the posts.

https://github.com/bbidulock/icewm/issues/41

When i change the preferences "TrayIconMaxHeight to 22" gets rid of the line. However if i change
the theme to another theme the tray icons disappear..

**Comment by bbidulock** [comment]
Need to find out where it is adding the one pixel.

**Comment by gijsbers** [comment]
This looks fine to me now. @SolisX is it still an issue for you?

**Comment by SolisX** [comment]
Hello Gijsbers,

I don't see the extra line but the trayicon is not using the colors of the taskbar.xpm. Also for some reason the window pager is being used when i had it set to off.

**Comment by gijsbers** [comment]
1. thx for noticing this. plz try again, works for me now.
2. what gives `icewm --postpreferences | grep Pager` ?
and what gives `grep Pager ~/.icewm/preferences` ?

**Comment by SolisX** [comment]
Hello Gijsbers,

1).Ok it seems to be working now. :)
2). The PagerShowPreview=0 # 0/1 in my preferences had a # in front of it. I guess you
changed the default to on when the PagerShowPreview is not manually set. On previous
versions of icewm it did not matter.

PagerShowPreview=1
PagerShowWindowIcons=1
PagerShowMinimized=1
PagerShowBorders=1
PagerShowNumbers=0
IceWM: A window manager is already running, use --replace to replace it
bash-4.3$ grep Pager ~/.icewm/preferences
1.# PagerShowPreview=0 # 0/1
2.#  Draw window icons inside large enough preview windows on pager (if PagerShowPreview=1)
3.# PagerShowWindowIcons=1 # 0/1
4.#  Draw even minimized windows as unfilled rectangles (if PagerShowPreview=1)
5.# PagerShowMinimized=1 # 0/1
6.#  Draw border around workspace buttons (if PagerShowPreview=1)
7.# PagerShowBorders=1 # 0/1
8.#  Show number of workspace on workspace button (if PagerShowPreview=1)
9.# PagerShowNumbers=1 # 0/1

**Comment by gijsbers** [comment]
@SolisX now also with support for TrayDrawBevel=1. plz try again, thx.

**Comment by SolisX** [comment]
Hello Gijsbers,

Just about all my themes work exepct for my "Ater-ice" theme. It's still drawing a white line on the bottom.

**Comment by gijsbers** [comment]
Ater-ice also has a white line under 1.3.12, so no prob?

**Comment by SolisX** [comment]
Is the default taskbar size 26? If it is then there is no problem i can just increase the taskbarbg.xpm to 26 which i have i set to set 25 now.

**Comment by gijsbers** [comment]
There doesn't seem to be a defined height of the taskbar. 
26 just appears to be it somehow. Maybe this has influence?:
```
# TaskBarGraphHeight=20 # [16-1000]
# TrayIconMaxHeight=24 # [16-128]
```

**Comment by SolisX** [comment]
I guess

1).# TaskBarGraphHeight=20 # [16-1000]
2).# TrayIconMaxHeight=24 # [16-128]

are new options. My old preferences does not have those entries.
I believe this issue ater-ice was not an issue with icewm-1.3.12.

**Comment by gijsbers** [comment]
ah right!
The height of 25 comes from the SysTray. It is calculated from the value of 24 for TrayIconMaxHeight and 1 for TrayDrawBevel. If TrayIconMaxHeight is set to 23 the white line disappears.

**Comment by gijsbers** [comment]
+ the taskbar takes that 25 (TrayIconMaxHeight + TrayDrawBevel) and adds 1 to it to make 26.
This last +1 was also there in 1.3.12. I think the change comes from TrayIconMaxHeight.
24 is a good icon size. Some apps have difficulty producing an icon at 23.

**Comment by SolisX** [comment]
I'm guessing it has something to do the new options. This is ater-ice on 1.3.12. no extra line.
![screen02](https://user-images.githubusercontent.com/15175058/34381016-c61d9ab6-ead3-11e7-835b-fa366dce8c68.png)

Would it not just be better to just have the taskbar size set by the size of the taskbarbg.xpm instead of having it set by a number in the default.theme?

**Comment by gijsbers** [comment]
I agree with you. Would require changing quite a few modules a bit. Not impossible.

**Comment by SolisX** [comment]
BTW: The reason i mention that is because most my themes are 26 pixmaps but Dark-Ice is 30 pixmaps
and when you have those two options it offsets the led clock.

**Comment by gijsbers** [comment]
The idea to "have the taskbar size set by the size of the taskbarbg.xpm instead of having it set by a number in the default.theme" is faulty for the reason that many themes have taskbarbg.xpm heights which are larger or even much larger than the intended taskbar height.

**Comment by gijsbers** [comment]
The Ater-ice theme was [fixed in March](https://www.box-look.org/p/1018108/) and no other themes have a similar problem.
