### ISSUE TITLE
cannot set focus

### ISSUE THREAD

**Issue by gijsbers** [bbidulock/icewm#185]
Left is tilda open, right a urxvt with focus and mouse. Sloppy. Want to set focus on tilda: move mouse from right to left over tilda. No change, focus still urxvt. Clicking no effect. Only by moving mouse from left to right and then to left again is focus set on tilda.

**Comment by bbidulock** [comment]
What's a tilda?

**Comment by gijsbers** [comment]
A very handy hotkeyable well-configurable terminal:
https://github.com/lanoxx/tilda
recommended

**Comment by bbidulock** [comment]
What focus model is it using?

**Comment by gijsbers** [comment]
Locally Active

**Comment by bbidulock** [comment]
Need to check if it is being focused when mouse enters window, or just sent WM_TAKE_FOCUS.  Locally active won't take focus on the later.

**Comment by gijsbers** [comment]
Nearly always I can move the mouse into a tilda and have it focussed immediately.

There is this other funny behavior. Tilda has this useful option `Display on all workspaces`. But if I then switch to a new empty workspace for the first time tilda is not focussed and Alt+Tab does not give me a switch window. To focus it I have to move the mouse into the tilda window or press its hotkey.

**Comment by gijsbers** [comment]
This works fine now.

**Comment by gijsbers** [comment]
This works fine now.
