### ISSUE TITLE
hotkeys not working

### ISSUE THREAD

**Issue by gijsbers** [bbidulock/icewm#186]
Since about less than a week sometimes global hotkeys don't work on an empty workspace. Difficult to reproduce. Seems that workspace had all windows closed, move to another, move back and can't use any hotkey. Have to click with the mouse on workspaces below.

**Comment by bbidulock** [comment]
IceWM manages the desktop.  It grabs keys on a child of root.  When focus is not set to this child of root, the keys do not work.

**Comment by gijsbers** [comment]
Uhm, on an empty desktop no global keys work? It normally does...

**Comment by bbidulock** [comment]
When there is no focused window IceWM assigns focus to the special child of root on which it has grabbed keys.  If, for some reason, it fails to do so, the keys will appear not to work.

**Comment by gijsbers** [comment]
This is fixed.
