### ISSUE TITLE
restart behavior is incorrect

### ISSUE THREAD

**Issue by gijsbers** [bbidulock/icewm#190]
When IceWM restarts it should not exhibit different behavior then if IceWM is started before any applications.

On  restart focus may change. Assume several running apps, one has focus, and a hotkey to restart IceWM. When pressing the hotkey IceWM restarts and focus shifts to a different app. Logical would be if focus remained with the same app.

When the tilda terminal is visible and active it is normally not shown on taskbar.
It has properties:

> _NET_WM_DESKTOP(CARDINAL) = 4294967295
> _NET_WM_STATE(ATOM) = _NET_WM_STATE_ABOVE, _NET_WM_STATE_STICKY, _NET_WM_STATE_SKIP_TASKBAR
> _NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL

However, after IceWM restarts tilda is shown on taskbar. If tilda option `Display on all workspaces` is enabled then taskbar pager preview shows tilda on all workspaces.
This seems incorrect and is ugly.

**Comment by bbidulock** [comment]
If it wants to not be displayed on the pager when sticky, it needs to set _NET_WM_STATE_SKIP_PAGER, or use a window type other than "Normal", so the later behaviour is correct.

Appearing on the task bar seems to be because Ice is not reading _NET_WM_STATE when first managing a window.

**Comment by bbidulock** [comment]
No, Ice is reading _NET_WM_STATE when first managing a window.  Dump those settings before and after the restart and see if there are any changes.

**Comment by bbidulock** [comment]
That might address it.  It was loading _WIN_STATE after _NET_WM_STATE when initially managing a window.

**Comment by gijsbers** [comment]
It is a bit better. After restart a mapped tilda is now only shown in the workspace pager preview on the workspace it was initially mapped on. This seems still incorrect as normally when I map tilda it is not show on the taskbar at all.

If I map tilda it has:

> _WIN_STATE(CARDINAL) = 1, 1023
> _NET_WM_STATE(ATOM) = _NET_WM_STATE_SKIP_TASKBAR

After restart this becomes:

> _WIN_STATE(CARDINAL) = 0, 1023
> _NET_WM_STATE(ATOM) = _NET_WM_STATE_SKIP_TASKBAR

Even though I have enabled `Display on all workspaces` tilda is only mapped on one.

Focus can still shift to a different app when I restart.

**Comment by bbidulock** [comment]
Ice makes no effort to leave focus where it was before startup or on restart.  The latest commit fixes losing the occupy-all-workspaces state on restart.

**Comment by bbidulock** [comment]
Focus is restored correctly to the last focused window on restart now.

**Comment by gijsbers** [comment]
Focus is restored correctly if it was given by clicking. Not if it was given by merely moving the mouse.

Tilda `Display on all workspaces` works, but after restart it is shown on all pager preview workspace buttons. 

If focus was with tilda and I switch to a new workspace then tilda loses focus. If that workspace was empty (apart from tilda) then tilda still doesn't have focus and nothing has.

**Comment by bbidulock** [comment]
Show the values of _NET_WM_STATE before and after restart (with focus by clicking, and focus by moving).  Also, does creating or destroying a window change the pager just after restart?

On changing workspaces, IceWM attempts to focus windows on a workspace that do not occupy all workspaces before those that do.  That was intentional.  Could maybe change to check for dock or desktop window type.

**Comment by gijsbers** [comment]
left to right moving
```
$ ./x
xprop -id 0x1800007
_NET_WM_STATE(ATOM) = _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_STICKY
xprop -id 0x1c00009
_NET_WM_STATE(ATOM) = _NET_WM_STATE_FOCUSED
xprop -id 0x1800007
_NET_WM_STATE(ATOM) = _NET_WM_STATE_FOCUSED, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_STICKY
xprop -id 0x1c00009
_NET_WM_STATE(ATOM) = 
```

left to right clicking
```
$ ./x
xprop -id 0x1800007
_NET_WM_STATE(ATOM) = _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_STICKY
xprop -id 0x1c00009
_NET_WM_STATE(ATOM) = _NET_WM_STATE_FOCUSED
xprop -id 0x1800007
_NET_WM_STATE(ATOM) = _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_STICKY
xprop -id 0x1c00009
_NET_WM_STATE(ATOM) = _NET_WM_STATE_FOCUSED
```

right to left moving
```
$ ./x
xprop -id 0x1800007
_NET_WM_STATE(ATOM) = _NET_WM_STATE_FOCUSED, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_STICKY
xprop -id 0x1c00009
_NET_WM_STATE(ATOM) = 
xprop -id 0x1800007
_NET_WM_STATE(ATOM) = _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_STICKY
xprop -id 0x1c00009
_NET_WM_STATE(ATOM) = _NET_WM_STATE_FOCUSED
```

right to left clicking
```
$ ./x
xprop -id 0x1800007
_NET_WM_STATE(ATOM) = _NET_WM_STATE_FOCUSED, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_STICKY
xprop -id 0x1c00009
_NET_WM_STATE(ATOM) = 
xprop -id 0x1800007
_NET_WM_STATE(ATOM) = _NET_WM_STATE_FOCUSED, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_STICKY
xprop -id 0x1c00009
_NET_WM_STATE(ATOM) = 
```

**Comment by gijsbers** [comment]
On changing workspaces, maybe IceWM attempts to assign focus to the taskbar with a WM_TAKE_FOCUS, but the taskbar never reacts to that. The focusable-non-focusing taskbar thwarts this design.

**Comment by bbidulock** [comment]
Are you sure that is the current version?  What is setting _NET_WM_STATE_STICKY?

**Comment by gijsbers** [comment]
yes. tilda. easy to check:
> git clone https://github.com/lanoxx/tilda.git
> grep -i -r stick tilda

**Comment by gijsbers** [comment]
ATM minimized windows are restored on icewm restart. Is annoying when after restart one has to minimize all these windows again. Problems started with commit 22f29da8b42668ee117f5101af7e28d774842052. That made minimized windows become hidden as well. This was fixed later, but minimization is not yet preserved.
