### ISSUE TITLE
IceWM restarts when right-clicking taskbar button of application that has dTitleBar: 0

### ISSUE THREAD

**Issue by marcelkorpel** [bbidulock/icewm#195]
Using version 1.4.2.712 in Arch Linux (using the AUR package), when I set `dTitleBar` to `0` within `winoptions` for a certain (set of) window(s), right-clicking the taskbar button of that application results in a restart of IceWM.

For instance, I added

    Navigator.dTitleBar: 0

to my `winoptions` and started Firefox. The title bar isn't shown, as expected. However, clicking on the taskbar button restarts IceWM (noticable by watching `htop`) instead of the window menu popping up. This setting does not affect other window buttons on the taskbar, nor is it a problem with the Firefox window alone (I tested with several applications).

This is different from hiding the title bar of *all* maximized windows using `HideTitleBarWhenMaximized=1` in `preferences`, as the behaviour is as expected in case of Firefox, but the same issue shows up when right-clicking urxvt taskbar buttons.

EDIT: The same happens when trying to open a menu of a toolbar button. E.g., my `toolbar` contains

    menu Terminals xterm {
      prog alsamixer xterm urxvt -geometry 80x25 -e alsamixer
    }

and when I click on the terminal icon, IceWM restarts.

It also results in all windows being drawn ±25 pixels lower.

**Comment by marcelkorpel** [comment]
Your commit solves the issue of IceWM restarting when right-clicking a taskbar button of a window without a title bar, but the second issue (described in the edit, probably unrelated) is still there.

BTW, do you know how to get a notification about commits mentioning an issue? I only coincidentally opened this issue again, seeing there's a commit that could solve it. Otherwise, can you please add a comment when committing something that might solve an issue, so I get notified? Thanks.

**Comment by gijsbers** [comment]
@marcelkorpel better not edit, but add a new comment. BTW try Watch or Github Help.

The 25 pixels lower is a useful feature to warn a crash happened, otherwise they go unnoticed.

Thanks a lot for reporting this. Should work now.

**Comment by marcelkorpel** [comment]
Okay, I'll submit a comment next time, to keep things clear.

The menu is now shown, too. Thanks!
