### ISSUE TITLE
Specifying both class and name in winoptions results in erroneous behaviour

### ISSUE THREAD

**Issue by marcelkorpel** [bbidulock/icewm#197]
I have several windows I want to style using `winoptions`. They have classes and names like

    
    WM_CLASS(STRING) = "Mail", "Thunderbird"
    WM_CLASS(STRING) = "evince", "Evince"
    WM_CLASS(STRING) = "explorer.exe", "Wine"

However, when using the `window_class.window_name.option: argument` syntax the window properties are not set accordingly:

    Thunderbird.Mail.dTitleBar: 0
    Evince.evince.geometry: 1075x995+0+0
    Wine.explorer\.exe.fClose: 0

When only specifying the class name *or* only specifying the window name everything works as expected. This is a long-standing bug, as it was already present in IceWM 1.3.8.

**Comment by gijsbers** [comment]
The [manual](https://github.com/bbidulock/icewm/blob/icewm-1-4-BRANCH/doc/icewm.adoc#window-options-updated-2017-11-18) was out of sync about winoptions. Swap the order of class and name with name first. Usually you won't need to specify both. The list of options is also updated.
