### ISSUE TITLE
Window closer button causes program to terminate prematurely

### ISSUE THREAD

**Issue by marcelkorpel** [bbidulock/icewm#201]
When pressing the closer button on window decorations several programs terminate abruptly. E.g., opening a new message window in Thunderbird and making changes in it, a click on the message window's closer button shows up a dialog asking whether or not I want to save the message, and within a second the complete application terminates.

At first I thought this was [a bug in Thunderbird](https://bugzilla.mozilla.org/show_bug.cgi?id=1417283), but the exact same behaviour can be seen in LibreOffice.

**Comment by gijsbers** [comment]
Works fine for me sofar. What is the last git commit number you have?
Could you try to get the same effect with icehelp when you start it from valgrind like this:

    valgrind icehelp --sync

**Comment by marcelkorpel** [comment]
784 is the last number I have, but it was already there with 725.

Should icehelp (or valgrind) show a confirmation dialog when pressing the window closer?

[icehelp.txt](https://github.com/bbidulock/icewm/files/1503424/icehelp.txt)

**Comment by Code7R** [comment]
I see very similar (probably same) effects with all program exit confirmation dialogs now. Like hexchat or vim.

Very easy to reproduce with gvim. Start gvim, change something (but not saving) and push the close button. Gvim window disappears (heh?), the save-the-file dialog appears instead (heh?) but does not get the focus (heh?) and the previous window is focused instead. And pushing the "Cancel" button in that dialog makes the whole application die (receives SIGTERM).

**Comment by gijsbers** [comment]
This commit makes things work fine for Gvim and LibreOffice. Please verify, thx!

**Comment by Code7R** [comment]
Thanks. At least the killing behavior is gone. But the window still disappears from the taskbar when you hit Cancel. The only way to reach is through window list or quickswitch selector.

**Comment by gijsbers** [comment]
All should be fixed now.
