### ISSUE TITLE
Scroll wheel events are not always passed to a window

### ISSUE THREAD

**Issue by marcelkorpel** [bbidulock/icewm#202]
In several programs scrolling up or down doesn't result in the expected behaviour. This happens at least in Evince and LibreOffice windows. Only after leaving the window, hovering over another one (which in my case gives focus to that one, using the 'quiet sloppy focus' mode), and going back to the Evince or LibreOffice window the mouse events of the scroll wheel operate correctly.

**Comment by gijsbers** [comment]
This seems to work better now since the latest focus improvements. Could you try again?

**Comment by marcelkorpel** [comment]
I now get

    misc.cc: In function ‘void tlog(const char*, ...)’:
    misc.cc:392:6: error: redefinition of ‘void tlog(const char*, ...)’
     void tlog(char const *msg, ...) {
          ^~~~
    misc.cc:99:13: note: ‘void tlog(const char*, ...)’ previously defined here
     #define msg tlog
                 ^
    misc.cc:382:6: note: in expansion of macro ‘msg’
     void msg(char const *msg, ...) {

**Comment by marcelkorpel** [comment]
Thanks for the quick fix, but now it seems the Ukrainian translation file is corrupt:

    uk.po:781: number of format specifications in 'msgid' and 'msgstr' does not match
    /usr/bin/msgfmt: found 1 fatal error
    uk.po: 302 translated messages, 7 fuzzy translations, 9 untranslated messages.

(I only see one instance of `%s` in the translation, whereas there are five in the original text, if I'm not mistaken.)

**Comment by gijsbers** [comment]
Try `make -k; make -k install`. The -k flag says to ignore errors.
Or else try `cd src; make -k; make -k install`.

**Comment by marcelkorpel** [comment]
That doesn't work: it seems to compile everything, but `make -k install` ends with the message

    make: Target 'install' not remade because of errors.

**Comment by gijsbers** [comment]
`touch po/uk.gmo` creates the faulty file and then it should work.

**Comment by marcelkorpel** [comment]
Indeed. And it looks like scroll wheel events are now passed on correctly, but in one case the behaviour is still erroneous: when I open a LibreOffice Calc spreadsheet, I can scroll through it, but when I open another non-maximized window (like Sublime Text), give it focus by hovering over it, then hovering back over the spreadsheet window, the scroll wheel events are gone again. I can also raise that window by clicking on the taskbar button, but no scroll wheel events, further. Only after raising another window by clicking the taskbar button and then going back to LibreOffice, it works again.

**Comment by gijsbers** [comment]
@marcelkorpel Commit  0b2fcfa fixes every scroll wheel problem for me.
