### ISSUE TITLE
Strange artefacts in window title bar

### ISSUE THREAD

**Issue by marcelkorpel** [bbidulock/icewm#203]
Since I installed commit 810 there appear strange artefacts in the window title bar of LibreOffice, always in the same location. I managed to capture two of them in a screenshot, the top one is after opening LibreOffice and raising a urxvt window, the second one after opening a document. One time a copy of the horizontal ruler appeared after closing a document.

I never had this issue in the previous version I used, commit 784, so I guess the bug was introduced after that one.

![artefacts](https://user-images.githubusercontent.com/367181/33294002-0a4dee50-d3cf-11e7-8f14-e136c92e6a4e.png)

**Comment by gijsbers** [comment]
Thx! Some recent changes to pixmap handling seem to have introduced this...
Does your icewm produce errors about X_CopyArea?

**Comment by marcelkorpel** [comment]
Indeed, several instances of

    18:34:24.225: IceWM: X error X_CopyArea(0x0): BadDrawable (invalid Pixmap or Window parameter)
    18:34:24.225: IceWM:    Resource id 0x0
    18:34:24.225: IceWM:    Failed request 2519
    18:34:24.225: IceWM:    Next request now 2551
    18:34:24.225: IceWM:    Last processed 2519

**Comment by gijsbers** [comment]
Unfortunately I cannot reproduce your problem, but I may have improved it a bit, so you could try again. At least all of the X_CopyArea errors should be gone now, I think. What is the name of the theme of the 2 screendumps?

**Comment by marcelkorpel** [comment]
I'll try and see.

> What is the name of the theme of the 2 screendumps?

"metal2", but as I posted (that comment is gone, for whatever reason) it doesn't matter which theme you use, it is also exhibited when using Haiku.

**Comment by marcelkorpel** [comment]
Alas, it's still there, only smaller. This is the top right of a FileZilla window (using the [Haiku theme](https://www.box-look.org/p/1018245/)):

![icewm-artefact3](https://user-images.githubusercontent.com/367181/33455702-26cae3b2-d61d-11e7-8bc0-9e70e0fc1154.png)

No errors about X_CopyArea, though.

**Comment by marcelkorpel** [comment]
And I just opened makemkv (and a terminal window) and got this:

![icewm-artefact4](https://user-images.githubusercontent.com/367181/33456191-ee865d72-d61e-11e7-9030-345f54fa5ec3.png)

(Note the malformed copy of the terminal window's title bar **and** the window title centered between the window icon and the artefact.)

**Comment by gijsbers** [comment]
Does commit 6c277f8  help you?

**Comment by marcelkorpel** [comment]
No, I still get artefacts.

**Comment by gijsbers** [comment]
New git commit. In file `src/ypaint.cc` in `Graphics::repHorz` on line 1196 you'll see a `#if 1`. You could try setting that to `#if 0`. That would give you old behavior which may work better.

**Comment by gijsbers** [comment]
What is your output of `icewm --postpreferences | grep Title` ?

**Comment by marcelkorpel** [comment]
> In file `src/ypaint.cc` in `Graphics::repHorz` on line 1196 you'll see a `#if 1`. You could try setting that to `#if 0`.

You probably meant line 966? Setting that conditional to `#if 0` results in IceWM hanging after opening the first terminal windows (in `.xprofile`), clearly when trying to draw the title bars. I had to kill `icewm-session` and rebuild IceWM to get a working instance.

> What is your output of `icewm --postpreferences | grep Title`?

    7:RaiseOnClickTitleBar=1
    39:HideTitleBarWhenMaximized=0
    160:TitleBarMaximizeButton=1
    161:TitleBarRollupButton=2
    294:TitleBarCentered=0
    295:TitleBarJoinLeft=0
    296:TitleBarJoinRight=0
    304:TitleBarHeight=25
    305:TitleBarJustify=50
    306:TitleBarHorzOffset=0
    307:TitleBarVertOffset=0
    321:TitleButtonsLeft="s"
    322:TitleButtonsRight="xmi"
    323:TitleButtonsSupported="sxim"
    324:TitleFontName="-*-sans-medium-r-*-*-*-120-*-*-*-*-*-*"
    325:TitleFontNameXft="sans-serif:size=10:bold"
    369:ColorNormalTitleButton="rgb:C0/C0/C0"
    370:ColorNormalTitleButtonText="rgb:00/00/00"
    377:ColorNormalTitleBar="#D8D8D8"
    378:ColorNormalTitleBarText="#000000"
    379:ColorNormalTitleBarShadow=""
    380:ColorActiveTitleBar="#D8D8D8"
    381:ColorActiveTitleBarText="#000000"
    382:ColorActiveTitleBarShadow=""
    IceWM: Менеджер окон уже запущен, используйте  -replace для его перемещения

**Comment by gijsbers** [comment]
Okay, thanks. New try for old behavior. Forgot that height is now unsigned (an unfornate decision).

**Comment by marcelkorpel** [comment]
I'm a bit confused now: you're talking about `repHorz` but changed `repVert` in your latest commit. I get a working IceWM with it, but still artefacts. If I change the conditional in `repHorz` IceWM still hangs, but you didn't change anything there, so that's kind of expected. Shouldn't you have changed `repHorz` instead?

**Comment by gijsbers** [comment]
repHorz instead...

**Comment by marcelkorpel** [comment]
You don't have an `h` parameter there, so compilation fails. With `w` it compiles, but I still get artefacts in title bars.

**Comment by gijsbers** [comment]
New commit always clears entire titlebar when `Look = metal`, 
like for metal2 and Haiku.
You could also try themes with different looks. 
pixmap, flat and gtk will have similar behaviour to metal.
win95, warp4, warp3, nice and motif should be OK.
Also OK are themes which use gradients, like CrystalBlue.

```
CrystalBlue/default.theme:Look="pixmap"
CrystalBlue/default.theme:Gradients="menubg.xpmdialogbg.xpm"
Helix/default.theme:Look=gtk
Infadel2/Ergonomic.theme:Look=pixmap
Infadel2/Overloaded.theme:Look=pixmap
Infadel2/default.theme:Look=pixmap
NanoBlue/default.theme:Look=flat
NanoBlue/default.theme:Gradients="menusep.xpmmenubg.xpmmenusel.xpmswitchbg.xpmtaskbarbg.xpmdialogbg.xpmtaskbuttonbg.xpmtaskbuttonactive.xpmtaskbuttonminimized.xpmtoolbuttonbg.xpmworkspacebuttonbg.xpmworkspacebuttonactive.xpm"
Natural/default.theme:Look=gtk
default/default.theme:Look=pixmap
gtk2/default.theme:Look=gtk
icedesert/default.theme:Look=pixmap
metal2/default.theme:Look=metal
motif/default.theme:Look=motif
nice/blue.theme:Look=nice
nice/default.theme:Look=nice
nice2/default.theme:Look=pixmap
warp3/default.theme:Look=warp3
warp4/default.theme:Look=warp4
win95/default.theme:Look=win95
yellowmotif/default.theme:Look=motif
```

**Comment by marcelkorpel** [comment]
Same problem, only the artefact is now always grey:

![artefact-icewm](https://user-images.githubusercontent.com/367181/33530830-72178658-d885-11e7-9094-5de0027dedc7.png)

What do you mean with those different themes? I tried several of them and they all exhibit this issue, so it is not theme-related. E.g., when trying icedesert I get this in the title bar when activated/not activated:

![artefact-icewm2](https://user-images.githubusercontent.com/367181/33530914-57ed5b6c-d886-11e7-93bb-06845edc661a.png)

(I suspect this is the title bar of win95-theme leaking through, which I tried just before icedesert.)

**Comment by gijsbers** [comment]
That is helpful. I would be surprised if warp3, warp4, win95 and motif also have the same artefacts. Is that really so? 

I'm still unsure where the bug resides. It could be icewm, the X server or even your graphics card in your PC. I made a new test. It tries to paint the titlebar in short pieces.

What is the output of `Xorg -version`?

Is there another computer which you can test icewm on? You run Arch right?
My Arch runs icewm fine without artefacts.

Thanks for all your patience 👍

**Comment by Code7R** [comment]
I can reproduce it too. Started happening a couple of weeks ago but appeared rarely, now quite often, but still not sure how to trigger it. Happens with the default theme and blueHeart. Using a Geforce 750ti with Nouveau driver, but this configuration has been reliable for a while now (apart from Debian Unstable updates, of course).

![still_cropped_pixmap_in_titlebar](https://user-images.githubusercontent.com/10660264/33570131-21e4c5e0-d92c-11e7-8ca6-30dba56d73ca.png)


```
X.Org X Server 1.19.5
Release Date: 2017-10-12
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.9.0-4-amd64 x86_64 Debian
Current Operating System: Linux zombie 4.13.0-trunk-amd64 #1 SMP Debian 4.13.1-1~exp1 (2017-09-11) x86_64
...
xorg-server 2:1.19.5-1 (https://www.debian.org/support) 
Current version of pixman: 0.34.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
```

**Comment by gijsbers** [comment]
@Code7R That you can reproduce it is good news. I rules out X11 and HW.
From the blueHeart theme you show I get another clue. It purposely draws
The titleAR.xpm too far left. Therefore in YFrameTitleBar::paint on line 535
the values for width() and height() must be incorrect from the real window.
Since you're a developer and debugger savvy you could fix this! :-)
You could for instance use XGetWindowAttributes to query the real values
and compare those.

**Comment by marcelkorpel** [comment]
Yeah, I run Arch Linux with an Intel processor (and Intel driver). And as Code7R pointed out, it only happened since a few weeks with that new commit, the older ones didn't have this.

And you're right, it does not appear in win95 theme, but it shows up in Motif theme (as a grey block separated from the rest of the title bar with a vertical divider):

![artefact-icewm3](https://user-images.githubusercontent.com/367181/33576474-3c0681fc-d940-11e7-8569-1c6127263c85.png)

Same versions of Xorg and pixman as in Code7R's screenshot (BTW, @Code7R how did you run `Xorg` within a terminal window? Mine complains "/usr/lib/xorg-server/Xorg.wrap: Only console users are allowed to run the X server").

It might also be interesting to know that the size of the bar seems pretty consistent, now: it's always **that** size in MakeMKV, always a much smaller one in FileZilla.

Thanks anyway, Mr Gijsbers, for your perseverance. ;) And although I'm a developer myself, my C++ foo is more or less nonexistent, so I can't help you with that (though I'm learning).

**Comment by marcelkorpel** [comment]
@Code7R Oh wait, you didn't: because you posted the screenshot of a terminal window above the console output, I thought it was part of the screenshot ;).

**Comment by gijsbers** [comment]
The impression sofar is that resizing titlebars does not properly propagate either the width of the titlebar or the position of the right corner buttons. Hopefully debugging could figure that out. The mystery here is how event handling causes this bug.

Commit 24fa54a658a8ef86500a728e01178ac5465acc38 is a new approach to computing this position which is more greedy in getting a rightmost position. This may give more defined titlebar drawing, but your testing should tell us that. Works for me, which doesn't prove much.

**Comment by marcelkorpel** [comment]
My first few tests reveal no artefacts for now, the titles are correctly centered in their title bars. We'll have to wait and see if this will endure.

**Comment by gijsbers** [comment]
Jolly good! Can we celebrate this with a screenshot?? ;-)

**Comment by marcelkorpel** [comment]
![no-more-artefacts](https://user-images.githubusercontent.com/367181/33675642-899b7340-dab3-11e7-9bdb-43606c5d4d58.png)
