### ISSUE TITLE
No taskbarless/iconless/menuless mode anymore

### ISSUE THREAD

**Issue by Code7R** [bbidulock/icewm#206]
In the last release, we had the possibility to disable the taskbar, disable icons and also turn off the context menu access, if I remember correctly.

Those options were dropped in the commit 45512fb6be7cd33200cdf259c904070a3216f3b0 and my comment was never replied.

Can anyone explain the reason, and if there is none, shall I try to restore parts of this functionality?

**Comment by gijsbers** [comment]
1. You can easily turn off the taskbar with `ShowTaskBar=0`.
More taskbar options with `icewm --postpreferences | grep Show | grep Task `.

2. Same for icons `icewm --postpreferences | grep Icon | grep Show`:
```
TaskBarShowWindowIcons=1
PagerShowWindowIcons=1
ShowMenuButtonIcon=1
```

3. `ShowWindowList=0`

4. We want to have as few ifdefs as possible. Primarily only for portability reasons. The taskbar & co are key features of Ice. If one doesn't want them one could easily use some other WM. (One idea is to write a package install script to modify these preferences file with different defaults.) See [commit comments](https://github.com/bbidulock/icewm/commit/0a08273caa31108981879b81754798bad7a4cafc#commitcomment-25466922).

**Comment by Code7R** [comment]
Ok, sounds like a plan. Actually, this changes comes quite handy, it was always PITA to maintain a special set of icewm binaries.

I still see a few glitches here and there (e.g. no icon in quickswitch in horizontal mode although space preserved, and always icon in vertical mode even if disabled... which might be my fault after all, I will have to check this).

I think there should also be something for the transition phase. I imagine something with a shell script called "icewm-lite" which invokes icewm with --config=some_cfg_with_different_defaults_for_lite_mode . I need to check how it behaves WRT other config files, though.

**Comment by Code7R** [comment]
Rolled out in Debian Experimental, should be good enough.
