### ISSUE TITLE
Automated icon name rewriting

### ISSUE THREAD

**Issue by Code7R** [bbidulock/icewm#207]
Hi,

as a packager of icewm, I want to have a possibility to exchange specific icons without having to touch the configuration. The background is, that there are sometimes different programs accessible via common redirector script and/or the alternatives meta-system which provides universal shortcuts like
x-www-browser, sensible-editor, etc. And depending on which backend is used, I would like to have the icon exchange, rather than finding some universal one or hardcoding a potentially wrong icon (like it happens today).

What I have in mind is a kind of persistent filter. A program which icewm would run in background and observe its stdin/stdout. When some icon is marked with a special token (for example: "+x-www-browser") the name would be sent as a line to our filter, and the response would be the real name of the icon.

This approach is supposed to make it easily customizable without sacrificing performance.

Another approach I have also considered would be to have a kind of automatic icon name resolution. I.e. most usecases for this requirement are handled via symlinks. The icewm code could simply follow the symlink chain until it finds the real executable file, and then derive the icon name from it. This is something which should be easy to implement and I would try that in the next days (unless somebody assigns this issue to himself).

**Comment by gijsbers** [comment]
My first thought is that having a separate process just for the dedicated task of filtering icon names is rather a high cost for a small isolated feature. So you want things to be extensible. Then a scriptable extension sounds better. Consider some nice lightweight scriptable language. Lua? This could be useful for future expansion, like sorting taskbar task buttons, winoptions-like features, window placement and focus behavior.

**Comment by Code7R** [comment]
Integrating a slave process might be overkill, yes.
I thought a bit more and found no best trade-off here. Adding a plugin interface is possible (the perl integration in hexchat comes to my mind) but for the very few usecases I am rather reluctant to follow that proposal.
Anyhow, I added a simple solution for that and it seems to do the job, good enough for me. It still can be optimized, for example by shifting the path resolution into the code of icon cache, so the repeated readlink syscalls are avoided. But IMHO this is nice-to-have.
