### ISSUE TITLE
Tray Icons sometimes not showing icon.

### ISSUE THREAD

**Issue by SolisX** [bbidulock/icewm#209]
Hello Everyone,

Tray Icons sometimes not showing icon tested o icewm 1.4.2.935. This happened with wicd-client and
Screengrab.

![screen1](https://user-images.githubusercontent.com/15175058/34174741-fcee4480-e4c7-11e7-84a2-9f2d20d88587.jpg)

**Comment by gijsbers** [comment]
For me it works fine even with wicd-client and screengrab:
![wicd-tray](https://user-images.githubusercontent.com/4169687/34277416-df624382-e6a5-11e7-95c9-b27878a0f61f.png)

1. When you hide the taskbar and then unhide it is it the same or changed?
2. When you drag some terminal over it does it change?
3. If you `icewm -r` a few times are things different?
4. Is it always only wicd-client and screengrab or do other apps also have it (hexchat / vlc / cbatticon / pasystray)?

**Comment by SolisX** [comment]
Hello Gijsbers,

The wicd problem appears for me when i try to disconnect and reconnect.

1).No
2).No
3).I'll try that.
4). It's only the 2 i mentioned as far as i know.

**Comment by gijsbers** [comment]
What versions of screengrab and wicd-client do you have? I get:
```
screengrab 1.97  (2.0-beta1)
wicd 1.7.4
```
and how can I reproduce your OS setup?

**Comment by SolisX** [comment]
I'm running Slackware 14.2 64bit with multilib support. My version of wicd is 1.7.4 and screengrab
is 1.2.1. I will try and upgrade screengrab.

Also wicd seems to be working fine with most recent version of icewm. So i will close this  issue.

**Comment by bbidulock** [comment]
Still a problem for me.

**Comment by SolisX** [comment]
I guess i spoke to soon. I'm now having the same issue. If disconnect wicd then click on the collapse button the issue appears.

**Comment by SolisX** [comment]
I'm still getting corruption with the wicd icon.

**Comment by SolisX** [comment]
I still get corruption when i first log in to icewm. However when i select a new change to a new icewm theme the wicd icon fixes.

You can watch the video to see what i mean.

https://streamable.com/541bt

**Comment by gijsbers** [comment]
Thx for the cool and helpful vid! Sofar only wicd-client and pidgin in #265 seem to have this problem. Both use GTK2. If all other tray apps don't have this problem then the bug is likely with GTK2. This commit enables backing store to keep the icon intact, but the icon for wicd-client and pidgin may sometimes not reflect the true status of the application.

**Comment by SolisX** [comment]
No problem. It's strange that once i change the theme the updates to the wicd icon work properly. It's only the 1st start of icewm that's it's not working on. 

Should i consider this bug fixed and close this bug?

**Comment by SolisX** [comment]
Hello Everyone,

Just wanted to mention that if i use

wicd-client -t &
pasystray &

sleep 2
icewm -r

in the startup file wicd updates properly on icewm-1.4.2-1357.
