### ISSUE TITLE
Gradients and window list?

### ISSUE THREAD

**Issue by SolisX** [bbidulock/icewm#212]
Hello Everyone,

I having an issue with window list.
![screen03](https://user-images.githubusercontent.com/15175058/34393217-ef3c992e-eb1e-11e7-83bb-c9c57d3e9d8e.png)

I don't remember having an issue on 1.3.12. It looks like it's using a xpm for windows list but i never had one.

Window list on icewm 1.3.12.
![screen04](https://user-images.githubusercontent.com/15175058/34393557-54e85a72-eb21-11e7-9b29-90d882591fa7.png)

**Comment by Code7R** [comment]
And what's the theme you are using?

**Comment by SolisX** [comment]
I'm using UltraBlack-Blue.  Also happens with Crystal-Blue which is included with the default themes.

**Comment by gijsbers** [comment]
Looks like it.

**Comment by SolisX** [comment]
Seems to work for me.
