### ISSUE TITLE
Icons get truncated when they are resized

### ISSUE THREAD

**Issue by marcelkorpel** [bbidulock/icewm#216]
Some icons in the menu, toolbar and windows are truncated after a few lines of pixels. This happens only when they are resized from a larger size than 16x16. Icons at a native size don't get truncated:

![icon-truncation](https://user-images.githubusercontent.com/367181/35187280-d3766a42-fe21-11e7-962c-dad94ab243da.png)

**Comment by marcelkorpel** [comment]
Possibly related, at least to [this comment](https://github.com/bbidulock/icewm/issues/215#issuecomment-359107735) by @gijsbers, my background gets distorted when being a JPEG that needs to be shrunk: a smaller JPEG or a larger PNG file works as expected, but when I load a film still of 1920x1080 on my 1280x1024 screen, I get this:

![background-distortion](https://user-images.githubusercontent.com/367181/35187668-c759fba6-fe27-11e7-84e5-2d84d96a03f2.jpg)

**Comment by bbidulock** [comment]
The JPEG is a different issue, please add separately.

**Comment by bbidulock** [comment]
On the icon issue, do you know whether those are .xbm, .png, or WM_HINTS icons?

**Comment by marcelkorpel** [comment]
Regarding the icons: some are .xpm, some are .png.

I'll file a separate issue about the jpeg background.

**Comment by bbidulock** [comment]
The icon clipping has nothing to do with the icons themselves, nor their scaling: the drawable that they are being composited upon is only 3 pixels high.  This is the double-buffered pixmap for drawing on titlebar, menu items, taskbar items, etc.  When YIcon::draw is called, it is called with a Graphics object that is associated with a drawable that is 3 pixels high.

The out of bounds errors in the attached xerrors file show the issue.

[.xerrors.txt](https://github.com/bbidulock/icewm/files/1649982/default.xerrors.txt)
