### ISSUE TITLE
Background gets distorted when it is a shrunk JPEG image

### ISSUE THREAD

**Issue by marcelkorpel** [bbidulock/icewm#217]
Related to [this comment](https://github.com/bbidulock/icewm/issues/215#issuecomment-359107735) by @gijsbers, my background gets distorted when being a JPEG that needs to be shrunk: a smaller JPEG or a larger PNG file works as expected, but when I load a film still of 1920x1080 on my 1280x1024 screen, I get this:

![background-distortion](https://user-images.githubusercontent.com/367181/35187668-c759fba6-fe27-11e7-84e5-2d84d96a03f2.jpg)

**Comment by marcelkorpel** [comment]
Alas @gijsbers, I still see this issue with the [same image](https://image.tmdb.org/t/p/original/zoHgrnMD0j6WqdCBLHiopvq7iJy.jpg).

**Comment by gijsbers** [comment]
Ah! You reported a different issue than my comment! :-)
This issue is about the fact that the yximage module doesn't yet support JPEG images in other formats than RGB like your grayscale image.
