### ISSUE TITLE
Issue with gradients

### ISSUE THREAD

**Issue by SolisX** [bbidulock/icewm#219]
Hello Everyone,

The gradients look a bit funny for me.

![screen03](https://user-images.githubusercontent.com/15175058/35373444-66df1796-016c-11e8-89aa-329e210e27b2.png)

![screen04](https://user-images.githubusercontent.com/15175058/35373447-6cbf6cec-016c-11e8-943d-87970d9c5ea3.png)

**Comment by bbidulock** [comment]
Maybe a silly question, but is the theme identically defined in both?

**Comment by SolisX** [comment]
It should be. The only thing i did was compile the current version of icewm. Then i uninstalled icewm-1.3.12 and installed icewm-1.4.1081.

**Comment by gijsbers** [comment]
The artefacts are due to yximage::upscale using a nearest-neighbor algorithm for enlarging a gradient, where a bicubic interpolation algorithm would be appropriate.
You can still configure icewm with --enable-gdk-pixbuf to avoid all these problems.

**Comment by SolisX** [comment]
Ok i tried that and it seems fixed to me.
