### ISSUE TITLE
Spooky window in taskbar for vlc tooltip

### ISSUE THREAD

**Issue by Code7R** [bbidulock/icewm#220]
When VLC plays a video and cursor hovers over the progress bar (so the time information is shown as tooltip) the taskbar gets an additional window called "vlc". When the tooltip disappears (cursor is moved) the taskbar entry disappears too.

**Comment by gijsbers** [comment]
Can't reproduce this anywhere.

**Comment by Code7R** [comment]
Well, for me it it's perfectly reproducible even in Xephyr (default AC or cmake config, does not matter).
See attached debug output, basically the moments around "SET FOCUS" is when the tooltip gets active or inactive.

[log.gz](https://github.com/bbidulock/icewm/files/1713735/log.gz)

**Comment by Code7R** [comment]
Little example...

![screeni](https://user-images.githubusercontent.com/10660264/36066727-e4e17c82-0ea6-11e8-9eeb-42ab228619de.png)

**Comment by gijsbers** [comment]
I believe you! :) But could create a new VM (which iso?) and write a script which sets up the VM until it reproduces this effect and then give me the VM setup script?

**Comment by Code7R** [comment]
That issue is really spooky. It is not easy to reproduce it. I saw it a few times last week on a laptop which is rarely rebooted. Now, I cannot recreate it no matter what I do, so there is basically no point in bisecting.

If the situation remains like this than I can live with it until I catch it one day (hopefully on a system with working dev environment).
