### ISSUE TITLE
titleAR.xpm and titleIR.xpm not showing up.

### ISSUE THREAD

**Issue by SolisX** [bbidulock/icewm#221]
Hello Everyone.

This on icewm 1.4.2.1086.

![screen07](https://user-images.githubusercontent.com/15175058/35441809-efc241c6-0272-11e8-9c62-94755966784a.png)

It should look like this.
![157309-1](https://user-images.githubusercontent.com/15175058/35785401-18591f92-09ee-11e8-87f1-870a34516787.jpg)

**Comment by gijsbers** [comment]
Which theme? What did you expect to see? Why is this a problem?

**Comment by SolisX** [comment]
The theme is SC-90. Here is a link to it.

https://www.opendesktop.org/p/1018190/

It should look like this.

![157309-1](https://user-images.githubusercontent.com/15175058/35785392-07dc34ec-09ee-11e8-8f0a-32ecfafa43ab.jpg)

**Comment by gijsbers** [comment]
Are you sure this refers to title[AI]R.xpm, not title[AI]L.xpm? The right one appears to be drawn, right? It's the left one which appears to be missing, not?

**Comment by SolisX** [comment]
In the SC-90 folder it's titleAR.xpm and titelR.xpm that are not shown. There is no [AI]. 
This issue happens with illuminate-ice. And it's the same titleAR.xpm and titleIR.xpm.
It's the xpm next to the minimizeA.xpm.

**Comment by gijsbers** [comment]
SC-90 looks better for me now.

**Comment by SolisX** [comment]
Yeah it's working now.
