### ISSUE TITLE
DesktopBackgroundCenter. Error when centering the small image.

### ISSUE THREAD

**Issue by arsonoff** [bbidulock/icewm#223]
One monitor (1600x1200).
DesktopBackgroundCenter=1, DesktopBackgroundScaled=0, DesktopBackgroundImage=image<screen_mode.png

Full size image (1600x1200)
[![full_size.png](https://s10.postimg.org/ji3xx7fex/full_size.png)](https://postimg.org/image/uugjezo3p/)
Half size image (800x600)
[![half_size.png](https://s10.postimg.org/49e0jgw15/half_size.png)](https://postimg.org/image/tfeyqaxb9/)

P.S.
The requirement of libpng>1.6 is how important?
The last CentOS-7.4 - libpng-1.5.13. 
Also compiled icewm with libpng-1.6.34, did not notice a difference.

**Comment by gijsbers** [comment]
Thanks for submitting this issue! Should be fixed now.
