### ISSUE TITLE
Gray background after start of compton

### ISSUE THREAD

**Issue by arsonoff** [bbidulock/icewm#224]
IceWM 1.4.2.1086 (default ./configure)
The problem is similar to this - https://github.com/chjj/compton/issues/162
I should use hsetroot/feh instead of icewmbg.
At execute from a command line (icewmbg after compton or compton after icewmbg ), there is a error:
`[    15.23 ] error    9 BadDrawable  request   14 minor    0 serial   6330: "BadDrawable (invalid Pixmap or Window parameter)"`

**Comment by gijsbers** [comment]
icewmbg does set _XROOTPMAP_ID:
```
$ xprop -root | grep _XROOTPMAP_ID
_XROOTPMAP_ID(PIXMAP): pixmap id # 0xc00010
```

**Comment by gijsbers** [comment]
This fixes the problem for me.

**Comment by arsonoff** [comment]
OK
