### ISSUE TITLE
Bug at drag mouse on GTK3 toolbar/titlebar

### ISSUE THREAD

**Issue by arsonoff** [bbidulock/icewm#225]
CentOS-7.4, IceWM 1.4.2.1086, gtk3-3.22.10, evince-3.22.1, geany-1.31

It is shown in GTK3 applications, for example: evince - titlebar (CSD), geany - toolbar.
At drag by a mouse (the left button press) on toolbar/titlebar of a window.
Instead of movement of a window there is resize of a window (to left/right).
[![gtk3_titlebar.png](https://s10.postimg.org/e7yz5y5gp/gtk3_titlebar.png)](https://postimg.org/image/ih3p848px/)

**Comment by gijsbers** [comment]
I can only reproduce this for evince, which is serious enough, but do you also get this bug for other applications?

**Comment by mrbrainsample** [comment]
I get this bug with Valve's Steam client (which furnishes it's own titlebar).

Not sure when it started, but right now I'm using icewm 1.4.2.r1101.g93b38fc8.

**Comment by arsonoff** [comment]
> but do you also get this bug for other applications?

dconf-editor-3.22.3, gedit-3.22.0 -- titlebar (CSD)
glade-3.20.0, geany-1.31 -- toolbar (free space)
chromium-61.0.3163.100 -- tabbar (free space)

**Comment by gijsbers** [comment]
My current impression is that this is a deliberate feature of GTK-3/GDK-3.
It only occurs for GTK apps. If an app doesn't have IceWM resize borders then IceWM doesn't do interactive resizing with the mouse. So, unless proven otherwise, this looks okay sofar.

**Comment by arsonoff** [comment]
In other WM (icewm-1.3.8, hackedbox) or without WM works correctly (movement of a window).

**Comment by gijsbers** [comment]
This may be it. Please try, thx! :-)

**Comment by arsonoff** [comment]
OK
