### ISSUE TITLE
How to force IceWM to draw decoration (titlebar, borders) for applications with client side decoration?

### ISSUE THREAD

**Issue by arsonoff** [bbidulock/icewm#227]
For each application it is necessary to add an option to ~/.icewm/winoptions manually.

**Comment by bbidulock** [comment]
Not too sure about the issue here: could you describe more?

**Comment by arsonoff** [comment]
It is a question, not big problem.
There are more and more applications with CSD (evince, gedit, etc.) which look as white crow (without normal titlebar).
That all windows looked equally it is necessary to edit style of windows in gtk.css (to delete excess CSD) and to add for each application to winoptions
```
evince.dTitleBar: 1
evince.dSysMenu: 1
evince.dMinimize: 1
evince.dMaximize: 1
evince.dResize: 1
evince.dBorder: 1
```
I thought can they have some general class (or other criterion) that it was possible to make somehow so: "CSD.dTitleBar: 1"

Or I came not from that side and it is necessary to look for options in gtk.css?

**Comment by gijsbers** [comment]
I documented a possible solution in [the IceWM manual](https://github.com/bbidulock/icewm/blob/117ea4dc56aff6f301cfdf168b2eb968b8a7f3f4/doc/icewm.adoc#window-options-updated-2017-11-18):

>  .option: argument
>
> The last format sets a default option value for all windows.

Does that help you?

**Comment by arsonoff** [comment]
If to take your advice, then all windows will have titlebar/border (conky, splashscreens) and even taskbar!
Tried to add "TaskBar.dTitleBar: 0" - without result, though:
```
WM_CLASS(STRING) = "icewm", "TaskBar"
WM_NAME(STRING) = "TaskBar"
```
At the option "TaskBarAtTop=1" titlebar of taskbar it is not visible (border is visible), but near taskbar there is "dead band" to which it is impossible to move a window (in 1.4.2 it is possible)

How to remove titlebar of taskbar in the presence of an option ".dTitleBar: 1"?

**Comment by gijsbers** [comment]
Taskbar wm_name/class wasn't properly initialized on startup. Should now be configurable via winoptions.

It's not clear to me how it can be detected that an app is CSD or not.

**Comment by gijsbers** [comment]
Ah you could look at https://github.com/PCMan/gtk3-nocsd and
https://askubuntu.com/questions/961161/how-do-i-disable-client-side-decoration-globally-in-gnome

**Comment by arsonoff** [comment]
>icesh - control properties of windows

xprop:
```
WM_CLASS(STRING) = "urxvt", "URxvt"
WM_NAME(STRING) = "urxvt"
```
Execute `icewmhint URxvt.urxvt dBorder 0`. Look without changes.
Execute `icewmhint URxvt.urxvt layer OnTop`. Nothing.
Execute `icesh -class URxvt setLayer OnTop`. Works.

How to use the utility of icewmhint?

**Comment by gijsbers** [comment]
only setting dBorder 0 doesn't help as dResize must also be set to 0:

>  icewmhint URxvt.urxvt dBorder 0 URxvt.urxvt dResize 0

**Comment by arsonoff** [comment]
I seem understood: 

icesh - influences on all existing windows and does not influence on started later;
icewmhint - influences only on one window, started after executed of icewmhint (after that the exposed hints are cleaned);

I correctly understood? From the description of the commands it is not really clear.

**Comment by gijsbers** [comment]
That's right. These manpages are indeed unclear.

**Comment by arsonoff** [comment]
~~`icesh -class URxvt setLayer OnTop`~~
restart Xorg ~~(Even not Icewm!)~~
`icewmhint URxvt.urxvt dBorder 0`
start `urxvt` -- no border and OnTop! 
~~How?! I have rebooted Xorg!~~

Following start of icewmhint already correct.
