### ISSUE TITLE
How to configure Gmail in MailBoxPath

### ISSUE THREAD

**Issue by mastaiza** [bbidulock/icewm#229]
Hi help to configure gmail mail in MailBoxPath

**Comment by gijsbers** [comment]
Gmail won't work because IceWM doesn't support encrypted IMAP connections.

**Comment by mastaiza** [comment]
thank you for the answer

**Comment by Code7R** [comment]
Do you you demand a solution? If no, please close. If yes, please elaborate, have you check the alternatives? My apt knows at least those:

```
checkgmail - alternative Gmail Notifier for Linux via Atom feeds
mail-notification - mail notification in system tray

```

**Comment by gijsbers** [comment]
@mastaiza Thanks for your suggestion. It should work now. See [for help](https://github.com/bbidulock/icewm/blob/icewm-1-4-BRANCH/doc/icewm.adoc#mailbox-monitoring-updated-2018-03-04).
