### ISSUE TITLE
reboot confirmation dialog losing focus in front of xchat

### ISSUE THREAD

**Issue by Code7R** [bbidulock/icewm#23]
I have a little glitch to report. Repro steps:

X-Chat must be the only window on the current workspace. Press Ctrl-Alt-Del and click reboot or use the hotkey. The confirmation window appears on top of xchat but it does NOT gain the focus.

I am not an expert WRT icewm's window handling, do you know someone more appropriate to care about this issue?  Smells like some kind of concurency issue but it's only a wild guess.

**Comment by bbidulock** [comment]
It might be a little related to the java hack thing.  I noticed that the code does not really appear to conform to ICCCM 2.0 behaviour for focus handling, particularly when WM_TAKE_FOCUS is specified (as it is in both cases).  xchat is using gtk2 on my box, so I can't really think that xchat has a problem.  What is your focus-new-windows setting?

**Comment by Code7R** [comment]
Nope, sorry. Disabling Java hack didn't change anything. I use default focus behavior (Click to focus).

I also see similar behaviour with the Eclipse startup dailog (Workspace selection), it does never get focus when created. Another funny effect is that when I start eclipse from the Taskbar command line, I get a fake "Task Bar" entry in the quick-switch list, which disappears the next time when Alt-Tab is pressed.

**Comment by bbidulock** [comment]
I'm a sloppy focus guy.  I didn't mean that the java hack would fix anything.  It seems that the need for the java hack in the first place was some non-conformance in IceWM to ICCCM 2.0 on the basis of focus behavior.  So, can you not click in the confirmation window to have it take focus?

**Comment by bbidulock** [comment]
XChat is stealing focus.  The confirmation dialog should likely grab both the keyboard and the pointer when presented so that no other window can simply steal its focus.  Eclipse is a different issue.

**Comment by gijsbers** [comment]
@bbidulock How can i understand the non-conformance you mentioned? I'm chasing a focus bug and I wonder if i'm onto the same thing, but i also need to know how i can verify if my solution is correct. The case is that sometimes no application window has input focus, even though it should. Then Alt+Tab shows the focus is with the taskbar, which  in my view is incorrect as focus never needs to be set to the taskbar. This is for sloppy focus. I tracked it down to `YFrameWindow::getInputFocusHint()`. If we trace the history of this function then commit 5b844af67ed19f337edb2f5c13f55737e97686a7 introduces this function and it looks fine. Then commit 8d10c683e7550ddb3e4dd1dea21e327b0443f370 still makes sense to me. But then commit d3b00cc4ed07f4f55695b9b91b20e0e9b08d9cf7 reverses this with the comment "JDK7 focus fix". That commit says that if InputHint is False and WM_TAKE_FOCUS is absent then `input` is `true`. Now the flow in `YFrameWindow::avoidFocus()` no longer makes sense either. So in my view we should revert commit d3b00cc4ed07f4f55695b9b91b20e0e9b08d9cf7 to get back on the right track. If I do that then I can fix the taskbar-has-focus bug easily and always have correct sloppy focus. Comments?

**Comment by bbidulock** [comment]
Wrong solution to this problem.  The dialogs at issue should grab the pointer and the keyboard.

**Comment by bbidulock** [comment]
I can't get the logout confirmation dialog to lose focus in front of xchat now.  Please recheck and close if fixed.

**Comment by bbidulock** [comment]
@Code7R does this work now?  Plesae reopen if it doesn't.
