### ISSUE TITLE
How to hide net status?

### ISSUE THREAD

**Issue by CheckB** [bbidulock/icewm#230]
Hello.
I have: ubuntu 16.04 x64 and icewm latest build from sources.

1. ./configure --enable-gdk-pixbuf --prefix=/usr --sysconfdir=/etc
make -k
make -k install
nano ~/.xinitrc.
icewm

2. mkdir ~/.icewm
mv /usr/share/icewm/* ~/.icewm

3. preferences:
TaskBarShowNetStatus=0

<details> 
  <summary>Details: </summary>
    
![1](https://user-images.githubusercontent.com/34208261/36075804-e30fedda-0f64-11e8-87a8-357cd62b2789.png)

</details>

**Comment by Code7R** [comment]
Uhm, might be a side effect of my changes. Let me have a look.

**Comment by CheckB** [comment]
Everything works as it should. Thank you!
