### ISSUE TITLE
Default icewm configuration is obsolete

### ISSUE THREAD

**Issue by zhengqiang130** [bbidulock/icewm#232]
The problem I have is that tray notifications icons are not working correctly due old icewm configuration in /etc/icewm.

Problem is that if I click on first "system-monitor" column in systray the netstat output should appear in xterm but nothing happen because netstat is not available by default - netstat came from net-tools-deprecated but it is not installed. So maybe we can call "ss" instead of "netstat".

**Comment by Code7R** [comment]
@zhengqiang130 

IMHO that does not replace the functionality exactly (it's not cycling). And you also hardcode a linux-specific tool there. What do you think about https://github.com/Code7R/icewm/commit/746054698ebf12355e019cfda4d7152b6cdd4492 ?

**Comment by zhengqiang130** [comment]
@Code7R 

JFYI: your commands may be not equivalent : ss -ptuswxn

netstat -c also lists unix domain sockets. which the cmdline doesnt. the "x" option adds them back. the "n" option skips resolving.

And what about considering adding the "e" option to netstat and ss

**Comment by Code7R** [comment]
I am not so sure, and I don't want to decide that. My proposal skips the UDS explicitly because IMHO it's just spam for most people, and the network monitor bar also doesn't count that traffic.

Same for -e - I prefer less information here, not more. It still should fit into normal terminal screen, right?

**Comment by arsonoff** [comment]
preferences:
```
#  Command to run on Net status
# NetStatusCommand="xterm -name 'socket statistics' -title 'Socket Statistics' -hold -e ss"

#  WM_CLASS to allow runonce for NetStatusCommand
# NetStatusClassHint="ss.XTerm"
```
`xterm -name 'ss'...` for runonce
