### ISSUE TITLE
Xsession-errors in latest Icewm Debian Sid (from repository)

### ISSUE THREAD

**Issue by frankzen** [bbidulock/icewm#234]
I keep seeing these in xsession-errors

10:59:23.574: IceWM: X error X_GetWindowAttributes(0x180000C): BadWindow (invalid Window parameter), #252899777, +2, +0.
10:59:23.586: IceWM: X error X_ChangeWindowAttributes(0x180000C): BadWindow (invalid Window parameter), #252899779, +14, +0.
10:59:23.586: IceWM: X error X_ChangeWindowAttributes(0x180000C): BadWindow (invalid Window parameter), #252899780, +13, +0.
10:59:23.586: IceWM: X error X_ConfigureWindow(0x180000C): BadWindow (invalid Window parameter), #252899781, +12, +0.
10:59:23.586: IceWM: X error X_ChangeSaveSet(0x180000C): BadWindow (invalid Window parameter), #252899782, +11, +0.
10:59:23.586: IceWM: X error X_ReparentWindow(0x180000C): BadWindow (invalid Window parameter), #252899783, +10, +0.
10:59:23.586: IceWM: X error X_ChangeProperty(0x180000C): BadWindow (invalid Window parameter), #252899784, +9, +0.
10:59:23.586: IceWM: X error X_SendEvent(0x180000C): BadWindow (invalid Window parameter), #252899785, +8, +0.
10:59:23.586: IceWM: X error X_SendEvent(0x180000C): BadWindow (invalid Window parameter), #252899786, +7, +0.
10:59:23.586: IceWM: X error X_ChangeWindowAttributes(0x180000C): BadWindow (invalid Window parameter), #252899787, +6, +0.
10:59:23.586: IceWM: X error X_ConfigureWindow(0x180000C): BadWindow (invalid Window parameter), #252899789, +4, +0.
10:59:23.601: IceWM: X error X_GetWindowAttributes(0x1800010): BadWindow (invalid Window parameter), #252903798, +2, +0.
10:59:23.601: IceWM: X error X_ChangeWindowAttributes(0x1800010): BadWindow (invalid Window parameter), #252903800, +14, +0.
10:59:23.601: IceWM: X error X_ChangeWindowAttributes(0x1800010): BadWindow (invalid Window parameter), #252903801, +13, +0.
10:59:23.601: IceWM: X error X_ConfigureWindow(0x1800010): BadWindow (invalid Window parameter), #252903802, +12, +0.
10:59:23.601: IceWM: X error X_ChangeSaveSet(0x1800010): BadWindow (invalid Window parameter), #252903803, +11, +0.
10:59:23.601: IceWM: X error X_ReparentWindow(0x1800010): BadWindow (invalid Window parameter), #252903804, +10, +0.
10:59:23.601: IceWM: X error X_ChangeProperty(0x1800010): BadWindow (invalid Window parameter), #252903805, +9, +0.
10:59:23.601: IceWM: X error X_SendEvent(0x1800010): BadWindow (invalid Window parameter), #252903806, +8, +0.
10:59:23.601: IceWM: X error X_SendEvent(0x1800010): BadWindow (invalid Window parameter), #252903807, +7, +0.
10:59:23.601: IceWM: X error X_ChangeWindowAttributes(0x1800010): BadWindow (invalid Window parameter), #252903808, +6, +0.
10:59:23.601: IceWM: X error X_ConfigureWindow(0x1800010): BadWindow (invalid Window parameter), #252903810, +4, +0.

Icewm 11.4.3.0~pre-20180217 ( Linux/x86_64)

![2018-02-25_112019_537566372](https://user-images.githubusercontent.com/717662/36643829-eda53cb8-1a1e-11e8-9c4d-d8d30cd1408f.png)

**Comment by SolisX** [comment]
Not related to your issue. I got to change the Theme Author to Puneet Singh Corrections made by Bluescorpio_7.

**Comment by gijsbers** [comment]
@frankzen These errors look okay. Due to buffering of events between clients, the X server and IceWM these errors just happen without reason for concern. At the moment they are printed just in case something interesting might show up. If they bother you you could start icewm like this:

> icewm-session |& grep -v -e 'X error'

**Comment by frankzen** [comment]
OK Good to know. Won't bother with avoiding the errors if they are inconsequential.
