### ISSUE TITLE
glitched xxkb icon in system tray

### ISSUE THREAD

**Issue by zaza42** [bbidulock/icewm#235]
I'm using Debian with [1.4.3.0~pre-20180217-1,](https://packages.debian.org/sid/icewm) and [xxkb](http://sourceforge.net/projects/xxkb/) icon has glitched background.
For example: 
![gkrellshoot_2018-02-26_144217](https://user-images.githubusercontent.com/16356124/36673883-a2a0db28-1b04-11e8-9888-1c37cef35c27.png)
or
![gkrellshoot_2018-02-26_144232](https://user-images.githubusercontent.com/16356124/36673895-b10fd1d2-1b04-11e8-9fae-05c66b9dbf95.png)
or
![gkrellshoot_2018-02-26_145046](https://user-images.githubusercontent.com/16356124/36673904-bb59e326-1b04-11e8-8505-d2976ab108fb.png)

This wasn't a bug in 1.4.2 or any other older releases.

**Comment by Code7R** [comment]
Any other tool having this problem? xxkb seems to be crap - does not start for me, symptoms of https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=670158 and the issue has not been fixed for years.

**Comment by gijsbers** [comment]
@Code7R To use xxkb one must first edit the app-defaults file for xxkb and set `XXkb.mainwindow.type: tray`. Apparently this was by design! So that debian issue could be closed.

Also set `XXkb.button.enable: no` or xxkb will modify minimize buttons everywhere, even in evince!

@zaza42 It seems xxkb is not adjusting its tray icon size. IceWM does set a default background. Could you play with `XXkb.mainwindow.geometry: 24x24` and `XXkb.mainwindow.geometry: 32x20`?

**Comment by Code7R** [comment]
@gijsbers I agree with the reporter there and I wouldn't close it. If a program requires initial configuration it must be documented prominently, not hidden in some internet forum. Even the manpage is wrong (this option is not described there, XXkb.mainwindow.in_tray is documented instead - but it does not work).

@zaza42 What is the theme used there? Elberg with custom font?

Still cannot reproduce it here.

**Comment by zaza42** [comment]
@gijsbers  With `XXkb.mainwindow.geometry: 24x24`:
![gkrellshoot_2018-02-27_102944](https://user-images.githubusercontent.com/16356124/36720833-669d5534-1ba9-11e8-8954-b9a3d0fb4125.png)
and with `32x20`:
![gkrellshoot_2018-02-27_103113](https://user-images.githubusercontent.com/16356124/36720852-777fd6a6-1ba9-11e8-9db2-3ccd57402995.png)
and xxkb says `xxkb: Incomplete geometry for mainwindow` line in console.

I'm currently using icewm 1.4.2 and xxkb with: `XXkb.mainwindow.geometry: 24x12+5+5`
![icewm-1 4 2-tray-xxkb](https://user-images.githubusercontent.com/16356124/36720961-cdb56b1c-1ba9-11e8-8099-2955db684cd1.png)

@Code7R It's a custom mixed theme from jim-mac and ElbergGreen with `ClockFontNameXft="chicago:size=12"`. https://ufonts.com/fonts/chicago.html

My ~/.xxkbrc:
```
XXkb.image.path: /home/DC-1/.config/xxkb
XXkb.mainwindow.enable: yes
XXkb.mainwindow.appicon: no
XXkb.mainwindow.type: tray
XXkb.mainwindow.in_tray: yes
XXkb.mainwindow.geometry: 24x12+5+5
XXkb.mainwindow.image.1: us.xpm
XXkb.mainwindow.image.2: hu.xpm
XXkb.mainwindow.border.width: 5
XXkb.mainwindow.label.enable: no
XXkb.mainwindow.border.color: white
XXkb.mainwindow.label.background: #dddddd
XXkb.mainwindow.label.foreground: black
XXkb.mainwindow.label.font: -2rebels-chicago-medium-r-normal-*-*-120-*-*-p-*-ascii-0
XXkb.controls.add_when_create: no
XXkb.controls.two_state: no
XXkb.group.base: 1
XXkb.group.alt: 2
XXkb.button.enable: no
XXkb.bell.enable: no
```

And the 2 images: 
[xxkb-xpms.zip](https://github.com/bbidulock/icewm/files/1762084/xxkb-xpms.zip)

**Comment by gijsbers** [comment]
Should work now. xxkb is a bit old and non-compliant. Unfortunately it looks unmaintained.

@Code7R [Maybe interesting](https://sourceforge.net/p/xxkb/support-requests/2/)

**Comment by zaza42** [comment]
Ok. The patch fixed the glitch, but... but the new version of icewm uses the bottom panel bar background with transparent tray icons, except xxkb. :-/
1.4.2 look:
![gkrellshoot_2018-03-02_135123](https://user-images.githubusercontent.com/16356124/36900022-e9721b6e-1e21-11e8-988b-e59ff107149f.png)
1.4.3-pre-20180302, latest git:
![gkrellshoot_2018-03-02_135411](https://user-images.githubusercontent.com/16356124/36900040-f9359616-1e21-11e8-86dd-9c361df8c869.png)

**Comment by zaza42** [comment]
Cool, thx!

![gkrellshoot_2018-03-05_182111](https://user-images.githubusercontent.com/16356124/36989438-0b9c40ca-20a2-11e8-8d63-ef88e549952a.png)
