### ISSUE TITLE
network-manager-gnome does not work

### ISSUE THREAD

**Issue by CheckB** [bbidulock/icewm#236]
Hello, friend!

I have:
ubuntu 16.04 (latest)
icewm (latest)
and: apt -y install network-manager-gnome
I launch icewm-session

The service itself works. But the gui does not start, there are also no icons...
For ubuntu 16.04, this is the only gui for working with the Internet...

**Comment by Code7R** [comment]
What gui?

Note that icewm-session does not run the gazillions of XDG session startup scripts. You can run setup their autostart if you want to (see README.Debian and /usr/share/doc/icewm-common/examples/startup ) or just run nm-applet from ~/.icewm/startup script.

**Comment by CheckB** [comment]
Thanks for the answer. Hurried with the question.
