### ISSUE TITLE
Winoptions file geometry option don't work in latest code

### ISSUE THREAD

**Issue by martintxoz** [bbidulock/icewm#237]
Hello

I was testing the icewm packages from Debian Testing and Experimental in the last months. Many thanks to the maintainer!!

In the last one, 1.4.3.0~pre-20180217-3, I detect a bug in the geometry parameter on the ~/.icewm/windoptions file. Any form of this parameter is not working in this pre-release...

I have in this file this option:
  evince.Evince.geometry: 1000x745
Without this, the evince pdf viewer window is to small for my needs and have always to resize...

In the last pre-release package: 1.4.3.0~pre-20171225-1, it was working fine. And in other PC with 1.3.8+mod+20161220-1 I check now that is working too...

So, I think that any new code have break this option.

Many thanks for your work. Greetings. Martintxo.

**Comment by gijsbers** [comment]
Could you try:
> Evince.evince.geometry: 1000x745

or else:
> evince.geometry: 1000x745

**Comment by martintxoz** [comment]
Ok. I try all possibilities, and only one is not working, and is that I had...

Don't work: 
- evince.Evince.geometry: 1000x745

Works as expected:
- Evince.evince.geometry: 1000x745
- evince.geometry: 1000x745
- Evince.geometry: 1000x745

That's all. Maybe you can close this bug report. Greetings. Martintxo.

**Comment by gijsbers** [comment]
I modified it so that `evince.Evince.geometry` should also work.
