### ISSUE TITLE
Not a bug just a request.

### ISSUE THREAD

**Issue by SolisX** [bbidulock/icewm#239]
I'd like to make the taskbuttonactive look like this. But that would require to add 10 pixal xpm to the begin and end of taskbuttonbg,taskbuttonactive and taskbuttonminimized. Also to keep this new change from breaking old themes it should only use the new xpms if they are found in the theme. Just my idea.
![screen](https://user-images.githubusercontent.com/15175058/36961747-b7dd2d28-201a-11e8-9334-db98c11b55dc.png)

**Comment by gijsbers** [comment]
Could it perhaps also be done by specifying a taskbutton margin of 10 pixels?

**Comment by SolisX** [comment]
@gijsbers  If you mean add 10 pixpels to the taskbutton. No because the taskbutton does not have set size. So it will go from looking like this.

![screen](https://user-images.githubusercontent.com/15175058/37006382-107ee79c-20a6-11e8-9993-38b0ea6e157b.png)

To looking like this.
![screen01](https://user-images.githubusercontent.com/15175058/37006389-1ef24a58-20a6-11e8-8c14-731bcf1af525.png)

As well as the fact that the higher the resolution the bigger the size of the taskbutton.

**Comment by gijsbers** [comment]
So if a TaskButtonMargin of 10 would mean to copy 10 pixels of the initially loaded XPM on the left and 10 on the right and only stretch those 10 vertically then it would work fine?

**Comment by SolisX** [comment]
Yes i think this might work except you will need a way to off set the start of the icon and name of program.
1.# taskbuttoniconoffset = 0 [0-10]
![taskbutton](https://user-images.githubusercontent.com/15175058/37058354-3ebb3c0c-2158-11e8-80f4-b2228404c22f.png)

**Comment by SolisX** [comment]
Don't you forget about me. :(

**Comment by gijsbers** [comment]
You are on my mind. :)
It's quite tedious to implement and not so obvious how to do it neatly. 
We can postpone this until after the 1.4.3 release.
We haven't had a release for over a year... :(
Do you expect this to work for Gradients too?
Do you expect it to work for taskbuttonactive.xpm, taskbuttonbg.xpm and taskbuttonminimized.xpm?

**Comment by SolisX** [comment]
Oh thanks i thought you forgot. :) It's up to you when you implement it. You're the coders.
Yeah i hope icewm does not go years with out a release. I hope it works with gradients and i think that's the 3 xpms that are needed for the taskbuttons to look properly when using taskbuttons that need to get scaled without getting the stretching of the xpms in beginning and the end of the xpms.

**Comment by gijsbers** [comment]
@SolisX Do you perhaps have test icons for this?

**Comment by SolisX** [comment]
@gijsbers Here is Outside-ice with icons to test.
[Outside-ice.zip](https://github.com/bbidulock/icewm/files/2507436/Outside-ice.zip)

**Comment by SolisX** [comment]
@gijsbers Tried the icon offset but this is what i get.


This is icon offset set to 1.
![icon offset not working](https://user-images.githubusercontent.com/15175058/47383129-f1eab580-d6d1-11e8-9416-e64c1f761314.png)

**Comment by gijsbers** [comment]
Icon offset should be 10 here. Try `git pull && ./configure --disable-gdk-pixbuf ...`.

**Comment by SolisX** [comment]
I'm not sure about the git pull. I did git clone then in the icewm directory i did git pull which told me
it's already up-to-date.

This is what i got.

![offset compare](https://user-images.githubusercontent.com/15175058/47460468-90e3e000-d7ac-11e8-93e4-3af490b334fa.png)

I also i noticed in the icewn menu some icons were not showing up.

**Comment by gijsbers** [comment]
For iconoffset=0 you see the button is stretched. For 16 the diagonal remains the same no matter how task buttons there are on the taskbar. 10 makes more sense and avoids the artifact. You wrote "10 pixels" at the top of this issue too.

Could you perhaps locate a few missing icons and give their paths on your system?

**Comment by SolisX** [comment]
For me i still get the same artifact whether i set offset to 10 or 16. I tried both i just for got to mention that in the previous comment. 

As far as the missing icons in the menu it appears for some reason they have transparency.
You can see that firefox seems transparent.

here is a screenhot.

![transparent-icon](https://user-images.githubusercontent.com/15175058/47463880-8548e700-d7b5-11e8-8946-f4770172d5d9.png)


Here is icon offset set to 10.

![icon offset 10](https://user-images.githubusercontent.com/15175058/47464644-e1146f80-d7b7-11e8-8186-1a6b3c9f80b7.png)

BTW: I think you misunderstood what i meant with # taskbuttoniconoffset = 0 [0-10]. I meant
icon of the program to not start  right on the line of the curve. To be able to offset that.
Maybe we will need taskbuttonoffset and taskbuttoniconoffset.

![correct](https://user-images.githubusercontent.com/15175058/47465630-ba583800-d7bb-11e8-9318-677bc5747853.png)

**Comment by gijsbers** [comment]
Icon offset = 16 is no good. Maybe icon offset = 8 or 9 will have no artifact.

Try `icewm --postpreferences  | grep IconPath | tr : '\n'`
and experiment with different orders of the directories.
Which directory has the transparent icons?

Now the icon is drawn after the left offset icon. Is this better?

**Comment by SolisX** [comment]
Ok tried both icon offset at 8 and 9. I got the same results.

![offset set at 8](https://user-images.githubusercontent.com/15175058/47527468-96a2f980-d870-11e8-8632-5f8a8fbefbe3.png)

The transparent icon issue appears to be only on the 32bit version of icewm. On the 64bit version of icewm it does not have the issue.

This is what i got from the icewm --postpreferences command.

IconPath="/usr/share/icons/oxygen/base
/usr/share/icons/Adwaita
/usr/share/icons/hicolor
/usr/share/pixmaps
/usr/local/share/icons/hicolor
"

![screen10](https://user-images.githubusercontent.com/15175058/47527802-7de71380-d871-11e8-87ff-848c6bf680a9.png)

prog "Gens" "/usr/share/gens/gens_small.png" gens
prog "Fceux" "/usr/share/pixmaps/fceux.png" fceux
prog "mupen64plus" "/usr/share/pixmaps/m64py.png" m64py
prog "Pcsx-Reloaded" "/usr/share/pixmaps/pcsxr-icon.png" pcsxr
prog "Pcsx2" "/usr/share/pixmaps/PCSX2.xpm" PCSX2
prog "pSX" "/usr/share/pixmaps/psxfin" pSX
prog "PPSSPP" "/usr/share/icons/hicolor/48x48/apps/ppsspp.png" ppsspp-qt
prog "Snes9x-gtk" "/usr/share/icons/hicolor/32x32/apps/snes9x.png" snes9x-gtk
prog "VisualBoyAdvanceM" "/usr/share/icons/hicolor/32x32/apps/vbam.png" vbam
menu "Xebra" "/usr/share/pixmaps/XEBRA" {
    prog "Xebra" "/usr/share/pixmaps/XEBRA" xebra
    prog "Cep"  "/usr/share/pixmaps/CEP.png" cep
    prog "Memory Manager" "/usr/share/pixmaps/MCM" mcm
    prog "SIM" "/usr/share/pixmaps/SIM" sim
    }
prog "Yabause" /usr/share/pixmaps/yabause.png yabause
prog "Zsnes" "/usr/share/pixmaps/zsnes.png" zsnes

**Comment by SolisX** [comment]
@gijsbers Ok i recompiled this time with --enable-gdk-pixbuf and the taskbuttoniconoffset set to 8.
It looks great. :).  Thank You!

![screen11](https://user-images.githubusercontent.com/15175058/47530352-58113d00-d878-11e8-9075-af5601d53c40.png)

Also i guess i need --enable-gdk-pixpuf so the icons don't look transparent.
