### ISSUE TITLE
Moving terminal or rox filer to to left of the screen cause it to go black.

### ISSUE THREAD

**Issue by SolisX** [bbidulock/icewm#240]
Hello Everyone,

If i move a terminal or rox filer to the left of the screen the area the middle of the window goes black. This happens onicewm-1.4.2.1188.

Here is a video of the issue.

[black area when moving.mkv.gz](https://github.com/bbidulock/icewm/files/1780041/black.area.when.moving.mkv.gz)

**Comment by martintxoz** [comment]
Ok. The same is happen to me with some applications if I move its window out of the screen in the left and upper sides. I test with evince (gtk3), pcmanfm and leafpad (gtk2), vlc (qt5) and the icewm about dialogue. In all the cases I can see a black bars if I put part of the window out of the screen in the left and upper sides of the screen, but not in the right and botton sides.

My icewm: 1.4.3.0~pre-20180217-3 from the Debian Sid repository.

**Comment by zaza42** [comment]
Confirmed with the newest git (20180305)

![maim-2018-03-05_18 22 27](https://user-images.githubusercontent.com/16356124/36989539-47c464f6-20a2-11e8-9eea-fde078593466.png)

**Comment by gijsbers** [comment]
Thanks for the confirmations and the nice screenshot! Should be fixed now.

**Comment by zaza42** [comment]
Ok, the bug has gone.

**Comment by SolisX** [comment]
@gijsbers The issue seems fix but it looks like there is more tearing when moving the window.

**Comment by SolisX** [comment]
Ok seems fixed to me too. Closing.
