### ISSUE TITLE
Claws-mail can't minimize itself on startup

### ISSUE THREAD

**Issue by zaza42** [bbidulock/icewm#241]
A small bug again in git-20180305:
![maim-2018-03-05_18 31 50](https://user-images.githubusercontent.com/16356124/36990030-b1f4d698-20a3-11e8-9636-b2f63c1dc66b.png)
At startup claws-mail remains on screen forever instead of minimize to systrem tray after some seconds. I can see a little black blink in window after some seconds - so i think that time it tried to minimize itself.
After I click on tray icon it moves to the tray...but in 1.4.2 there was no need for any interaction.

**Comment by gijsbers** [comment]
How do you configure claws-mail to minimize itself to the system tray?

**Comment by zaza42** [comment]
There is a [claws-mail-multi-notifier](https://packages.debian.org/buster/amd64/claws-mail-multi-notifier) plugin for it. It has a very simple interface: 
![scrot-2018-03-05-20-17-54_805x550](https://user-images.githubusercontent.com/16356124/36994750-4e810050-20b2-11e8-8581-25c4fa7813d6.png)
When the window blinks black for a moment the icon appears in systray. 

Update: new effect: when i change workspace very early at startup, the claws-mail window respawns at the current workspace when creating tray icon.

**Comment by gijsbers** [comment]
All minimization problems on startup are duplicate of bug #190.

**Comment by gijsbers** [comment]
@zaza42 is this still a problem for you?

**Comment by zaza42** [comment]
Yes, claws-mail can't be started with automatically minimized.

**Comment by pankajk1997** [comment]
1. Install Claws-mail tray notifier: sudo apt install claws-mail-multi-notifier
2. Load the plugin from Claws Mail: Configuration -> Plugins
3. Configure the plugin from Claws Mail: Configuration -> Preferences
4. Now Add or Edit a file named claws-mail.desktop in startup directory having following content:-

> Content of:  ~/.config/autostart/claws-mail.desktop

> [Desktop Entry]
> Version=1.0
> Name=Claws Mail
> GenericName=E-mail client
> Exec=sh -c "sleep 10 && claws-mail &"
> Icon=claws-mail
> Categories=Network;Email;
> Keywords=lightweight;fast;gui;extensible;plugin;pop;pop3;imap;imap4;nntp;news;
> Comment=Lightweight and Fast GTK+ based Mail Client
> Terminal=false
> Type=Application
> StartupNotify=true
> X-Info=Claws Mail

**Comment by zaza42** [comment]
The new version in Debian (1.4.3.0~pre-20180809) doesn't need this kind of hack, minimize on startup works like a charm.

**Comment by OdinVex** [comment]
Using same options, Linux Mint, Claws always shows on startup even with .desktop work-around. Never remembers that its last state was also Maximized. (I always have it Maximized when using it and close to tray, never starts Minimized to tray and doesn't open to Maximized state when opened from tray/notifications.)

**Comment by gijsbers** [comment]
In your IceWM `winoptions` file, do you have:

    claws-mail.mainwindow.startMinimized: 1

What is the output of `claws-mail --version-full`?
What does the file `/etc/os-release` say about your Mint release version?
You did install and configure the plugin like mentioned above?

**Comment by OdinVex** [comment]
> In your IceWM `winoptions` file, do you have:
> 
> ```
> claws-mail.mainwindow.startMinimized: 1
> ```
> 
> What is the output of `claws-mail --version-full`?
> What does the file `/etc/os-release` say about your Mint release version?
> You did install and configure the plugin like mentioned above?
```
NAME="Linux Mint"
VERSION="20 (Ulyana)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20"
VERSION_ID="20"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.ubuntu.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=ulyana
UBUNTU_CODENAME=focal
```
```
claws-mail.mainwindow.startMinimized: 1
```
```
Claws Mail version 3.17.5
runtime GTK+ 2.24.32 / GLib 2.64.3
buildtime GTK+ 2.24.32 / GLib 2.63.5
Compiled-in features:
 compface
 Enchant
 GnuTLS
 IPv6
 iconv
 LDAP
 libetpan 1.9
 libSM
 librSVG 2.46.4
```
IceWM...Oh woops, I should be hitting up Claws Mail. *facepalm* Using Mint's default DM, plugin installed and configured. This was the only place I found with any info about Claws Mail and minimizing, so I thought to query here.
