### ISSUE TITLE
missing AllWorkspaces toggle in icesh and Sticky has no effect

### ISSUE THREAD

**Issue by zaza42** [bbidulock/icewm#243]
`AllWorkspaces` toggle switch is missing in icesh since 1.4.3 and `Sticky` has also no effect. I can still put window on all workspaces with `Occupy All` on pulldown menu.

`icesh -window focus setState Sticky 1` also does nothing.

**Comment by gijsbers** [comment]
According to the comment of commit e735002cf1cdfd0abcb621b61d9925df3d63aef4 this was on purpose.

**Comment by zaza42** [comment]
So, how can I make a sticky window? with icesh or other tools?

**Comment by gijsbers** [comment]
Commit 83b24001345e165c10aa6bbe50a538c8dea92bf0 implements "setWorkspace 0xFFFFFFFF" which was mentioned in commit e735002cf1cdfd0abcb621b61d9925df3d63aef4 .

**Comment by zaza42** [comment]
:-/
```
$ icesh -window focus setWorkspace 0xFFFFFFFF
icesh: Workspace out of range: 2147483647

```

**Comment by gijsbers** [comment]
```
$ ./icesh -window focus setWorkspace 0xFFFFFFFF
$ ./icesh --version
icesh 1.4.2.1219, Copyright
```

**Comment by bbidulock** [comment]
I would recommend using ```wmctrl``` or ```xdotool``` to make changes that are supported by EWMH/NetWM such as setting the focused window on all workspaces.  ```icesh``` really only exists to support features that are not present in EWMH/NetWM.

    wmctrl -r :ACTIVE: -b add,sticky

**Comment by zaza42** [comment]
okie, icesh is working, wmctrl is not working without any error message.
(i haven't updated icesh binary alongside with icewm binary)

**Comment by zaza42** [comment]
One more question: are there any easier way to toggle Sticky on/off?
```
#!/bin/sh
id=$(xdotool getactivewindow)
curdesk=$(xdotool get_desktop)
windesk=$(xdotool get_desktop_for_window $id 2>/dev/null)
if [ "$windesk" = "-1" ]; then
    icesh -window $id setWorkspace $curdesk
else
    icesh -window $id setWorkspace 0xFFFFFFFF
fi
```
