### ISSUE TITLE
_NET_ACTIVE_WINDOW event on fullscreen

### ISSUE THREAD

**Issue by zaza42** [bbidulock/icewm#244]
bug or feature?

In 1.4.3 there are no `_NET_ACTIVE_WINDOW` event when changing a window to fullscreen. While in 1.4.2 every fullscreen generate a 
`_NET_ACTIVE_WINDOW(WINDOW): window id # 0x18000cb`
line when watching it via `xprop -spy -root _NET_ACTIVE_WINDOW`, in 1.4.3 there is nothing in xprop. I'm using this in my scripts, so what should I watch instead of `_NET_ACTIVE_WINDOW`? 

And a little feature request: it would be cool to generate an event in xprop when restoring window from fullscreen to windowed mode.

**Comment by gijsbers** [comment]
I'd monitor the _NET_WM_STATE of the _NET_ACTIVE_WINDOW:

> _NET_WM_STATE(ATOM) = _NET_WM_STATE_FOCUSED, _NET_WM_STATE_FULLSCREEN

**Comment by zaza42** [comment]
How can i do that?
```
xprop -spy -root _NET_WM_STATE _NET_WM_STATE_FOCUSED _NET_WM_STATE_FULLSCREEN
_NET_WM_STATE:  not found.
_NET_WM_STATE_FOCUSED:  not found.
_NET_WM_STATE_FULLSCREEN:  not found.

```
I've found _WIN_CLIENT_LIST and _NET_CLIENT_LIST_STACKING, so I can use them.
```
_WIN_CLIENT_LIST(CARDINAL) = 10485783, 10485796, 10485809, 10485822, 31457283, 27263005, 27263045, 27263048, 27263051, 27263054, 10485834, 10485769, 20971523, 10485847
_NET_CLIENT_LIST_STACKING(WINDOW): window id # 0xa00017, 0xa00024, 0xa00031, 0xa0003e, 0x1e00003, 0x1a0001d, 0x1a00045, 0x1a00048, 0x1a0004b, 0x1a0004e, 0xa0004a, 0xa00009, 0x1400003, 0xa00057
```
Any idea for monitoring window restore event with xprop or any other tool?

**Comment by gijsbers** [comment]
This illustrates the idea:
```
#!/bin/bash

while :; do
    echo "# repeat"
    xprop -root _NET_ACTIVE_WINDOW |
    awk '{print $NF}' |
    if read id; then
        echo "# $id is active"
        xprop -spy -id $id _NET_WM_STATE |
        while read a; do
            echo "# $id state = $a"
            if [[ ! $a =~ _NET_WM_STATE_FOCUSED ]] ; then
                kill -9 $(ps -f |
                          grep -e "xprop -spy -id $id _NET_WM_STATE" |
                          grep -v grep |
                          awk '{print $2}')
            else
                echo "# $id is focused"
            fi
        done
        echo "# $id lost focus"
    fi
done
```

**Comment by zaza42** [comment]
Thx!
