### ISSUE TITLE
windowfocus restore after stayontop

### ISSUE THREAD

**Issue by zaza42** [bbidulock/icewm#245]
I run mpv from rxvt, and when it finishes I get back the focus on rxvt. But if i'm using mpv with stay on top toggle, then the focus won't go back to rxvt. The focus will go to the last ontop application which is gkrellm in my situation.
This bug also affects version 1.4.2.

**Comment by gijsbers** [comment]
This is not a bug. If layer becomes OnTop then rxvt is moved to a different place in the focus sorting order and the next application then becomes gkrellm. IceWM first looks in the same layer before trying lower layers.

**Comment by zaza42** [comment]
Could we get an option for controlling this behavior?

(as a workaround i added to mpv's input.conf: `ESC set ontop no; quit`)

**Comment by gijsbers** [comment]
Not a good idea, sorry.

**Comment by zaza42** [comment]
okie
