### ISSUE TITLE
Does not show an icon in the toolbar

### ISSUE THREAD

**Issue by ghost** [bbidulock/icewm#246]
I took an icon from the Internet and made myself an icon from it in the toolbar of three sizes! Then I went to icewm and saw that it was not displayed. When I click on the icon, I do not even open the file manager thunar.
My file ~/.icewm/toolbar:
```
# This is an example for IceWM's toolbar definition file.
#
# Place your variants in /etc/icewm or in $HOME/.icewm
# since modifications to this file will be discarded when you
# (re)install icewm.
#
prog Xterm xterm term
prog Firefox firefox firefox
prog Thunar thunar thunar
```
I attach 2 screenshots of my problem and really hope for your help!
![1](https://user-images.githubusercontent.com/30781944/37037838-1e6716ae-214b-11e8-9567-c6fffe327c67.jpg)
![2](https://user-images.githubusercontent.com/30781944/37037850-21f4fa3e-214b-11e8-9cbe-ff4c9b7cf8eb.jpg)

**Comment by Code7R** [comment]
The extra lines starting with "Place your variants..." are just garbage that you copypasted?
Please remove them and try again, restarting icewm from the menu.

**Comment by gijsbers** [comment]
This looks like issue #163, right?

Where are your icons located?
Could you attach them?

**Comment by SolisX** [comment]
Looks like you have a " ` " at the end of thunar. That may be causing the issue.

**Comment by ghost** [comment]
> he extra lines starting with "Place your variants..." are just garbage that you copypasted?
Please remove them and try again, restarting icewm from the menu.

This garbage is just a comment, they do not interfere and do not fix the problem.

**Comment by ghost** [comment]
> Looks like you have a " ` " at the end of thunar. That may be causing the issue.

No, it's just crookedly inserted text, but now it's fixed.

**Comment by ghost** [comment]
> This looks like issue #163, right?

No, it was quite different there.

> Where are your icons located?
> Could you attach them?
Just wanted to throw them off! Here they are all three:

1. [thunar_16x16.txt](https://github.com/bbidulock/icewm/files/1798779/thunar_16x16.txt)
2. [thunar_32x32.txt](https://github.com/bbidulock/icewm/files/1798781/thunar_32x32.txt)
3. [thunar_48x48.txt](https://github.com/bbidulock/icewm/files/1798782/thunar_48x48.txt)
Just need to rename them to the xpm extension!

**Comment by bbidulock** [comment]
In what directory are they located?

**Comment by bbidulock** [comment]
Could you try putting the full path in the second element and see if that works?  Such as:

    prog Thunar /the/dir/where/icons/are/thunar_16x16.xpm thunar

**Comment by ghost** [comment]
> In what directory are they located?

In the catalog _/home/user/.icewm/icons_

**Comment by ghost** [comment]
> Could you try putting the full path in the second element and see if that works? Such as:
> prog Thunar /the/dir/where/icons/are/thunar_16x16.xpm thunar

i write
`prog Thunar /home/user/.icewm/icons/thunar_16x16.xpm thunar`
But everything does not work exactly

**Comment by bbidulock** [comment]
If that doesn't work exactly, there is some bug.  What exactly doesn't work?

**Comment by ghost** [comment]
> If that doesn't work exactly, there is some bug. What exactly doesn't work?

I did not have time to understand the work, but now I finally got it.I did this:
`prog thunar thunar thunar`
And it all worked, the icon is now visible! I do not know whether this is a bug or not, but this is how it was fixed.
