### ISSUE TITLE
update PO files using --previous’

### ISSUE THREAD

**Issue by elchevive** [bbidulock/icewm#247]
Hi,

I don't know how you update the po files, but if you are using the msgmerge program, would be nice to invoke it with the parameter --previous as it keeps the changed string (in case of a fuzzy one), so Weblate show us translators exactly what changes.

Regards,

Luiz - pt_BR translator

**Comment by bbidulock** [comment]
Added --previous to Makevars.  Thank you for the report!

**Comment by elchevive** [comment]
Hi,

I already see some strings changed after this was implemented. Much better to see what really changes.

Thanks!
