### ISSUE TITLE
Window positions after desktop geometry change

### ISSUE THREAD

**Issue by zaza42** [bbidulock/icewm#248]
Some terminal windows changing it's position after changing the desktop geometry with xrandr. In most cases 2 or more terminal windows had swapped.
![maim-2018-03-05_22 53 01](https://user-images.githubusercontent.com/16356124/37095086-33cb6480-2215-11e8-8e87-75643f45bf60.png)
```
 xrandr --output LVDS --primary --mode 1600x900 --pos 0x0 --rotate normal \
	--output VGA-0 --mode 800x600 --pos 1600x300 --rotate normal
```
![maim-2018-03-05_22 53 10](https://user-images.githubusercontent.com/16356124/37095105-42521ecc-2215-11e8-8cd1-190331a41815.png)
Watch the the first and second rxvt window!

This bug is in 1.4.2, too.

**Comment by bbidulock** [comment]
The title on the second window in the first image and the first window in the second image are different.  I think that you have your screen-shots mixed up!

**Comment by zaza42** [comment]
No. The system load is changing always, i'm updating the average load in title via `PROMPT_COMMAND` dynamically. But i can make screenshots for you without any `PROMPT_COMMAND`. 
**Watch the clock at bottom right!** (8 seconds delay)
![maim-2018-03-12_16 52 25](https://user-images.githubusercontent.com/16356124/37294355-eeebf2b2-2615-11e8-9522-7b23ff87b4a2.png)
![maim-2018-03-12_16 52 35](https://user-images.githubusercontent.com/16356124/37294443-14dcf7a0-2616-11e8-9a8a-4ecef2b6d1ca.png)
![maim-2018-03-12_16 52 59](https://user-images.githubusercontent.com/16356124/37295123-9f8b973e-2617-11e8-80a5-f66326691231.png)

This happens all the time when i'm changing geometry, that's why i've wrote a workaround script weeks ago.

**Comment by bbidulock** [comment]
Please show output of

    xwininfo -root -all

before and after the change.

**Comment by zaza42** [comment]
[icewm-xwininfo-before.txt](https://github.com/bbidulock/icewm/files/1806287/icewm-xwininfo-before.txt)
![maim-2018-03-13_10 31 32](https://user-images.githubusercontent.com/16356124/37333660-2ae89cb8-26aa-11e8-87b3-7d35de8aef10.png)

[icewm-xwininfo-after_extended.txt](https://github.com/bbidulock/icewm/files/1806295/icewm-xwininfo-after_extended.txt)
![maim-2018-03-13_10 35 01](https://user-images.githubusercontent.com/16356124/37333707-500848b8-26aa-11e8-9b46-0faf65a8caf9.png)

**Comment by bbidulock** [comment]
Ice placed the windows in stacking order.  The stacking order changed since they were originally laid out, and two one window was raised above the other some time between the change.  You don't show where your pointer is at during the change, but window enter and leave events will be generated even when the pointer does not move while doing xrandr.  What is your focus and placement settings?  An where is your pointer when this happen?

Also, how about dropping the gkrell, the conky and everything else except ice and the six urxvt windows?

**Comment by zaza42** [comment]
Okie, clean desktop:
![maim-2018-03-14_13 53 45](https://user-images.githubusercontent.com/16356124/37403573-8576f1bc-278f-11e8-8994-35cf6da85988.png)
![maim-2018-03-14_13 53 54](https://user-images.githubusercontent.com/16356124/37403593-96d0cba4-278f-11e8-9a37-8af645ac4eb2.png)
My cursor is on the 6th  urxvt and haven't touched between the screenshots.
```
FocusRequestFlashTime=0
FocusRequestFlashInterval=0
SmartPlacement=1

```
As I can see the order of windows was completely reversed.

**Comment by gijsbers** [comment]
Did you try setting `ArrangeWindowsOnScreenSizeChange = false` ?

**Comment by zaza42** [comment]
Hmm... I've never heard about this option, but it solved the problem.
