### ISSUE TITLE
Workspace numbering not starting at 1.

### ISSUE THREAD

**Issue by SolisX** [bbidulock/icewm#249]
Hello Everyone,

Look at the screenshot.

![screen10](https://user-images.githubusercontent.com/15175058/37249429-38d4a91c-24b5-11e8-9205-14ab18557d89.png)

**Comment by bbidulock** [comment]
Please also check output of

    xprop -root _NET_DESKTOP_NAMES

**Comment by SolisX** [comment]
When i reboot the system the issue went away so i'm going close it from now.
