### ISSUE TITLE
Minimized windows are restored when `icewm -r`

### ISSUE THREAD

**Issue by zaza42** [bbidulock/icewm#254]
All of my minimized windows on taskbar had restored after/during `icewm -r` of `killall -HUP icewm`.

**Comment by gijsbers** [comment]
As already mentioned in #241 all minimization problems on startup are duplicate of bug #190.

**Comment by gijsbers** [comment]
@zaza42 is this still a problem for you?

**Comment by zaza42** [comment]
It's fixed with the newest git version.
