### ISSUE TITLE
An unusual bug :)

### ISSUE THREAD

**Issue by CheckB** [bbidulock/icewm#256]
With uptime in a few days I notice such a problem:
![untitled](https://user-images.githubusercontent.com/34208261/37757227-4646dabe-2dbd-11e8-955a-dec4a840cf2a.png)

I just do not have a title in my headlines.
I assume that this happens after switching over ctrl + alt + F2 and back to ctrl + alt + F1

Info:
Ubuntu 16.04.04 Linux 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Icewm (build from source)

**Comment by bbidulock** [comment]
Are you sure icewm was still running?

**Comment by CheckB** [comment]
@bbidulock 
Yes. I can run any applications. The same GIMP launched from the menu icewm and made a screenshot by tyke

@Code7R 
Update debian/sid please. I'll check it again on the latest version.

**Comment by CheckB** [comment]
This problem manifests itself in periods. I notice it is not the first time.
Helps reboot.

**Comment by CheckB** [comment]
@bbidulock 

There is a possibility that this is due to switching to another "tty", "tty2" in particular via ctrl + alt + f2

**Comment by bbidulock** [comment]
@CheckB 

Which Xorg driver?  i915?

**Comment by CheckB** [comment]
@bbidulock 

Yes.
Last time I do not notice a problem, probably the bug was not in icewm.

p.s. By the way, how do I get updates now if Code7R has not performed the merge for a long time (debian/sid)?

**Comment by CheckB** [comment]
@bbidulock 

The problem is also observed in the latest version of icewm

**Comment by Code7R** [comment]
I have never seen this before. If you can reproduce it with the version in Sid or Testing, please send all your config (icewm --postpreferences)

But I have seen similar issues in case when the selected font was bad and partially missed support of some glyphs. Have you checked your fonts, maybe something is buggy? (man fc-list, fc-cat, try "fc-cache -f").

**Comment by ldarby2** [comment]
@CheckB Instead of rebooting does restarting just icewm (Logout > Restart icewm) fix it?(That should preserve your windows at least, won't help troubleshooting this.)

Also icewm depends on other libraries for font rendering (libfreetype & fontconfig, and the graphics driver as well which Code7R mentioned), so it's worth upgrading those to the latest as well, i.e. ugrading to ubuntu 18.04 should upgrade those.
