### ISSUE TITLE
Focus and Theme menu disappear when...

### ISSUE THREAD

**Issue by SolisX** [bbidulock/icewm#259]
Hello Everyone,

Turning the setting

ShowSettingsMenu=0

Cause the focus and theme menus to disappear.

**Comment by bbidulock** [comment]
Are not the focus and theme menus settings menus?

**Comment by SolisX** [comment]
The focus menu is above the preferences menu and the themes menu is below the preferences menu.

Is it suppose to work that way? You have a way to disable

ShowFocusModeMenu=1 # 0/1

ShowThemesMenu=1 # 0/1

but no way to disable the preferences menu with disabling the other 2.

**Comment by SolisX** [comment]
Ok this issue is fix for me with the current icewm-1.4.2.1304.
