### ISSUE TITLE
Bug when maximizing windows at the option HideTitleBarWhenMaximized=1

### ISSUE THREAD

**Issue by arsonoff** [bbidulock/icewm#261]
Many programs (for example libreoffice, geany) when opening unwrap a window on all screen, but at the same time not maximize.
In this case, command for maximizing a window does not work (titlebar remains it is visible).
Workaround: move a window before maximizing a window.

**Comment by gijsbers** [comment]
Works fine here.
Maximizing is with Alt+F10?
Or fullscreen with Alt+F11?
What OS? Is this CentOS again? How do you install geany on CentOS?

**Comment by arsonoff** [comment]
>Works fine here.

With HideTitleBarWhenMaximized=1?
>Maximizing is with Alt+F10?

Yes
>Is this CentOS again?

Yes
>How do you install geany on CentOS?

EPEL repo

Test1: Open libreoffice/geany. Maximize, Close, Open, UnMaximize, Close, Open... Try to maximize
Result:
[![2018-04-25-142341_1600x1200_scrot.png](https://s9.postimg.cc/ca7g42p8v/2018-04-25-142341_1600x1200_scrot.png)](https://postimg.cc/image/6m15d6kwb/)
Should be:
[![2018-04-25-142349_1600x1200_scrot.png](https://s9.postimg.cc/oc2ty98rz/2018-04-25-142349_1600x1200_scrot.png)](https://postimg.cc/image/zbo19uz6z/)

Test2: Open terminal. Execute "make xconfig" in kernel source... Try to maximize

**Comment by arsonoff** [comment]
Toggle in preferences: HideTitleBarWhenMaximized=1
```
$ xprop -root | grep _NET_WORKAREA\(
_NET_WORKAREA(CARDINAL) = 0, 25, 1600, 1175,...
$ xclock -g 1600x1175
```
Try to maximize

**Comment by gijsbers** [comment]
Works fine here.
Does it work for you with default preferences and default theme?

**Comment by arsonoff** [comment]
>Does it work for you with default preferences and default theme?

Delete all from .icewm/
Add file preferences with one string "HideTitleBarWhenMaximized=1"
Try to maximize - TitleBar does not hide if not to shift a window. :(

**Comment by gijsbers** [comment]
Can you reproduce it on other hardware with a default English language distro like Debian or Ubuntu?

**Comment by arsonoff** [comment]
LANG=C, default config (only HideTitleBarWhenMaximized=1)
Two different computers (however on both the built-in intel - skylake/apollolake).
Xorg drivers -- modesetting/inte/fbdev/vesa
CentOS 7.4 and 7.5 ;) (I have no ubuntu)

git-bisect indicates it -- 6a03d437b7c944993d6ea78bd75e5cf548660d2f is the first bad commit
If to return back the line `performLayout();`, then the bug disappears.

**Comment by gijsbers** [comment]
Okay I believe you :). Let us see how this works out. The comment for 6a03d437b7c944993d6ea78bd75e5cf548660d2f should have been more informative.
