### ISSUE TITLE
 To make possible to set the different sizes border for top and bottom border

### ISSUE THREAD

**Issue by arsonoff** [bbidulock/icewm#262]
Example of a theme: https://aur.archlinux.org/packages/icesimple-icewm-theme
Upper border is absent (is transparent).
Between windows there are slots:
[![2018-04-25.png](https://s9.postimg.cc/n4kas93jj/2018-04-25.png)](https://postimg.cc/image/ytoag7ui3/)
In attempt to move up a window closer, the window jumps on another.

**Comment by gijsbers** [comment]
You could try and modify SnapDistance.
```
#  Snap to nearest screen edge/window when moving windows
# SnapMove=1 # 0/1
#  Distance in pixels before windows snap together
# SnapDistance=8 # [0-64]
```

**Comment by arsonoff** [comment]
>SnapMove=0

It solves a problem of manual movement, but when IceWM automatically locates windows: "Tile Horisontally" (Alt+Shift+F3) or when opening a new window, between windows remain slots.

**Comment by arsonoff** [comment]
>BorderSizeY -- Top/bottom border height.

Whether it is possible to make separately BorderSizeT and BorderSizeB?

**Comment by bbidulock** [comment]
The theme should set the border size smaller instead of making borders transparent.  When they are transparent, the borders are still there.  The slots are an intention of the theme designer in this case.

**Comment by arsonoff** [comment]
[:enhancement:]
To make possible to set the different sizes border for top and bottom border.

**Comment by gijsbers** [comment]
I think this is poorly motivated and it causes massive code bloat. At 97 different places in the code you suddenly have two different values (top + bottom) where currently there is just 1. So the cost doesn't justify whatever marginal gains there are.

**Comment by arsonoff** [comment]
I probably not correctly formulated the issue. More correctly so:
Add the option the defining actual visible height of TopBorder (or it is even simpler, TopBorder - visible/invisible), which would be considered at automatic placement of the window on the screen and when snapping (optionally). 

All the rest is also so normally displayed.

It is not easier?

The Top-border disturbs when using the touchscreen. It would be desirable to have normally displayed theme without top-border.

**Comment by gijsbers** [comment]
If the theme is wrong then better talk with the theme author to fix his theme.
Not ask icewm to add Yet Another Silly Option (YASO).
