### ISSUE TITLE
Directive similar menuprog, but creating not the submenu, but just additional menu items.

### ISSUE THREAD

**Issue by arsonoff** [bbidulock/icewm#264]
[Enhancement] 
Whether it is possible to make the directive similar menuprog, but creating not the submenu, but just additional menu items?

**Comment by arsonoff** [comment]
I wanted to generate the menu through `mkfifo ~/.icewm/menu`, it did not turn out.
Icewm ignores the menu file of zero length at start...

It is possible to add the option MenuCommand - to execute command before opening of the menu (to create menu)?
Why it is possible to generate only a submenu (with menuprog), and the root-menu is impossible?

**Comment by gijsbers** [comment]
The icewm-menu manpage is incomplete.

You could use the **"include"** statement.

If you use an absolute path for your filename then you should be able to use a FIFO.

**Comment by gijsbers** [comment]
`includeprog` should be it.

**Comment by arsonoff** [comment]
Great
