### ISSUE TITLE
Unclosable Window.

### ISSUE THREAD

**Issue by SolisX** [bbidulock/icewm#267]
Hello Everyone,

After i add 

wicd-client
sleep 2
icewm -r

to the startup file i some times get an unclosable black box. What i noticed is that some times the wicd-client tray will not be there but when i switch the theme i can see a small box at the top left that is unclosable. I'm using icewm-1.4.2.1364.

WM_NAME(STRING) = "Frame"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW

![unclosable window](https://user-images.githubusercontent.com/15175058/39743859-520205ae-5270-11e8-8792-cc915fb3b275.png)

**Comment by gijsbers** [comment]
Can't reproduce it with wicd 1.7.4. Could be a bug in wicd.

**Comment by SolisX** [comment]
@gijsbers Doesn't happen everytime. It's random when it happens. I'm also using wicd 1.7.4.

**Comment by gijsbers** [comment]
If it was a bug in icewm then it would likely happen more often and be reproducible and also occur with other apps. Because that is not the case it is likely a bug in wicd and you should report there and not here.

**Comment by SolisX** [comment]
@gijsbers Ok Thanks. I'm not sure which it is but i'll close this bug. I'll try and see what they think.
