### ISSUE TITLE
Unknown window is showed up

### ISSUE THREAD

**Issue by duongvuhong** [bbidulock/icewm#268]
I have a process included 3 window ID (xdotool search --pid)
One of them is a window with blank content
![screenshot](https://user-images.githubusercontent.com/3413118/39751809-91bc50dc-52e3-11e8-8d1c-f4ef4174a4f2.png)
And this is info from xprop command
[unknown.txt](https://github.com/bbidulock/icewm/files/1983394/unknown.txt)
But with gnome desktop, there is no window like that.

**Comment by gijsbers** [comment]
See `man icewm-winoptions`.
You could try things like:
Wfica.workspace: 4
Wfica.startMinimized: 1

**Comment by duongvuhong** [comment]
@gijsbers I run that process on gnome desktop environment, but there is no window like that.

**Comment by gijsbers** [comment]
icewm is not responsible for how many windows an application creates. Better ask at Wfica.

**Comment by duongvuhong** [comment]
@gijsbers Thank you for your answer. I think the window does exist on gnome desktop environment but it is hidden.
I will close this issue now
