### ISSUE TITLE
When i click on about the desktop switches.

### ISSUE THREAD

**Issue by SolisX** [bbidulock/icewm#269]
Hello Everyone,

When i click on the "about" on the taskbar the desktop switches to the 4 desktop. It seems like it selects 1 desktop when you click about and switches to that desktop. 

For example

Some times it happens on the 1st desktop when you switch to desktop 3 then click about it
switches to desktop 1.

I have 4 workspaces. This happens on icewm-1.4.2.1379.

**Comment by ghost** [comment]
Why do not you disable this thing in the settings and it would be gone from the menu?

**Comment by SolisX** [comment]
Okay seems fixed to me.
