### ISSUE TITLE
clock isn't displayed

### ISSUE THREAD

**Issue by zaza42** [bbidulock/icewm#273]
I'm trying the new 20180520 git version, and the clock only shows the background:
![gkrellshoot_2018-05-24_014320](https://user-images.githubusercontent.com/16356124/40456884-ddc10222-5ef3-11e8-9717-b66eee4eadbc.png)
When I downgrade icewm to the old 20180430 version, then I do `icewm -r` or `killall -HUP icewm` then everything goes to normal behavior: 
![gkrellshoot_2018-05-24_014515](https://user-images.githubusercontent.com/16356124/40456936-2130d0e6-5ef4-11e8-9c1e-0333f2e83419.png)

~/.icewm/prefoverride:
`ClockFontNameXft="chicago:size=12"
`
https://www.myfonts.com/fonts/apple/chicago/

**Comment by gijsbers** [comment]
@zaza42 You didn't mention how you build or what platform. I assume you used CMake? Could you try again with configure instead?

**Comment by zaza42** [comment]
I'm using the standard debian packaging scripts from http://http.debian.net/debian/pool/main/i/icewm/icewm_1.4.3.0~pre-20180217-4.debian.tar.xz on Debian sid/unstable amd64.

**Comment by gam3** [comment]
After 35c632fa21bbb990435e95b430f27fe1428800a5 I get odd clock display!

![untitled](https://user-images.githubusercontent.com/99491/43738494-22f50b16-99c5-11e8-9b30-1d3ce2e55eba.png)

**Comment by zaza42** [comment]
No problem with 1.4.3.0~pre-20180809-2.
