### ISSUE TITLE
WM_CLASS is <unknown> with Linux kernel 4.18-rc1

### ISSUE THREAD

**Issue by zaza42** [bbidulock/icewm#275]
Very strange error, may not be an icewm error. Audacious hasn't got WM_CLASS property with kernel v4.18rc1. Only one app is audacious, all others have WM_CLASS.
![maim-2018-06-17_18 53 09](https://user-images.githubusercontent.com/16356124/41510195-60e526b8-7260-11e8-9712-35e4c9c053c7.png)

And with linux 4.17.2: 
![maim-2018-06-17_18 49 45](https://user-images.githubusercontent.com/16356124/41510198-786d8f0a-7260-11e8-97ba-b1d387404172.png)

Everything are the same, only the kernel is different. I've rebooted 4 times, and this is the effect always.

Point me the right way, if it's not icewm bug.

**Comment by bbidulock** [comment]
4.18rc1 has many issues and incompatibilities.

**Comment by zaza42** [comment]
Okey, it was fixed in 4.18-rc2.
