### ISSUE TITLE
ICEWM taskbar position

### ISSUE THREAD

**Issue by duongvuhong** [bbidulock/icewm#276]
I have an external monitor and using xfce4-settings to configure monitors.
When I set the external monitor to primary, ICEWM taskbar is moved to the primary one.
Could I prevent this action?

**Comment by gijsbers** [comment]
Does it help if you change the option `XRRPrimaryScreenName=""` to the name of the monitor where you wish to keep the taskbar?

**Comment by tkonopelski** [comment]
@cuncon You can tray **arandr** 
ARandR: Another XRandR GUI

**Comment by duongvuhong** [comment]
Thank you for your comment. I had solved my issue.
