### ISSUE TITLE
Error build:

### ISSUE THREAD

**Issue by CheckB** [bbidulock/icewm#278]
./autogen.sh
./configure --enable-gdk-pixbuf --prefix=/usr --sysconfdir=/etc

configure: error: Package requirements (librsvg-2.0) were not met:

No package 'librsvg-2.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LIBRSVG_CFLAGS
and LIBRSVG_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

apt install librsvg2-2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
librsvg2-2 is already the newest version (2.40.13-3).
librsvg2-2 set to manually installed.

apt install librsvg2-common
Reading package lists... Done
Building dependency tree       
Reading state information... Done
librsvg2-common is already the newest version (2.40.13-3).
librsvg2-common set to manually installed.

**Comment by bbidulock** [comment]
ls -l /usr/lib/pkgconfig/librsvg*

which must return

    /usr/lib/pkgconfig/librsvg-2.0.pc

If not, link whatever it is named to librsvg-2.0.pc.  If it returns nothing, maybe there is a librsvg2-dev package that you need to load to get it.

**Comment by CheckB** [comment]
apt -y install librsvg2-dev

fix it
