### ISSUE TITLE
Failure to build the documentation

### ISSUE THREAD

**Issue by HJarausch** [bbidulock/icewm#28]
With the current GIT version I get lots of
nsgmls:<OSFD>0:242:33:E: "DESCRIP" not finished but document ended
nsgmls:<OSFD>0:242:33:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:236:0: start tag was here
nsgmls:<OSFD>0:242:33:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
html2html: Problem with ref "lib"

and lateron
 /usr/bin/install -c -m 644 icewm.html icewm-1.html icewm-2.html icewm-3.html icewm-4.html icewm-5.html ./icewm-6.html ./icewm-7.html ./icewm-8.html ./icewm-9.html ./icewm-10.html ./icewm-11.html ./icewm-12.html ./icewm-13.html ./icewm-14.html ./icewm-15.html ./icewm-16.html ./icewm-17.html ./icewm-18.html ./icewm-19.html ./icewm-20.html '/var/tmp/portage/x11-wm/icewm-9999/image//usr/share/doc/icewm'
/usr/bin/install: cannot stat './icewm-6.html': No such file or directory
/usr/bin/install: cannot stat './icewm-7.html': No such file or directory
/usr/bin/install: cannot stat './icewm-8.html': No such file or directory
/usr/bin/install: cannot stat './icewm-9.html': No such file or directory
/usr/bin/install: cannot stat './icewm-10.html': No such file or directory
/usr/bin/install: cannot stat './icewm-11.html': No such file or directory
/usr/bin/install: cannot stat './icewm-12.html': No such file or directory
/usr/bin/install: cannot stat './icewm-13.html': No such file or directory
/usr/bin/install: cannot stat './icewm-14.html': No such file or directory
/usr/bin/install: cannot stat './icewm-15.html': No such file or directory
/usr/bin/install: cannot stat './icewm-16.html': No such file or directory
/usr/bin/install: cannot stat './icewm-17.html': No such file or directory
/usr/bin/install: cannot stat './icewm-18.html': No such file or directory
/usr/bin/install: cannot stat './icewm-19.html': No such file or directory
/usr/bin/install: cannot stat './icewm-20.html': No such file or directory

**Comment by Code7R** [comment]
Works for me...
~/git/icewm/build/doc $ make
sgml2html ../../doc/icewm.sgml
Processing file ../../doc/icewm.sgml
~/git/icewm/build/doc $ sgml2html -h
LinuxDoc-Tools version 0.9.69

**Comment by HJarausch** [comment]
On 07/08/2015 07:41:06 PM, Code7R wrote:

> Works for me...
> ~/git/icewm/build/doc $ make
> sgml2html ../../doc/icewm.sgml
> Processing file ../../doc/icewm.sgml
> ~/git/icewm/build/doc $ sgml2html -h
> LinuxDoc-Tools version 0.9.69
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bbidulock/icewm/issues/28#issuecomment-119673670

I have upgraded from LinuxDoc-Tools version 0.9.68 to LinuxDoc-Tools version 0.9.69
but the problem persists:

Making install in doc
make[1]: Entering directory '/var/tmp/portage/x11-wm/icewm-9999/work/icewm-9999/doc'
sgml2html icewm.sgml
sgml2html icewm.sgml
sgml2html icewm.sgml
sgml2html icewm.sgml
Processing file icewm.sgml
Processing file icewm.sgml
Processing file icewm.sgml
Processing file icewm.sgml
nsgmls:<OSFD>0:242:33:E: "DESCRIP" not finished but document ended
nsgmls:<OSFD>0:242:33:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:236:0: start tag was here
nsgmls:<OSFD>0:242:33:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
nsgmls:<OSFD>0:242:33:E: "DESCRIP" not finished but document ended
nsgmls:<OSFD>0:242:33:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:236:0: start tag was here
nsgmls:<OSFD>0:242:33:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
nsgmls:<OSFD>0:242:33:E: "DESCRIP" not finished but document ended
nsgmls:<OSFD>0:242:33:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:236:0: start tag was here
nsgmls:<OSFD>0:242:33:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
nsgmls:<OSFD>0:242:33:E: "DESCRIP" not finished but document ended
nsgmls:<OSFD>0:242:33:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:236:0: start tag was here
nsgmls:<OSFD>0:242:33:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
html2html: Problem with ref "lib"
html2html: Problem with ref "lib"
html2html: Problem with ref "lib"
html2html: Problem with ref "lib"
sgml2html icewm.sgml
sgml2html icewm.sgml
sgml2html icewm.sgml
sgml2html icewm.sgml
Processing file icewm.sgml
Processing file icewm.sgml
Processing file icewm.sgml
Processing file icewm.sgml
nsgmls:<OSFD>0:242:33:E: "DESCRIP" not finished but document ended
nsgmls:<OSFD>0:242:33:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:236:0: start tag was here
nsgmls:<OSFD>0:242:33:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
nsgmls:<OSFD>0:242:33:E: "DESCRIP" not finished but document ended
nsgmls:<OSFD>0:242:33:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:236:0: start tag was here
nsgmls:<OSFD>0:242:33:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
nsgmls:<OSFD>0:242:33:E: "DESCRIP" not finished but document ended
nsgmls:<OSFD>0:242:33:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:236:0: start tag was here
nsgmls:<OSFD>0:242:33:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
nsgmls:<OSFD>0:242:33:E: "DESCRIP" not finished but document ended
nsgmls:<OSFD>0:242:33:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:236:0: start tag was here
nsgmls:<OSFD>0:242:33:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
html2html: Problem with ref "lib"
html2html: Problem with ref "lib"
html2html: Problem with ref "lib"
sgml2html icewm.sgml
html2html: Problem with ref "lib"
sgml2html icewm.sgml
sgml2html icewm.sgml
sgml2html icewm.sgml
Processing file icewm.sgml
Processing file icewm.sgml
Processing file icewm.sgml
Processing file icewm.sgml
nsgmls:<OSFD>0:242:33:E: "DESCRIP" not finished but document ended
nsgmls:<OSFD>0:242:33:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:236:0: start tag was here
nsgmls:<OSFD>0:242:33:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
nsgmls:<OSFD>0:242:33:E: "DESCRIP" not finished but document ended
nsgmls:<OSFD>0:242:33:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:236:0: start tag was here
nsgmls:<OSFD>0:242:33:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
nsgmls:<OSFD>0:242:33:E: "DESCRIP" not finished but document ended
nsgmls:<OSFD>0:242:33:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:236:0: start tag was here
nsgmls:<OSFD>0:242:33:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
html2html: Problem with ref "lib"
nsgmls:<OSFD>0:242:33:E: "DESCRIP" not finished but document ended
nsgmls:<OSFD>0:242:33:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:236:0: start tag was here
nsgmls:<OSFD>0:242:33:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
html2html: Problem with ref "lib"
sgml2html icewm.sgml
html2html: Problem with ref "lib"
sgml2html icewm.sgml
sgml2html icewm.sgml
html2html: Problem with ref "lib"
Processing file icewm.sgml
Processing file icewm.sgml
Processing file icewm.sgml
nsgmls:<OSFD>0:242:33:E: "DESCRIP" not finished but document ended
nsgmls:<OSFD>0:242:33:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:236:0: start tag was here
nsgmls:<OSFD>0:242:33:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
nsgmls:<OSFD>0:242:33:E: "DESCRIP" not finished but document ended
nsgmls:<OSFD>0:242:33:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:236:0: start tag was here
nsgmls:<OSFD>0:242:33:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
nsgmls:<OSFD>0:242:33:E: "DESCRIP" not finished but document ended
nsgmls:<OSFD>0:242:33:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:236:0: start tag was here
nsgmls:<OSFD>0:242:33:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
html2html: Problem with ref "lib"
html2html: Problem with ref "lib"
html2html: Problem with ref "lib"
make[2]: Entering directory '/var/tmp/portage/x11-wm/icewm-9999/work/icewm-9999/doc'
make[2]: Nothing to be done for 'install-exec-am'.
sgml2html icewm.sgml
sgml2html icewm.sgml
 /bin/mkdir -p '/var/tmp/portage/x11-wm/icewm-9999/image//usr/share/doc/icewm'
 /bin/mkdir -p '/var/tmp/portage/x11-wm/icewm-9999/image//usr/share/man/man1'
 /usr/bin/install -c -m 644 icewm.sgml techinfo.sgml '/var/tmp/portage/x11-wm/icewm-9999/image//usr/share/doc/icewm'
 /usr/bin/install -c -m 644 'icewm.man' '/var/tmp/portage/x11-wm/icewm-9999/image//usr/share/man/man1/icewm.1'
sgml2html icewm.sgml
sgml2html icewm.sgml
Processing file icewm.sgml
Processing file icewm.sgml
Processing file icewm.sgml
Processing file icewm.sgml
nsgmls:<OSFD>0:242:33:E: "DESCRIP" not finished but document ended
nsgmls:<OSFD>0:242:33:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:236:0: start tag was here
nsgmls:<OSFD>0:242:33:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
nsgmls:<OSFD>0:242:33:E: "DESCRIP" not finished but document ended
nsgmls:<OSFD>0:242:33:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:236:0: start tag was here
nsgmls:<OSFD>0:242:33:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
nsgmls:<OSFD>0:242:33:E: "DESCRIP" not finished but document ended
nsgmls:<OSFD>0:242:33:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:236:0: start tag was here
nsgmls:<OSFD>0:242:33:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
nsgmls:<OSFD>0:242:33:E: "DESCRIP" not finished but document ended
nsgmls:<OSFD>0:242:33:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:236:0: start tag was here
nsgmls:<OSFD>0:242:33:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
html2html: Problem with ref "lib"
html2html: Problem with ref "lib"
sgml2html icewm.sgml
html2html: Problem with ref "lib"
html2html: Problem with ref "lib"
sgml2html icewm.sgml
sgml2html icewm.sgml
sgml2html icewm.sgml
Processing file icewm.sgml
Processing file icewm.sgml
Processing file icewm.sgml
Processing file icewm.sgml
nsgmls:<OSFD>0:242:33:E: "DESCRIP" not finished but document ended
nsgmls:<OSFD>0:242:33:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:236:0: start tag was here
nsgmls:<OSFD>0:242:33:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
nsgmls:<OSFD>0:242:33:E: "DESCRIP" not finished but document ended
nsgmls:<OSFD>0:242:33:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:236:0: start tag was here
nsgmls:<OSFD>0:242:33:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
nsgmls:<OSFD>0:121:11:E: end tag for "VERB" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:113:0: start tag was here
nsgmls:<OSFD>0:121:11:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
html2html: Problem with ref "lib"
nsgmls:<OSFD>0:242:33:E: "DESCRIP" not finished but document ended
nsgmls:<OSFD>0:242:33:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:236:0: start tag was here
nsgmls:<OSFD>0:242:33:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
sgml2html icewm.sgml
html2html: Problem with ref "lib"
html2html: Problem with ref "lib"
sgml2html icewm.sgml
sgml2html icewm.sgml
sgml2html icewm.sgml
Processing file icewm.sgml
Processing file icewm.sgml
Processing file icewm.sgml
Processing file icewm.sgml
nsgmls:<OSFD>0:242:33:E: "DESCRIP" not finished but document ended
nsgmls:<OSFD>0:242:33:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:236:0: start tag was here
nsgmls:<OSFD>0:242:33:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
nsgmls:<OSFD>0:242:33:E: "DESCRIP" not finished but document ended
nsgmls:<OSFD>0:242:33:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:236:0: start tag was here
nsgmls:<OSFD>0:242:33:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
html2html: Problem with ref "lib"
nsgmls:<OSFD>0:242:33:E: "DESCRIP" not finished but document ended
nsgmls:<OSFD>0:242:33:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:236:0: start tag was here
nsgmls:<OSFD>0:242:33:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
nsgmls:<OSFD>0:242:33:E: "DESCRIP" not finished but document ended
nsgmls:<OSFD>0:242:33:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:236:0: start tag was here
nsgmls:<OSFD>0:242:33:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
sgml2html icewm.sgml
html2html: Problem with ref "lib"
html2html: Problem with ref "lib"
sgml2html icewm.sgml
html2html: Problem with ref "lib"
sgml2html icewm.sgml
Processing file icewm.sgml
Processing file icewm.sgml
Processing file icewm.sgml
nsgmls:<OSFD>0:242:33:E: "DESCRIP" not finished but document ended
nsgmls:<OSFD>0:242:33:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:236:0: start tag was here
nsgmls:<OSFD>0:242:33:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
nsgmls:<OSFD>0:242:33:E: "DESCRIP" not finished but document ended
nsgmls:<OSFD>0:242:33:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:236:0: start tag was here
nsgmls:<OSFD>0:242:33:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
nsgmls:<OSFD>0:242:33:E: "DESCRIP" not finished but document ended
nsgmls:<OSFD>0:242:33:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:236:0: start tag was here
nsgmls:<OSFD>0:242:33:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:2:0: start tag was here
html2html: Problem with ref "lib"
html2html: Problem with ref "lib"
html2html: Problem with ref "lib"
 /bin/mkdir -p '/var/tmp/portage/x11-wm/icewm-9999/image//usr/share/doc/icewm'
 /usr/bin/install -c -m 644 icewm.html icewm-1.html icewm-2.html icewm-3.html icewm-4.html icewm-5.html ./icewm-6.html ./icewm-7.html ./icewm-8.html ./icewm-9.html ./icewm-10.html ./icewm-11.html ./icewm-12.html ./icewm-13.html ./icewm-14.html ./icewm-15.html ./icewm-16.html ./icewm-17.html ./icewm-18.html ./icewm-19.html ./icewm-20.html '/var/tmp/portage/x11-wm/icewm-9999/image//usr/share/doc/icewm'
/usr/bin/install: cannot stat './icewm-6.html': No such file or directory
/usr/bin/install: cannot stat './icewm-7.html': No such file or directory
/usr/bin/install: cannot stat './icewm-8.html': No such file or directory
/usr/bin/install: cannot stat './icewm-9.html': No such file or directory
/usr/bin/install: cannot stat './icewm-10.html': No such file or directory
/usr/bin/install: cannot stat './icewm-11.html': No such file or directory
/usr/bin/install: cannot stat './icewm-12.html': No such file or directory
/usr/bin/install: cannot stat './icewm-13.html': No such file or directory
/usr/bin/install: cannot stat './icewm-14.html': No such file or directory
/usr/bin/install: cannot stat './icewm-15.html': No such file or directory
/usr/bin/install: cannot stat './icewm-16.html': No such file or directory
/usr/bin/install: cannot stat './icewm-17.html': No such file or directory
/usr/bin/install: cannot stat './icewm-18.html': No such file or directory
/usr/bin/install: cannot stat './icewm-19.html': No such file or directory
/usr/bin/install: cannot stat './icewm-20.html': No such file or directory
Makefile:485: recipe for target 'install-nodist_docDATA' failed

**Comment by bbidulock** [comment]
Gosh, works for me too.  Why are most things repeated 3 or 4 times in this listing above?  Something bad.  Try working with a fresh clone of the repository or try building the 1.3.10 release tarball.

**Comment by bbidulock** [comment]
Is this working for you yet?
