### ISSUE TITLE
The latest version of smartgit kills icewm (xorg).

### ISSUE THREAD

**Issue by CheckB** [bbidulock/icewm#280]
I have with me:
icewm latest version from source
ubuntu 16.04 with all updates
integrated graphics card
smartgit latest version

When you run smartgit, icewm and xorg fall, respectively. I doubt that the problem is in smartgit.
In the logs I did not find anything, but I can not make a photo (bad quality).

Any ideas?

**Comment by bbidulock** [comment]
Do you get a core dump?

**Comment by bbidulock** [comment]
These types of problems are often due to buggy i915 xorg drivers.
