### ISSUE TITLE
Is the KeyTaskBarSwitchNext always enabled?

### ISSUE THREAD

**Issue by targzeta** [bbidulock/icewm#281]
I use to use `Alt+N` for my GNU Screen configuration. For a while, when I press `Alt+1` (and only with `Alt+1`) I have a unexpected behavior: it changes the focus to another window, like the `KeySysSwitchNext`.
So I have seen that `Alt+1` is linked to the `KeyTaskBarSwitchNext` within the global configuration file (`/usr/share/icewm/preferences`). It's associated but commented:
```
# KeyTaskBarSwitchNext="Alt+1"
```

The only mode I have found to remove this behavior it was override the global configuration with my personal preferences within the `~/.icewm/preferences`.

**Comment by bbidulock** [comment]
The commented entries in the default preferences file indicate the default setting.  Yes, the way to override the defaults is with your own preferences file or to change the system preferences file.

**Comment by targzeta** [comment]
Thank you for your reply. Is there a way to disable this key binding? What if I don't want this feature?

Best regards,
Emanuele

**Comment by gijsbers** [comment]
Just define it as the empty string.

**Comment by targzeta** [comment]
Ok, thank you very much!

Emanuele
