### ISSUE TITLE
How is the height of the taskbar handled?

### ISSUE THREAD

**Issue by mobusdorphin** [bbidulock/icewm#283]
I am currently trying to fiddle with the size of the taskbar in IceWM 1.2.37.  I was able to adjust the height of the start menu icon and the menu buttons, but I wasn't able to figure out how to adjust the height of the actual tasks on the taskbar.  When I edited the (Normal|Active)TaskBarFontName values, the font would grow, but would be cut off if it was larger than the task bar, which is not how (Normal|Active)ButtonFontName behaved.  Note that I am in double-height mode, so the task bars are on a separate row underneath the start menu and menu buttons.  I know that messing with the sizes of the tray goodies isn't supported until 1.4, but I was wondering how to mess with the size of the actual taskbar on the bottom row, and if that also requires 1.4.

**Comment by bbidulock** [comment]
Can't really help you with 1.2.7 as this fork started on the 1.3 branch.

**Comment by Code7R** [comment]
I have no idea either, never touched that part.

@mobusdorphin Are you going to redesign the double-height mode? If yes, shall we use this ticket to discuss changes? (IMHO the current double-height mode sucks and wastes too much space and also is also inconvenient because the show-desktop button is ditched in the corner instead of the task menu).

**Comment by mobusdorphin** [comment]
@Code7R I wouldn't mind helping out but I'm still quite the beginner at working with C.  I'm starting to get a vague idea of how things are put together in IceWM but still overall trying to get my head wrapped around it.  Aside from fixing the behaviour of the show-desktop button, what were you hoping to see from a new double-height mode?

**Comment by covex** [comment]
According to theme howto I wrote many years ago the taskbar can be resized like this:

Resizing taskbar

Taskbar height could be changed in two ways. Either increased by making taskbar "start.xpm" higher (in 1.2.23 it is broken for TaskBarDoubleHeight=0) or by changing SmallIconSize pref. Taskbar is then height to fit icons of that size. Remember that while taskbar height is changed not all taskbar parts are changed accordingly (e.g. monitors).

**Comment by cheapy** [comment]
I realize this is an old request, but at least in more recent versions the toolbar and taskbar height varies depending on what theme I'm using, ie Clearview Blue Large, Medium or Small in antiX that I use, and as noted above, the height of the start button on the theme.  

![screenshot_11](https://user-images.githubusercontent.com/7473967/92412542-da741480-f111-11ea-9cec-aa7458235ed9.jpg)
I also use autohide and doubleheight at the same time so if I add my commonly used applications to the toolbar, I rarely need to use the menus, and screen space is only used when I pop up the toolbar and taskbar.
