### ISSUE TITLE
FYI icewm.org seems to be up for auction

### ISSUE THREAD

**Issue by ldarby2** [bbidulock/icewm#287]
icewm.org is redirecting to https://www.dropcatch.com/Domain/icewm.org which says:

Current Bid:  $360 USD
Auction Ends In: 5h 22m (as of Saturday, 18 August 2018, 13:38:24 GMT).

It looks like this was taken over from the original owner 3 days ago (or possibly earlier):

```
$ whois icewm.org
Domain Name: ICEWM.ORG
Registry Domain ID: D402200000007199727-LROR
Registrar WHOIS Server: whois.namebright.com
Registrar URL: http://www.NameBright.com
Updated Date: 2018-08-15T15:36:06Z
Creation Date: 2018-08-15T14:30:21Z
Registry Expiry Date: 2019-08-15T14:30:21Z
Registrar Registration Expiration Date:
Registrar: DropCatch.com 1477 LLC
Registrar IANA ID: 3686
Registrar Abuse Contact Email: abuse@NameBright.com
Registrar Abuse Contact Phone: +1.7204960020
Reseller:
Domain Status: serverTransferProhibited https://icann.org/epp#serverTransferProhibited
Domain Status: addPeriod https://icann.org/epp#addPeriod
Registrant Organization: www.DropCatch.com
Registrant State/Province: CO
Registrant Country: US
Name Server: NS1.NAMEBRIGHTDNS.COM
Name Server: NS2.NAMEBRIGHTDNS.COM
DNSSEC: unsigned
URL of the ICANN Whois Inaccuracy Complaint Form https://www.icann.org/wicf/)
>>> Last update of WHOIS database: 2018-08-18T13:38:21Z <<<
```

Just thought someone here might want to know about this and try to get it if possible...

**Comment by ldarby2** [comment]
(if you're wondering who I am, I authored this: https://sourceforge.net/p/icewm/mailman/message/34259046/)

**Comment by bbidulock** [comment]
Does it really matter if it goes away?  We can always host the content here on gh-pages.

**Comment by gijsbers** [comment]
It does matter, because a lot of sites and software refer to it. Even this repo. A short recognizable domain name would be nice. We could use another. Also see #92.

**Comment by ldarby2** [comment]
I didn't watch the end of the auction but this page says https://namebio.com/blog/daily-market-report-for-august-18th-2018/ says it went for $3,750.

Personally, I really didn't like having to register ldarby2 here because someone else already has ldarby.  That's my opinion of icewm2.org.    There are several better ideas that would involve a minor rebrand (thinking of what other projects have done, e.g. ncurses, rsyslog, etc).

**Comment by gijsbers** [comment]
Don't understand why they are willing to pay so much.

Updated homepage url to something githubish for the time being:
    https://ice-wm.github.io/
I'd be happy to give full permissions to whoever wishes to improve that website.

**Comment by ldarby2** [comment]
It's been a couple of weeks and nothing has changed since the take over.  Are we happy with  https://ice-wm.github.io?  How about getting the domain ice-wm.org?

**Comment by bbidulock** [comment]
I would rather have something that an active maintainer controls, so ice-wm.github.io is fine.

**Comment by ldarby2** [comment]
ice-wm.org isn't currently registered, doesn't that mean you can get it for $10 per year or something like that?

**Comment by gijsbers** [comment]
If desired one could allocate a domain and donate it. In order to conform to bbidulocks wish I could manage it for you. The domain would need to be allocated for a significant number of years. Say 15 or 20 or so, in order to be worthwile. E.g., create an account on joker.com or versio.eu, buy the domain of your choice with the number of years, and donate the account or transfer the domain. I'll configure the details then. Doesn't need to be in the .org domain, as that can be more expensive others. Look at the yearly renewal cost. Names like icewm.eu, icewm.de, icewm.nl, icewm.io and icewm.ca are all still free. Also consider the privacy regulations of the TLD of your choice.

**Comment by ldarby2** [comment]
Ok, good plan, thanks, I'm happy to go ahead with that.  I'm not really a fan of a location specific tld, and .io is way too expensive to consider (and they're actually a country anyway).  I'll try to get ice-wm.org, for 20 years, and I'll need to spend some time searching for the cheapest registras for this (that allows privacy, it looks like Joker does and Versio doesn't, from what I can see).

**Comment by gijsbers** [comment]
Cool! Maybe interesting: 3 Year Value Score and Rating at
https://tld-list.com/tld/org

**Comment by ldarby2** [comment]
Alright, thanks for finding that, I went with porkbun and got it now.  10 years is the max though for any domain though, per ICANN rules.  I think you just need to create an account there and I can "push" it you, see https://kb.porkbun.com/article/72-how-to-push-a-domain-into-another-account.

**Comment by gijsbers** [comment]
Free beer for ldarby2 from now on everywhere he goes: [site is up](https://ice-wm.org). Thanks!

**Comment by ldarby2** [comment]
You're welcome,  I've also now updated Wikipedia: https://en.wikipedia.org/wiki/IceWM.  Let's close this issue!
