### ISSUE TITLE
[Information Request]  What is the window information for IceWM's menus?

### ISSUE THREAD

**Issue by rdrms** [bbidulock/icewm#289]
I've tried a few things, including `wmctrl -l` while the menu is active, and it appears to simply not exist according to this tool.  I'm unable to get a window ID or name with `xprop` either, because I can't click on it.  It doesn't appear to be a command, although `icewm-menu (5)` is listed in my system - apparently documenting the configuration.

Reason I'm looking for this issue is that I would like to add true transparency to the menu to match the rest of the desktop, I'm hoping to accomplish this with compton and it needs to be an opacity rule either a name or a class_g I think are the two options.  The menu-opacity setting doesn't appear to effect IceWM, although thankfully the window border opacity setting does work.   Bonus points if this works on the window resize OSD that pops up on moving/rezising windows.

Thanks for your time and this great wm.

**Comment by gijsbers** [comment]
Good point. This commit introduces IceMenu, IceStatus and IceSwitch titles.

You can see those names connected to window IDs if you do something like:

    sleep 5 ; xwininfo -tree -root

**Comment by rdrms** [comment]
Amazing!  Not only responded but patched and made available within 9 hours.  Great job!

I'll just share my relevant compton config.conf settings and post a screenshot with what I have achieved with your help, and I'll close this issue since it is 100% resolved to my satisfaction.

in `~/.config/compton.conf` 
```
opacity-rule = [
   "60:class_g *= 'IceWM'",
   "75:class_g *= 'dmenu'", 
   "60:name *= 'IceMenu'",
   "60:name *= 'IceStatus'",  
   "60:name *= 'IceSwitch'",
];
```

![2018-08-26-085103_2560x1440_scrot](https://user-images.githubusercontent.com/2936638/44629544-3e05bd80-a90e-11e8-8a55-27a8a3f0d185.png)


Thanks again for your help
