### ISSUE TITLE
How can I prevent windows from covering my non-default panel?

### ISSUE THREAD

**Issue by rdrms** [bbidulock/icewm#290]
I'm using tint2 as a replacement for the IceWM default panel since I like it better, but I'm having an issue where maximized windows will either cover or go underneath the tint2 panel (depending on the setting of tint2).  This happens when you maximize a window or switch to a different layout (tile, stacked, etc).

Basically I'm looking for something similar to OpenBox's feature that lets you create a margin on the sides of the screen so that maximized windows do not cover the space reserved for the panel (but the panel is still able to go there).  

I think I'm on to something with the winoptions config file, but I'm not sure what sort of arguments I would pass to it.  `tint2.geometry` seems to change where the panel goes, but I'm not sure how to specify the geometry for every other window (possibly `*.geometry` ?).

Essentially I'm trying to reserve 24 pixels at the top for tint2 and then use the rest of the screen for windows.

Thanks for your help!

**Comment by gijsbers** [comment]
Looks like this is not supported by icewm.

**Comment by bbidulock** [comment]
Icewm did at one time support _NET_WM_STRUT which is how the panel tells the window manager to reserve space for the panel.  Also, _NET_WORKAREA is supported as well as _NET_WM_STATE_MAXIMIZED_VERT and _NET_WM_STATE_MAXIMIZED_HORZ, and _NET_WM_STATE_FULLSCREEN.  Check that your tint setup is setting _NET_WM_STRUT, otherwise, windows will maximize over the panel.

**Comment by arsonoff** [comment]
~/.icewm/preferences:
`LimitByDockLayer=1`

~/.config/tint2/tintrc:
`panel_layer = Dock`

**Comment by gijsbers** [comment]
Good! This might also work:
~/.icewm/winoptions:
`tint2.doNotCover: 1`

**Comment by ghost** [comment]
Should setting `_NET_WM_STRUT_PARTIAL` also work? I have this issue with polybar instead of tint2, even after setting `LimitByDockLayer=1`. polybar sets `_NET_WM_STRUT_PARTIAL` instead of `_NET_WM_STRUT`.

**Comment by gijsbers** [comment]
Icewm treats _NET_WM_STRUT_PARTIAL as _NET_WM_STRUT. It only takes the first four values.
