### ISSUE TITLE
Windows with STATIC gravity change its y position when showing/hiding

### ISSUE THREAD

**Issue by albert-astals-cid-kdab** [bbidulock/icewm#291]
With these example files
  icewm_bug.pro https://paste.kde.org/pbctvf96o
  main.cpp https://paste.kde.org/pljxbmv36
that you can compile by doing
```
  qmake
  make
```

You will have an application that has a window with STATIC gravity and changes its y position every time it's hidden and then shown.

I think there's a bug in YFrameWindow::unmanage that should have a similar 
```
        if (sh && (sh->flags & PWinGravity) &&
            sh->win_gravity == StaticGravity)
```
branch like YFrameWindow::doManage has.

**Comment by gijsbers** [comment]
Thanks for the excellent problem report!
This commit fixes it for me.

**Comment by albert-astals-cid-kdab** [comment]
Thanks for such a quick fix :)

**Comment by bbidulock** [comment]
@albert-astals-cid-kdab, if this problem is resolved, please close the issue.

**Comment by albert-astals-cid-kdab** [comment]
Sorry for the delay, was on holiday.
