### ISSUE TITLE
KeySysWorkspace?TakeWin Doesn't Focus Last Window

### ISSUE THREAD

**Issue by kuwanger** [bbidulock/icewm#292]
If you have three windows on workspace 1--A, B, and C--shift focus from B to C, then use KeySysWorkspace2TakeWin (for example) to move C to workspace 2, when you switch back to workspace 1 focus will go to A, not B.  I presume this has something to do with the logic of occupy all for window C then occupy one for window c on workspace 2 not honoring the last focus on workspace 1, but I can't fully follow the logic to debug/fix this myself.

While this may be the new desired behavior (from 1.4.2 (I believe that's the last version I was using)), it wasn't the old behavior and it'd be nice if it was user configurable.  If there already is a new option to effect this, I'd be interested because it's not clear from the options.

Edit: Sorry, "A, not B".

**Comment by bbidulock** [comment]
Not too sure about this.  Ice doesn't maintain a focus stack as far as I know like some other window managers do.  I find that behaviour annoying too (I think you meant "A not B").

**Comment by kuwanger** [comment]
Yes, sorry about that.  Looking at an older version (1.2.16) I don't immediately see any change to switchToWorkspace() itself that would be the issue.  My understanding was icewm used a looping linked (double linked?) list, so the issue seems to be that it's moving up the list instead of down (effectively).  What's particularly annoying for me is that I have all the auto focus stuff disabled, so switching back the actual focused window isn't even raised.

In the same vein if you do KeySysWorkspace2TakeWin(A window) -> KeySysWorkspace1() - > KeySysWorkspace2(), A won't be focused on workspace 2.  It's all very inconsistent to me, and I don't know what sort of magic made it work correctly in older versions.  I should probably bisect some older versions and see if I can narrow down the commit.

Edit:  Just writing to confirm that 1.4.2 here is the last release that doesn't have this bug.  Oddly, every release (1.4.0, 1.4.1, and 1.4.2) here I grab and compile will hang and then segfault when I try to click on the taskbar toolbar.  Maybe it has something to do with menuprogreload or some other feature that was added and breaks older versions?  Regardless, the near latest f6b12a7d doesn't have this issue, so it's mostly a moot point except that I can't use 1.4.2 in the interim.  I'll probably do some googling and work on figuring out which commit is the culprit.  My guess is it has something to do with the taskbutton switching as I'm unaware of anything else that's changed the focus code.

Edit2:  After some bisecting, I found out it's commit 8d8d827f579ce833ba10daabad0252649a4dba91 "Move brittle inline frame list manipulations into robust dedicated list class."

**Comment by gijsbers** [comment]
twasatypo a46609eb7dc42fb37fee27ce4d8bdc53ae6756dc

**Comment by kuwanger** [comment]
Thank you for the fix.

**Comment by gijsbers** [comment]
You're welcome. Thx for the bisect!
