### ISSUE TITLE
Primary screen decission and task workspace viewer dimensions sometimes not updated

### ISSUE THREAD

**Issue by Code7R** [bbidulock/icewm#296]
Hi,

while working in nomad mode I ran multiple time in situations where taskbar is displayed on the wrong monitor and the panel size in the taskbar previewer is not updated. This seems to happen when:
a) additional monitor is attached and xrandr is used to move to change the virtual location (although primary monitor shall remain the same)
b) second screen is disconnected while system is suspended

It feels like some XRANDR/Xinerama event might get lost or confused or something like this.

Sample pic is attached, the second screen was disconnected at that moment and the previewer size should not be that wide (it looks like with the previous with two screens, and restarting icewm makes it look normal again.

![bildschirmfoto_2018-09-08_11-05-38](https://user-images.githubusercontent.com/10660264/45252572-f09b3e80-b358-11e8-9e11-47b92d0212c6.png)

**Comment by gijsbers** [comment]
Commit 15c52bdfb3637674b208e5e1101c10cc5695b4f2 tries to address this. Could you verify?

**Comment by Code7R** [comment]
It's much better now. Feels like 90 percent of the glitches previously seen are now gone. Sometimes there are weird things in window placement but I think I can attribute them to a suboptimal algorithm in icewm-menu-xrandr . I will try to observe it in detail in the next week. For now, we can close this.

Thank you.
