### ISSUE TITLE
Tab autocompletion of yinputline shows misleading results

### ISSUE THREAD

**Issue by Code7R** [bbidulock/icewm#297]
The current behavior of autocompletion action is weird. On success, it display the input as marked. On multiple option, it does the same. On failure, it does not indicate anything.

I have a vague idea on how to make it better.

a) rewrite globit.c in true C++ to get rid of the GOTO hell, and to collect output of multiple glob() rounds

b) indicate error as color change of the input line. Maybe red background? Or red font? Anyone having good arguments?

c) indicate multiple options by displaying them behind the cursor, with darker font (or lighter? Or just an average color, mean value of background and font?), maybe highlighting the first deviating letter after the length of entered prefix string with some color. Orange?

**Comment by gijsbers** [comment]
b) Maybe draw in inverse colors for half a second?
c) Maybe a choice of possible deviating letters like `tint|<Tab>` -> `tint|[23]`,
where the choice `[23]` is selected and overwritten.

**Comment by Code7R** [comment]
Instead of inverse colors, I decided to use the existing Tooltip and show the alternatives line by line, while using a Ellipsis to separate the prefix and the potential candidates. Tried spaces and [] and | but ... still looked best.

The implementation is not perfect, maybe globit code should be reimplemented in plain C++ after all to have easier and more precise information collection.
