### ISSUE TITLE
Taskbar transparency

### ISSUE THREAD

**Issue by takiz** [bbidulock/icewm#299]
Hi.
How to make taskbar's background transparent?

**Comment by gijsbers** [comment]
Change the taskbarbg.xpm to be transparent.

**Comment by takiz** [comment]
theme_name/taskbar/taskbarbg.xpm transparent:
```
/* XPM */ 
static const unsigned char * pic_xpm[] = {
"1 5 1 1",
"  c None",
" ",
" ",
" ",
" ",
" "};
```

Doesn't work with any icewm-theme — only black color instead of the transparency.   
At that time, transparency in the other windows (e.g. conky) works fine.

**Comment by bbidulock** [comment]
I think you need to run a composite manager to turn the black into transparent.

**Comment by gijsbers** [comment]
Looked into this and it turns out not so easy as the background is set and copying of pixmaps ignores transparency. [This technique](https://www.dis.uniroma1.it/~liberato/screensaver/trans.html) isn't applied by Ice. Even if it was then it still is tricky to setup. So no it can't.

**Comment by frankzen** [comment]
I am wondering what technique tint2 (taskbar replacement) uses to implement transparency. On my machine (no composite manager) I have a transparent taskbar under IceWm drawn by tint2.

**Comment by gijsbers** [comment]
@takiz Is this issue still of interest to you?
It is possible to do in the 1.6.1 release if you set Alpha=1
and use the following taskbar/taskbarbg.xpm:

```C
/* XPM */
static char * taskbarbg_xpm[] = {
"1 26 1 1",
"       c None",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" "};
```

**Comment by gijsbers** [comment]
This feature is used beautifully by the [Alette-Icewm theme](https://www.box-look.org/p/1319927/).

**Comment by gijsbers** [comment]
Theme JustIce_MD also has interesting effects.

**Comment by gijsbers** [comment]
+ aluminium
