### ISSUE TITLE
Missing icons in "Desktop Apps" menu

### ISSUE THREAD

**Issue by rezso** [bbidulock/icewm#30]
Snip from the, menu which is generated with icewm-menu-fdo:

menu "Games" folder {
prog "0 A.D." 0ad 0ad
prog "cave9" /usr/share/cave9/icon.png cave9

The icons for 0ad is missing in the menu, the cave9 icon is showed.
The Icon key in the 0ad desktop file contains "Icon=0ad", because the icon is a png file, and the "Icon=0ad.png" not allowed by desktop-file-validate command. The icewm-menu-fdo command doesn't appends neither full path, neither .png extension.

**Comment by Code7R** [comment]
First: I cannot SEE the problem. The icon is displayed just fine (at least for me, on Debian).

Second: yes, the suffix is missing piece of information in the original file. It might be an xpm and might be located elsewhere, do you expect miracles or from the menu generator on guessing this? Or waste of CPU cycles for no good reason? (icewm does scan the filesystem already, no need to repeat this)

Third: most .desktop files I see here are "affected" by this non-problem, is there anything special about 0ad?
/usr/share/applications $ grep Icon= . -r | grep -v png | grep -v "xpm|png" | wc -l
259

**Comment by rezso** [comment]
I attach two screenshot. 
![uv1](https://cloud.githubusercontent.com/assets/2437550/8599806/cc2c2fea-2662-11e5-9432-dcd82449efc7.png)
![uv2](https://cloud.githubusercontent.com/assets/2437550/8599813/d44b884c-2662-11e5-9137-dd22d8e8f872.png)

So, if the menu file contains just a filename for the icon (f. ex. "prog "0 A.D." 0ad 0ad"), the icon is missing in the menu.
But if the menu file contains full path for the icon (f. ex. prog "cave9" /usr/share/cave9/icon.png cave9"), the icon is displayed.

**Comment by rezso** [comment]
Solved.
This problem caused by the empty IconPath in the preferences file.
It should be contain the /usr/share/icons and /usr/share/pixmaps directories, I think these directories are commonly used.

**Comment by rezso** [comment]
Just a note: the preferences file is not generated, if I build the source with cmake.

**Comment by bbidulock** [comment]
Please file a separate issue for the preferences file not being generated in cmake build.
