### ISSUE TITLE
Start of runonce-programs from the key.

### ISSUE THREAD

**Issue by arsonoff** [bbidulock/icewm#300]
It is possible to start the runonce-program from the menu and toolbar, but from the key it is impossible?
Thought icewmhint will help, but there are no such options.

**Comment by gijsbers** [comment]
The key could start a script you write which checks the runonce property you want.

**Comment by arsonoff** [comment]
Something similar? 
```
$ wmctrl -lx | grep ...
$ xdotool search ...
```
Tools from icewm will not turn out?
