### ISSUE TITLE
Bug in start menu button

### ISSUE THREAD

**Issue by asdplayer** [bbidulock/icewm#302]
Happens only with the stock themes **motif**, **yellowmotif** and **gtk2**.
Left-clicking and releasing on the start menu button normally brings up the start menu.
But if the left-click is done in the bottom two rows of pixels of the start menu button, **when releasing the left-mouse-button the menu disappears.**
This is best noticed when aiming fast and not precisely the mouse pointer to the bottom left corner of the screen, such as when you want to reach the start menu fast. As a result of the subsequent left-click, the menu just flashes instead of appearing steady.
I'm running yesterday's git version (24/09/2018), however the bug is present since a while. I didn't file a report until now because I wasn't able to reproduce consistently this issue. Moreover, I just got away with a workaround: I click-and-dragged on the start menu button and released over the application I wanted to launch.
I've not been able to debug the code myself, since I'm just beginning to do such a thing on others' applications.

**Comment by asdplayer** [comment]
My preferences file, renamed so that it was accepted by GitHub.
[preferences.txt](https://github.com/bbidulock/icewm/files/2414526/preferences.txt)

**Comment by gijsbers** [comment]
Can't reproduce it. Might depend on your system setup?

**Comment by asdplayer** [comment]
Maybe. I don't know where to start, so you may want to point me what information I should provide.
I'm running icewm on Arch Linux (building the [package from AUR](https://aur.archlinux.org/packages/icewm-git/) on an [Atom x5-z8300](https://ark.intel.com/products/87383/Intel-Atom-x5-Z8300-Processor-2M-Cache-up-to-1-84-GHz-) netbook with intel HD graphics; the driver is i915 1.6.0, it runs on default settings for my GPU.

**Comment by asdplayer** [comment]
In the past few days I noticed that another user I have on the same machine has a similar issue: clicking and releasing on the bottom ~10 lines of pixels of the start menu button, the start menu doesn't stay, it just flashes and goes away with the release of the mouse button.
Recently I added some more items to the menu of that user, so that it doesn't fit in the screen anymore. Now clicking on the start menu button always brings the menu on steady, leaving some pixels from the bottom (I think they are actually 10...), while it overflows off the screen from the top. If I click on the remaining portion of the start button (such as for closing the menu), the menu flickers but doesn't disappear. This happens at the release of the mouse button, nothing happens on mouse button-down (I mean pressing-and-holding the button). I attached a screenshot.

I should point out that Ctrl-ESC or the "windows" keyboard keystrokes work as expected.

![bug-icewm-startmenu](https://user-images.githubusercontent.com/43568018/46259347-8ea5a300-c4d8-11e8-8510-c2e42d4ad7b9.png)

**Comment by gijsbers** [comment]
I'm sorry but I still cannot reproduce it. Can you reproduce
it for other X servers like Xvfb, Xvnc and Xephyr?

**Comment by asdplayer** [comment]
I didn't know that other X servers existed. I'll try within some time.

**Comment by bbidulock** [comment]
There are, unfortunately, a lot of problems with the i915 driver in current kernels, that plague a lot of my machines running Arch.  The ones with the most problems are my Atom x5-z8300 and x5-z8350 boxes because current kernels cause lots of difficulties with Atom SoC too.  See if you can recreate on a machine not running an intel video chip, or at least a somewhat current intel based machine, very compatible with Linux, that is not a notebook.

**Comment by asdplayer** [comment]
Thank you for your answers. At some point in the last four months the issue disappeared. I don't know what caused it, in the meantime the Intel graphics driver has been updated many times, and IceWM too, but I had no time to dig further. So, for now, thank you, but I have got nothing else about this.

**Comment by bbidulock** [comment]
If it is no longer a problem, please close this issue.

**Comment by asdplayer** [comment]
Ok, thank you!
