### ISSUE TITLE
Change modifier key to move window with mouse (currently is Alt+mouse drag)

### ISSUE THREAD

**Issue by morfeus2** [bbidulock/icewm#304]
I looked everywhere and I can not find a way to redefine the modifier key to allow moving window by clicking everywhere on the window. The default is "Alt" that is perfect for standard use, but I use very often a second instance of icewm inside VNC and I would like to have the possibility to set another modifier key for it.
If it's not possible to change it at runtime I would appreciate if someone could point me where to change it in the sources.

**Comment by gijsbers** [comment]
`icewm --postpreferences | grep MouseWin` should give you those settings.
`cp ~/.icewm/preferences /tmp/p && vi /tmp/p && icewm -c /tmp/p -d :1`
should succeed.

**Comment by morfeus2** [comment]
Wow thanks for the very fast and useful answer!!
icewm --postpreferences does not work, I think cause my icewm version is quite old (Debian still ships 1.3.8+mod+20161220-1), but the key was the setting keyword "MouseWinMove".
I'm sorry I did not find it before.
Adding
`MouseWinMove="Super+Pointer_Button1"`
in preferences file did it!!

Since this resolution was so fast I dare to as another question (I promise this is my last one!)
Any way to have the mouse button 2 click on window title to lower the window? (as found in other window manager like for eg. xfwm4)

From what I tried, I think `KeyWinLower` only accepts keys as parameters, not mouse clicks unfortunately.
For the moment the most similar behavior I found is `LowerOnClickWhenRaised=1`

**Comment by gijsbers** [comment]
You may want to upgrade because of the many many
many new features and improvements since 1.3.8. 
https://packages.debian.org/buster/icewm
and
https://github.com/Code7R/icewm/releases
are 2 places to look for Debianics.
Note that 1.3.8 is from 2013-11-17!

I agree it's inconsistent that we do have a
`MouseWinRaise` but not a `MouseWinLower`.
I'll add it sometime someday.

**Comment by morfeus2** [comment]
> You may want to upgrade because of the many many
> many new features and improvements since 1.3.8.
> https://packages.debian.org/buster/icewm
> and
> https://github.com/Code7R/icewm/releases
> are 2 places to look for Debianics.

Sure, i'll have a look.

> Note that 1.3.8 is from 2013-11-17!

Yeah, I just noticed today and I was really surprised too.
 
> I agree it's inconsistent that we do have a
> `MouseWinRaise` but not a `MouseWinLower`.
> I'll add it sometime someday.

Thanks for everything, I love this WM (it's the default of my laptops and runs inside VNC on all my desktops)
