### ISSUE TITLE
Icewm crashing when going into full screen.

### ISSUE THREAD

**Issue by SolisX** [bbidulock/icewm#307]
Hello Everyone,

I've gotten 2 crashes when entering into full screen. One happened with wine. The other was with
zsnes. I don't have any of logs of what happened though. I just remember that the icewm crashed and
a dialog box giving me the option to restart icewm.

This happened on icewm-1.4.2-1571. I'll see if i can get a log of the crash.

**Comment by gijsbers** [comment]
Any more success with this? Could you run icewm from valgrind or from gdb?

**Comment by SolisX** [comment]
@gijsbers No unfortunately i haven't got it to crash again. I'm going to try a few more times. If i can not get it to crash i will close the issue out.

**Comment by SolisX** [comment]
Closing this issue because i have not been able to get it to crash again. If i can get icewm to crash and have a log of the crash i will reopen the issue.
