### ISSUE TITLE
Theme "motif" not show the "menuButton.xpm" icon

### ISSUE THREAD

**Issue by winlin0330** [bbidulock/icewm#31]
Hi~
I use a motif theme under icewm.
In $HOME/.icewm/themes/motif-blue/default.theme, my setting is
Look=motif
ShowMenuButtonIcon=0

I have "menuButtonA.xpm", "menuButtonI.xpm" and "menuButton.xpm" in $HOME/.icewm/themes/motif-blue/ ,
![motif_no_icon2](https://cloud.githubusercontent.com/assets/13253588/8593473/9f9edbf0-266a-11e5-9ddd-bdf08c556514.png)
But I found icewm will not show any "menuButton*.xpm" icon on the title bar.
![motif_no_icon](https://cloud.githubusercontent.com/assets/13253588/8593447/5af7c962-266a-11e5-8056-d21e21a24024.png)
Would you fix this problem?
Thank you~

Note: I posted the bug before:
http://sourceforge.net/p/icewm/bugs/914/

**Comment by bbidulock** [comment]
Try the above commit and see whether that fixes things for you.

**Comment by winlin0330** [comment]
bbidulock:
Hi~ 
I downloaded and replaced the 2 files (decorate.cc and wmbutton.cc) in icewm-1.3.10/src.
After recompiling, the result was the same, title bar still had no menu button icon.
Thanks.

**Comment by winlin0330** [comment]
The motif theme I used can be downloaded here:
https://sites.google.com/site/winlin0330/files/motif-dark.tar.gz?attredirects=0&d=1
Thanks~

**Comment by gijsbers** [comment]
This commit shows your menuButton pixmap for me. Could you verify? The menuButton seems to have a different feel than the other buttons of motif-dark? I like the theme. Would be a nice addition or replacement for one of the blue themes.
