### ISSUE TITLE
Feature Request:  Start Menu on Double Height Taskbar

### ISSUE THREAD

**Issue by kuwanger** [bbidulock/icewm#314]
It'd be useful to be able to define where components are placed on the Taskbar, especially when using a Double Height Taskbar and especially the ability to swap the Start Menu location with the Show Desktop/Show Windows List buttons so moving to the most bottom left would allow quickly accessing the start menu.  It's really the last part that seems the most useful and readily doable.

**Comment by gijsbers** [comment]
If `Win95Keys=1` then the left Windows key will popup the Start Menu. Doesn't that work for you @kuwanger?

**Comment by kuwanger** [comment]
Yes.  The reason I make the feature request is that it would seem good design that being able to quickly move to the corner of the screen (bottom left or top right depending on where you put your taskbar) to access the Start Menu instead of necessarily relying upon a keyboard hotkey or having to carefully move up ~32 pixels to actually be over the Start Menu.  A lot of other WMs are much worse actually putting a 1px unclickable border around their Start Menu and this is obvious not an issue with IceWM if you're using a single height taskbar.  Still being able to swap the buttons would restore the usefulness of not having to exactly aim with the mouse.

**Comment by gijsbers** [comment]
Adding more options for this gives overhead which is not worth the benefit, but simply swapping the buttons is an option if nobody complains.
