### ISSUE TITLE
In installation Without any Browser the Browser icon in icewm Has No Effect.

### ISSUE THREAD

**Issue by zhengqiang130** [bbidulock/icewm#318]
In icewm there is a browser icon in the menu bar. Clicking on that icon is having no effect. `~/.xsession-errors-:0` lists "x-www-browser: command not found" and the same for many alternatives, e.g. "firefox, iceweasel", etc.

/usr/bin/xdg-open: line 844: firefox: command not found
/usr/bin/xdg-open: line 844: iceweasel: command not found
/usr/bin/xdg-open: line 844: seamonkey: command not found
/usr/bin/xdg-open: line 844: mozilla: command not found
/usr/bin/xdg-open: line 844: epiphany: command not found
/usr/bin/xdg-open: line 844: konqueror: command not found
/usr/bin/xdg-open: line 844: chromium: command not found
/usr/bin/xdg-open: line 844: chromium-browser: command not found
/usr/bin/xdg-open: line 844: google-chrome: command not found
/usr/bin/xdg-open: line 844: www-browser: command not found
/usr/bin/xdg-open: line 844: links2: command not found
/usr/bin/xdg-open: line 844: elinks: command not found
/usr/bin/xdg-open: line 844: links: command not found
/usr/bin/xdg-open: line 844: lynx: command not found
/usr/bin/xdg-open: line 844: w3m: command not found
xdg-open: no method available for opening 'about:blank'

**Comment by bbidulock** [comment]
Make sure you have PATH environment variable set properly before launching icewm: you're xdg-open is saying that it cannot find any of them by name.

**Comment by zhengqiang130** [comment]
> Make sure you have PATH environment variable set properly before launching icewm: you're xdg-open is saying that it cannot find any of them by name.

In this situation that there is no browser installed, whether the browser icon in the menu bar should not be displayed?

**Comment by chuchingkai** [comment]
IIUC, zhengqiang130 means that some distribution provides a minimal installation set which doesn't include any web browser application in it.

But /lib/toolbar is defined statically as:
> prog "@XTERMCMD@" utilities-terminal @XTERMCMD@
> prog "Web browser" web-browser xdg-open about:blank

So a Web browser icon is displayed in toolbar even though there is no web browser in your system. And there is no response if you click the icon.

I think the point of this issue is:
Can icewm display toolbar icon dynamically?

**Comment by chuchingkai** [comment]
Another finding, if w3m is the only browser app in the system:
> prog "Web browser" web-browser xdg-open any_valid_url

can't start w3m in the default terminal.

If I modified it as:
> prog "Web browser" web-browser xterm -e xdg-open any_valid_url

it works.

**Comment by gijsbers** [comment]
Could you explain how you build your icewm? Using autoconf or cmake?

**Comment by chuchingkai** [comment]
> Could you explain how you build your icewm? Using autoconf or cmake?

I tested this issue with openSUSE Leap 15.1 which uses autoconf.
The version is icewm-1.4.2, you can find the build configuration via [openSUSE Build System](https://build.opensuse.org/package/view_file/openSUSE:Leap:15.1:Update/icewm/icewm.spec?expand=1)

**Comment by chuchingkai** [comment]
> Another finding, if w3m is the only browser app in the system:
> 
> > prog "Web browser" web-browser xdg-open any_valid_url
> 
> can't start w3m in the default terminal.
> 

It turns out the output of w3m was directed to journal logs:
![icewm-w3m-toolbar](https://user-images.githubusercontent.com/3013329/65307837-5270c400-dbbb-11e9-90c4-e5e04dcc6c0e.png)

icewm doesn't know how to handle w3m, one simple workaround is as below

> If I modified it as:
> 
> > prog "Web browser" web-browser xterm -e xdg-open any_valid_url
> 
> it works.

But we can also add a w3mCommand just like cupCommand and mailCommand

**Comment by bbidulock** [comment]
Why not use [xdg-launch](/bbidulock/xdg-launch)?  You can then launch any browser, including a console based one with a proper `.desktop` file using the command

    xdg-launch text/html
