### ISSUE TITLE
DesktopBackgroundImage now does not work with relative path

### ISSUE THREAD

**Issue by bedna-KU** [bbidulock/icewm#319]
I had before in theme:

`DesktopBackgroundImage="default.jpg"`

but now work only with absolute path:

`DesktopBackgroundImage="/home/mario/.icewm/themes/LegacyIce-Dark/default.jpg"`

Path with ~ also does not work

**Comment by gijsbers** [comment]
Useful!

**Comment by bedna-KU** [comment]
Work with .png images but does not work with .jpg

LOG .xsession-errors:

icewmbg: Warning: Support for JPEG images was not enabled
icewmbg: Warning: Could not load image "/home/mario/.icewm/themes/LegacyIce-Dark/ku_1.jpg": No such file or directory
...

Image exists I try show image from commandline

**Comment by bedna-KU** [comment]
I now install libjpeg-dev and compile IceWM, and all works OK.

But why before is Debian testing package works fine and now bad.

Changed default config or ...?

**Comment by gijsbers** [comment]
What is relevant is the output of `icewm --configured` to see what was configured.
Can you verify that just "ku_1.jpg" suffices?
And that '~' and $HOME/... also work?

**Comment by bedna-KU** [comment]
IceWM original from Debian testing (background image does not work):
icewm --configured
icewm configured options: ao fribidi gdkpixbuf i18n librsvg nls session shape wordexp xfreetype2 xinerama xrandr xrender

~ and $HOME does not work

Icewm compiled from git (background image OK):
icewm --configured
icewm configured options: fribidi i18n libjpeg libpng libxpm nls session shape wordexp xfreetype2 xinerama xrandr xrender

relative path, ~ and $HOME work

The bug is in the missing library "libjpg" but absolute path is working without library.
Absolute path no use icewmbg (I think)

**Comment by gijsbers** [comment]
Thank you for your testing. This was very helpful to gain confidence in the new solution.
