### ISSUE TITLE
.xsession-errors

### ISSUE THREAD

**Issue by frankzen** [bbidulock/icewm#321]
Noticed today a new bunch of errors in .xsession-errors.

08:20:51.577: IceWM: ERROR: point y = 0 is out of bounds
08:20:51.577: IceWM: ERROR: point y = 1 is out of bounds
08:20:51.577: IceWM: ERROR: point y = 2 is out of bounds
08:20:51.577: IceWM: ERROR: point y = 3 is out of bounds
08:20:51.577: IceWM: ERROR: point y = 4 is out of bounds
08:20:51.577: IceWM: ERROR: point y = 5 is out of bounds
08:20:51.577: IceWM: ERROR: point y = 6 is out of bounds
08:20:51.577: IceWM: ERROR: point y = 7 is out of bounds
08:20:51.577: IceWM: ERROR: point y = 8 is out of bounds
08:20:51.577: IceWM: ERROR: point y = 9 is out of bounds
08:20:51.577: IceWM: ERROR: point y = 10 is out of bounds
08:20:51.577: IceWM: ERROR: point y = 11 is out of bounds
08:20:51.577: IceWM: ERROR: point y = 12 is out of bounds
08:20:51.577: IceWM: ERROR: point y = 13 is out of bounds
08:20:51.577: IceWM: ERROR: point y = 14 is out of bounds
08:20:51.577: IceWM: ERROR: point y = 15 is out of bounds
08:20:51.577: IceWM: ERROR: point y = 16 is out of bounds
08:20:51.577: IceWM: ERROR: point y = 17 is out of bounds
08:20:51.577: IceWM: ERROR: point y = 18 is out of bounds
08:20:51.577: IceWM: ERROR: point y = 19 is out of bounds
08:20:51.577: IceWM: ERROR: point y = 20 is out of bounds
08:20:51.577: IceWM: ERROR: point y = 21 is out of bounds
08:20:51.577: IceWM: ERROR: point y = 22 is out of bounds
08:20:51.577: IceWM: ERROR: point y = 23 is out of bounds

Icewm seems to run fine with no obvious problems. What is causing these errors ??

**Comment by gijsbers** [comment]
Nothing to worry about @frankzen. The yximage module was never really finished. It could be helpful to know which theme you were using. If the messages are annoying you could `configure --enable-gdk-pixbuf` to get a more robust solution.

**Comment by frankzen** [comment]
I'll recompile using your suggestion. Don't remember the theme. I'll check when I'm back in IceWm.
Thanks

**Comment by bbidulock** [comment]
@frankzen please close this issue if it is no longer a problem.
