### ISSUE TITLE
Some keyboard shortcuts in preferences not working, Is it something wrong on my systems?

### ISSUE THREAD

**Issue by cheapy** [bbidulock/icewm#328]
I have antiX 17 and these are all keys setup in the default install.

Here are the results of testing all the keys mapped. I wonder if I need to be using a special keyboard somehow for my HP DV9000 series laptop (17″ with separate numeric keypad built in) and a Dell D620 14" laptop.  I also tested with a normal Logitech USB keyboard on both machines with the same results.

I see they are commented out in other distros.

from Preferences
does nothing - KeyWinArrangeN="Ctrl+Alt+KP_8"
does nothing - KeyWinArrangeNE="Ctrl+Alt+KP_9"
does nothing - KeyWinArrangeE="Ctrl+Alt+KP_6"
does nothing - KeyWinArrangeSE="Ctrl+Alt+KP_3"
does nothing - KeyWinArrangeS="Ctrl+Alt+KP_2"
does nothing - KeyWinArrangeSW="Ctrl+Alt+KP_1"
does nothing - KeyWinArrangeW="Ctrl+Alt+KP_4"
does nothing - KeyWinArrangeNW="Ctrl+Alt+KP_7"
does nothing - KeyWinArrangeC="Ctrl+Alt+KP_5"
doesn't move the window - KeySysWorkspacePrevTakeWin="Alt+Ctrl+Shift+Left"
doesn't move the window - KeySysWorkspaceNextTakeWin="Alt+Ctrl+Shift+Right"
doesn't move the window - KeySysWorkspaceLastTakeWin="Alt+Ctrl+Shift+Down"
doesn't move the window - KeySysWorkspace1TakeWin="Alt+Ctrl+Shift+1"
doesn't move the window - KeySysWorkspace2TakeWin="Alt+Ctrl+Shift+2"
probably doesn't work - KeySysWorkspace3TakeWin="Alt+Ctrl+Shift+3"
probably doesn't work - KeySysWorkspace4TakeWin="Alt+Ctrl+Shift+4"
does nothing - KeySysTileVertical="Alt+Shift+F2"
does nothing - KeySysTileHorizontal="Alt+Shift+F3"
closes window - KeySysCascade="Alt+Shift+F4"
doesn't seem to work -KeySysArrange="Alt+Shift+F5"
put window into resize mode - KeySysArrangeIcons="Alt+Shift+F8"
went to browser window - KeySysMinimizeAll="Alt+Shift+F9"
didn't work right - KeySysHideAll="Alt+Shift+F11"
put window into move window mode - KeySysUndoArrange="Alt+Shift+F7"

**Comment by gijsbers** [comment]
Thanks for reporting this! In a default setup most of these keys do work for me. Only the "Alt+Shift+FX" keys bring me to a Linux console terminal. But the Arrange and TakeWin do work at least. If you understand X11 key definitions a bit could you try with the "xev" program to see what you get? You could also define these keys in the preferences file to a different key combination which does work for you.

**Comment by cheapy** [comment]
There was a post today and from what I understood antiX has IceWM version 1.4.2 in the stable version that I am running.  Is it possible that the keys (or any of them) have been fixed since then?

https://www.antixforum.com/forums/topic/icewm-workspaces-move-window-to-workspace-to-and-launch-window-in-workspace/
 
From that post It looks its caused by the old version.

**Comment by gijsbers** [comment]
@cheapy I tried with versions 1.3.12, 1.4.2 and current. They all work fine for me.

**Comment by cheapy** [comment]
Yesterday I tried mapping the ones that are problems for me to other keys, and that fixed all of those, so it must be conflicts on the default keys or tmy keyboards causing it on those.  If I can, I'll test again on their next alpha release.

**Comment by rayluo** [comment]
@cheapy The issue seems still exist even in latest antiX 19, at least for the tiling hotkey `KeySysTileHorizontal` and `KeySysTileVertical`. But I found your workaround above helps.

FWIW, even after your workaround, it is still not perfect but that seems to be partially caused by Firefox. I'm trying to tile my several Firefox windows. As it turns out, it seems I can tile only those windows created by dragging a tab out of the very first Firefox window; that original Firefox window won't be tiled in any way. So confusing.

**Comment by cheapy** [comment]
Yes, there are definitely Problems tiling with Firefox.  I get the windows where and how I want them, and from there try to only maximize or restore.  Firefox takes over many keys, and since it is "on top of" icewm, I'm not sure there is a good solution other than to avoid using it, or avoid using keys it also assigns.  Do you have a list of those?  Maybe we could find the conflicts and try to come up with something different, especially if other browsers used those same keys as defaults.  We could try that on top of antiX, but it might not be as easy to get the defaults there changed unless we had the backing of others and few to none objections.

I had been meaning to setup horizontal tiling, but didn't try it till tonight.  I found that Alt+Ctrl+Down is not a good choice if looking for Firefox compatibility.

**Comment by rayluo** [comment]
> I'm not sure there is a good solution ... avoid using keys Firefox also assigns. Do you have a list of those?

I do not. I was just in a need to tile some 2 or 3 browser windows when I was doing some side-by-side purchase comparison. And it seems those function keys `F1`, `F2`, `F3`, etc. tend to be assigned by many apps, and `Alt` combination tend to trigger the menu (which I don't want), so I settle with `Ctrl+Shift+V` for Vertical tiling, and `Ctrl+Shift+H` for horizontal tiling.
