### ISSUE TITLE
Include HTML docs in the release tarballs

### ISSUE THREAD

**Issue by sfzhi** [bbidulock/icewm#33]
Would it be possible to include generated HTML documentation in the release tarballs? Building it requires several packages that are not useful for much of anything else. It is kind of a big deal if you building the whole system from sources - you don't want to waste time for things that you will likely never need again.

**Comment by bbidulock** [comment]
Html docs will be distributed with next release tarball.  Autoconf build tested and works.  I think that the cmake build will just warn if sgml2html is missing on the system and the docs will be installed anyway, but, not tested.

**Comment by Code7R** [comment]
The install code did not consider them unless generating was executed. It should be fixed now. I fail to see how they will be generated in the release procedure so I simply expect them in the doc folder. Please adjust the file in the last commit if that is not the case, line 27.
