### ISSUE TITLE
icewm 1.5.1: slightly more difficult to activate resize handles in upper corners

### ISSUE THREAD

**Issue by apocalyptech** [bbidulock/icewm#331]
After an upgrade to icewm 1.5.1 (from 1.4.2), it feels like the upper corner resize handles have become more difficult to actually activate.  Like the mouseover text for my "close" button remains mouseover'd (and the mouse cursor doesn't change to the resize handle) even when it would've switched over in previous versions.  I'd thought I was imagining it at first, but after a day of working with it, I'm pretty sure it's not just my imagination.  I ended up downgrading back to 1.4.2 and I felt the difference immediately.

I have the best luck with it when I come at the window from the outside (rather than the inside), or start on a flat edge and move up, but it still just feels tetchy.  This is perhaps more noticeable to me since I'm still using focus-follows-mouse and auto-raise, so it's caused an awful lot of unintentional raises of windows today.

I can't fully discount confirmation bias or something, since human brains are dumb, but it definitely feels *off* to me.  Let me know if I can provide any other info.

**Comment by gijsbers** [comment]
Could you test this? I also tried it with your cj theme.

**Comment by apocalyptech** [comment]
Aha, will do, thanks!  Though I'm on the road now and won't be back until Thurs, so don't expect any test results from me until late in the week.  :)

**Comment by gijsbers** [comment]
Any luck?

**Comment by apocalyptech** [comment]
Hello!  So I got back home from being on the road and then got super lazy with all my FOSS stuff, sorry!

Anyway, yep: current github (in `icewm-1-4-BRANCH`) feels great now!  Thanks a bunch!
