### ISSUE TITLE
Is it possiable using mouse button, like "Button8", in "keys" file?

### ISSUE THREAD

**Issue by Tetralet** [bbidulock/icewm#333]
Hi,

I'm using 'xbindkeys' to map the 'Button8' to 'scrot' to grab a screenshot of games.
But sometimes it didn't work.
The game often grab the mouse button events first, and never sent it to xbindkeys.
So I think that if icewm can handle the mouse button, It may work better.

Is it possiable using mouse button, like "Button8", in "keys" file?
Thanks!

**Comment by gijsbers** [comment]
IceWM supports buttons as Pointer_Button1, ... so maybe Pointer_Button8 works.
Let us know. Sofar I've only seen the first 5 buttons work, but it might just work.

**Comment by Tetralet** [comment]
I tried both Pointer_Button1/Pointer_Button8. They didn't work at all. Sorry...

**Comment by gijsbers** [comment]
I looked into the code now and your findings are right. The `keys` file is only for keys.
The only case where it does look for pointer buttons is in:

    # MouseWinMove="Alt+Pointer_Button1"
    # MouseWinSize="Alt+Pointer_Button3"
    # MouseWinRaise="Ctrl+Alt+Pointer_Button1"
    # MouseWinLower="Ctrl+Alt+Pointer_Button1"

**Comment by danfe** [comment]
Thanks for 1f6c4e2, it indeed allows me to bind some action on e.g. `Pointer_Button1` and it works as expected.  However, my mouse has these two extra buttons under the (right) thumb which I'd like to bind to something as well.  `xev(1)` reports them as buttons 8 and 9, however, when I add corresponding actions to my `keys` file, IceWM complains to `Unknown key name Pointer_Button8 in Pointer_Button8` in the debug log (ditto for `Pointer_Button9`).

I've grepped for `XK_Pointer_Button` in my X11 header files, and found something odd:
```shell
$ grep -R XK_Pointer_Button /usr/local/include/X11
/usr/local/include/X11/keysymdef.h:#define XK_Pointer_Button_Dflt           0xfee8
/usr/local/include/X11/keysymdef.h:#define XK_Pointer_Button1               0xfee9
/usr/local/include/X11/keysymdef.h:#define XK_Pointer_Button2               0xfeea
/usr/local/include/X11/keysymdef.h:#define XK_Pointer_Button3               0xfeeb
/usr/local/include/X11/keysymdef.h:#define XK_Pointer_Button4               0xfeec
/usr/local/include/X11/keysymdef.h:#define XK_Pointer_Button5               0xfeed
```
Could it be the cause?  How to handle these higher mouse button numbers properly?

**Comment by gijsbers** [comment]
Show some xev output which highlights these differences in detail between various buttons.
You could examine the xev source code to see how it handles it?

**Comment by danfe** [comment]
> Show some xev output which highlights these differences in detail between various buttons.

For `xev(1)` it seems there is no difference about the mouse buttons, it does not report any key symbol, just the number:
```
ButtonPress event, serial 38, synthetic NO, window 0x2200001,
    root 0x137, subw 0x2200002, time 39272381, (46,57), root:(1195,81),
    state 0x0, button 1, same_screen YES

ButtonPress event, serial 38, synthetic NO, window 0x2200001,
    root 0x137, subw 0x2200002, time 39277399, (54,30), root:(1203,54),
    state 0x0, button 8, same_screen YES

ButtonPress event, serial 38, synthetic NO, window 0x2200001,
    root 0x137, subw 0x2200002, time 39279394, (51,19), root:(1200,43),
    state 0x0, button 9, same_screen YES
```
It does report those for keys:
```
KeyPress event, serial 38, synthetic NO, window 0x2200001,
    root 0x137, subw 0x0, time 39616097, (120,99), root:(1269,123),
    state 0x0, keycode 67 (keysym 0xffbe, F1), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False
```
> You could examine the xev source code to see how it handles it?

It only performs keycode lookup for keyboard presses, not mouse ones, per what I see in the `do_KeyPress()` and `do_ButtonPress()` functions.

**Comment by gijsbers** [comment]
Are we the first ones in the universe to consider this situation?

Try the following code at line 106 of yconfig.cc:
```
    if (*key == NoSymbol && !strncmp(arg, "Pointer_Button", 14)) {
        int button = 0;
        if (sscanf(arg + 14, "%d", &button) == 1 && button > 0) {
            *key = button + XK_Pointer_Button1 - 1;
        }
    }
```
Before the line which reads `    if (*key == NoSymbol && *arg) {`.

**Comment by danfe** [comment]
> Try the following code at line 106 of yconfig.cc:

Weird: it works, but only for buttons 1 and 8, not 9.  Here's my `keys` file:
```
key "Alt+Ctrl+t" xterm
key "Alt+Ctrl+k" xmessage OK
key "Pointer_Button1" xmessage 1111
key "Pointer_Button8" xmessage 8888
key "Pointer_Button9" xmessage 9999
```

**Comment by danfe** [comment]
You actually don't need to use the rat with physical 8th and 9th buttons, I could reproduce it with `xdotool(1)` while logged in via SSH (just to avoid dealing with nuisances of moving the mouse away from the `xterm` window or playing with `xbindkeys`) from the nearby desktop computer so I could trigger mouse events on the IceWM-running laptop independent of the pointer position:
```shell
$ DISPLAY=:0 xdotool click 8
$ DISPLAY=:0 xdotool click 9
```
First command works, second does not.

**Comment by gijsbers** [comment]
Same here. It works for all button numbers from 1 to 8, but not for 9.
