### ISSUE TITLE
Rox-file did not get focus.

### ISSUE THREAD

**Issue by minhsien0330** [bbidulock/icewm#336]
Hi~ 
After updated to 1.4.3, I found icewm won't give focus on rox-file sometimes.
Icewm 1.3.7 does not have this issue. I updated to 1.5.2, and this issue is still there.

The replicating steps are:
(1) Please install rox-filer and leafpad for testing this issue.
(2)Add following lines to ~/.icewm/keys:
key "F1"	rox-filer
key "F2"	leafpad
(3) Restart your icewm (version 1.4.3 or 1.5.2).
(4) Press "F2" to open the editor Leafpad, and type some words in it.
(5) Press "F1" to open rox-file, then you can see rox-filer was there, but rox-filer does not be focused, the focus is still on Leafpad.

Thank you~

**Comment by minhsien0330** [comment]
Sorry, I got a workaround:
Edit  ~/.icewm/keys, and modify the line about rox-filer as following:
key "F1" rox -n 
Then this issue never happened.

**Comment by gijsbers** [comment]
1.3.7 is from 2010-10-31. It is not clear from your description if its behavior is more correct than the 1.4.3 behavior for rox. Since 1.3.7 a lot of effort went into standards compliance.
