### ISSUE TITLE
Feature request: Sort windows in task bar by virtual desktop

### ISSUE THREAD

**Issue by Polynomial-C** [bbidulock/icewm#337]
Hi,

I'd like to request a new feature for icewm which I am missing since I started using icewm back in 1.2.x days.
I usually have six virtual desktops configured in icewm and I find it quite hard to keep track where the windows are located in the task bar once I have opened about a dozen or more windows. That's because no matter on which virtual desktop the window appears, it will always get added to the task bar on the most right side. So yeah, in terms of "history" I can now find out wich window I opened before or after which other window, but when you have lots of windows spread over all your six virtual desktops, it becomes really hard to find the right window in the task bar.
That's why I'd like to request an option to sort window entries in the task bar by virtual desktop.

Kind regards

**Comment by gijsbers** [comment]
Sounds reasonable. But did you try these:

1. use the `order` option in the `winoptions` file? See icewm-winoptions(5).
2. simply drag a new task button to where you want it to be.
3. use `icewmhint` to set the order when you launch the app. See icewmhint(1).
4. use the Alt+Tab quick switch which does sort on workspace. See icewm(1).
5. use the `KeyTaskBarMoveNext` and `KeyTaskBarMovePrev` keys. See icewm(1).
