### ISSUE TITLE
icewm 1.5.3 error: use of overloaded operator '[]' is ambiguous

### ISSUE THREAD

**Issue by AngryPenguinPL** [bbidulock/icewm#340]
Hi.

When build icewm 1.5.3 I see issue on x86 and armv7:

> /builddir/build/BUILD/icewm-1.5.3/src/icesh.cc:1358:55: error: use of overloaded operator '[]' is ambiguous (with operand types 'YWindowTree' and 'int')
> (windowList.count() == 1 && windowList[0] == root))

Full log: http://file-store.openmandriva.org/api/v1/file_stores/92f5a605b73956c8576010ea389c632ec2f25ac9.log?show=true

This issue does not occur on x64, znver1 and aarch64.
Previous 1.5.2 build fine.

**Comment by gijsbers** [comment]
Why does it work on one, but not the other?
Are there differences in compilers or command line invocations?
What language standard do they use?

**Comment by AngryPenguinPL** [comment]
Hi.
We compile all arch with Clang 7.0.1 and now also with Clang 8.0.

As temporary solution I switch i686 and ARMv7 to GCC and this fix build process.

This is spec which we use: https://github.com/OpenMandrivaAssociation/icewm/blob/master/icewm.spec

**Comment by gijsbers** [comment]
This one line change ought to fix the clang build for you:

    sed -i 's|windowList\[0\]|windowList[0U]|'  src/icesh.cc

I don't understand why the spec file requires `libpcap-devel` and `xlockmore`.
They seem redundant.

Does your compiled icewm give you this output too?

    $ icewm --configured
    icewm configured options: alsa ao fdomenus fribidi i18n libjpeg libpng libxpm nls session shape wordexp xfreetype2 xinerama xrandr xrender

**Comment by AngryPenguinPL** [comment]
Sorry for late reply. 
Yes this fix my issue.

Thanks.

pcap and xlockmore removed from br and deps.

BTW.
icewm --configured
`alsa ao fribidi i18n libjpeg libpng libxpm nls oss session shape wordexp xfreetype2 xinerama xrandr xrender`
