### ISSUE TITLE
configure.ac undefined macro: AC_DISABLE_STATIC

### ISSUE THREAD

**Issue by 5x3** [bbidulock/icewm#342]
```
~/icewm$ ./autogen.sh
...
autoreconf: running: /usr/bin/autoconf --force
configure.ac:69: error: possibly undefined macro: AC_DISABLE_STATIC
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:74: error: possibly undefined macro: AC_PROG_LIBTOOL
autoreconf: /usr/bin/autoconf failed with exit status: 1

```

**Comment by bbidulock** [comment]
What versions of autoconf tool chain are you attempting to run?

**Comment by 5x3** [comment]
im just a user attempting to run icewm with official instruction from github.
i use autogen.sh as described in it.
the later i got reported error.
autoconf --version
autoconf (GNU Autoconf) 2.69
thanks.

**Comment by gijsbers** [comment]
Looks like required dependencies are missing.
install autoconf automake libtool pkg-config m4
The website explains how to use the [os-depends.sh](https://ice-wm.org/scripts/os-depends.sh) script.

**Comment by bbidulock** [comment]
I don't like closing issues on users, I prefer they close them themselves.  @5x3 please close this issue if it is no longer a problem.

**Comment by tulilirockz** [comment]
Just a note since I _always_ show up here from google results from time to time. The package that you actually want is `libtool` for this specific macro (`AC_DISABLE_STATIC`)
