### ISSUE TITLE
Is there an example of using icewmbg displaying multiple backgrounds?

### ISSUE THREAD

**Issue by cheapy** [bbidulock/icewm#346]
Thanks...  I love IceWM.  It's so nice to see new life in the project!

**Comment by gijsbers** [comment]
What you do is create a directory like `/path/to/wallpapers/directory` which contains your desktop background wallpapers or symbolic links to them. The files can be sorted on name or a prefix number like 00-fileA, 01-fileB, etc. Then you create a `prefoverride` in your icewm directory with contents something like this:

```
DesktopBackgroundCenter=0 
DesktopBackgroundScaled=1 
DesktopBackgroundColor=black
DesktopBackgroundImage=/path/to/wallpapers/directory
ShuffleBackgroundImages=0
SupportSemitransparency=1 
DesktopTransparencyColor="rgb:32/3d/4c"
DesktopTransparencyImage=""
DesktopBackgroundMultihead=0 
CycleBackgroundsPeriod=3600
```

Please study the [`icewmbg(1)`](https://ice-wm.org/man/icewmbg) man page for details.

**Comment by cheapy** [comment]
Thanks, I got it working with prefoverride.
