### ISSUE TITLE
No _NET_CLIENT_LIST_STACKING update event when exiting fullscreen

### ISSUE THREAD

**Issue by tsipinakis** [bbidulock/icewm#347]
This is a forward of dunst-project/dunst#613.

We're listening on any PropertyNotify and Focus events on the root window in order to detect changes on the fullscreen status of the currently focused window.

While troubleshooting the linked issue I discovered that my own WM (i3) sends PropertyNotify on `_NET_CLIENT_LIST_STACKING` both when entering but also while exiting fullscreen while according to my tests IceWM only sends that event when entering fullscreen mode.

I am not sure if this is actually a bug on your side but the inconsistent behaviour of only notifying when entering fullscreen leads me to believe that it is (unless there is some other reasoning behind this that I'm missing?)

**Comment by gijsbers** [comment]
Thanks a lot for reporting! 
Does EWMH require updating _NET_CLIENT_LIST_STACKING even though its values hasn't changed?
If what dunst is trying to is to monitor fullscreen status, isn't the most reliable way to monitor the window property _NET_WM_STATE for _NET_WM_STATE_FULLSCREEN?

**Comment by tsipinakis** [comment]
> Does EWMH require updating _NET_CLIENT_LIST_STACKING even though its values hasn't changed?

I've now tested i3, xfce and gnome and all of them update this hint when entering or exiting fullscreen even when the values are identical. I can't say much more than that however as I haven't found anything in the spec that could support this.

>  If what dunst is trying to is to monitor fullscreen status, isn't the most reliable way to monitor the window property _NET_WM_STATE for _NET_WM_STATE_FULLSCREEN?

Indeed that's the best way, and it's what we're checking internally after receiving the event. However, we want to monitor whether the currently focused window is fullscreened, not dunst itself. So it was a choice between spamming XSelectInput everytime the active window changes to monitor _NET_WM_STATE, or latching on an event that appears to be sent by most WMs on status change. We chose the latter (perhaps wrongfully).

**Comment by gijsbers** [comment]
Testing shows me that IceWM actually supports having multiple windows in fullscreen mode.
They don't even have to be in layer Fullscreen (=14), but can be in layer Normal (=4) and still be in fullscreen mode. So even if one window returns from fullscreen there can still be another fully covering the screen. IceWM guievents isn't even reporting on fullscreen mode. I think it's best to code on the EWMH spec, otherwise all of the 469 window managers would need to be examined to be sure: https://www.gilesorr.com/wm/table.html

**Comment by tsipinakis** [comment]
Obviously, as I said we are checking for the fullscreen hint but the problem is finding a proper event to latch on to in order to re-check the state.

Anyway, I thought I'd report this inconsistency since I couldn't find anything about this hint related to fullscreen (I'm still not sure why other WMs send out an event even if it didn't change).

Feel free to close it.

**Comment by gijsbers** [comment]
It's good point you raised. Why do WMs create unnecessary events? It wakes up idle processes for nothing. Not desirable for laptop users.
