### ISSUE TITLE
Disabling Keyboard shortcut

### ISSUE THREAD

**Issue by ghost** [bbidulock/icewm#348]
Ctrl+Alt+Space is conflicting with the same shortcut in Emacs. When i disable it in ~/.icewm/keys with
    key "Ctrl+Alt+Space"
log out in login again, it seems that the keyboard shortcut is still not free. The default behavior in Emacs is still not back with these keys. What is the point?

**Comment by gijsbers** [comment]
You need to redefine KeySysAddressBar="" in your preferences file, not keys file.

**Comment by ghost** [comment]
> You need to redefine KeySysAddressBar="" in your preferences file, not keys file.

I added a preferences file to ~/.icewm with KeySysAddressBar="", also changed the same entry in /use/share/icewm/preferences. Nothing happens, the problem still remains. The key combination is still not freed for other applications

**Comment by gijsbers** [comment]
But you still have it defined in your `keys` file, right?
Edit it so that you get this output:

    $ icewm --postpreferences | grep KeySysAddressBar
    KeySysAddressBar=""

**Comment by ghost** [comment]
> But you still have it defined in your `keys` file, right?
> Edit it so that you get this output:
> 
> ```
> $ icewm --postpreferences | grep KeySysAddressBar
> KeySysAddressBar=""
> ```

Great! That solved the problem! Many thanks!
