### ISSUE TITLE
xmessage displayed in incorrect position or not at all

### ISSUE THREAD

**Issue by kelsoo** [bbidulock/icewm#349]
I use a small hot corner launcher application called fittstool 
https://github.com/jeanCarloMachado/fittstool

It uses xmessage to display hints, without  follow mouse enabled so it should place the xmessage in the centre of the screen but dosen't.  Xmessage top and bottom also fails to display though the launcer works fine

from my fittstoolrc:
 Enter=xmessage -buttons ,  "North-West: Files: LMB=Rox MMB=PathFinder RMB=Spacefm Wheel=Skippy-xd"
Leave=killall xmessage

These configs work as expected in openbox so I'm lead to believe either openbox ignores something or interprets them differently?

I have these setting in my preferences
 EdgeSwitch=0 
HorizontalEdgeSwitch=0
VerticalEdgeSwitch=0
ContinuousEdgeSwitch=0

A screen capture to explain 

http://monimail.org/kelsoo/dragora-icewm-xmessage-bug.webm

Thanks

**Comment by gijsbers** [comment]
Nice bug. Did you try the xmessage option `-center`? Or do you have some X resources set?

**Comment by kelsoo** [comment]
Hi I have tried  the -centre option but it made no difference. I recall removing -nearmouse  on my openbox machine and it just went to the centre. Both machines have the same configs. 

 I have another machine with a clean install and the default upstream Xresources file without a Xmessage setting and it behaves identically except the message does work at the top of the screen but not at the bottom. Thinking about it that was how it was until a few months ago on my main machine. Just the bottom did not work then one day the top stopped. I wondered if it was something to do with tint2 having 

tint2.doNotCover: 1

in winoptions 

I also have

xmessage.dTitleBar: 0
xmessage.doNotCove: 1
xmessage.ignoreTaskBar: 1
xmessage.ignoreNoFocusHint: 1
xmessage.dBorder: 0

But removing them and testing made no difference

Anyway.  Here are my xmessage settings from .Xresources in case there is something amiss or can be added.
 
 #  X M E S S A G E - Setting
 Xmessage.form.okay.shapeStyle:         rectangle
 Xmessage.form.okay.background:         red
 Xmessage.form.okay.foreground:         yellow
 Xmessage*message*background:          #3c3c3c
 Xmessage*buttons:                       OK
 Xmessage*defaultButton:                 OK
 Xmessage*Background:                  #3c3c3c
 Xmessage*Foreground:                  #D3D3D3
 Xmessage.Scrollbar:                   WhenNeeded
 Xmessage.form.message.Scroll:          WhenNeeded
 Xmessage*Font:                         -*-FreeSans-*-*-*-10-*-*-*-*-*-*-*
 Xmessage*borderWidth:                  0
 Xmessage*Text.borderWidth:             0
 Xmessage*Command.shapeStyle:           rectangle
 Xmessage*Text.?.cursorColor:           #D3D3D3

Thanks for looking any ideas welcome

**Comment by gijsbers** [comment]
I tried fittstool, with what you give from your rc, but it doesn't do anything.
What icewm version do you use?

**Comment by kelsoo** [comment]
I have icewm 1.37 on one machine and icewm 1.42 on another.
all my configs for icewm are here.

https://we.riseup.net/assets/556141/dragora-ice-20190601-dot-icewm.tar.bz2

This is my fittstoolrc  ~.config/fittstool/fittstoolrc
############ fittstoolrc ################
#files#
[TopLeft]
LeftButton=rox 
MiddleButton=PathFinder
RightButton=spacefm
WheelUp=skippy-xd
WheelDown=skippy-xd
Enter=xmessage  -buttons ,  "North-West: Files: LMB=Rox MMB=PathFinder RMB=Spacefm Wheel=Skippy-xd"
Leave=killall xmessage

#Utils#
[TopCenter] 
LeftButton=lilyterm
MiddleButton=btrxtrlock-wrapper
RightButton=killall fittstool; fittstool
WheelUp=spacefm -f
WheelDown=/usr/lib/Thunar/ThunarBulkRename
Enter=xmessage -buttons , "North: Utils: LMB=Term MMB=Lock Screen RMB=Fittstool Wheelup=Search Wheeldown=Rename"
Leave=killall xmessage

##############################
#windows#
[TopRight]
LeftButton=killall xmessage; xdotool key shift+alt+F2           
MiddleButton=killall xmessage; xdotool key  shift+alt+F4          
RightButton=killall xmessage; xdotool key  shift+alt+F3          
WheelUp=killall xmessage; xdotool key alt+F10                             
WheelDown=killall xmessage; xdotool key alt+F10                         
Enter=xmessage -buttons ,  "North-east: Windows: LMB=Tile-V MMB=Casscade RMB=Tile-H Wheel=Maximize"
Leave=killall xmessage

#########################
#media#
[Right]
LeftButton=mpv                         
MiddleButton=asunder                     
RightButton=simpleburn
Enter=xmessage -buttons , "East: Media: LMB=Mplayer MMB=Asunder RMB=Burn"
Leave=killall xmessage  


###########################
#chat#
[BottomRight]
LeftButton=mumble                           
MiddleButton=pidgen                      
RightButton=utox  
Enter=xmessage -buttons , "South-East: Chat: LMB=Mumble MMB=Wicd RMB=Utox"
Leave=killall xmessage            

############################
#internet#
[BottomCenter]
LeftButton=seamonkey
MiddleButton=transmission-gtk
RightButton=claws-mail
WheelUp=gftp                              
WheelDown=lilyterm -T gopher -e gopher 
Enter=xmessage -buttons , "South: Internet: LMB=Browser MMB=Torrents RMB=Mail Wheelup=FTP Wheeldown=Gopher"
Leave=killall xmessage
#########################
#editing#
[BottomLeft]
LeftButton=adie
MiddleButton=geany
RightButton=lowriter
Enter=xmessage -buttons , "South-West: Editing: LMB=Leafpad MMB=Geany RMB=Office"
Leave=killall xmessage

##########################
#sound#
[Left]
LeftButton=xterm -C alsamixer
MiddleButton=amixer -q sset Master toggle 
RightButton=lilyterm -T Cplay -s -e cplay ~/music
WheelUp=amixer -q sset Master 2+
WheelDown=amixer -q sset Master 2-
Enter=xmessage -buttons , "West: Sound: LMB=Mixer MMB=Toggle sound RMB=Cplay Wheel=Volume"
Leave=killall xmessage
###########################


#Available positions: TopLeft, TopCenter, TopRight,  Right, BottomRight,  BottomCenter, BottomLeft, Left, 
#Available events: LeftButton, RightButton, MiddleButton, WheelUp, WheelDown, WheelUpOnce, WheelDownOnce, Enter, Leave

**Comment by kelsoo** [comment]
The only time  fittstool didn't run for me was when I added my fittstoolrc before building it. It seems to need to create the file before  if could read my already created one.

Another pointer was that on openbox the bug exists but only on the top left corner when there are windows open. all the other trigger points worked as expected. At that time I used the xmessage  -nearmouse  option.

**Comment by kelsoo** [comment]
Well I've found a workaround. Rather than a fix.
That said I will confess to a PEBKAC 

Oscar Wilde described America and Britain as "two great nations divided by the same language."
I now know the difference between the words centre and center!

xmessage now will go to the CENTER of the screen but still doesn't show at top and bottom

Anyway, I replaced xmessage with yad and after a bit of fiddling the fittstool notification are working almost as expected. Only if I use the -mouse option (follow mouse) is the message displaced by the position of other windows as it was with xmessage.

Cheers

**Comment by kelsoo** [comment]
Fixed: I placed this in winoptions and the notify message no longer gets moved by other windows. 
yad-fittstool.layer: OnTop

Thanks for your efforts

**Comment by gijsbers** [comment]
Okay! Well, the good news is that, despite your best efforts, sofar no bug has been proven.

What may be the case is that fittstool doesn't check if its windows get obscured by observing for Visibility events. It should have raised its windows, I think.

**Comment by kelsoo** [comment]
I do apologise for wasting your time. I now also think the issue lies elsewhere and not in icewm. Once I realised my centre/center error I went back to re-test xmessage. I also set xmessage.layer: OnTop in winoptions. This fixed the being displaced by other windows. But unfortunately xmessage was still not displayed at the top or bottom of the screen.

I then checked on my openbox machine. First I checked the ontop flag was set in openbox xml.rc . It was. That explained why there was no issue with xmessage being displaced by other windows in openbox. Then I added the correct -center flag to  all the xmessage commands in fittstool. Low and behold the TopCenter xmessage no longer showed in openbox! removing the -center flag just on TopCenter it displayed incorrectly in the center of the screen even though as I understand it, it should default to -nearmouse. This explains why it's been working for the past 2 years as I wanted but without the correct flag.

The fact that switching from xmessage to yad cured the issue lead me to believe the issue was in xmessage.  I was curious so started removing xmessage flags in fittstool running  icewm... and BOOM it worked. Displaying on all edges of the screen. 
It appears that having the  -buttons flag empty at top or bottom of the screen stops it displaying. In fact the center and -nearmouse flags work at the top of the screen but not at the bottom.  There I needed to remove all flags for it to display and it displayed at the top left which I take it is the fall back default .  This doesn't explain why the xmessage  -center and -nearmouse flags work on openbox at BottomCenter though and not icewm. I'm past worrying as yad works without issue and I'm really pleased with my icewm setup. I just thought it wise to post it here just in case it helps someone else.

**Comment by gijsbers** [comment]
We learned from this. Since you are an expert v1.4.2 user, you could help by testing if [1.5.5](https://github.com/ice-wm/icewm/releases/latest) is at least as good in all respects.

**Comment by kelsoo** [comment]
We will test 1.5.5 as we want icewm as the default in Dragora 3. 

The bug has been found thanks to "Frusen"

in fittstool.c 
line 61
char commands[9][100];  

changing it to 

char commands[9][200];  

fixes it. It seem that the original dev never envisaged someone like me adding more than 100 characters to the command :-)

**Comment by gijsbers** [comment]
The same argument applies to 200! Better use ARG_MAX or _POSIX_ARG_MAX.
fittstool still uses `strcpy`!
