### ISSUE TITLE
Missing preferences file with cmake build

### ISSUE THREAD

**Issue by rezso** [bbidulock/icewm#35]
If I build the source with cmake, the preferences file is missing: not generated and installed.

**Comment by Code7R** [comment]
Yeah, I will care about it.

**Comment by Code7R** [comment]
Added in git, will be installed among other docs.

**Comment by rezso** [comment]
Unfortunately, not works for me. The preferences file not generated. Don't ask, why, I don't know...

**Comment by Code7R** [comment]
The last commit above was not sufficient, I fixed it in a later commit.
