### ISSUE TITLE
Marking window hidden 

### ISSUE THREAD

**Issue by dlawle** [bbidulock/icewm#352]
Is there a function that will mark a window as "hidden" from the Alt+Tab function? I've attempted a few parameters from winoptions and preferences, but I can't seem to find the correct combo, or it's not working properly. I would essentially like to disable a specific window (ID from xprop?) from displaying on the quickswitch menu.

**Comment by gijsbers** [comment]
You have `ignoreQuickSwitch` in icewm-winoptions(5). You either need a unique `WM_CLASS` or set the `WM_WINDOW_ROLE` property on the window. This could be done using `xprop`. Another option is to use `icewmhint`.

**Comment by dlawle** [comment]
Thanks for the heads up. Both icewmhint and supplying the value in winoptions are failing however. I know the WM_CLASS portions are correct because they're also being used to hide window decorations: 

`
Xephyr.Xephyr.dTitleBar: 0

Xephyr.Xephyr.dBorder: 0

Xephyr.Xephyr.ignoreQuickSwitch: 1
`

Doesn't appear to be working/make a difference. Currently running version 1.3.12

**Comment by gijsbers** [comment]
Those settings do work fine for me in 1.5.5. Only if Xephyr has focus then it does show up in the quick switch, but not if it hasn't. Also tested with two Xephyrs. Works as advertised.

**Comment by dlawle** [comment]
@gijsbers mildly weird request, but can you send me a screen shot of what your Alt+Tab menu looks like? I'm beginning to wonder if X11 is handling the Alt+Tab and not icewm

**Comment by gijsbers** [comment]
Here is one. The last one. https://ice-wm.org/screenshots/
Last year the Alt+Tab quick switch was rewritten. So what you have in 1.3.12 doesn't relate.
Why don't you use 1.5.5?

**Comment by dlawle** [comment]
Thanks for the heads up, that's probably gonna be the issue. We're using 1.3.12 due to repo limitations, but I think we may be upgrading with our next security update. I'm going to test this in an isolated environment and let you know! Thanks for the help!

**Comment by dlawle** [comment]
@gijsbers Do you know when this feature was added in? Looks like 1.5.5 requires glibc 2.6+, and we're currently locked into 2.2

**Comment by dlawle** [comment]
Wanted to mark this issue as closed. I was able to get the configuration working in 1.3.12. It turns out the configuration file was expecting an order that I was not not following (capital > alphabetical, lower-case > alphabetical). 

Closing this issue! Thanks for all the help!
