### ISSUE TITLE
icewmhint bugs

### ISSUE THREAD

**Issue by arsonoff** [bbidulock/icewm#353]
1) The application started with 'ignoreQuickSwitch 1', once is visible in QuickSwitch 
    ```
    icewmhint xclock ignoreQuickSwitch 1 && xclock
    ```
	Alt+Tab - I see xclock, I select xclock
	Alt+Tab - I see xclock, I select other application
	Alt+Tab - OK, I do not see xclock

2) properties the established icewmhint are reset
	 ```
	 icewmhint Xephyr dBorder 0 \
	           Xephyr fMove 0 \
	           Xephyr tray Exclusive \
	           Xephyr ignoreQuickSwitch 1 \
	           Xephyr allWorkspaces 1 && Xephyr :1 &
	 DISPLAY=:1 xterm
	 ```
	 I close xterm on the display :1 (exit or Ctrl+D)
	 
	 Properties 'dBorder 0', 'fMove 0', 'ignoreQuickSwitch 1' are reset.
	 The Xephyr window has border, the window it is possible to move and switch on Alt+Tab.

**Comment by arsonoff** [comment]
> 2. properties the established icewmhint are reset

It is possible to reset properties just having restarted the IceWM

**Comment by gijsbers** [comment]
It is indeed possible to reset icewmhint properties by restarting IceWM. This is as specified. Please note that icewmhint properties are one-time-only properties for startup purposes. If you want them permanent then you need to specify them in https://ice-wm.org/man/icewm-winoptions

**Comment by arsonoff** [comment]
> Please note that icewmhint properties are one-time-only properties for startup purposes.

But I do not restart the application, I restart only icewm. The existing window loses the properties, and not all but only the part. 

> If you want them permanent then you need to specify them in https://ice-wm.org/man/icewm-winoptions

I and made. Created for each configuration the symbolic link with the unique name and registered in winoptions. That is everyone when I will want to start the window with non-standard
properties I shall edit winoptions and restart icewm? I thought for this purpose icewmhint is intended.

> 1. The application started with 'ignoreQuickSwitch 1', once is visible in QuickSwitch

I seem understood, the window is present at quickswitch anyway if it in focus.

**Comment by gijsbers** [comment]
Some (or most?) icewmhint options are lost on icewm restart. I added `icesh winoptions` to avoid restart.

**Comment by gijsbers** [comment]
So the title of this issue is misleading.

**Comment by arsonoff** [comment]
> So the title of this issue is misleading.

Yes I agree. The first paragraph does not depend on icewmhint.
Just when using this command it is most noticeable. As after its accomplishment the window receives focus.
What to make? Create separate issue?

Command 'icesh winoptions' has no effect.

**Comment by arsonoff** [comment]
> 1

Understood. Confused me that xvkb works "correctly", and other windows did not. But xvkbd simply does not receive focus.
> 2

I solved my problem (through winoption and restart).
The fact that the part of options is reset in value by default, and another remains without changes, probably and shall be.
