### ISSUE TITLE
The order of windows is broken

### ISSUE THREAD

**Issue by arsonoff** [bbidulock/icewm#355]
I start geany (or LO, or gimp). Maximize.
I start three xterm (or urxvt). 
Now, if to click Alt-Tab focus will be on other xterm, if to close one xterm focus will be on other xterm,
BUT if to Minimize xterm (Alt+F9), then focus will pass to geany.
	
If geany not Maximize, then it occurs not always.
If instead of three xterm to start xterm and urxvt, then already at start of urxvt xterm will disappear under geany.

**Comment by gijsbers** [comment]
Could you give the output of:

    icewm --postpreferences | grep -e Focus -e Place

**Comment by arsonoff** [comment]
```
ClickToFocus=1
FocusOnAppRaise=1
RequestFocusOnAppRaise=1
RaiseOnFocus=1
FocusOnClickClient=1
FocusChangesWorkspace=0
FocusCurrentWorkspace=1
FocusOnMap=1
FocusOnMapTransient=0
FocusOnMapTransientActive=1
MiniIconsPlaceHorizontal=0
StrongPointerFocus=0
ManualPlacement=0
SmartPlacement=1
DelayPointerFocus=1
ShowFocusModeMenu=1
PointerFocusDelay=200
FocusRequestFlashTime=0
FocusRequestFlashInterval=250
IceWM: A window manager is already running, use --replace to replace it
```

I also checked behavior of windows with the clean profile, most too.
