### ISSUE TITLE
Dock-window cannot be minimized click on the taskbar

### ISSUE THREAD

**Issue by arsonoff** [bbidulock/icewm#357]
The normal window is possible for Minimize/UnMinimize clicking on the taskbar (or tray),
The Dock-window is possible only UnMinimize.

**Comment by gijsbers** [comment]
Cannot reproduce this. Works fine for me.

**Comment by arsonoff** [comment]
https://i.postimg.cc/ZRFQPBz4/screencast.gif

**Comment by gijsbers** [comment]
Does it help if you also press the Control key?

**Comment by arsonoff** [comment]
Works with Control key

**Comment by gijsbers** [comment]
So if it works with Control key then that means that some other application in layer Dock is higher. This could be the taskbar, for instance. Could you check the _WIN_LAYER property? It should be equal to 8.

**Comment by arsonoff** [comment]
In the configuration I have several dock-windows (all '_WIN_LAYER(CARDINAL) = 8').
But I also checked in the configuration by default (delete ~/.icewm, ~/.Xresources, /etc/xorg.conf, in .xinitrc only 'exec icewm-session') with one dock-window (' _WIN_LAYER(CARDINAL) = 8').
Result same.

The only way which I found, it to change focus type to 'explicit focus'.
But it is the unusual mode of work with windows.

**Comment by gijsbers** [comment]
You could monitor `xprop -root -spy _NET_CLIENT_LIST_STACKING`.
If your window is not on top in its layer, that is, if it can still raise, then minimization by clicking on the task button won't work, unless you have the Control key pressed.

**Comment by arsonoff** [comment]
Only one xterm window:
```
$ echo $WINDOWID
10485773
$ xprop -root -spy _NET_CLIENT_LIST_STACKING
_NET_CLIENT_LIST_STACKING(WINDOW): window id # 0xa0000d
_NET_CLIENT_LIST_STACKING(WINDOW): window id # 0xa0000d
_NET_CLIENT_LIST_STACKING(WINDOW): window id # 0xa0000d
...
```
If the 'Normal' window, then just switches (xprop is silent).
If the 'Dock' window, then does not switch, but the new line appears:
```
_NET_CLIENT_LIST_STACKING(WINDOW): window id # 0xa0000d
```

**Comment by gijsbers** [comment]
But you didn't examine the layer of the taskbar. My guess is that you have TaskBarKeepBelow=0. That causes the taskbar to have layer 8 and hence there is an extra window, which is not show in _NET_CLIENT_LIST_STACKING. Then you just have to use the Control key to minimize. 
That is not a problem. There is no issue to work on.

**Comment by arsonoff** [comment]
> Cannot reproduce this. Works fine for me.
> My guess is that you have TaskBarKeepBelow=0

But this value by default?!
With TaskBarKeepBelow=1 Maximize-window begin to climb on taskbar, normal to block it.
Yes any quantity of dock-windows so works. But when taskbar from below, this option at all not the worker.
> That is not a problem. There is no issue to work on.

From the point of view of the user it looks as the bug, some windows do not react to standard actions.
Click - one hand. Ctrl+Click - two hands (also the keyboard is still necessary).


Fix:
It is necessary to use the bypass way.
Instead of placement of the window in the tray to place the button on toolbar with command like 
```
prog xvkbd input-keyboard.png icesh -class xvkbd toggleState Minimized
```
It works ;)
