### ISSUE TITLE
What distros have good examples of current IceWM implementation?

### ISSUE THREAD

**Issue by cheapy** [bbidulock/icewm#359]
I tried to word that realizing that it is a subjective question, but I'm sure there are probably some shining star IceWM implementations where the new capabilities are being used that I can test out and look to for good examples.

TIA :)

**Comment by gijsbers** [comment]
OpenMandriva, Mageia Cauldron, OpenSuSE Tumbleweed, Debian Sid.
Manjaro, PCLinuxOS.

**Comment by cheapy** [comment]
Thanks for the reply, I have now installed and tried all but Debian Sid.  Mageia Cauldron was my favorite of your list in terms of IceWM setup.  I'm working on reconfiguring AntiX19, which is in beta, and includes 1.5.5, and I'm trying to see if I can help make it ultra user friendly.

**Comment by gijsbers** [comment]
@cheapy 19b2 looks great!, but it still uses the stale website www.icewm.org.

**Comment by cheapy** [comment]
I will pass that on to get it corrected.
I will watch for a fresh review, hopefully of antiX 19, and am hoping to see my keys file in the new release.   It's not in 19b2 yet.
I will submit the following:
menu "IceWM" /usr/share/icons/papirus-antix/48x48/places/folder.png menu-icewm-papirus {
    prog "IceWM FAQ" - x-www-browser https://ice-wm.org/FAQ/
    prog "IceWM Manual" - x-www-browser https://ice-wm.org/manual/
    separator
    prog "OSNews Cool-Window-Manager" - x-www-browser http://www.osnews.com/story/7774/IceWM--The-Cool-Window-Manager/
    prog "BoxLook IceWM Themes" - x-www-browser https://www.box-look.org/browse/cat/142/ord/latest/0
}


    On Monday, August 12, 2019, 2:30:58 PM CDT, gijsbers <notifications@github.com> wrote:  
 
 
@cheapy 19b2 looks great!, but it still uses the stale website www.icewm.org.

**Comment by cheapy** [comment]
The website links have been corrected in antiX 19b3.  

The IceWM keyboard mapping is now significantly improved as well, but note that it only affects new user being added, not existing users via upgrade unless you copy the new configuration files from /etc/skel/.icewm

**Comment by gijsbers** [comment]
@cheapy My impression of 19b2 and 19b3 was that dhcp6 is expected and fail to setup networking if only dhcp4 is available. Not sure.

**Comment by cheapy** [comment]
I will pass that on.  I saw one person said they couldn't connect with b2.  I had submitted a script that would pop up the connection manager if no connection was available within 10 seconds, which has worked well on mine when I go to places it doesn't know, and that would help newbies that didn't know how to connect, but I don't know if that would help with a dhcp problem.
