### ISSUE TITLE
Not an issue. A question

### ISSUE THREAD

**Issue by frankzen** [bbidulock/icewm#360]
Is there a way to run icewm-session without it running icewmbg? I never use it for backgrounds and seeing it taking up memory for nothing seems a waste. I considered replacing icewmbg with a null file but that means repeating it every time I update. And Icewm by itself doesn't run the startup file.

**Comment by gijsbers** [comment]
There is no such way. But without icewmbg there is no longer much justification for icewm-session. You could start icewm by hand yourself in the way you want. Here is a script which replaces icewm-session without icewmbg. It's called `frank-zession.sh`:

```bash
#!/bin/bash

if [[ -d $HOME/.config/icewm ]]; then
    CONF=$HOME/.config/icewm
elif [[ -d $HOME/.icewm ]]; then
    CONF=$HOME/.icewm
else
    echo "$0: No IceWM config directory!" >&2
    exit 1
fi

notify () {
    if [[ -f $CONF/startup ]]; then
        bash $CONF/startup &
    fi
}

trap notify SIGUSR1

icewm --notify "$@" &
icepid=$!
while kill -0 $icepid
do
    wait $icepid
done

if [[ -f $CONF/shutdown ]]; then
    bash $CONF/shutdown
fi
```

**Comment by frankzen** [comment]
Works great. Thank you. Have to spend some time learning BASH :)
