### ISSUE TITLE
Segfault after commit 04cdb045

### ISSUE THREAD

**Issue by targzeta** [bbidulock/icewm#364]
Hi,
starting from the commit 04cdb045 icewm doesn't work form me. With my preference file it doesn't start at all. Without ~/.icewm directory, it start, but if I do a rapid double click (left) on the workspace name, it crash.
![screenshoot](https://user-images.githubusercontent.com/2431105/61177620-2ee93600-a5da-11e9-98ad-816cb5b639f3.jpg)

Thank you in advance for your work!
Emauele

**Comment by gijsbers** [comment]
Thanks for reporting this. Even without preferences or ~/.icewm it works fine for me.
Also if I run it from a new user account. Could you perhaps try running from valgrind?
Like `valgrind icewm`.
What is your OS + version and compiler + version?

**Comment by targzeta** [comment]
Hi,
I've just compiled the latest version (770da7d0), and now all is OK!

Thank you for your works!
Emanuele
