### ISSUE TITLE
KeySysMaximizeAll

### ISSUE THREAD

**Issue by siikamiika** [bbidulock/icewm#366]
Would it make sense to add a new keyboard shortcut to preferences that allowed maximizing all windows in the current workspace? There is already `KeySysMinimizeAll` that is bound to `Alt+Shift+F9` by default, so the default key binding could be either empty or `Control+Alt+Shift+F9` (`Alt+Shift+F10` is taken).

**Comment by gijsbers** [comment]
If the behavior is available in `icesh` then it is easy to bind your own key.
In this case `icesh -s maximize` does what you want, so you can define in `keys`:

    key "Control+Alt+Shift+F9" icesh -s maximize

**Comment by siikamiika** [comment]
Works perfectly, thank you! Closing this issue.
