### ISSUE TITLE
Window title not always updated in taskbar

### ISSUE THREAD

**Issue by siikamiika** [bbidulock/icewm#367]
Steps to reproduce:
1. Open terminal emulator window (urxvt)
2. Run [ranger](https://github.com/ranger/ranger) with `set update_title true` in `~/.config/ranger/rc.conf`
3. Observe the window title update in the titlebar but not the taskbar

This could also be a bug in urxvt or ranger.

**Comment by gijsbers** [comment]
Works fine for me. Could you run `xprop` on your terminal and show us which properties have the old title and which properties have the new title? For this use a simple shell which doesn't change the terminal title, like csh.

**Comment by siikamiika** [comment]
In a state where the taskbar shows `r /home/siikamiika` and the titlebar (and curiously also the taskbar mouseover tooltip) shows `ranger:/home/siikamiika/Documents`, the output of xprop is the following:
```_ICEWM_TRAY(CARDINAL) = 0
_WIN_LAYER(CARDINAL) = 4
_NET_WM_DESKTOP(CARDINAL) = 1
_WIN_WORKSPACE(CARDINAL) = 1
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_STATE(ATOM) = 
_WIN_STATE(CARDINAL) = 0, 1023
_NET_FRAME_EXTENTS(CARDINAL) = 2, 2, 22, 2
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_SHADE, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW, _NET_WM_ACTION_STICK, _NET_WM_ACTION_CHANGE_DESKTOP
_NET_WM_VISIBLE_ICON_NAME(UTF8_STRING) = "r /home/siikamiika"
_NET_WM_VISIBLE_NAME(UTF8_STRING) = "ranger:/home/siikamiika/Documents"
_NET_WM_PID(CARDINAL) = 77294
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLASS(STRING) = "urxvt", "URxvt"
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		window id # of group leader: 0x1e00009
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 11 by 22
		program specified resize increment: 7 by 18
		program specified base size: 4 by 4
		window gravity: NorthWest
WM_CLIENT_MACHINE(STRING) = "refuge"
WM_COMMAND(STRING) = { "urxvt", "-e", "fish" }
_NET_WM_ICON_NAME(UTF8_STRING) = "r /home/siikamiika"
WM_ICON_NAME(STRING) = "r /home/siikamiika"
_NET_WM_NAME(UTF8_STRING) = "ranger:/home/siikamiika/Documents"
WM_NAME(STRING) = "ranger:/home/siikamiika/Documents"
```

I'm not running git master but the newest Arch package (1.5.5-1), so I could be missing some latest fixes.

**Comment by gijsbers** [comment]
It is clear that ranger only updates the title, but not the icon.
There is a terminal escape code which could be used: `ESC]0`.
The icewm task buttons use the icon name.

**Comment by siikamiika** [comment]
Interesting decision in the Xorg spec that `WM_NAME` is not the same as `WM_ICON_NAME`. I wonder if there are legitimate use cases for setting the title to something different from icon name. Maybe sometimes you could want to set the title to something shorter due to space constraints?

I found the offending line in ranger source:
https://github.com/ranger/ranger/blob/669100aad83e3a51f140b6085d836a8260eda8d0/ranger/gui/ui.py#L385
Replacing it with `'\x1b]0;',` makes the title update `WM_ICON_NAME` too. I'll open an issue for ranger instead. Thanks a lot for the pointers!
