### ISSUE TITLE
Question about tiling order

### ISSUE THREAD

**Issue by siikamiika** [bbidulock/icewm#368]
Is it possible to make the windows tile so that they are ordered by the taskbar rather than last focused (Alt+Tab)? My use case is switching between tiling windows with `KeyTaskBarSwitchNext` and `KeyTaskBarSwitchPrev`. I understand that this isn't primarily a tiling WM, so not a feature request but just an idea.

**Comment by gijsbers** [comment]
The tiling in IceWM is only primitive. For the moment it is better to use external means to add better tiling. One place to look at is issue #335. It would be helpful if more people posted their tiling setups for IceWM. Maybe we can add more support for tiling in `icesh`. The ordering you want is given by `xprop -root _NET_CLIENT_LIST`.
