### ISSUE TITLE
What keyboard shortcuts are possibly valid?

### ISSUE THREAD

**Issue by cheapy** [bbidulock/icewm#369]
Could you tell me where to find a complete list of what key names are possibly valid for redefining in IceWM, please?

I need to know what modifier keys are possible, and how to tell if those are available on a particular system/keyboard, and what syntax to use in my IceWM keys and preferences files to refer to that key, ie "Alt+Ctrl+KP_Home".   All of the many keyboards I own have left and right Alt, Ctrl and Shift keys, as well as one Windows key.

For example, I am trying to find a nice way to allow both the WinArrange (move windows) functions and the WinGrid (move and resize windows) to both peacefully co-exist with various normal applications on different muti-modifier key functions.  If I could distinguish between the left and right alt and control keys, that might help.  If I pressed left-control and left-alt with the keypad Home key, it would use WinArrange to move the current window to the top left corner, and if I pressed right-control and right-alt with the keypad Home key, it would use WinGrid to move/resize the current window to the top left corner quadrant instead. 

I would like to assign things to multi-modifier keys in order to avoid key conflicts with the applications.  Many use Ctrl, many use Alt, many use Win, but most don't use multi-modifiers on the keys.

I did find a couple files similar to ones referenced by the ubuntu manpage for 1.43 by hunting the distros I have loaded (I renamed from .h to .txt to upload), but for example "Ctrl" isn't there.  Maybe take a quick look and see if they are my list?

[keysymdef.txt](https://github.com/bbidulock/icewm/files/3420000/keysymdef.txt)
[XF86keysym.txt](https://github.com/bbidulock/icewm/files/3420001/XF86keysym.txt)

Thanks

**Comment by gijsbers** [comment]
The modifiers supported by IceWM are:
```C
        { "Alt+",   kfAlt   },
        { "AltGr+", kfAltGr },
        { "Ctrl+",  kfCtrl  },
        { "Hyper+", kfHyper },
        { "Meta+",  kfMeta  },
        { "Shift+", kfShift },
        { "Super+", kfSuper },
```
The keys available you can find in the output of `icewm --postpreferences`, or in `grep Key ~/.icewm/preferences`. The `xev` program could be useful as well.

**Comment by cheapy** [comment]
Thanks for the --postpreferences option, its also useful for analyzing other things
