### ISSUE TITLE
With double height taskbar, autohide hides taskbar while hovering over upper half

### ISSUE THREAD

**Issue by cheapy** [bbidulock/icewm#370]
I found that increasing the hide delay helps give more time to click, but it can be frustrating when the menu hides while trying to select something.  

The real problem is that when you are over the upper half, it doesn't think youicewm --postpreferences,  are wanting the menu to stay up.

BTW, the double height menu is a great feature, and combined with autohide will allow many launchers without sacrificing screen space

**Comment by cheapy** [comment]
I increased my delay to 1.5 seconds and it has helped give me time to click on something.  

But something I noticed is that it doesn't hide if there is a tool tip popping up from the top row over whatever I am hovering over.  There is no tool tip over the address bar in the middle.

Thanks for a great program!

**Comment by gijsbers** [comment]
Is that for plain 1.5.5 or for current? Current works for me. Otherwise post a screencast of the problem and grep the relevant TaskBar and ToolTip changes from `icewm --postpreferences` here.

**Comment by cheapy** [comment]
I tried it on NuTyX 11.1 rolling and it also had the problem.  I think its the combo of autohide and double height (on NuTyX those were my only preferences changes), and it's intermittent.  

On antiX I switched to JWM temporarily and tried to build from git clone, but ended up with 3 packages with errors: configure: error: Package requirements (fontconfig xext x11) were not met.

Since I like running antiX most, I think the best thing to do is just wait for the next update, so I'm going to close the ticket.

PS: Currently on antiX19b2 the version shows IceWM 1.5.5+git20190610 but my understanding is that there are some changes, but I don't know how to tell if someone implements a newer version that I can retest with.

**Comment by gijsbers** [comment]
So I may assume your original message was for 1.5.5? The output of `icewm --version` is helpful whenever you report something.

**Comment by gijsbers** [comment]
Ah here I find what NuTyx 11.1 is using:
http://www.nutyx.org/en/?type=pkg&branch=rolling&arch=x86_64&searchpkg=icewm
2 months old, so without commit 6ce96b1.
What is relevant is if tooltips play a role in the problem you reported?

**Comment by cheapy** [comment]
I see my reply didn't post here, so from now on, I will answer on site.

I think whether or not there is a tooltip and if it pops up or doesn't does affect whether the problem will occur or not.

I looked at what I think to be the antiX source for 1.5.5 and the changes are not in that code, either.  I will wait for the code to get updated via Sid.  I can live with it till then.  Thank you very much for investigating, and if you hear of a distro that runs very fresh code, please post it so I can setup a test partition to use for smarter testing so I don't bother you for issues you have already addressed.

**Comment by cheapy** [comment]
Thanks very much.  Sorry for the delay as I didn't know how to do any of these things.  

I learned how to download, build, change (I just entered the 1 commit) and rebuild the packages, and reinstall them all.  Your fix worked and I am a little more knowledgeable for if I ever have another issue.
