### ISSUE TITLE
'WorkspaceNames' missing in icewm-preferences

### ISSUE THREAD

**Issue by micrococo** [bbidulock/icewm#371]
The Workspaces section is empty. IceWM's man page says "The number of work spaces and their names are configurable in the preferences file through the 'WorkspaceNames' option". This is on openSUSE Tumbleweed and IceWM 1.5.4.

**Comment by bbidulock** [comment]
How is it missing?  Do you mean from the default preferences?  It is not mandatory to set this preference.

**Comment by micrococo** [comment]
No, I meant that it is not documented in the man page (icewm-preferences), it isn't there.

https://ice-wm.org/man/icewm-preferences#workspaces

But it is in the IceWM Manual page:

https://ice-wm.org/manual/#workspaces
