### ISSUE TITLE
icewm errors

### ISSUE THREAD

**Issue by frankzen** [bbidulock/icewm#373]
Noticed these lately in my .xsession-errors file. Are they significant ??

10:07:58.294: IceWM: gdk pixbuf channels 3 != 4 || has_alpha 0 != 1
10:07:58.294: IceWM: gdk pixbuf channels 3 != 4 || has_alpha 0 != 1
10:07:58.294: IceWM: gdk pixbuf channels 3 != 4 || has_alpha 0 != 1

**Comment by gijsbers** [comment]
I assume this is for version 1.5.5? Are you running Debian Sid?

**Comment by frankzen** [comment]
Yes I believe so. Debian Sid.

**Comment by gijsbers** [comment]
I see that this has already been fixed in the current source code.
