### ISSUE TITLE
Dark artifacts in system tray after upgrade to 1.6.0

### ISSUE THREAD

**Issue by tim77** [bbidulock/icewm#374]
How we can fix this?
![DeepinScreenshot_select-area_20190821105420](https://user-images.githubusercontent.com/5614476/63413494-7ac1a300-c402-11e9-8a1f-bb38bd64729a.png)

**Comment by gijsbers** [comment]
Which theme and which systray apps are you using?
Could you try setting Alpha=1 or start by adding the option -a?

**Comment by tim77** [comment]
Adding `Alpha=1` helped with this issue but i got a another bug: :smile: 
![DeepinScreenshot_select-area_20190821214541](https://user-images.githubusercontent.com/5614476/63459455-3ca59d00-c45d-11e9-95d6-c2c7da9d3b63.png)
But this because of `compton` probably. Without it its fine.

I am using `IceClearlooks2` theme and apps in systray GTK apps, except Telegram.

**Comment by gijsbers** [comment]
What is the "another bug" precisely?
How does it look without compton?

**Comment by tim77** [comment]
This is how it look without compton and how it should look like:
![DeepinScreenshot_select-area_20190822063516](https://user-images.githubusercontent.com/5614476/63484096-35a37c80-c4a7-11e9-8d4a-9cd2d1ec7863.png)

The problem with font rendering and visual blue glitches around text.

**Comment by tim77** [comment]
But https://github.com/bbidulock/icewm/commit/2766da4de269a61272ca189dd9ac8be96039915f fixed tray issues, can confirm. Only this issue with font now.

**Comment by gijsbers** [comment]
This commit is in the 1.6.1 release.

My impression was that you modified your `IceClearlooks2/default.theme`.
Is that right? Can you post the changes? Otherwise I can't help.

What is the output of `icesh xembed` ?

**Comment by tim77** [comment]
> My impression was that you modified your `IceClearlooks2/default.theme`.
> Is that right?

https://gist.github.com/tim77/b90b50601cf8710a48d5fc486121d38c

> What is the output of `icesh xembed` ?

```
0x1800006   0  1353 "Telegram (36677)"  : (telegram-desktop.TelegramDesktop) 1280x976+0+19
0xc0496d    0  1352 "GWE"               : (com.leinardi.gwe.com.leinardi.gwe) 24x24+1030+998
0x1800dd8   0  1353 ""                  : (telegram-desktop.TelegramDesktop) 24x24+1006+998
0x600038    0  1349 "redshift-gtk"      : (redshift.redshift)  24x24+1078+998
0x1200c36   0  1350 "workrave"          : (workrave.Workrave)  24x24+1102+998
0xa001ef    0  1347 "PulseAudio system tray": (pasystray.Pasystray) 24x24+1054+998
0x180000a   0  1353 "Media viewer"      : (telegram-desktop.TelegramDesktop) 1280x1024+0+0
```

**Comment by tim77** [comment]
@gijsbers i'll close this bug since it fixed and open new one with compton issue if you wouldn't mind? And thanks a lot.

**Comment by gijsbers** [comment]
Perfect! You can always close your issues.
