### ISSUE TITLE
1.6.1: ColorQuickSwitchActive not working

### ISSUE THREAD

**Issue by Thyname** [bbidulock/icewm#375]
I'm using 1.6.1 from https://copr.fedorainfracloud.org/coprs/atim/icewm/

ColorQuickSwitchActive isn't working (see screenshots with two different themes).

![Screenshot_2019-08-23_06-51-24](https://user-images.githubusercontent.com/30552880/63585445-808bc580-c575-11e9-93a2-3ffbe9f9ac7e.png)
![Screenshot_2019-08-23_06-53-21](https://user-images.githubusercontent.com/30552880/63585454-871a3d00-c575-11e9-98a2-8b90e3442a6c.png)

**Comment by gijsbers** [comment]
Thanks! Could you clarify "is not working"?
What disappointing details do you observe exactly
and what improvements do you expect instead?

**Comment by Thyname** [comment]
Hi, thank you very much for not only keeping icewm alive but improving it so much.

I may be wrong as I'm just starting again with icewm after quite a while, but doesn't ColorQuickSwitchActive mean the color for the active item in the quick switch box?

It may be perhaps the kind of theme but in the first screenshot it should be purple and is light gray and in the second screenshot it should be blue and in practice is the same as the background making it not noticeable in the quick switch box.

**Comment by gijsbers** [comment]
Okay good! Maybe the quick switch expert @Code7R can join us?
Which themes are those? That would help us to reproduce your problem.

**Comment by gijsbers** [comment]
Okay now I see that the themes are IceClearlooks2-Magi and IceNumix3-Aqua. Very good!

**Comment by Code7R** [comment]
Uhm, ok... Yes, I made that comment in the code but I seriously don't remember which themes were problematic for me. IMHO we can keep your change/reversion for now and when I see something weird, this topic can be discussed again.

**Comment by Thyname** [comment]
I'm using the git version and it's working great for these themes. Thank you all.
