### ISSUE TITLE
FR: enable png for start menu icon.

### ISSUE THREAD

**Issue by Thyname** [bbidulock/icewm#377]
Feature request:

Currently taskbar can use png icons in toolbar file for the launchers but the 'start menu' icon can use only xpm, from my tests (it first tries /taskbar/icewm.xpm, then start.xpm, then linux.xpm).
So, as feature request, please enable png icons for that when possible.

Thank you.

**Comment by gijsbers** [comment]
Works for me. The idea is that the entire theme could be PNG only. Needs testing.

**Comment by gijsbers** [comment]
Here is a script I used to convert themes to PNG. No warranties. Use at own risk:

```bash
#!/bin/bash
if ! command -v convert >/dev/null || ! convert -version >/dev/null
then
    echo "Please install convert"
    exit 1
fi
if test $# -eq 0
then
    set -- "`pwd`"
fi
for d
do
    if ! test -f "$d"/default.theme 
    then
        echo "Missing $d/default.theme"
        continue
    fi
    for f in $(find "$d" -name '*.xpm')
    do  
        if test -L "$f"
        then
            g=$(readlink "$f")
            rm -fv -- "$f"
            ln -sv -- "${g%.xpm}.png" "${f%.xpm}.png"
        else
            g=${f%.xpm}.png
            echo convert "$f" "$g"
            convert "$f" "$g"
            rm -fv -- "$f"
        fi
    done
done
```

Current git IceWM can use PNG-only themes just fine.
