### ISSUE TITLE
Problem compile IceWM on Debian testing

### ISSUE THREAD

**Issue by bedna-KU** [bbidulock/icewm#38]
I compiled IceWM on Ubuntu with g++ 4.8.4 and all is OK.
I compiled IceWM on Debian testing (antiX) g++ 4.8.5 and compilation jump from /tmp/icewm
into /var/tmp/icewm
I do not understand why.

mario@antix1:/tmp/icewm
$ make V=0
 make  all-recursive
 make[1]: Entering directory '/var/tmp/icewm'
Making all in src
make[2]: Entering directory '/var/tmp/icewm/src'
   CXX      mstring.lo
 In file included from mstring.cc:6:0:
 ../config.h:549:15: error: multiple types in one declaration
  #define pid_t int
                ^
 ../config.h:549:15: error: declaration does not declare anything [-fpermissive]
 Makefile:1543: recipe for target 'mstring.lo' failed
 make[2]: **\* [mstring.lo] Error 1
 make[2]: Leaving directory '/var/tmp/icewm/src'
 Makefile:580: recipe for target 'all-recursive' failed
 make[1]: **\* [all-recursive] Error 1
 make[1]: Leaving directory '/var/tmp/icewm'
 Makefile:477: recipe for target 'all' failed
 make: **\* [all] Error 2

**Comment by bbidulock** [comment]
I understand that there exists a Debian experimental package built from here.  I think that it uses the cmake build system instead of the autoconf one.  I am running under gcc 5.2.0.  4.8.4/5 is really old.  Nevertheless, the define in question was generated by autoconf (autoheader, really).  Try using the cmake build environment under Debian/Ubuntu instead.

**Comment by Code7R** [comment]
The oldest compiler I tried on Debian is the one from Stable and it builds just fine with the mentioned cmake build system. Consider taking that jessie-backports version as base.

It's not release-suitable, though (there is a fresh RC bug #798698).

**Comment by bedna-KU** [comment]
I upgrade system and all is OK. 
Thank you for your replies.
