### ISSUE TITLE
font corruption with 1.6.1 Alpha and nvidia

### ISSUE THREAD

**Issue by gensenio** [bbidulock/icewm#381]
Im am using icewm with proprietary nvidia drivers 435.21 and i am using plank dock and compton as compositing manager.

with 1.5.5 icemw was working properly.

with 1.6.1 with Alpha= 0 i have a black background behind the plank dock.

![2019-09-08_10-45](https://user-images.githubusercontent.com/3276068/64486037-6403b480-d228-11e9-808a-073d6882bf78.png)

if i set Alpha=1 plank is working properly but the fonts in menus and window titles are corrupted.

![2019-09-08_10-44](https://user-images.githubusercontent.com/3276068/64486034-5bab7980-d228-11e9-9644-8ac52863e5fa.png)

**Comment by gijsbers** [comment]
Thanks very much for reporting this. I'm struggling to reproduce this since I don't have such a video driver. The first problem might be related to joewing/jwm#130. Could you check that?
#374 is another possible related issue. I'll see if I can undo some changes to become more like 1.5.5.

**Comment by gensenio** [comment]
ok i will check jwm

**Comment by gensenio** [comment]
these problems seems to happen only with the Nvidia proprietary drivers. I have also a laptop which is using radeon open source drivers and a workstation with intel drivers and i don't have the font corruption at all.

if i set Alpha to 0 the problem with Plank it is happening also with the open source drivers.
![2019-09-10_09-44](https://user-images.githubusercontent.com/3276068/64594006-752afd80-d3af-11e9-87df-da070505330e.png)
As you can see from the screenshot the background is not really black because there is some transparency

**Comment by gensenio** [comment]
with jwm 2.3.2 i have no problems

**Comment by gijsbers** [comment]
The theme you use is always Infadel2?
How are the icewm windowlist and the Alt+Tab QuickSwitch?

**Comment by gensenio** [comment]
yes i use infadel2 but the problem persist also with other themes
![2019-09-10_22-34](https://user-images.githubusercontent.com/3276068/64648496-506c6f80-d41b-11e9-8dc4-f71573516c2a.png)
Yes the windowlist text is also corrupted
![2019-09-10_22-33](https://user-images.githubusercontent.com/3276068/64648555-6ed26b00-d41b-11e9-963d-00c8867c46dd.png)

**Comment by gensenio** [comment]
and the problem is not present if i disable compton.

**Comment by gijsbers** [comment]
Yes, some changes I made were specifically to circumvent what seemed like bugs in compton.

**Comment by gensenio** [comment]
by the way i reverted to 1.5.5 which is working fine with nvidia and compton.

Was in the 1.5.5 alpha=1 enabled by default?

**Comment by gijsbers** [comment]
Support for alpha blending in the icewm windows only started in 1.6.0.

**Comment by gensenio** [comment]
ok if i disable alpha in 1.6 i get this (cairo-clock)
![2019-09-10_23-13](https://user-images.githubusercontent.com/3276068/64651106-fcfd2000-d420-11e9-8092-42ec65589747.png)
but in 1.5.5 which don't support alpha blending cairo clock is rendered correctly
![2019-09-10_23-20](https://user-images.githubusercontent.com/3276068/64651380-a9d79d00-d421-11e9-8c6c-4c3eb2eb654b.png)

**Comment by gijsbers** [comment]
I can reproduce this! That makes for a good easy test case. thx!
Could you post a screendump of the corrupted `windowlist` on 1.6.1?

**Comment by gensenio** [comment]
![2019-09-11_00-01](https://user-images.githubusercontent.com/3276068/64653672-4a7c8b80-d427-11e9-8b36-b004097fa9f5.png)
[video.zip](https://github.com/bbidulock/icewm/files/3597895/video.zip)
I added also a video seems that the text background is blendend with the desktop

**Comment by gijsbers** [comment]
This should fix plank and cairo-clock if Alpha=0.

**Comment by gijsbers** [comment]
Perhaps a different compton backend gives other results?
https://github.com/chjj/compton/wiki/perf-guide

**Comment by gensenio** [comment]
ok thanks for the commiI will check

**Comment by gensenio** [comment]
Changing the backend didn't resolve the fonts corruption

**Comment by gijsbers** [comment]
Did the commit work?
Do you use the chjj compton and did you try https://github.com/yshui/compton/?

**Comment by gensenio** [comment]
i'm using yushi compton.

**Comment by gensenio** [comment]
the commit is working!!! now i can run with alpha= 0 and i don't have font corruption

**Comment by gijsbers** [comment]
Good!
The question that remains is to what degree the font
corruption is dependent on the use of Xft fonts.
Could you try non-Xft fonts or configure --disable-xfreetype?

**Comment by gensenio** [comment]
ok with --disable-xfreetype there is no corruption. So only with nvidia + alpha=1 + xft + compton

**Comment by gijsbers** [comment]
This is very useful information!

**Comment by gijsbers** [comment]
You could try this patch:
```diff
diff --git a/src/ypaint.cc b/src/ypaint.cc
index 15fa4263..6814f968 100644
--- a/src/ypaint.cc
+++ b/src/ypaint.cc
@@ -118,5 +118,5 @@ Graphics::~Graphics() {
 XftDraw* Graphics::handleXft() {
-    if (fXftDraw == nullptr && rdepth() == 32 && xapp->alpha()) {
+    /* if (fXftDraw == nullptr && rdepth() == 32 && xapp->alpha()) {
         fXftDraw = XftDrawCreateAlpha(display(), drawable(), 32);
-    }
+    } */
     if (fXftDraw == nullptr) {
```

**Comment by gensenio** [comment]
yes the patch solved the font corruption problem

**Comment by gijsbers** [comment]
I made a slightly different commit to take into accounts different depths.
If you think we are done with this we can head for a new release.

**Comment by gensenio** [comment]
ok it tested it and i have no issue anymore!! thank you for your work! i use icewm from 20 year and now is getting better and better
