### ISSUE TITLE
startMinimized does not work with some applications

### ISSUE THREAD

**Issue by gensenio** [bbidulock/icewm#383]
slack.startMinimized: 1
slack.icon:  /usr/share/pixmaps/slack.png
slack.tray: Exclusive

in winoptions  is not working the application start and the window is shown.
also skype is not workig.
evolution seems to work properly

**Comment by gensenio** [comment]
Hint skype and slack are both electron applications

**Comment by gijsbers** [comment]
What happens is that they start in state minimized, but almost immediately icewm receives a `_NET_ACTIVE_WINDOW` client message to activate them. That removes the minimized bit and maps them, overriding startMinimized. [See](https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#idm140200472702304). Can't do much about it, except ignore the activate message for the first umpteen milliseconds after startMinimized? Hm.

**Comment by gijsbers** [comment]
In fact [icewmhint](https://ice-wm.org/man/icewmhint) gives an example you could try.

**Comment by gensenio** [comment]
here is my icewm startup file: 
icewmhint Slack startMinimized 1 \
          Slack workspace 3 \
          Slack ignorePagerPreview 1 \
          Slack ignorePositionHint 1 \
          Slack ignoreTaskBar 1 \
          Slack ignoreQuickSwitch 1 \
          Slack ignoreUrgentHint 1 \
          Slack noFocusOnAppRaise 1
slack &
sleep 5
copyq &
evolution &
nm-applet &
skypeforlinux &


but is not working...
in my opinion if the application it is send  _NET_ACTIVE_WINDOW after start this is not an icewm bug.

**Comment by gensenio** [comment]
and i found a command line option for the application (slack) to start minimized ;)
and there is also and option for skype...
so for me you can close the issue
