### ISSUE TITLE
Own cursors - icewm/themes/theme_name/cursors/left.xpm ... doesn't work

### ISSUE THREAD

**Issue by bedna-KU** [bbidulock/icewm#384]
I have in my theme directory **cursors** and here files left.xpm right.xpm and move.xpm but the cursor doesn't change

Documentation https://github.com/bbidulock/icewm/blob/icewm-1-4-BRANCH/doc/icewm.adoc#mouse-cursors

example left.xpm:
```
/* XPM */
static char * left_xpm[] = {
"11 17 3 1",
" 	c None",
".	c #FFFFFF",
"+	c #000000",
"...........",
".+++++++...",
".+++++++...",
".+++++++...",
".+++++++...",
".+++++++...",
".+++++++...",
".+++++++...",
".+++++++...",
".+++++++...",
".+++++++...",
".+++++++...",
".+++++++...",
"...........",
"           ",
"           ",
"           "};
```

**Comment by gijsbers** [comment]
Sofar I can't get cursors to work for any icewm version starting from 1.3.8 and upwards.

**Comment by bedna-KU** [comment]
I tried it for the first time to screencast

**Comment by gijsbers** [comment]
This works for me again. You can try either with gdk-pixbuf or without.
Thanks for reporting this, otherwise I might never have discovered this.

**Comment by bedna-KU** [comment]
Thank you so much for your work.
I tried it quickly and it didn't work.
After a long journey, I have to go to sleep tomorrow

**Comment by gijsbers** [comment]
You need to `autogen.sh` and `configure` again. (Or rebuild using cmake.)

**Comment by bedna-KU** [comment]
Thanks a lot, it works great.
(with gdk-pixbuf or without it is the same)
