### ISSUE TITLE
Worse quality of antialiasing for scaled background with the trunk version

### ISSUE THREAD

**Issue by gensenio** [bbidulock/icewm#385]
using the icevm from git i got a worse scaling quality of the bacground image

with 1.5.5:
![2019-09-14_08-08](https://user-images.githubusercontent.com/3276068/64904207-dbbd5d80-d6c6-11e9-8747-b41f06781e3c.png)
with trunk the antialiasing is worse
![2019-09-14_07-59](https://user-images.githubusercontent.com/3276068/64904208-e37d0200-d6c6-11e9-8e86-111a6b2488b4.png)

**Comment by gijsbers** [comment]
For the git icewm you need to configure --enable-gdk-pixbuf.

**Comment by gensenio** [comment]
sorry i will close the bug
