### ISSUE TITLE
Application icon overlaps menuButton

### ISSUE THREAD

**Issue by micrococo** [bbidulock/icewm#388]
The image shows the problem. Both the application icon and the menuButtonX.xpm pixmap are displayed at the same time. The hover and pressed effect still work as it can be seen in the bottom image.

![screenshot](https://user-images.githubusercontent.com/7717273/66198544-ed2dd000-e69c-11e9-81e8-329ff68b512c.png)

This happens on VirtualBox with IceWM built from latest git source code.

**Comment by gijsbers** [comment]
Which theme? Which operating system?

**Comment by micrococo** [comment]
Sorry, I overlooked the `ShowMenuButtonIcon=0` option. When it is set to 1 both icons are painted, but it is only noticeable if the application icon has transparent parts. In addition, it only affects to the pixmap based looks (_pixmap_, _metal_, _gtk_, and _flat_). For example, CrystalBlue if you set `ShowMenuButtonIcon` to 1.

![CrystalBlue](https://user-images.githubusercontent.com/7717273/66224122-68ab7380-e6d5-11e9-9f5e-22b79b6cd48c.png)

System is openSUSE Tumbleweed. It's a theme of my own, a clone of Breeze. Work in progress...

![theme](https://user-images.githubusercontent.com/7717273/66224713-e328c300-e6d6-11e9-8f5b-d3192692ce06.jpg)
