### ISSUE TITLE
autogen error in latest release

### ISSUE THREAD

**Issue by frankzen** [bbidulock/icewm#389]
Extracted latest icewm. debian/1.6.2+git20190929-1

autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:43: installing 'scripts/ar-lib'
configure.ac:13: installing 'scripts/compile'
configure.ac:14: installing 'scripts/config.guess'
configure.ac:14: installing 'scripts/config.sub'
configure.ac:28: installing 'scripts/install-sh'
configure.ac:28: installing 'scripts/missing'
configure.ac:5: error: version '1.6.1.42' doesn't follow Gnits standards
src/Makefile.am: installing 'scripts/depcomp'
autoreconf: automake failed with exit status: 1

Help !!

**Comment by bbidulock** [comment]
Your configure.ac is out of sync.  Check it back out and then run autogen.sh again.  Or just edit it and remove the word "gnits" from AM_INIT_AUTOMAKE.

**Comment by frankzen** [comment]
I chose the 2nd solution. Fixed. Thank you.

**Comment by targzeta** [comment]
I have the same problem. What does mean that our configure.ac is out of sync? I have
[this file](https://github.com/bbidulock/icewm/blob/icewm-1-4-BRANCH/configure.ac).

Emanuele

**Comment by gijsbers** [comment]
What is your output of `git checkout -f configure.ac && git pull && git status && ./autogen.sh` ?
You could also try `sed -i 's/gnits //' configure.ac` .

**Comment by targzeta** [comment]
Thank you! [This commit](https://github.com/bbidulock/icewm/commit/bce25cdf041588f7386b376bc2ecc5a7f7e09e47) has resolved the problem!

Thank you again!
Emanuele
