### ISSUE TITLE
Proposal to include IceWM into GNU project

### ISSUE THREAD

**Issue by gnusupport** [bbidulock/icewm#391]
GNU is an operating system that is [free software](https://www.gnu.org/philosophy/free-sw.html)—that is, it respects users' freedom.

The GNU operating system consists of GNU packages (programs specifically released by the GNU Project) as well as free software released by third parties.

[Dr. Richard Stallman](https://www.gnu.org) has started the [free software philosophy] https://www.gnu.org/philosophy/free-sw.html) and created various licenses such as [GNU General Public License](https://www.gnu.org/licenses/licenses.html#GPL) (GNU GPL), and others. 

Hereby I am asking developers of IceWM if you would like to include IceWM into GNU project, for it to become official GNU project, so that IceWM may be better promoted into truly free [GNU operating system distributions](https://www.gnu.org/distros/free-distros.html).

If you have proposals and wish to do so, let me know by writing to bugs@gnu.support or writing directly to GNU project.

**Comment by bbidulock** [comment]
I think that we are all quite familiar with open source software, Dr. Richard Stallman and the GNU organization.  The GNU project does not need our permission to include icewm (it is, after all, licensed under LGPL 2.1).  If you would like us to comment on a proposal of yours, please elucidate them here.

**Comment by gnusupport** [comment]
Dr. Richard Stallman have begun GNU project and free software philosophy back in 1983 and 1984. He envisioned freedom and user's rights. I have given you few links and references to free software philosophy and definitions of such. 

The term "open source" was introduced by corporate interests to promote sales of software, and quality of software, but not freedom for users and users rights. That movement is something different. They do not push neither promote users' rights in computing and software. In general "open source" advocates are promoting software as their main focus, not quite the free software politics and freedom that is given and shall be given to users. 

Both "open source" advocates and free software advocates are friends and work towards more free software in friendly manner, some people may be not, but I am saying that we are friends, but we are in various movements, various politics. See: https://www.gnu.org/philosophy/open-source-misses-the-point.html.en

The question that I am making and mysel I am user of IceWM since many years is if current developers of IceWM would be willing to understand what free software means, what are users' human rights and freedom in computing and then based on that understanding, if developers would like for IceWM to become official GNU software project. 

That would probably, but without promise, as I am just supporter, ask for developers to stick to some of GNU policies, and it would get its branding GNU, and it would probably be supported by FSF, probably with donations, it could develop IceWM maybe to one greater level, it would get support by endorsed GNU operating system distributions. 

Richard Stallman have asked me what developers think about that. I am asking you now what developers are thinking about that. I have also asked Marko, the first author what he thinks, I have not get answer by email.

Your feedback is welcome.

**Comment by E5ten** [comment]
I don't think it's possible for this to seem less legitimate...

**Comment by gnusupport** [comment]
@E5ten what is your stance? Would you like that IceWM becomes official GNU project?

**Comment by gnusupport** [comment]
1.  The package should say that it is a GNU package.
2.  It should be distributed via ftp.gnu.org, or another site offering access to everyone.
3.  The package's homepage should be on the GNU website.
4.  The developers must pay attention to making their software work well with other GNU packages.
5.  Documentation should be in [Texinfo](https://en.wikipedia.org/wiki/Texinfo "Texinfo") format, or in a format easily convertible to Texinfo.
6.  Should use [GNU Guile](https://en.wikipedia.org/wiki/GNU_Guile "GNU Guile") for its
    extension language, but exceptions are explicitly possible in this regard.
7.  Should not recommend any non-free program, nor refer the user to any non-free documentation or non-free software.
8.  Use GNU terminology, including referring to "[GNU/Linux](https://en.wikipedia.org/wiki/Linux_naming_controversy "Linux naming controversy") systems" in many situations where other observers would just write "Linux", and "free software" rather than "open source".
9.  The maintainer should be contactable, at least infrequently, to discuss problems in the software or fixing compatibility issues.

https://www.gnu.org/prep/standards/html_node/index.html

Please think about that. There is process how to propose it as GNU project. 

Please see: https://www.gnu.org/help/evaluation.html

Please inform me or try to discuss with friends developers if there could be consent reached to propose it as part of official GNU project.

GNU project does need Window Manager and IceWM is in my opinion the best choice.

**Comment by 717g301github** [comment]
> @E5ten what is your stance? Would you like that IceWM becomes official GNU project?

Yes.

**Comment by Code7R** [comment]
Oh, well, I don't have much to say in this project. But I just don't like that list of criteria, it sounds too much like cultist thinking, i.e. "don't mention ever the other group", "use what we like", "use the words we prescribe", "use the format and script language we like most" even if it's probably not the greatest alternative nowadays, "user our way of distribution" (and not the evil Microsoft's GitHub service).

**Comment by gnusupport** [comment]
I think you are mistaken. GNU project does not drive people to use non-free javascript, such websites may not be recommended. So far I know, there are several GNU software projects hosted on Github. Important is to have them also hosted on GNU servers, and that they can be mirrored in some standardized way. Even GNU Coreutils can be found on Github: https://github.com/coreutils/coreutils or LibreDWG and others, I am not following that.

It would be good if your comment is more specific that I may answer your doubts. As you did not say "which other group" and "use what we like", what do you mean specifically?

If you refer to Guile, you need not make IceWM extensible with Guile, that is up to you really. One cannot satisfy needs of everybody. 

Question is if developers of IceWM value freedom and users' human rights in computing and if that is the case, then IceWM could become GNU IceWM and official GNU project, which could increase number of contributors, and maybe IceWM becomes good alternative to bloated desktop environments.

**Comment by gijsbers** [comment]
So it would lead to extra work and in turn restrict our freedom.

**Comment by E5ten** [comment]
Obviously since I'm not a developer I don't have a say, but I couldn't be more opposed to this.

**Comment by bbidulock** [comment]
I too think that it is more work than benefit.  (I have been around long enough to see the Savannah project be born and die.)

Looking at the others' responses, I think that the answer is no.

I am not surprised that you got no response from Marko: I started this fork because Marko would not respond to support requests nor incorporate patches.  Understandable, though: I hear he is a Submarine Captain in the US Navy.  We are thankful for all his efforts to create a worthy window manager and influence the GNOME/WMH specification.

**Comment by gnusupport** [comment]
You do not need to host at Savannah. There is almost nothing to be changed but some cosmetics.

**Comment by gnusupport** [comment]
Would IceWM become GNU project, I would personally make donations. I am personally interested to include and further market GNU with official window manager for GNU.

**Comment by gijsbers** [comment]
I don't understand why you think donations should make any difference.

**Comment by bbidulock** [comment]
That's a little harsh.  I think we can just close it.
