### ISSUE TITLE
Anti-aliasing icon edges

### ISSUE THREAD

**Issue by tim77** [bbidulock/icewm#392]
Is this possible to use .png and .svg icons with anti-aliasing edges?

![DeepinScreenshot_select-area_20191018182624](https://user-images.githubusercontent.com/5614476/67107356-ff4b5a80-f1d4-11e9-9d0c-ab1764a3e689.png)

- IceWM ver 1.6.2

**Comment by bbidulock** [comment]
Yes, it is possible, but doesn't appear to be doing so.

**Comment by tim77** [comment]
At first i thought i built it incorrectly after switching to cmake build system, but i tried with old one with `  --enable-antialiasing` 1.6.1 version and it rendering still like this. My current build options is:

```cmake
-DCONFIG_GDK_PIXBUF_XLIB=on \
-DCONFIG_LIBPNG=on \
-DCONFIG_LIBRSVG=on \
-DCONFIG_XPM=on \
```

**Comment by gijsbers** [comment]
It is a bug which i will fix.

**Comment by gijsbers** [comment]
Does this suffice?

**Comment by tim77** [comment]
> Does this suffice?

It's definitely more accurate, but could it be better? There is no AA on some icons. But look on GWE (green .png icon) it renders perfectly. How we can solve this issue completely in general and how to make all icons rendered like that?

![DeepinScreenshot_select-area_20191027001640](https://user-images.githubusercontent.com/5614476/67632632-a2276700-f8ae-11e9-824d-7fede9a50bdb.png)

**Comment by gijsbers** [comment]
Some icons may have an alpha channel while others may not?
Attach the icons which you think are worst.

**Comment by tim77** [comment]
> Some icons may have an alpha channel while others may not?

At first i though too, but they all have alpha channel. I tested with default GNOME Adwaita theme as well.

> Attach the icons which you think are worst.

For example `themes_32x32.png`
![DeepinScreenshot_select-area_20191027130503](https://user-images.githubusercontent.com/5614476/67633598-7dd18780-f8ba-11e9-8f40-a50a8fe0e16d.png)

Original GNOME icon: 
![preferences-desktop-theme](https://user-images.githubusercontent.com/5614476/67633612-9e99dd00-f8ba-11e9-8677-0d893c0fe8db.png)

**Comment by gijsbers** [comment]
Thanks. It might have to do with xrender needing different alpha values.

**Comment by gijsbers** [comment]
@tim77 @Code7R Could you evaluate commit b48663e?

**Comment by tim77** [comment]
> @tim77 @Code7R Could you evaluate commit [b48663e](https://github.com/bbidulock/icewm/commit/b48663e27682ba173743699909a8695c41dc7745)?

Oh this is amazing improvement! I consider this is a fix for this issue. Thank you! What about https://github.com/bbidulock/icewm/commit/981ce098b467e8e5e52bb1141b2305dc7bc97a41? Do you plan reverting it or it also can improve a little bit AA edges?

Also can i build now new version with this patch or better wait for new release? If so any ETA?

**Comment by gijsbers** [comment]
You can evaluate if the revert of 981ce09 is  better or not.
You can check for Alpha=0 or 1.
Of course we make a new release when this is all OK.

**Comment by gijsbers** [comment]
@tim77 Is this perfect now or do we need to further improve this?

**Comment by Code7R** [comment]
I think this was the fix in 1.6.3, for my "spots on corners" problem? If yes, it looks good.

**Comment by tim77** [comment]
Give me few days please. :) I am not forgot about report. I waiting for some feedback as well about this issue from other users. Yes, it fixed in 1.6.3 probably, but one thing still worries me.

**Comment by tim77** [comment]
Edges aliasing is working now and look smooth, but it still not accurate a little bit, maybe this can be tweaked?

- Example with current look:
![DeepinScreenshot_select-area_20191206145853](https://user-images.githubusercontent.com/5614476/70325328-6b902500-183a-11ea-9464-2620927a2243.png)


- Example with how it could look:
![fm](https://user-images.githubusercontent.com/5614476/70325359-78ad1400-183a-11ea-841f-ccf629e2ba80.png)

**Comment by gijsbers** [comment]
If you could post example icons which need improvement then I will look at it.

**Comment by tim77** [comment]
Maybe it's a little bit blurry with https://github.com/bbidulock/icewm/commit/38f55a509ac709da98164a2affe9a476284e2cf6 but IMHO it is definitely best variant for now. Looks pleasant. Thank you ♥️
![DeepinScreenshot_select-area_20191210210150](https://user-images.githubusercontent.com/5614476/70560245-ecc81e80-1b90-11ea-835e-0ef3c0848b4e.png)
