### ISSUE TITLE
Current workspace not highlighted on taskbar's switching buttons on start

### ISSUE THREAD

**Issue by micrococo** [bbidulock/icewm#393]
When IceWM starts, the current workspace isn't highlighted, it has the same appearance than the inactive workspaces. The example image shows how it looks after the session starts (top) and after switching to another workspace and then back to the first (bottom) with two different themes. I've tested a few more and all of them exhibit the issue.

![example](https://user-images.githubusercontent.com/7717273/67474293-82950200-f654-11e9-868f-5f3b4f31e32b.jpg)

The same happens when you change the current theme.  You have to select a different workspace for the highlight effect to start working. This is on openSUSE Tumbleweed with IceWM build from git's latest source, but the issue has been present for sometime (I can precise more, I only use IceWM on a VM now and then).

Note that the red artifacts are not an IceWM issue but a mess I made editing the image.

**Comment by bedna-KU** [comment]
I have the same problem.

**Comment by micrococo** [comment]
Fixed. Thank you.
