### ISSUE TITLE
Taskbar not repositioned after display resize

### ISSUE THREAD

**Issue by mihkelader** [bbidulock/icewm#394]
Just upgraded to Fedora 31 with IceWM 1.6.2.

If I resize the window of a remote desktop session (IceWM running in the far end), the desktop itself and maximized windows resize as expected, but the taskbar remains in its original location. There is even empty space at the bottom of the screen for the taskbar, but it is not drawn there. 

Problem is the same with both NoMachine and VNC sessions.

Screenshot attached after starting a session, maximising an xterm and then making the NoMachine window slightly larger.

This used to work just fine with the previous IceWM in Fedora (1.3.8)

![Screenshot at 2019-10-31 16-03-44](https://user-images.githubusercontent.com/38290771/67953753-66ff9d80-fbf8-11e9-8776-49b1a7cae60b.png)

**Comment by covex** [comment]
Have the same issue as a workaround just go to icewm/Window Manager/icewm or ctrl+alt+del + restart icewm.

**Comment by gijsbers** [comment]
Does commit 5968d9f work for you?

**Comment by mihkelader** [comment]
Yes, taskbar moves correctly with IceWM built from current Git sources.

**Comment by bbidulock** [comment]
@mihkelader please close this issue if it is resolved.
