### ISSUE TITLE
icewm-1.6.x - xterm titles often get blanked out? (turned out to be a bug in xterm itself)

### ISSUE THREAD

**Issue by apocalyptech** [bbidulock/icewm#395]
I've noticed after an upgrade from icewm-1.5.5 to icewm-1.6.2 that my xterms are often having their titles completely cleared out.  One easy and reliable way to reproduce it for me is to start a `ping localhost` and then hit Ctrl-C.  The title will get blanked out when I hit Ctrl-C, and come back when I hit enter (which would make a bit of sense since `$PROMPT_COMMAND` would get re-applied once the fresh command prompt is drawn).

My `$PROMPT_COMMAND` is:

    printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"

Here's a short gif showing the behavior above:
![window_title](https://user-images.githubusercontent.com/443343/68408254-a4a97c80-014a-11ea-9db3-18ea5b60f559.gif)

I'm not sure exactly when this started happening in the 1.6.x line; could've been 1.6.0, 1.6.1, or 1.6.2.

(A bit offtopic, but is this still the best place for icewm issues?  I've often been a bit confused by the relationship between this repo and the ice-wm-owned repo, esp. since that one seems to have the 1.6.2 commit but this one doesn't?  Regardless, thanks for keeping this WM alive; I've been using this thing since the early 2000s.)

**Comment by bbidulock** [comment]
What version of xterm?

**Comment by apocalyptech** [comment]
Looks like I'm on xterm patch 349:

    $ uxterm -v
    XTerm(349)

(*Edit:* I'd said 348 at first, but realized I'd run that check on a system which hasn't gotten those updates yet.  It's 349 on the icewm-1.6.2 machine which was seeing the problem.)

Further edit, actually: well, heh, looks like downgrading that system back to 348 appears to solve the problem, actually, which would seem to point to this being an xterm issue rather than icewm, eh?  :)  I'll have to see if 350 clears things up at all.  Apologies for the spurious bugreport!  I'll update this for the record if I can find out more about it from that angle.

Final edit: Bah, yeah, xterm-350 clears it up, looks like it was just a problem in that one xterm version.  Sorry for the bother, again!  Hadn't realized that xterm was still seeing regular updates, tbh.

**Comment by bbidulock** [comment]
I saw it go by a few times on Arch Linux, which is on 350, so I asked.  Figured that no window manager would clear the title bar in response to an interrupt in a terminal unless the terminal told it to.  Anyhoo: problem solved.  Don't worry about reporting things like this: next time it could be icewm at fault.
