### ISSUE TITLE
icewm-keys: mention how to unbind a key

### ISSUE THREAD

**Issue by jidanni** [bbidulock/icewm#398]
icewm-keys man page only mentions how to bind keys. Also add an example
of how to unbind a key, so it gets passed through uncaught by icewm.

Also mention on both icewm-keys and icewm-preferences that both can bind
(and unbind) keys, but with different syntax.

**Comment by gijsbers** [comment]
1. This is mistaken since there is no way to unbind a key.

2. What they bind to is unrelated, therefore this is also mistaken.

**Comment by jidanni** [comment]
OK, then please on both man pages mention that there is no way to unbind keys.
Also I wonder how the workaround in
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=944414
is supposed to work.

**Comment by gijsbers** [comment]
You can define a key to be the empty string in `preferences`. Then it is not bound.

**Comment by bbidulock** [comment]
It is now mentioned in the icewm-preferences.5 manual page under EXAMPLES.

**Comment by jidanni** [comment]
OK, I can confirm
```
$ grep Ke .icewm/preferences
KeySysWinMenu=
```
allows Shift+Esc to pass through to Chrome unscathed!
