### ISSUE TITLE
man pages: FILES repeated in SYNOPSIS

### ISSUE THREAD

**Issue by jidanni** [bbidulock/icewm#399]
On the man pages regarding the FILES section, e.g.,

```
FILES
       Locations for the keys file are as follows:

        $ICEWM_PRIVCFG/keys
        $XDG_CONFIG_HOME/icewm/keys
        $HOME/.icewm/keys
        /etc/icewm/keys
        /usr/share/icewm/keys
```
- Please don't repeat them again in the SYNOPSIS section. In fact maybe one doesn't need a SYNOPSIS section.
- Mention what order they are read in, or if one is found, the others are
not read, etc.

**Comment by gijsbers** [comment]
Please provide more detailed reasoning as to why.

**Comment by bbidulock** [comment]
The order that configuration files are searched are listed in FILES section of icewm(1).  It also says in icewm(1) FILES section that the first file found is used.  Nevertheless, I added the note to the FILES sections in section 5 manual pages.

With regard to the SYNOPSIS section, section 5 manual pages require a SYNOPSIS section that gives the location of the file that it describes to conform to BSD manual page standards, so it will stay.

**Comment by jidanni** [comment]
OK!
