### ISSUE TITLE
The Gimp crashes by copying

### ISSUE THREAD

**Issue by PericlesSyC** [bbidulock/icewm#402]
Using icewm - and only icewm - the gimp crashes when copying a selection. It does not matter whether Ctrl-C or the menu is used for copying.

The following output appears on the console:

> The program 'gimp' received an X Window System error.
> This probably reflects a bug in the program.
> The error was 'BadWindow (invalid Window parameter)'.
>   (Details: serial 182033 error_code 3 request_code 18 minor_code 0)
>   (Note to programmers: normally, X errors are reported asynchronously;
>    that is, you will receive the error a while after causing it.
>    To debug your program, run it with the --sync command line
>    option to change this behavior. You can then get a meaningful
>    backtrace from your debugger if you break on the gdk_x_error() function.)
> 
> (script-fu:4504): LibGimpBase-WARNING **: 23:24:09.010: script-fu: gimp_wire_read(): error

With KDE, XFCE, LxQt or Fluxbox this error does not occur.

The error is reproducible. It does not always occur with the first copy, but often with the second such action.

**Comment by gijsbers** [comment]
Works fine here.

**Comment by bedna-KU** [comment]
I tried it with big pictures 5893x2946 but not have this issue.
Your version of IceWM? (icewm -V)

**Comment by PericlesSyC** [comment]
IceWM 1.6.3

**Comment by bedna-KU** [comment]
Please distribution name and version.

**Comment by PericlesSyC** [comment]
OS: Arch Linux 
Kernel: x86_64 Linux 5.4.6-arch3-1
Resolution: 1920x1080
CPU: AMD Athlon X4 860K Quad Core @ 4x 3.7GHz
GPU: AMD/ATI Cedar [Radeon HD 5000/6000/7350/8350 Series

**Comment by gijsbers** [comment]
`gimp --version` ?

**Comment by gijsbers** [comment]
Also, could you run it with `valgrind gimp --sync` ?

**Comment by PericlesSyC** [comment]
GNU Image Manipulation Program Version 2.10.14
git-describe: GIMP_2_10_12-511-ga4f55d6c7e
C compiler:
	Using built-in specs.
	COLLECT_GCC=gcc
	COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/lto-wrapper
	Target: x86_64-pc-linux-gnu
	Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto gdc_include_dir=/usr/include/dlang/gdc
	Thread model: posix
	gcc version 9.2.0 (GCC) 

verwendet babl Version 0.1.72 (gebaut gegen Version 0.1.72)
verwendet GEGL Version 0.4.18 (gebaut gegen Version 0.4.18)
verwendet GLib Version 2.62.4 (gebaut gegen Version 2.62.2)
verwendet GdkPixbuf Version 2.40.0 (gebaut gegen Version 2.40.0)
verwendet GTK+ Version 2.24.32 (gebaut gegen Version 2.24.32)
verwendet Pango Version 1.44.7 (gebaut gegen Version 1.44.7)
verwendet Fontconfig Version 2.13.91 (gebaut gegen Version 2.13.91)
verwendet Cairo Version 1.17.3 (gebaut gegen Version 1.17.3)

Have started it with valgrind and tried to reproduce the error. It did not occur. Even after frequent copying.

Then I started Gimp normally and even then the error did not occur anymore.

I will watch this. And report if it occurs again.

It may be due to a system update yesterday.
