### ISSUE TITLE
Can't compile icesh 1.6.4

### ISSUE THREAD

**Issue by zaza42** [bbidulock/icewm#403]
```
[ 19%] Linking CXX executable ../icesh
/usr/bin/ld: CMakeFiles/icesh.dir/icesh.cc.o: in function `IceSh::spy()':
icesh.cc:(.text+0x95b3): undefined reference to `walltime()'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/icesh.dir/build.make:144: icesh] Error 1
make[1]: *** [CMakeFiles/Makefile2:210: src/CMakeFiles/icesh.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Debian sid x86_64
gcc version 9.2.1 20200104 (Debian 9.2.1-22)

**Comment by zaza42** [comment]
Ok, i've could fix it with copy some lines from `ytimer.cc`:
```
/*
 * Note that POSIX.1-2008 marks gettimeofday as obsolete,
 * recommending the use of clock_gettime instead.
 */
static inline timeval timeofday() {
    timeval tv;
    gettimeofday(&tv, 0);
    return tv;
}

/*
 * Convert timespec to timeval.
 */
#if _POSIX_TIMERS >= 200112L
static inline timeval fromspec(timespec ts) {
    return (timeval) { ts.tv_sec, ts.tv_nsec / 1000L };
}
#endif

/*
 * Give real wall clock time in seconds + microseconds.
 */
timeval walltime() {
#if _POSIX_TIMERS >= 200112L
    timespec ts;
    if (clock_gettime(CLOCK_REALTIME, &ts) == 0)
        return fromspec(ts);
#endif
    return timeofday();
}

```

**Comment by gijsbers** [comment]
It compiles without problems on Debian 10 buster and on Ubuntu 16.04,
if you use configure. Maybe the cmake build is broken, again.

**Comment by gijsbers** [comment]
Ah right. In the file `src/CMakeLists.txt` look for the line:

    ADD_EXECUTABLE(icesh${EXEEXT} icesh.cc misc.cc mstring.cc ref.cc yarray.cc)

Append `ytimer.cc`. That would be easier than what you try to do.

**Comment by zaza42** [comment]
Thanx, it solved the problem cleanly!

**Comment by tim77** [comment]
So what is real fix? Fallback to autotools?

**Comment by E5ten** [comment]
I think ytimer.cc needs to be added as an icesh source in cmake.

**Comment by zaza42** [comment]
In `src/CMakeLists.txt` find the relevant line and add `ytimer.cc` at the end, like:
`ADD_EXECUTABLE(icesh${EXEEXT} icesh.cc misc.cc mstring.cc ref.cc yarray.cc ytimer.cc)
`

**Comment by tim77** [comment]
Great. Thank you. Anyone interested upstreaming PR with this? ☺️

**Comment by zaza42** [comment]
It's already in other repo's patch: https://github.com/ice-wm/icewm/commit/6b1721fec3e5608327e553c43f3fd8f761cb66a7
I wish it will be merged soon here.

**Comment by tim77** [comment]
Thanks a lot again.

**Comment by tim77** [comment]
TBH this two separate GH repos and issue trackers confusing. Same issue here https://github.com/ice-wm/icewm/issues/6
