### ISSUE TITLE
icesh: setGeometry by percentage

### ISSUE THREAD

**Issue by E5ten** [bbidulock/icewm#404]
It would be nice to be able to provide percentages to icesh for setting the geometry of a window. Maybe there could even be a flag to factor in the taskbar into that percentage, so that a setGeometry call specifying 50% as the height would make the window half the height of the screen not including the taskbar as opposed to including?

**Comment by gijsbers** [comment]
`icesh sizeto 50% 50%` already does that? Or you want setGeometry also to accept percentages?
