### ISSUE TITLE
Override window-manager key bindings via config files?

### ISSUE THREAD

**Issue by coleifer** [bbidulock/icewm#406]
Is it possible to override the window-manager keybindings via the config files? For example instead of using Alt+Tab and Alt+Shift+Tab to switch focus forward/backward, I would like to use Alt+l and Alt+h.

I did not see this documented anywhere. Please let me know if this is possible!

**Comment by gijsbers** [comment]
`man icewm`. Search for `Alt\+Tab`.

**Comment by coleifer** [comment]
I understand what alt+tab does by default. What I'd like to do is use a different key combination for the same effect.

**Comment by gijsbers** [comment]
```man
KEYBOARD SHORTCUTS
       icewm supports a large number of hotkeys to activate some behaviour with a
       single key combination.  These are all configurable in the preferences
       file.  Here we give their default values, followed by their preferences
       names and short descriptions of their effect:

        ...

        "Alt+Tab"
           "KeySysSwitchNext" opens the "QuickSwitch" popup (see "INPUT FOCUS")
           and/or moves the selector in the "QuickSwitch" popup.

       "Alt+Shift+Tab"
           "KeySysSwitchLast" works like "KeySysSwitchNext" but moving in the
           opposite direction.

```

**Comment by coleifer** [comment]
Shit, thanks I missed the bit about 

>These are all configurable in the preferences file.

Thanks!
