### ISSUE TITLE
How to define cfg dir with Cmake?

### ISSUE THREAD

**Issue by tim77** [bbidulock/icewm#407]
Hello. If i build with `-DCFGDIR=/etc/icewm` for example, nothing actually changes and all configuration files installed in `/usr/share/icewm/` even if i see during configuration process:

```ini
-- PACKAGE => icewm
-- VERSION => 1.6.4
-- DATADIR => /usr/share
-- LIBDIR => /usr/share/icewm
-- LOCDIR => /usr/share/locale
-- DOCDIR => /usr/share/doc/icewm
-- CFGDIR => /etc/icewm
```

**Comment by Code7R** [comment]
If I remember correctly (and co-maintainers here might correct me), this define only says where the binary look for the configuration files, they first go to the user config directories, then to the system admins config directory (like /etc/icewm) and then to the default configuration directory.

Or did you expect that it will put stuff into /etc/? That is quite dangerous to do from the regular build systems, might kill user's configuration!

**Comment by tim77** [comment]
> Or did you expect that it will put stuff into /etc/? That is quite dangerous to do from the regular build systems, might kill user's configuration!

Of cource i want put stuff into `/etc`, proper place for config files. And there is nothing dangerous at least in Fedora since all this handled by RPM and `%config(noreplace)` :P 

https://docs.fedoraproject.org/en-US/packaging-guidelines/#_configuration_files

**Comment by gijsbers** [comment]
CFGDIR is meant for local customized system defaults. Nothing is installed to it by default.

**Comment by tim77** [comment]
I'll try to tinker more with this. But users reporting that their old previous IceWM version stored config files in `/etc/icewm` And if i remember correct i did this as well with Autotools so yes, this seems like just Cmake issue.

**Comment by gijsbers** [comment]
@tim77 Could you perhaps have a look at `icewm-set-gnomewm`? Does this work under Fedora? What is the proper way under Fedora to make icewm the default window manager?
