### ISSUE TITLE
set exact taskbar height

### ISSUE THREAD

**Issue by E5ten** [bbidulock/icewm#408]
It would be very useful to have a setting to specify the desired taskbar height in pixels.

**Comment by gijsbers** [comment]
If that is so then it is very easy for you to provide clear motivations as to why.

**Comment by E5ten** [comment]
For starters, the closest I can get to my desired taskbar height using the only method I know of, adjusting the small icon size, is pretty far from what I actually want. But even more importantly, the height I get using that method is an odd number, so no matter what I do, scripted tiling leads to 1 pixel overlap in some place or another. It's obviously not a very big deal, but it does bug me a bit and I'd really like to be able to avoid it.

**Comment by gijsbers** [comment]
Maybe two cases need to be considered, at least:
User wants to limit the taskbar height to a small maximum.
User wants to increase the taskbar height to a larger minimum.
Since the tray uses 24x24 icons they need to be at least 25 or so?
Or the tray must fall back to a smaller icon size if needed?

**Comment by cheapy** [comment]
I believe we can use the monitor graph height to control the taskbar height in preferences or prefoverride.  I believe this now can be set in the theme, too.  Maybe I'm underthinking it...

TaskBarGraphHeight=36
