### ISSUE TITLE
Icewm 1.3.8 title bar transparent 

### ISSUE THREAD

**Issue by SolisX** [bbidulock/icewm#41]
Hello Everyone,

This bug does not appear in icewm-1.2.38pre2. I believe it started with icewm 1.3.0.

The title bar is transparent when the xpm width is 1. Also some of the icons set by the winoptions just go to default icons. This a screen shot of what it looks like.

http://s15.postimg.org/ackxua8e3/icewm.png

I have no problem like this when i use icewm 1.2.38pre2.

BTW: I'm running Slackware 14.1 Multilib. Nvidia GeForce 430GT Driver 340.65.

**Comment by bbidulock** [comment]
Try turning off your compositor and see if they re-appear.

**Comment by SolisX** [comment]
Hello Brian,
I don't have any compisitor running. It's a bug with icewm 1.3.0+. I have no problem with thetitle bar on icewm 1.2.38pre2.

```
 On Saturday, October 17, 2015 5:44 PM, Brian Bidulock <notifications@github.com> wrote:
```

 Try turning off your compositor and see if they re-appear.—

**Comment by bbidulock** [comment]
Then how are your terminal backgrounds transparent?  Pseudo-transparency?
What version is this that you have running?  Is it a release version from here or a git version?
What options are being applied when configuring and compiling the package?  Particularly shaped-decorations option?
Is this a theme released with icewm?  Custom theme?  Can you share the theme files and xpms?
What happens if you make the XPMs 2 pixels wide?  10 pixels?
What happens if you shut off rounded corners?

**Comment by SolisX** [comment]
Hello Brian,
I just compiled 1.3.11.1 with the instructions found in github. Yes shaped-decorations was on.This a theme i made myself. My themes can be found in here
Solisx7's profile Box-Look.org
|   |
|   |  |   |   |   |   |   |
| Solisx7's profile Box-Look.orgSolisx7's profile Box-Look.org Community Portal for FVWM Openbox Blackbox Fluxbox WindowMaker Themes Linux Multimedia Graphic Development Utilities |
|  |
| View on box-look.org | Preview by Yahoo |
|  |
|   |

 If i change the size of all xpms to a width of 2 then the title bar looks properly. Here is a screenshotof icewm 1.3.11.1  running roxterm with my illuminate-ice theme.

```
 On Saturday, October 17, 2015 10:01 PM, Brian Bidulock <notifications@github.com> wrote:
```

 Then how are your terminal backgrounds transparent? Pseudo-transparency?
What version is this that you have running? Is it a release version from here or a git version?
What options are being applied when configuring and compiling the package? Particularly shaped-decorations option?
Is this a theme released with icewm? Custom theme? Can you share the theme files and xpms?
What happens if you make the XPMs 2 pixels wide? 10 pixels?
What happens if you shut off rounded corners?—

**Comment by SolisX** [comment]
Hello Brian,

Here is the screen shot of icewm 1.3.11.1 compiled with the instructions on github. Using roxterm
for transparency on terminal.

http://s14.postimg.org/5anbmp1rk/icewm.jpg

Also my themes can be found here:
http://box-look.org/usermanager/search.php?username=Solisx7&action=contents

**Comment by bbidulock** [comment]
Is there a problem simply making your xpms 2 pixels wide?  It strikes me as a better solution than rooting around in the code and possibly introducing regressions or new defects...

**Comment by SolisX** [comment]
Hello bbidulock,
The only problem with that is that i would have to redo all 18 icewm themes i created.

**Comment by bbidulock** [comment]
And nice themes they are.  Most of the ones that come with icewm are horrid.

**Comment by SolisX** [comment]
Hello bbidulock,

I made the width of the illuminate-ice theme 2 but i noticed that the taskbar for some
reason now needs to be 26 px instead of my original 25 px otherwise i get an extra line.

BTW: Thanks some of the themes are ports i made of ones i liked and a few are my own.

**Comment by SolisX** [comment]
Hello bbidulock,

The extra line in the taskbar appears only when i set the look to gtk or pixmap. If i set the look to
flat or metal it does not have and exta line.

**Comment by SolisX** [comment]
Hello Bbidulock,

Just wanted to mention that if i add the taskbarbg.xpm to gradients in the default.theme seems to
fix the taskbar having an extra pixal.

**Comment by bbidulock** [comment]
Has this issue been resolved?

**Comment by SolisX** [comment]
Yes i would close this issue.
