### ISSUE TITLE
toolbar menu not updated as fast as in menu

### ISSUE THREAD

**Issue by martintxoz** [bbidulock/icewm#411]
Hello

I'm in Debian Testing, with Icewm 1.6.4-1.

I'm testing a setup for the removable media (usb sticks) similar to MS Windows, with a menu in the toolbar for unmount the automatically mounted medias. For this I copied and altered the scripts iceplaces.sh and icefb.sh from here:
http://www.murga-linux.com/puppy/viewtopic.php?t=87536&sid=14edee45ad1d48f74e1a73d973cc2ca7

I put in this report 2 scripts for test it, these are test1.sh and test2.sh, and you need to put these in your executable path, like /usr/local/bin... 

/usr/local/bin/test1.sh:
```
 #!/bin/bash
 if [ ! "$(mount | grep '/media/')" = "" ] ; then
  for removable in $(mount | grep '/media/' | cut -f 3 -d ' ')
   do
   echo "menuprogreload $(basename $removable) \"/usr/share/icons/nuoveXT2/48x48/devices/gnome-dev-removable-usb.png\" 0 test2.sh ${removable}"
  done
 fi
```

/usr/local/bin/test2.sh:
```
 #!/bin/bash
 DIR="$1"
 [ "$DIR" = "" ] && DIR=/
 self=$(realpath $0)
 cat << EOF
 prog "Unmount $(basename $DIR)" /usr/share/icons/nuoveXT2/48x48/devices/gnome-dev-removable-usb.png /usr/local/bin/devmon-unmount-notifysend.sh "$DIR"
 prog "$DIR filemanager" /usr/share/icons/nuoveXT2/48x48/places/folder.png pcmanfm "$DIR"
 prog "$DIR terminal" utilities-terminal lxterminal --working-directory="$DIR"
 menu hidden folder {
 EOF
 find "$DIR" -maxdepth 1 -mindepth 1 -type d -name '.*'  | sort | while read SUBDIR
 do
  MENUPROG="$(basename "$SUBDIR")"
  echo "menuprogreload \"$MENUPROG\" folder 0 $self \"$SUBDIR\""
 done
 find "$DIR" -maxdepth 1 -mindepth 1 -type f -name '.*'  | sort | while read FILE
 do
  NAME="$(basename "$FILE")"
  echo "prog \"$NAME\" text-x-preview xdg-open \"$FILE\""
 done
 cat << EOF
 }
 separator
 EOF
 find "$DIR" -maxdepth 1 -mindepth 1 -type d ! -name '.*'  | sort | while read  SUBDIR
 do
  MENUPROG="$(basename "$SUBDIR")"
  echo "menuprogreload \"$MENUPROG\" folder 0 $self \"$SUBDIR\""
 done
 find "$DIR" -maxdepth 1 -mindepth 1 -type f ! -name '.*'  | sort | while read FILE
 do
  NAME="$(basename "$FILE")"
  echo "prog \"$NAME\" text-x-preview xdg-open \"$FILE\""
 done
```

With this, you can put menus in the toolbar or in the Icewm menu, for unmount and browse the removable devices. For this to happen, put in ~/.icewm/toolbar or ~/.icewm/menu this:
`menuprog "Removable" /usr/share/icons/nuoveXT2/48x48/devices/gnome-dev-harddisk-usb.png /usr/local/bin/test1.sh`

But problem is this. If I put this in the menu file, it works OK: when I plug an usb stick it appears in the menu, and when I remove it, it disappears... OK.

But in the toolbar this is not working the same. When I plug the stick sometimes appears in the toolbar menu in this moment, and sometimes not, it delays 1 minute or so (I don't count it). And when I unmount it, in the toolbar remains the menu for a minute or so always, when in the menu it disappears at this moment.

So, I think that it will be interesting that the two menus works the same, and updates itself in the same manner.

Many thanks for this spectacular windowmanager. Greetings. Martintxo.

**Comment by gijsbers** [comment]
Could you try using `menuprogreload`?

Could you edit your previous text and use the three backticks like explained here:
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code
https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by martintxoz** [comment]
Many thanks for the fast response.
I try with this code in both the menu and the toolbar:
`menuprogreload "Removable" /usr/share/icons/nuoveXT2/48x48/devices/gnome-dev-harddisk-usb.png 0 /usr/local/bin/test1.sh`
But the result is the same or worse. If in menu file, the update is immediate. But in the toolbar file, there is not update in the unmount action. 
(I try now to edit my previous post)

**Comment by gijsbers** [comment]
Not 0 please. A little bigger. Please experiment with different values.

**Comment by martintxoz** [comment]
Oh yea!!!
Yes, it is working good now. I put in the toolbar file:
`menuprogreload "Removable" /usr/share/icons/nuoveXT2/48x48/devices/gnome-dev-harddisk-usb.png 1 /usr/local/bin/test1.sh`

With 1 as this valor, it is updating at the moment of mount or unmount. 

I try with 10 too (and restart icewm), but in the unmount I can see a lag for the menu to disappear. But with 1 is OK!!

Many thanks!!

**Comment by gijsbers** [comment]
Good! Thanks for letting us know!
If you are happy then you can close this issue.

**Comment by martintxoz** [comment]
Yes. Happy!! :-D
