### ISSUE TITLE
Title-bar does not span whole screen for maximized XTerm

### ISSUE THREAD

**Issue by DieSpinne** [bbidulock/icewm#413]
1. Open XTerm. 

2. Maximize it.

Unless the width of your screen is a multiple of the character width of the XTerm font, there will be a gap between the window and the right edge of the screen (and another between the window and the bottom edge / taskbar, for similar reason). This is a well known characteristic of XTerm and has been mentioned [in Reddit](https://www.reddit.com/r/linuxquestions/comments/6as35j/terminal_windows_not_fully_maximized/?utm_source=share&utm_medium=web2x). Those gaps may be partially or completely filled by your window border if you have one. 

What really annoys me is that, under those circumstances, **the title-bar close button does not touch the upper-right corner**, because the title-bar only extends to the width of the window. So you can't quickly reach the button with the mouse pointer by moving it to the corner, instead once reaching the corner you need to move a few pixels to the left to reach the button. So

**I propose that the title-bar spans the whole screen when a window is maximized.** 

Now, there is a interesting bug.

3. Enter fullscreen for the XTerm window, not via icewm fullscreen but XTerm built-in fullscreen (Ctrl-LeftClick, Fullscreen option).

4. Leave fullscreen likewise.

Voilá! After last step I have exactly what I want, the title-bar spans whole screen and I can easily click close button.

**Comment by gijsbers** [comment]
Step 4 is due to xterm, which you can see if you do `icesh -c xterm spy`:

     WM_NORMAL_HINTS PSize(1920,1200) MinSize(32,29) Inc(10,23) Base(22,6)

Examine the various Maximize options in icewm preferences.
You may like `ConsiderSizeHintsMaximized=0`.

**Comment by Entebate** [comment]
Unbelievable, you Icewm guys have thought of every detail! That does solve it!

**Comment by Code7R** [comment]
Maybe a topic for the FAQ?

**Comment by gijsbers** [comment]
Would he have read it? ;-)

**Comment by DieSpinne** [comment]
Honestly I would never think my question would be a frequent asked one. But maybe the search engine would have taken me there.
