### ISSUE TITLE
Tray icons inherit background from ColorNormalTaskBarApp instead of ColorDefaultTaskBar

### ISSUE THREAD

**Issue by DieSpinne** [bbidulock/icewm#414]
If I put an application in tray by setting it in `winoptions` file, the background of the square that contains it will be of color `ColorNormalTaskBarApp`. Is there any way to make it the same color of the taskbar, `ColorDefaultTaskBar` (just as other tray applications which I have not set in `winoptions`, such as _telegram_ and _nm-applet_)?

![Tr](https://user-images.githubusercontent.com/62444221/77225632-6dfb5e00-6b4f-11ea-8f43-053f49b85e4a.png)

**Comment by gijsbers** [comment]
Create a taskbuttonbg.xpm and keep ColorNormalTaskBarApp the same as ColorDefaultTaskBar.

**Comment by DieSpinne** [comment]
Thank you for the reply. I created a xpm (just an orange square), but still the background color `ColorNormalTaskBarApp` is visible around the icon.

![SC](https://user-images.githubusercontent.com/62444221/77266116-51f5da80-6c7d-11ea-9194-64d9d601ed48.png)

If i make `ColorNormalTaskBarApp` the same as `ColorDefaultTaskBar`, then the taskbar color will be the same as the rectangles representing the inactive windows. I mean, the reason to make both as separate options would be lost. But I think there is no other option, right?

**Comment by gijsbers** [comment]
Right, it is all we can do now.

**Comment by DieSpinne** [comment]
I solved my problem with an external tool, `alltray`. It will correctly display the icon in systray, as can be seen below.

![AB](https://user-images.githubusercontent.com/62444221/80863722-8f725e00-8c54-11ea-9152-fa8617c13a3d.png)

**Comment by gijsbers** [comment]
That is a cool program! Maybe it is also useful for issue #382 ?

**Comment by Entebate** [comment]
Very cool indeed, and if you look at the tray, there is no visible difference between icons in `alltray` and icons in standard Icewm tray.

About #382, it may be useful for that too, because I tested it with dynamical icons and it worked as a charm. I'll leave a comment there too.
