### ISSUE TITLE
Autohide no longer working with Double Height Taskbar in 1.6.5

### ISSUE THREAD

**Issue by cheapy** [bbidulock/icewm#415]
Autohide still works if DoubleHeight is off, but when I turn DoubleHeight on, the taskbar no longer comes up or hides when expected.  It was working correctly on 1.6.4.  This is on antiX-19.1_x64 stable (based on Debian).  I haven't tried it on any other distro at this point.

**Comment by gijsbers** [comment]
This may have something to do with the fix for #412, but sofar it works fine for me. Can't reproduce it yet. If you use a standard theme like CrystalBlue and a default preferences file with only TaskBarAutoHide=1 and TaskBarDoubleHeight=1 changed, does it still happen?

**Comment by cheapy** [comment]
i will test with a more normal preferences file and toolbar from debian testing, which has the icewm 1.6.5 that antiX 19.2 is based on.  Changing to metal2 or default didn't fix it.  Thanks for trying it.  Maybe its just something in my settings.

**Comment by cheapy** [comment]
I upgraded and then copied the entire debian testing setup, from /usr/share/icewm to ~/.icewm on my antiX19 system and using default and crystal blue themes, autohide works with doubleheight off, and stops working if doubleheight is turned on.  I will go back and try changing just those 2 settings on the now up to date debian testing system to see if it works there or not.  I looked at a repo site and it said Manjaro has 1.6.5 in its current stable version, also PCLinuxOS and I think Mandriva Cauldron.  I will get the current Manjaro installed and try it there if it doesn't work on Debian Testing.

**Comment by cheapy** [comment]
I had the same problem with Debian testing.  I'm downloading Manjaro Gnome now, and will add IceWM to it, and try there, next.

I am using the Preferences option from the menu, then saving it to change it rather than editing the preferences file.  I will try it via editing...

**Comment by gijsbers** [comment]
OK I see it now. Maybe it was something in my own settings. I'll look into it...

**Comment by gijsbers** [comment]
This should do it. Thanks for reporting @cheapy .

**Comment by cheapy** [comment]
I got it compiled and tested and the problem is gone.  Thanks much for the Fix :)

**Comment by gijsbers** [comment]
@cheapy I made several improvements to TaskBarAutoHide and TaskBarDoubleHeight. Can you test them? Since you are the only one I know who uses this combination.

**Comment by cheapy** [comment]
Sure, I will test after work tonight :)

**Comment by gijsbers** [comment]
Any luck?

**Comment by cheapy** [comment]
Sorry, Had forgotten.  I just built it and installed it fresh, now and it looks to be working fine
![screenshot-2022Jan19_174313](https://user-images.githubusercontent.com/7473967/150236333-2f778f1c-8399-4ffd-a366-fa07499ee04b.jpg)
