### ISSUE TITLE
Add keyboard option to raise taskbar

### ISSUE THREAD

**Issue by cheapy** [bbidulock/icewm#416]
There is an option to collapse the taskbar, which works fine, and when the taskbar is hidden, moving the mouse over it raises it just fine.

But there are people that like to be able to do everything from the keyboard, and also those who don't know the taskbar is hidden, it would be nice to have the ability to program a key to raise the toolbar/taskbar to match the collapse taskbar key.  

KeySysRaiseTaskBar=""

Obviously this is not anything major, but would be nice to have on my autohiding toolbar/taskbar driven setup.

BTW, its very cool/efficient for me because I DO know its hiding there, and I added a clue to my conky and my IceWM keykoard help screen
![icewm-antiXbc19 2_1](https://user-images.githubusercontent.com/7473967/77987629-f7ddc080-72df-11ea-8be9-2122e904f29b.jpg)
 :)

**Comment by gijsbers** [comment]
Could this perhaps be accomplished by defining a key in .icewm/keys to move the mouse to the bottom of the screen?

    key "Alt+v"   xdotool mousemove 899 899

**Comment by cheapy** [comment]
I will give that idea a try, thanks

**Comment by cheapy** [comment]
I'm just using Ctrl+Esc to pop up the menu when the mouse won't do it, which also brings up the toolbar
