### ISSUE TITLE
[1.6.5] partial border missing glitch while moving active window

### ISSUE THREAD

**Issue by zaza42** [bbidulock/icewm#417]
A little annoying bug came with release 1.6.5. While moving the active window on foreground, the background windows lost their near borders for some moments. I had no similar glitches with 1.6.4 or earlier versions. I've tried the stock 1.6.5-1 from Debian sid, and also tried my own compiled binary. The effects are the same.

Here you are some pictures + videos:
![icewm165bug1](https://user-images.githubusercontent.com/16356124/78218072-7b083d80-74bd-11ea-8d41-9ba069a71c12.png)
![icewm165bug2](https://user-images.githubusercontent.com/16356124/78218082-7f345b00-74bd-11ea-810a-2ac9fad28792.png)
![icewm165bug3](https://user-images.githubusercontent.com/16356124/78218090-8196b500-74bd-11ea-98ac-a7f9606875f8.png)

[1.6.4 demonstration video](https://0x0.st/iMDd.mp4)
[1.6.5 demonstration video](https://0x0.st/iMDn.mp4)

Debian sid, x86-64, Linux 5.5.13-xanmod1, xserver 1.20.8 (tried with also 1.20.7)

**Comment by gijsbers** [comment]
What theme do you use? This is probably due to commit a287348f866c19d11d73107015b114404387db97. We tested it but didn't find any such glitches. Is your graphics a bit slow or underpowered somehow?

**Comment by zaza42** [comment]
Yes, this was that commit. I reverted, recompiled, and the glitch has gone away.
I have no such glitch with IceWM on my good old p233mmx laptop (fujitsu b110) with 64mb of ram (before 1.6.5), but my main computer is Intel i5-2520M (4) @ 2.501GHz, AMD ATI Radeon HD 6400M/7400M, 8G ram. And -almost- nothing ran in the background during the tests.

Here is my custom theme
[icewm-theme-DC-macdebian.tar.gz](https://github.com/bbidulock/icewm/files/4422244/icewm-theme-DC-macdebian.tar.gz)

**Comment by zaza42** [comment]
For testing purposes I've created a new user and using the default options with default theme, and the effects are the same on 1.6.5. ;-<
[video: 1.6.5 window glitch with a fresh user + very default config](https://0x0.st/iMF_.mp4)

Software versions:
- mesa 20.0.3 and 20.0.2 also
- xorg 1.20.8 and 1.20.7
- xserver-xorg-video-radeon 1:19.1.0
- libdrm-radeon1 -  2.4.100

**Comment by gijsbers** [comment]
I removed the small delay to repaint immediately when the expose arrives. Still can't reproduce it, so we depend on you to notice any such effects in the future :-)

**Comment by zaza42** [comment]
Ok. This was the fix. I'm happy again!
[example video](https://0x0.st/iMCi.mp4)

THANX for the rapid reply & fix!
