### ISSUE TITLE
How do i theme logout dialog buttons?

### ISSUE THREAD

**Issue by blue-devil-93** [bbidulock/icewm#419]
Hi, as seen in the screenshot.
Icewm works very good in virtualbox and i really like it. 
However is there a way to theme these logout buttons?

1) make the text readable
2) insrease spacing and button bg.

![icewm-question](https://user-images.githubusercontent.com/59343188/79116518-fce34b00-7d88-11ea-82a5-171b394c66b9.png)

**Comment by gijsbers** [comment]
Yes I think so. Other themes do it. [See](https://ice-wm.org/themes/#other-buttons-and-backgrounds).
