### ISSUE TITLE
need NetworkStatusDevice="enx*" wildcards or some other way to deal with today's million device names

### ISSUE THREAD

**Issue by jidanni** [bbidulock/icewm#42]
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=801867

Nowadays one needs ~/.icewm/preferences :
NetworkStatusDevice="enxf258d44c275c enx8efaba64c25e enx2e5e0fa75f52 ... ppp0 wlan0"

I.e., thousands and thousands of enx\* devices listed,
and you never know what the next one will be called!

**Comment by bbidulock** [comment]
I think this is more of a system configuration problem than an issue with icewm.  Check out the ifrename capability <code>man 5 iftab</code> to rename your interfaces to something more predictable.  Another approach is suppressing the fancy naming of interfaces by overriding the udev rules that generate them.

**Comment by jidanni** [comment]
You are asking me to override Debian defaults and install obsolete
packages?
E: Unable to locate package iftab
http://bethesignal.org/blog/2008/04/16/this-is-progress-iftab-vs-udev/
Wouldn't it be better for you to update icewm to deal with the new standard?

**Comment by bbidulock** [comment]
ifrename is part of the wireless tools package for linux, which is current.
Please propose a patch if you want an update.

**Comment by jidanni** [comment]
I am just a simple user.
All I know about are workarounds.
One might be:
1) user connects device; then
2) user runs shell script that determines the enx\* number, e.g., by
scraping /sbin/route output. script rewrites the NetworkStatusDevice=
line in ~/.icewm/preferences, and restarts icewm.

Idea 2: Often there is only one interface in /sbin/route output. So maybe
icewm could please just monitor all the devices in there (via
NetworkStatusDevice=\* or NetworkStatusDevice=ALL), and provide an
additional IgnoredNetworkStatusDevice= variable to instead exclude
devices.

**Comment by bedna-KU** [comment]
ip addr | grep enx.*:
