### ISSUE TITLE
How to restore minimized windows from systray?

### ISSUE THREAD

**Issue by zaza42** [bbidulock/icewm#423]
I couldn't find a method to restore a window from system tray.
I've tried the window id from `icesh systray` and `icesh xembed`, but it has no effect.
When I try the original window id it also has no effect.

Okay, I can do it with 
`xdotool mousemove $(icesh xembed|sed -n '/Hexchat/ s/.*24x24+\([0-9]*\)+\([0-9]*\)/\1 \2/g p') click 1 mousemove restore`
, but is there a simpler solution?

**Comment by gijsbers** [comment]
Nah, that window is not managed nor manageable by icewm when it is hidden.
You can shorten it a bit with `icesh -t -n ^HexChat `.

**Comment by zaza42** [comment]
Ohh, how?
`icesh -t -n ^hex minimize` do nothing nor `icesh -t -n ^hex restore`.
Which part can be replaced by `icesh`?

**Comment by gijsbers** [comment]
To obtain the window id which you want to become mapped.
New option: `icesh -x -n hexchat click 5 5 1`.
Mouse is warped though.
