### ISSUE TITLE
ICEWM-1.6.5 EXA+DOLPHIN-EMU+FULLSCREEN = Crash Icewm

### ISSUE THREAD

**Issue by JC7897** [bbidulock/icewm#426]
Hello Icewm team,

I got icewm  git May 03, 2020 icewm-1.6.5. Icewm crashes with dolphin-emu when trying to go to full screen if i'm using exa. 

Here is a bt

https://pastebin.com/e69c1HKR

**Comment by gijsbers** [comment]
That backtrace is from the X11 server, not from IceWM. It is a bug in X11, icewm is fine.

**Comment by JC7897** [comment]
OK. Thank you gijsbers.
