### ISSUE TITLE
ICEWM-1.6.5 Glamor Dolphin-emu Does Not Get Out Of Fullscreen Properly.

### ISSUE THREAD

**Issue by JC7897** [bbidulock/icewm#427]
Hello Icewm team,

ICEWM-1.6.5 Glamor Dolphin-emu Does Not Get Out Of Fullscreen Properly. When i try to
get out of fullscreen the dolphin screen has no window.

This is an issue with icewm it works fine on xfce.

**Comment by gijsbers** [comment]
I don't understand "the dolphin screen has no window".

Could you run `icesh spy`. 
Then click on the dolphin-emu window.
Then go Fullscreen.
Then leave Fullscreen.
Then show us the output of `icesh spy`.

**Comment by JC7897** [comment]
> I don't understand "the dolphin screen has no window".
> 
> Could you run `icesh spy`.
> Then click on the dolphin-emu window.
> Then go Fullscreen.
> Then leave Fullscreen.
> Then show us the output of `icesh spy`.

Ok here is what i get.

bash-5.0$ icesh spy
33:16.448: 0x0c001c6: Leave Normal Virtual Nofocus
33:17.136: 0x0c001c6: Enter Normal Virtual Nofocus
33:17.344: 0x0c001c6: Leave Grab Virtual Nofocus
33:17.346: 0x0c001c6: Enter Ungrab Virtual Nofocus
33:17.365: 0x0c001c6: Visibility PartiallyObscured 
33:17.365: 0x0c001c6: Focus Grab NonlinearVirtual
33:23.809: 0x0c001c6: Leave Ungrab Virtual Nofocus
33:23.809: 0x0c001c6: Defocus Ungrab NonlinearVirtual
33:23.809: 0x0c001c6: Visibility Unobscured 
33:27.414: 0x0c001c6: Visibility PartiallyObscured 
33:28.040: 0x0c001c6: Visibility Unobscured 
33:35.957: 0x0c001c6: Visibility FullyObscured 
33:37.062: 0x0c001c6: Visibility PartiallyObscured 
33:41.753: 0x0c001c6: Visibility Unobscured 
33:41.780: 0x0c001c6: Visibility FullyObscured 
33:46.144: 0x0c001c6: Visibility Unobscured 
34:04.288: 0x0c001c6: Visibility PartiallyObscured 
34:04.424: 0x0c001c6: Visibility Unobscured 
34:04.513: 0x0c001c6: Visibility PartiallyObscured 
34:04.600: 0x0c001c6: Visibility Unobscured

**Comment by gijsbers** [comment]
Can I reproduce this on ubuntu after `apt-get install dolphin-emu`?
I then get dolphin 4.0.2. Is that what you have?
Is your use of the word "Glamor" important?
I get "No ISOs or WADs found", but I can get in and out of fullscreen okay.
I assume your dolphin-emu has WM_CLASS property "dolphin-emu", right?
Could you then give the output of `icesh -c dolphin-emu +r spy` ?
spy

**Comment by JC7897** [comment]
> Can I reproduce this on ubuntu after `apt-get install dolphin-emu`?
> I then get dolphin 4.0.2. Is that what you have?
> Is your use of the word "Glamor" important?
> I get "No ISOs or WADs found", but I can get in and out of fullscreen okay.
> I assume your dolphin-emu has WM_CLASS property "dolphin-emu", right?
> Could you then give the output of `icesh -c dolphin-emu +r spy` ?
> spy

Sorry i did not realize you had posted. I'm running Slackware-14.2 and Slackware Current. Right now with ICEWM-1.6.5.74 the issue appears to be fix. However i did notice another bug with glamor on slackware-14.2.
