### ISSUE TITLE
Icewm-1.6.5 Conky transparency goes black.

### ISSUE THREAD

**Issue by JC7897** [bbidulock/icewm#428]
Hello Icewm team,

Conky starts of transparent but then turns black.
![conky-black](https://user-images.githubusercontent.com/65046150/81450711-f1e5c580-9150-11ea-9176-be5cd7d30965.png)

**Comment by gijsbers** [comment]
you need to configure conky a bit or give the right options.

**Comment by JC7897** [comment]
> you need to configure conky a bit or give the right options.

What options? I know conky looks fine on icewm-1.4.2-1765 with the way i have it.

**Comment by gijsbers** [comment]
Are you running icewm with a 32-bit visual now? Alpha=1?
Conky has --window-id=. So you can point it to the root window.
You can set own_window_argb_visual, own_window_argb_value,
own_window_transparent, own_window_hints, own_window.

**Comment by JC7897** [comment]
Are running icewm with a 32-bit visual now? Alpha=1? 

Not sure. Here is the window options. 

#############################
# - Window specifications - #
#############################
own_window yes
own_window_type normal
own_window_argb_visual no
own_window_argb_value 0
own_window_transparent yes
own_window_hints undecorated,below,sticky,skip_taskbar,skip_pager

**Comment by gijsbers** [comment]
`grep Alpha preferences`
or `xwininfo | grep -e Depth -e Visual` then click on taskbar.
repeat for conky.
you may need to read the conky docs and tweak the conky settings.

**Comment by JC7897** [comment]
Ok. Here is the xwininfo.

Taskbar
bash-5.0$ xwininfo | grep -e Depth -e Visual
  Depth: 24
  Visual: 0x21
  Visual Class: TrueColor

Conky
bash-5.0$ xwininfo | grep -e Depth -e Visual
  Depth: 24
  Visual: 0x21
  Visual Class: TrueColor

**Comment by gijsbers** [comment]
OK, so no Alpha.

With these settings + icewm-1.6.5 i do get a transparent conky:

```
    own_window_argb_visual = false,
    own_window_argb_value = 0,
    own_window_transparent = true,
    own_window_hints = undecorated,below,sticky,skip_taskbar,skip_pager,
```

You can also experiment with `own_window_hints = override`.

**Comment by gijsbers** [comment]
You seem to use old conky configuration syntax. Run `conky -C` and compare.
Or check https://github.com/brndnmtthws/conky/wiki/Configurations
for a conversion script.

**Comment by JC7897** [comment]
> You seem to use old conky configuration syntax. Run `conky -C` and compare.
> Or check https://github.com/brndnmtthws/conky/wiki/Configurations
> for a conversion script.

I tried to change the conky theme to what you posted but it still goes black. I was also using conky
1.9.0 but i just upgraded to conky 1.10.8 and the issue remains.

**Comment by gijsbers** [comment]
That is funny because it works for me for conky versions 1.10.6 and 1.11.6_pre.
The key line is `own_window_transparent = true`.

**Comment by JC7897** [comment]
I got it to work by changing "own_window_argb_visual yes" to own_window_argb_visual no in conky 1.10.8. Thanks gijsbers.
