### ISSUE TITLE
Icewm-1.6.5 Icons on some themes go invisible.

### ISSUE THREAD

**Issue by JC7897** [bbidulock/icewm#429]
Hello Icewm team,

I believe that when icewm starts with a smaller icewm menu icons then, you switch to a larger icon
theme it causes them to go invisible.

![missing icons](https://user-images.githubusercontent.com/65046150/81450977-86502800-9151-11ea-8044-a7990bd61d63.png)

**Comment by gijsbers** [comment]
what commands do I need to do to repeat that?

**Comment by Code7R** [comment]
And also what's your configuration, can you share config.h or CMakeCache.txt from the build?

**Comment by JC7897** [comment]
> what commands do I need to do to repeat that?

Here is a video you see how to do it.

https://streamable.com/4dimsg

> And also what's your configuration, can you share config.h or CMakeCache.txt from the build?

I just followed the build instructions on the icewm-git page.

$> git clone https://github.com/bbidulock/icewm.git
$> cd icewm
$> ./autogen.sh
$> ./configure
$> make
$> make DESTDIR="$pkgdir" install

**Comment by JC7897** [comment]
This issue appears to be fixed for me.
