### ISSUE TITLE
Icewm 1.6.5  Trayicon bg seems not to be properly set.

### ISSUE THREAD

**Issue by JC7897** [bbidulock/icewm#430]
Hello Icewm team,

Trayicon bg seems not to be properly set.

![icewm tray](https://user-images.githubusercontent.com/65046150/81451243-0aa2ab00-9152-11ea-9324-3f8cb88f7c57.png)

**Comment by gijsbers** [comment]
looks good to me.

**Comment by JC7897** [comment]
> looks good to me.

??? This is not the way it used to look. It should look like this.

Notice it does not have the extra black lines on icewm-1.4.2.1765.

![screen03](https://user-images.githubusercontent.com/65046150/81477200-7d5c6680-91e4-11ea-8d3a-176467ff8f29.png)

**Comment by gijsbers** [comment]
What theme do you use? What is the output of `icesh xembed`?

**Comment by JC7897** [comment]
I'm using the theme Nano-blu. Here is the icesh xembed output.

0x1000003   0 12019 "wicd-client.py"    : (wicd-client.py.Wicd-client.py) 24x24+1225+873
0xa00003    0 12020 "pnmixer"           : (pnmixer.Pnmixer)    24x24+1201+873

**Comment by ch4itu** [comment]
Hi!

In Taskbar preferences, set TrayDrawBevel to 0.

I suppose this is what you are looking for.

Regards,
Chaitanya Kumar Jagabathula

**Comment by JC7897** [comment]
> Hi!
> 
> In Taskbar preferences, set TrayDrawBevel to 0.
> 
> I suppose this is what you are looking for.
> 
> Regards,
> Chaitanya Kumar Jagabathula

It's already set to 0 and that does not fix the problem. Thanks though.

**Comment by gijsbers** [comment]
Not sure there is a problem. Perhaps @SolisX can comment?

**Comment by JC7897** [comment]
> Not sure there is a problem. Perhaps @SolisX can comment?

You can't see the double lines in icewm-1.6.5 or is it that it's not doing that on your system with icewm-1.6.5? You guys have ./configure, make on the github page are you using cmake now? Maybe my issue is caused by using different tools?

@SolisX can comment? It's me. I created the SolisX account along time ago and i forgot the email address then when i tried to log in to github, github was asking for confirmation from my email which i don't have. So i had to created this account.

**Comment by gijsbers** [comment]
Good to have you back then. :-)
This may fix it. Please evaluate.

**Comment by JC7897** [comment]
Glad to be back. :).

Yes the patch fixes the issue for me. Thanks gijsbers.
