### ISSUE TITLE
CPU temperature disfigured in tray monitor widget

### ISSUE THREAD

**Issue by DieSpinne** [bbidulock/icewm#431]
I have `CPUStatusShowAcpiTempInGraph=1` in my `~/.icewm/preferences` and my Icewm is version 1.6.5. The temperature inside the CPU widget becomes disfigured as new "frames" are drawn (see picture below), so that the temperature is only readable at the very first moments after starting Icewm.

![CPU](https://user-images.githubusercontent.com/62444221/81502544-017e1f00-92b5-11ea-9820-b842e816bb0c.png)

This bug has been introduced recently as I didn't have this problem in previous versions of Icewm.

**Comment by gijsbers** [comment]
This was due to 35c632fa2, two years ago. Does the fix work for you?

**Comment by Entebate** [comment]
Oh, not so recent then. Sorry, I do not know how I should test the fix.

**Comment by Entebate** [comment]
Just installed 1.6.6, fix worked, thank you!
