### ISSUE TITLE
Combining ShowWindows=0 and autohide hides the taskbar permanently

### ISSUE THREAD

**Issue by LogicPhase** [bbidulock/icewm#434]
In Preferences, set:
TaskBarShowWindows=0
TaskBarAutoHide=1

This hides the taskbar permanently. Mousing in the region won't raise the taskbar. I was able to unhide the taskbar by CTRL+ALT+SPACE (used to invoke the address bar, when ShowAddressBar=1). This permanently unhides the taskbar: it won't autohide again.

**Comment by gijsbers** [comment]
Is this the same as #415 ? What gives `icewm --version` ?

**Comment by LogicPhase** [comment]
% icewm -V
IceWM 1.6.5
Unrelated to  #415 as it doesn't involve taskbar doubleheight, only TaskBarShowWindows. Doubleheight is set to the default in my config.

**Comment by gijsbers** [comment]
This is another detail for the fix to #415. It should work now. Thanks for reporting!
