### ISSUE TITLE
Icewm-1.6.5.74 glamor workspaces numbers are a small black box.

### ISSUE THREAD

**Issue by JC7897** [bbidulock/icewm#435]
Hello guys,

Icewm-1.6.5.74 glamor workspaces numbers are a small black box. If i hover the mouse over the workspace it shows the number until i move the mouse pasted the little square box.

![screen01](https://user-images.githubusercontent.com/65046150/83185130-83b17480-a0f8-11ea-9a13-2a61bc7b7f56.png)

**Comment by gijsbers** [comment]
Since which version? Which themes are affected? Which themes are not affected? What means "glamor" ?? Does it help if you turn off glamor?

**Comment by JC7897** [comment]
> Since which version? Which themes are affected? Which themes are not affected? What means "glamor" ?? Does it help if you turn off glamor?

The only theme effect is Nano-blu with glamor on. If i set "AccelMethod" to "exa" it looks fine.
This was just tested on icewm-1.6.6.6.

**Comment by gijsbers** [comment]
Wait, Nano_Blue is that theme with some icons being PNG files, even though they have an .xpm filename extension. Maybe that is important??

You could then test if similar themes, like Spoof, OnyX and BlueObscureICEWM-master, have the same problem. That would be interesting!

But really there should not be a difference if you switch X11 drivers. That points to a bug in Glamor, which would be best if reported to them. Then IceWM is only a place where it shows up for some reason.

**Comment by JC7897** [comment]
> Wait, Nano_Blue is that theme with some icons being PNG files, even though they have an .xpm filename extension. Maybe that is important??
> 
> You could then test if similar themes, like Spoof, OnyX and BlueObscureICEWM-master, have the same problem. That would be interesting!
> 
> But really there should not be a difference if you switch X11 drivers. That points to a bug in Glamor, which would be best if reported to them. Then IceWM is only a place where it shows up for some reason.

I don't know. I did try BlueObscureICEWM-master and it looked fine. I could not find OnyX or the Spoof themes. However i did some checking on Nano Blu and found 2 ways to get the workspace
numbers to show up with glamor. 

1).Remove workspacebuttonbg.xpm and workspacebuttonactive.xpm from the gradients section in  the default theme file.

2).Changing the look to pixmap or gtk.

**Comment by JC7897** [comment]
You may want upgrade nano-blu to the version below.

[Nano Blu-1.3.zip](https://github.com/bbidulock/icewm/files/4741092/Nano.Blu-1.3.zip)

* I modified the default theme gradients and remove xpm that are not needed.
* I also converted the icons that were pngs to xpms and resized them to the correct size.
* I remade the clock with a blueish color.
* I changed white font color to grayish color.

I don't why gradients causes that issue with this theme but this new version will at least work properly on icewm with glamor.

**Comment by gijsbers** [comment]
Thanks! This is in commit 467bae4a2886a0b07eb5e30711dbdeeeb0647fef. 

There are two strange files: drameAB.xpm drameATR.xpm

**Comment by JC7897** [comment]
No problem. :) I only found drameATR.xpm. I have deleted it. Here is a new upload, check and see if you can find drameAB.xpm.

Nano Blu 1.3 JULY162020 Nevermind this download. 

I checked dframeAB. I don't know why it says bordo basso instead of dframeAB.
 
/* XPM */
static char * bordo basso_xpm[] = {
"8 2 4 1",
" 	c None",
".	c #837183",
"+	c #7B6D7B",
"@	c #000000",
".+.+.+.+",
"@@@@@@@@"};

I will check all the xpms to see how many have this problem. I will try and see if i can fix it with gimp or a text editor.

**Comment by JC7897** [comment]
Hello  gijsbers,

I could not find  drameAB.xpm. This is a new upload of Nano Blu-1.4.

* Deleted the drameATR.xpm.
* Fix xpms static char * name_xpm[] = {

Nano Blu-1.4
[Nano Blu-1.4.zip](https://github.com/bbidulock/icewm/files/4934426/Nano.Blu-1.4.zip)

**Comment by gijsbers** [comment]
Good! But eos.jpg is now twice as big? Directories cursors/ and mailbox/ are empty.

**Comment by JC7897** [comment]
Yeah when i resaved the eos.jpg in gimp it became larger. I will up load the smaller eos.jpg one.
Also if you look at original Nano Blu theme here

https://www.box-look.org/p/1018254/#files-panel

The cursors and mailbox directories were empty.

Nano Blu-1.4 Original eos.jpg

[Nano Blu-1.4.zip](https://github.com/bbidulock/icewm/files/4935752/Nano.Blu-1.4.zip)

**Comment by gijsbers** [comment]
If those directories are intended to be empty then they can simply be removed.

There is a problem with themes CrystalBlue and Illuminate-ice. 
Their frameAT.xpm   frameATL.xpm  frameATR.xpm icons have empty rows at the top.
CrystalBlue has 3 empty pixel rows and Illuminate-ice 9.
This results in miscalculations in frame positioning.
There remains unused space above a frame.
Users have to drag the frame to the top of the screen each time.
This is tedious. Could this perhaps be fixed?

**Comment by JC7897** [comment]
Ok this new upload also has the empty directories deleted.

Nano Blu-1.4 with deleted empty directories.

[Nano Blu-1.4.zip](https://github.com/bbidulock/icewm/files/4939488/Nano.Blu-1.4.zip)

As far as the frameAT.xpm, frameATL.xpm, and frameATR.xpm icons for CrystalBlue
and Illuminate ice 9 i think i needed to make the themes that way for it to look properly
but i will try and see if i can remove the extra 3-5 pixels of transparent space.

**Comment by JC7897** [comment]
Hello gijsbers,

I made an issue for the CrystalBlue theme +3 empty pixal rows problem found here.

https://github.com/bbidulock/icewm/issues/447

**Comment by gijsbers** [comment]
Okay, thanks for pointing that out!
Maybe there is a software solution for this problem.
Then the themes can remain as is.

BTW, did you notice you can use transparency features in themes?
For instance, if you look at the aluminium theme from https://triq.net/theme
and run icewm with Alpha=1 and a compositor like picom or compton
you will see a pattern of holes in the titlebar like this:

![alu](https://user-images.githubusercontent.com/4169687/87852870-0b9c4980-c906-11ea-833a-eed40b26c8d5.png)

**Comment by JC7897** [comment]
No Problem.

No i did not know that. I don't use compton because i had it freeze the screen if i use some options.
Thanks for the info though.

**Comment by gijsbers** [comment]
Compton seems not to be maintained anymore, but Picom is at https://github.com/yshui/picom.

BTW, you can also use PNG for all theme pixmaps.
They can be smaller and have more colors and transparency features.

**Comment by JC7897** [comment]
I will check it out and see if it works better for me. Thanks.
