### ISSUE TITLE
Is there a way to generate a winoptions entry to remember a windows attributes?

### ISSUE THREAD

**Issue by cheapy** [bbidulock/icewm#436]
This could be an add-on script based on a key mapped to save the active window's settings, or an option on the window menu to remember a window so that the next time the same program is run the window is created with the same attributes.   It is an option on Fluxbox and I've had situations where it would improve convenience and efficiency.  People have trouble creating the winoptions entries, especially geometry, by hand.

**Comment by gijsbers** [comment]
Perhaps give some links to or quotes of the specific issues? Maybe they are right about geometry. Looks a bit counterintuitive to me too. Is the man page clear or confusing?
Fluxbox has way fewer options.

**Comment by cheapy** [comment]
Yes, I will try to show my examples.  I admit to being confused by the geometry calculations  There is some confusion with whether to include "decorations" or not.  For it to be correct in my eyes, it should look the same on the screen.  I don't actually know what is right on that as there are too many sites with conflicting answers.  

As for remembering programmatically, I know that what is easy for the user is likely difficult to code, but if you could, please try to help me identify a solution of some kind if you can.

I am very uncomfortable using Fluxbox, generally.  I am so used to using MS versions of windows back to the days of DeskView on DOS 5.0, that Fluxbox seems very foreign, but IceWM feels natural, which makes sense because it was designed to work like Win95, which I liked.

If it was included as part of IceWM, I would look at Fluxbox's option to decide what I would use or not use from its long list.  On the right-click window menu Fluxbox has button that says "Remember", clicking it brings up a long list of checkboxes of what specifically to remember, I guess.  I just want it to remember either everything (LOL, if that's easy), or just the size and position related attributes, most critically being what workspace, top left position, height, and width.  If this could easily be written to winoptions and then work when I open that program again, that would be great, because then if I wanted to go tweak what it put there, I could do that.

If it was not included in IceWM, I would want a script that would run when I press a hotkey for the active window that would then take all the info about that window and write the entry to winoptions, or if that wouldn't work, instead to write a script that runs a program like wmctrl to change the window attributes to what was saved.  I wonder if that is the intent of icewmhint which I have never used.

Anyway, I tried using xdotool, xwininfo, and xprop to show the window's attributes, and then tried to put them into winoptions, to get it to reproduce the attributes when I opened the program again, but it didn't work.  The window came up the same size, but not in the same location.  

Since I'm an IceWM fan, I wanted to show the user that IceWM is just as good or better than Fluxbox and didn't like that being the excuse why even though their browser didn't work right under Fluxbox, which is very major these days, they still couldn't switch.  So I'm looking for a way to remember and reproduce the window's position and attributes some how.

Since different programs might be more willing to let winoptions control the window that gets opened, can you suggest a good program to run in the active window that you typically use to test with?  I was using Gnome's solitaire game, but maybe that isn't the best choice.  I will try to use the program you suggest to generate my tests with, and thus it will be easy for you to duplicate.

**Comment by cheapy** [comment]
Ok, I decided to try it with SpaceFM, so I created a window, centered it, then lowered the bottom to make it taller in height, then ran my little script that I hacked together from what I found on the web:

I will attach the script that displays all the info.  I then closed the spacefm window.

I then went to winoptions and added a line with what line 43 calls net geometry

spacefm.Spacefm.geometry: 987x754+480+270
sol.Sol.geometry: 1201x669+600+168

To make a 3 hour story short, I fiddled with something from xprop called NET_FRAME_EXTENTS adding and subtracting them or not, and sometimes omitting values of 1, and at this point the calculation is working, at least for the setup I have currently, but I don't have much faith because I don't really understand the meaning of the values themselves, and don't know what causes those border size values to change.  

Moving forward, if that code is correct(ed), I am thinking that I could add more code to remove the current program line from winoptions if it exists already, and then write a new line for it with the calculated net geometry values, then save the winoptions file and restart icewm.  I could assign running the script that does it to a key that I would press to make it remember that window, since I can't add it to the window menu itself.  

Do you think that will work?

[get_window_info-sh.txt](https://github.com/bbidulock/icewm/files/4734083/get_window_info-sh.txt)

[get_window_info.txt](https://github.com/bbidulock/icewm/files/4734113/get_window_info.txt)

**Comment by bbidulock** [comment]
The geometry position is (normally) the coordinate of the upper-left pixel of the client (e.g. spacefm) window, excluding any border assigned by the client to that window.  The geometry size is the size of the client window excluding any window border.  _NET_FRAME_EXTENTS is the widths of all four decorative borders of the frame applied to the client window by the window manager.  Perhaps you are off by one here and there because the client window has a 1 pixel window border applied to it that is not included in the other sizes or calculations.  However, it should be sufficient to specify the location and size of the client window alone to recreate the size and position of the window.  There should be no need to look at borders  or window frames at all.

**Comment by bbidulock** [comment]
As a side note, I am aware of the feature in Fluxbox, but could find no useful purpose for it, even back when I was a serious fluxbox user.

**Comment by gijsbers** [comment]
It is more difficult than it should. This script will do it for the moment, but we need to add something easy.

```bash
#!/bin/bash

set -- $(icesh -f getGeometry prop _NET_FRAME_EXTENTS prop WM_CLASS | tr '+,' '  ')

geo=$1
x=$2
y=$3
left=$7
top=$9
class=${14}

let x-=$left
let y-=$top

echo "${class}geometry: ${geo}+${x}+${y}"
```

**Comment by cheapy** [comment]
Lots to learn from, there.  I haven't ever seen icesh used anywhere before, or set...

I need to figure out how to make use of the value, still...

**Comment by cheapy** [comment]
Ok, I added a few lines at the end to make it work...

Thanks for your help.  I'll post back if there are any comments by users on it.  If its not hard to build in, it would be a welcome addition, but that's up to you as I don't know the difficulties.

[add_geo_entry.txt](https://github.com/bbidulock/icewm/files/4739188/add_geo_entry.txt)

**Comment by gijsbers** [comment]
There are 47 winoptions. There is no way that a script could obtain most of these settings. Most of them are for internal use by icewm only. It seems unlikely to me that a user would want to set the majority of them for some application. The winoptions provide a way to tweak a few of them for some applications, as the need arises.

You are right that geometry is an exception, as it is more general. Geometry is also important, because so many Gnome applications don't have a --geometry option. So that gives the motivation to make this script work.

You already pointed out the difficulty to get an accurate geometry specification. For terminals this is also difficult, because they calculate their size from character positions and the font size. Your choice of SpaceFM and Sol as test applications is fine.

However, you need to be a bit careful as to where you write the winoptions to. IceWM
 supports several different locations, which you can find in the man pages. I edited
 your script a bit to support this.

```bash
#!/bin/bash
# add geometry entry for active window to winoptions

set -- $(icesh -f getGeometry prop _NET_FRAME_EXTENTS prop WM_CLASS | tr '+,' '  ')

geo=$1
x=$2
y=$3
left=$7
top=$9
class=${14}

let x-=$left
let y-=$top

# locate winoptions
if [[ -d $ICEWM_PRIVCFG ]]
then
    winoptions=$ICEWM_PRIVCFG/winoptions
elif [[ -d $XDG_CONFIG_HOME && -d $XDG_CONFIG_HOME/icewm ]]
then
    winoptions=$XDG_CONFIG_HOME/icewm/winoptions
elif [[ -d $HOME/.config/icewm ]]
then
    winoptions=$HOME/.config/icewm/winoptions
elif [[ -d $HOME/.icewm ]]
then
    winoptions=$HOME/.icewm/winoptions
else
    echo "$0: Cannot find your icewm config directory" >&2
    exit 1
fi

cls_geo="${class}geometry"
newline="${cls_geo}: ${geo}+${x}+${y}"

# delete previous 
sed -i -e "/$cls_geo/d" "$winoptions"
# add new
echo "$newline" >> "$winoptions"

# is there a need to restart icewm?
# icewm -r
```

**Comment by cheapy** [comment]
gijsbers, thanks for your thoughts and time.  Yes, I was looking at the problem the way that IceWM is installed on my system, and on other distros, the files could be somewhere else.  I agree that there are way too many options to put on a window menu, and then you would struggle deciding what needs to be clicked, when the correct answer was likely none of them.

I did find that the users would like to optionally remember the workspace number as well as geometry.  Some people have their workspaces organized for different tasks.  Basically that means that I need to allow them to optionally designate what workspace to use as well as position, or not, in which case it opens on the current workspace with the expected geometry.

They also wanted a Forget option to remove the setting.  I am thinking of using a YAD popup to control the few options needed.  We concluded that people set things like this up, and then don't need to change them often after that.

I think I added the icewm restart because I didn't think the settings would take effect until IceWM was restarted, but maybe that's not true, or maybe I should just be reloading winoptions?

Again, thanks for helping with this.  The users I've spoken to so far were very happy with the idea that IceWM might make this easy in future.  It was too tricky setting it up manually in winoptions, I think..

**Comment by gijsbers** [comment]
This script supports geometry, layer and workspace. It can also remove them.

```bash
#!/bin/bash
#
# Remember (or forget) window settings in icewm-winoptions.
#

usage () {
    cat >&2 <<EOI
    Usage: $0 [options...]
    Options are:
        -a : Use the active window
        -i : Choose a window interactively
        -g : Apply the geometry settings
        -l : Apply the layer settings
        -r : Remove the existing settings
        -w : Apply the workspace settings
EOI
    exit 1
}

# options defaults
active=0
intact=0
geomet=0
layers=0
remove=0
worksp=0

# parse options
while [[ $# -ge 1 ]]
do
    case $1 in
        (-a) active=1 ;;
        (-i) intact=1 ;;
        (-g) geomet=1 ;;
        (-l) layers=1 ;;
        (-r) remove=1 ;;
        (-w) worksp=1 ;;
        (*) usage ;;
    esac
    shift
done

# icesh -f?
if [[ $active -eq 1 || $intact -eq 0 ]]; then
    focus=-f
fi
if [[ $intact -eq 1 ]]; then
    focus=
fi
if [[ $layers -eq 0 && worksp -eq 0 ]]; then
    geomet=1
fi

# create temporary file
temp=$(mktemp)

# obtain window settings
icesh $focus getGeometry getLayer getWorkspace \
    prop WM_CLASS prop _NET_FRAME_EXTENTS >"$temp"

# file must have something
if [[ ! -s $temp ]]
then
    exit 1
fi

# remove punctuation
sed -i -e 's|[+,]| |g' "$temp"

# empty values
geo=
x=
y=
left=
top=
class=
layer=
work=

# read values from file
while read a b c d e f g h
do
    if [[ $a =~ ^0x ]]
    then
        if [[ $b =~ ^WM_CLASS ]]
        then
            class=$d
        elif [[ $b =~ ^_NET_FRAME_EXTENTS ]]
        then
            left=$d
            top=$f
        elif [[ $b =~ ^[0-9]+$ || $b -eq -1 || $c = '"All"' ]]
        then
            work=$b
        elif [[ $b =~ ^[A-Z][a-z] ]]
        then
            layer=$b
        fi
    elif [[ $a =~ ^[0-9] ]]
    then
        geo=$a
        x=$b
        y=$c
    fi
done <"$temp"

# remove temporary file
rm -f -- "$temp"

# print values if debug?
if false
then
    echo "geo=$geo"
    echo "x=$x"
    echo "y=$y"
    echo "left=$left"
    echo "top=$top"
    echo "class=$class"
    echo "layer=$layer"
    echo "work=$work"
fi

# correct geometry
let x-=$left
let y-=$top

# locate winoptions
if [[ -d $ICEWM_PRIVCFG ]]
then
    winoptions=$ICEWM_PRIVCFG/winoptions
elif [[ -d $XDG_CONFIG_HOME && -d $XDG_CONFIG_HOME/icewm ]]
then
    winoptions=$XDG_CONFIG_HOME/icewm/winoptions
elif [[ -d $HOME/.config/icewm ]]
then
    winoptions=$HOME/.config/icewm/winoptions
elif [[ -d $HOME/.icewm ]]
then
    winoptions=$HOME/.icewm/winoptions
else
    echo "$0: Cannot find your icewm config directory" >&2
    exit 1
fi

cls_geo="${class}geometry"
new_geo="${cls_geo}: ${geo}+${x}+${y}"

cls_lay="${class}layer"
new_lay="${cls_lay}: ${layer}"

cls_wsp="${class}workspace"
new_wsp="${cls_wsp}: ${work}"

# geometry
if [[ $geomet -eq 1 ]]
then
    # delete previous 
    sed -i -e "/$cls_geo/d" "$winoptions"
    if [[ $remove -eq 0 ]]
    then
        # add new
        echo "$new_geo" >> "$winoptions"
    fi
fi
# layer
if [[ $layers -eq 1 ]]
then
    # delete previous 
    sed -i -e "/$cls_lay/d" "$winoptions"
    if [[ $remove -eq 0 ]]
    then
        # add new
        echo "$new_lay" >> "$winoptions"
    fi
fi
# workspace
if [[ $worksp -eq 1 ]]
then
    # delete previous 
    sed -i -e "/$cls_wsp/d" "$winoptions"
    if [[ $remove -eq 0 ]]
    then
        # add new
        echo "$new_wsp" >> "$winoptions"
    fi
fi

# let icewm reload the winoptions
icesh winoptions
```

**Comment by cheapy** [comment]
Thanks very much for your knowledge and effort.  I see you went above and beyond and added layers.  I haven't ever done anything with those before, but trust that you think it will be useful to remember that setting.  I'm sure it would become apparent when it was missed but needed.

What would you think would be a friendly way for users to run it?  I wasn't able to figure out the Yad prompt box, still.  I need something to work from that has similar features to make sense of Yad, as its not something I've created before.  Maybe you have a good way in mind?

From what I could tell from the users workflows that I know about, the most common uses will be:
1. Remember the window (including geometry and layer), and which workspace to create it on
2. Remember the window (including geometry and layer), but not workspace so it would be created on the active workspace
3. Forget the window and remove its settings

I will go test what you created. 

I have to try it to understand your interactive mode.  Maybe that means the Yad dialog won't be needed, or could be used as a front end for your command. 

Thanks again.

**Comment by cheapy** [comment]
The devs wanted a GUI solution, so we used your code as a base and created a YAD based script.  If you want I can provide a copy when the final version is included in the distro.
