### ISSUE TITLE
Translations management

### ISSUE THREAD

**Issue by scarabeusiv** [bbidulock/icewm#44]
We at SUSE use icewm as default fallback wm and thus would like to have pretty full translations of the thing.

For that if you guys are interested we could offer our openSUSE translation infrastructure that could glue in via services in github. Translators access it over web:
https://l10n.opensuse.org/

And for example on how it looks like on github:
https://github.com/rofirrim/eiciel/commits/master

Would that be something you would like?

**Comment by bbidulock** [comment]
I'm not that familiar with the mechanism.  If I give you commit access can you work it in?

**Comment by scarabeusiv** [comment]
Yup, can tweak it up, I would give you the guide even :) I first wanted to know if it is something that would be interesting or not...

**Comment by scarabeusiv** [comment]
And having access is probably not enough, as it is in project hooks configuration, will give you the guide in few hours, now lunch

**Comment by scarabeusiv** [comment]
Two steps are needed:
1. Add user opensuse-i18n to a list of collaborator.
2. Add Weblate web service:
   https://docs.weblate.org/en/latest/admin/continuous.html#automatically-receiving-changes-from-github
   URL to be added:
   https://l10n.opensuse.org/

Optional things:

1a. Register to https://l10n.opensuse.org/ and ask for admin privileges 
for your Weblate project.

otherwise

1b. Weblate admin will have to add new po files on request. Admin needs 
to be informed how it can be done.

Things that needs to be done continually:
If you have string changes and you want translators to translate them, 
update po/pot files in the github repository.

**Comment by scarabeusiv** [comment]
(Technically Optional 1b you completed by giving me the access rights).

**Comment by scarabeusiv** [comment]
And import on openSUSE side done:

https://l10n.opensuse.org/projects/icewm/icewm-1-3-branch/

Works from now, when the ACL are done per above it will auto publish even the translations that were done in the meantime :)

**Comment by bbidulock** [comment]
I think things are set up now...

**Comment by bbidulock** [comment]
Translations are moving...
