### ISSUE TITLE
Permanently disable tray network monitors of some interfaces?

### ISSUE THREAD

**Issue by DieSpinne** [bbidulock/icewm#440]
I am usually Internet connected on wireless `wlp3s0` interface, so I don't need monitoring the wired `enp2s0f1` interface. I know I can disable its monitor in the menu that shows up with a right click on the monitors, but the changes are not persistent on a reboot. **Is there any way to permanently disable the tray monitor for a certain interface?** I could not find anything in the `preferences` file.

Thanks!

**Comment by gijsbers** [comment]
From preferences:
```
#  Network device to show status for
# NetworkStatusDevice="[ew]*"
```

**Comment by Entebate** [comment]
Ops... The file in my home directory was from a previous version so it didn't have that option, but the one in `/usr/share` had that option indeed. Sorry and thanks once again!
