### ISSUE TITLE
Incorrect workspacenames

### ISSUE THREAD

**Issue by cefer60** [bbidulock/icewm#443]
WorkspaceNames as:

WorkspaceNames=" Office ", " Internet ", " Development ", " Games "

remain showing 1, 2, 3

**Comment by gijsbers** [comment]
Icewm first looks at the root window for workspace names:

    xprop -root _WIN_WORKSPACE_NAMES _NET_DESKTOP_NAMES

If it doesn't have any yet, then icewm will use the ones from your preferences file.
If you change WorkspaceNames you need to logout and login again, sorry.
You could also use icesh:

    icesh setWorkspaceNames " Office " " Internet " " Development " " Games "
    icesh restart

**Comment by gijsbers** [comment]
#249
