### ISSUE TITLE
Icewm-1.7.0.14 taskbar button restore issue

### ISSUE THREAD

**Issue by JC7897** [bbidulock/icewm#446]
Hello Everyone,

On Icewm-1.7.0.14 when i click on taskbar button to restore a window the window restores like this

Bad
![bad](https://user-images.githubusercontent.com/65046150/87826510-8adb4000-c868-11ea-8508-cdefd7bab111.png)

Good
![good](https://user-images.githubusercontent.com/65046150/87826524-9595d500-c868-11ea-9ea5-fa3fb38d5be5.png)

**Comment by JC7897** [comment]
Hey i just compiled icewm-1.7.0.24 and it seems to fix the issue but if i rollup a window then try to rolldown the window by the rolldown button on the theme the window rolls down then back up again with one click.

**Comment by JC7897** [comment]
Ok it's working better but i noticed that if i press the rollup and rolldown buttons really fast the window stays up or down. Also i noticed that in icewm-1.4.2 the titlebar does not rolldown the window if i single click the titlebar when a window is rolled up. I dont
know if that's a new feature?

**Comment by gijsbers** [comment]
A double click is different from a single click. Is that what you do?
If you double click with the middle mouse button on the title bar it should roll up.

**Comment by JC7897** [comment]
No i do a single click with the left mouse button on the titlebar. It rolls down the window if it is rolled up and it only works to roll down the window not rollup the window.

**Comment by gijsbers** [comment]
I undid it as it makes it harder to drag a rolled up frame.

**Comment by JC7897** [comment]
That fixed the titlebar restoring the window rollup with a mouse left button single click but the issue with the restore button is still present. I made two very short videos of the problem may be the videos  will help you
understand the problem.

Restore button good

https://streamable.com/nvju9j

Restore button bad.

https://streamable.com/0pad2b

**Comment by gijsbers** [comment]
Actually that was an old unintended misfeature, but I have restored it for you.

**Comment by JC7897** [comment]
Thanks.
