### ISSUE TITLE
BorderSize +3 empty pixal rows issue

### ISSUE THREAD

**Issue by JC7897** [bbidulock/icewm#447]
Hello gijsbers,

Here is the problem with CrystalBlue +3 empty pixal rows.

![borderissue](https://user-images.githubusercontent.com/65046150/87832258-1f4b9f80-c875-11ea-8355-de7d268fee51.png)

The BorderSizeX and BorderSizeY controls the size of frame not the frame xpms. This means that if you put BorderSizeY = 0 you will get no added size to top and button frames even if you have a frameAB.xpm with a size of 5 pixals you will not see it because the BorderSizeY is at 0. The BorderSizeY would need to be set to 5 so you can see the 5 pixals of the frameAB.xpm. With the frameAT.xpm the BorderSizeY will start at top of frameAT.xpm and place 5 pixals on top of the frame which is different to the bottom because there is no title
frame at the bottom.

**Comment by gijsbers** [comment]
But couldn't you use `TitleBarVertOffset` to overcome this problem?

    #  Vertical offset for the window title text

These themes use it: CoolSteel, Crunchy-grey, Crunchy-orange, DarkT_II,
IceClearlooks2, IceClearlooks2-Magi, IceNumix3-Aqua, LunaDotHome,
OpenLook-shaped, Sky, Smooth_Aqua, Trisquel, lovena, motif-dark.

**Comment by JC7897** [comment]
No i don't believe that will work. This is what happen if change TitleBarVertOffset +5/-5.

TitleBarVertOffset +5
![+5](https://user-images.githubusercontent.com/65046150/88633159-2445f580-d0a4-11ea-8ee8-c313b6e4dd5c.png)

TitleBarVertOffset -5
![-5](https://user-images.githubusercontent.com/65046150/88633246-3f186a00-d0a4-11ea-9d7c-01af124b0af3.png)

But i noticed that IceNumix3-Aqua does not have any title.xpms. He only made the frame.xpms. Could that why you are getting better frame positioning with that theme? I could try and remove the title.xpms and make just the frame but i guess that will have to wait until later on today.

UPDATE: Removing the title xpms will not work for CrystalBlue or any other theme that is using multi colors for the title bar. The reason IceNumix3-Aqua works without the title xpms is because it's using one color which i believe is set in the default.theme. If i remove the title xpms on CrystalBlue, i get a
solid blue bar not a gradient, which i can only change to another solid color.

**Comment by gijsbers** [comment]
The theme IceNumix3-Aqua uses Look=flat. That is why it can go without title xpms.
For CrystalBlue and Illuminate-ice you need a much smaller value for TitleBarVertOffset.
-2, or +2 or so. Illuminate-ice is an especially suitable test theme, because
it has an empty top side mask of 9 pixels!

**Comment by JC7897** [comment]
This is what i got.

This what Illuminate-ice should look like.

![Good](https://user-images.githubusercontent.com/65046150/88708436-2be8b700-d103-11ea-8d6d-146cca8ec7cd.png)

This is Illuminate-Ice with the 9 transparent pixals removed. (notice the 9 extra pixaps are on top of the titlebar)

![0-T](https://user-images.githubusercontent.com/65046150/88708564-59cdfb80-d103-11ea-8392-4e4749dfe95a.png)

This is Illuminate-Ice with the 9 transparent pixals removed and TitleBarVertOffset at -10.

![-10-T](https://user-images.githubusercontent.com/65046150/88708769-b3362a80-d103-11ea-8a2e-3e959ca2213f.png)

This is Illuminate-Ice with the 9 transparent pixals removed and TitleBarVertOffset at +10.

![+10-T](https://user-images.githubusercontent.com/65046150/88708955-fabcb680-d103-11ea-9538-563b5c86cc20.png)

The only way i found to take into account the 10 BorderSize and not use the 9 transparent pixals
was to change the TitlebarHeight to 20 and keep the bordersize at 10 but there is a problem with
that. The problem is that since the title bar is smaller you would need to draw half the button on the
Close,Maximize,Minimize and Restore buttons and the other half of the button on the frame which
can not be done. The only other option is to redo the buttons a lot smaller and changing the look of Illuminate-ice.

I think for CrystalBlue i might be able to do that without changing the look but i will need to redo the theme but i can not do that for Illuminate-ice.

**Comment by gijsbers** [comment]
OK, sounds good.

**Comment by JC7897** [comment]
Ok i think i have corrected the issue but i did run into another issue with the workspace buttons.

This is the way i intended it to look. Which is the 1st CrystalBlue theme.

![workspacebutton-good](https://user-images.githubusercontent.com/65046150/88789972-f4bbe980-d186-11ea-9319-5443b95c1252.png)

This is how it looks like in slackware current. It looks like the spacing in the fonts changed.

![workspacebutton-bad](https://user-images.githubusercontent.com/65046150/88790190-511f0900-d187-11ea-9a13-90448068efaf.png)

So i made CrystalBlue-default.zip without the nice workspace buttons i made.

Try this one first.
[CrystalBlue.zip](https://github.com/bbidulock/icewm/files/4994291/CrystalBlue.zip)

But if you have issues with workspace buttons, use this one instead.
[CrystalBlue-Default.zip](https://github.com/bbidulock/icewm/files/4994296/CrystalBlue-Default.zip)

**Comment by gijsbers** [comment]
Is there a version of icewm which shows your CrystalBlue.zip as your 1st CrystalBlue?
None of the ones I tried did.
If you want your buttons like the 1st, then you could simply add the workspace buttons as Gradients:

    Gradients="menubg.xpm dialogbg.xpm workspacebuttonactive.xpm workspacebuttonbg.xpm"

There is a problem with:

    DesktopBackgroundImage=                 "/usr/share/wallpapers/wallpaper-00.jpg"

This may not exist, but it may override some user setting in preferences.

**Comment by JC7897** [comment]
This new one should be correct expect for the wallpaper-00.jpg. The reason i don't share the wallpaper is i did not make it and i don't know where i got the picture from. 

CrystalBlue

[CrystalBlue.zip](https://github.com/bbidulock/icewm/files/4997605/CrystalBlue.zip)

Make sure you remove the old CrystalBlue package in your /usr/share/icewm/themes location. It's provably conflicting with the CrystalBlue in your /home/user/.icewm directory.

**Comment by JC7897** [comment]
Should be fix. Closing.

**Comment by JC7897** [comment]
Should be fix. Closing.

**Comment by gijsbers** [comment]
Could it perhaps be that titleAJ.xpm, titleAQ.xpm, titleIJ.xpm and titleIQ.xpm are missing?
There are some artefects on the left and right side of the titlebar.

**Comment by gijsbers** [comment]
There are small dots in the corners of the titlebar. See image.
The buttons of the message dialog may need to become gradients?
![killclientdialog](https://user-images.githubusercontent.com/4169687/89078819-65c8f000-d385-11ea-8757-09c7f103ce9a.png)

**Comment by JC7897** [comment]
The small dots in the corners are transparent spaces that i use to make the theme have a rounded corner. For some reason the theme appears to have lost transparency. I don't think i need the title?J and title?Q.xpms. This what i get.

Icewm-1.7.0.98.
![Dialog](https://user-images.githubusercontent.com/65046150/89155111-bc862380-d557-11ea-9a1c-1f4d09d36c3b.png)

I can add them just incase but they should not be needed. However since i see a minor color issue with buttons i try and
make a new CrystalBlue download later on today.

**Comment by JC7897** [comment]
You can try and see if this new version fixes the issue.

**Comment by JC7897** [comment]
Sorry i forgot to fix the color issue. Try this download.

[CrystalBlue.zip](https://github.com/bbidulock/icewm/files/5015070/CrystalBlue.zip)

**Comment by gijsbers** [comment]
![dialog](https://user-images.githubusercontent.com/4169687/89200735-ba9c7e80-d5b0-11ea-82c6-23cd371303ff.png)
The dialog buttons are no good yet. See image.
Also, the theme modifies desktop background settings,
even though it doesn't provide a background image.
It should leave the desktop background settings untouched.
Then users can set them in their preferences.

**Comment by JC7897** [comment]
The dialog buttons might look better if i add taskbuttonbg.xpm to the gradients but it's still not going to look correct. The reason is because icewm does not use a dialogbuttonbg.xpm so it just uses the taskbuttonbg.  With the background image i will remove DesktopBackgroundImage=""  and DesktopBackgroundScaled=1 from the default.theme.

Here is CrystalBlue.

* With taskbuttonbg, taskbuttonactive and taskbuttonminimized added to gradients.
* Removed DesktopBackgroundImage= ""  and DesktopBackgroundScaled=1 from default theme.

[CrystalBlue.zip](https://github.com/bbidulock/icewm/files/5019033/CrystalBlue.zip)

**Comment by gijsbers** [comment]
The case is that this theme doesn't provide buttonA.xpm or buttonI.xpm.
The solution for the dialog buttons would be to add buttonA.xpm and buttonI.xpm to Gradients.

**Comment by JC7897** [comment]
Ok here is a new CrystalBlue download.

* With menuButtonA.xpm,menuButtonI.xpm,buttonA.xpm and buttonI.xpm added.
* buttonA.xpm and buttonI.xpm are also added to the gradients section in the default.theme.

[CrystalBlue.zip](https://github.com/bbidulock/icewm/files/5046740/CrystalBlue.zip)

**Comment by JC7897** [comment]
Ok here is a new CrystalBlue download.

* With menuButtonA.xpm,menuButtonI.xpm,buttonA.xpm and buttonI.xpm added.
* buttonA.xpm and buttonI.xpm are also added to the gradients section in the default.theme.

Not sure why but i can't seem to upload the file to this site directly, so i uploaded it to the link below.

http://s000.tinyupload.com/index.php?file_id=74523626556221160036

**Comment by JC7897** [comment]
Ok here is a new CrystalBlue download.

* With menuButtonA.xpm,menuButtonI.xpm,buttonA.xpm and buttonI.xpm added.
* buttonA.xpm and buttonI.xpm are also added to the gradients section in the default.theme.

Not sure why but i can't seem to upload the file to this site directly, so i uploaded it to the link below.

http://s000.tinyupload.com/index.php?file_id=74523626556221160036

**Comment by JC7897** [comment]
Ok here is a new CrystalBlue download.

* With menuButtonA.xpm,menuButtonI.xpm,buttonA.xpm and buttonI.xpm added.
* buttonA.xpm and buttonI.xpm are also added to the gradients section in the default.theme.

Not sure why but i can't seem to upload the file to this site directly, so i uploaded it to the link below.

http://s000.tinyupload.com/index.php?file_id=74523626556221160036

**Comment by JC7897** [comment]
Ok here is a new CrystalBlue download.

* With menuButtonA.xpm,menuButtonI.xpm,buttonA.xpm and buttonI.xpm added.
* buttonA.xpm and buttonI.xpm are also added to the gradients section in the default.theme.

Not sure why but i can't seem to upload the file to this site directly, so i uploaded it to the link below.

http://s000.tinyupload.com/index.php?file_id=74523626556221160036

**Comment by JC7897** [comment]
Nevermind the other download i got it to upload here. Use the CrystalBlue in the post above.

**Comment by gijsbers** [comment]
Looks good! :+1: 

If you like, you could test the new MiniIcons. Play with:

    MinimizeToDesktop=1 # 0/1
    MiniIconsPlaceHorizontal=1 # 0/1
    MiniIconsRightToLeft=1 # 0/1
    MiniIconsBottomToTop=1 # 0/1

**Comment by JC7897** [comment]
I'll check it later but right now there seems to be an issue with CrystalBlue not adding the files i added on icewm-1.7.0.113. I can see the files in the icewm/lib/themes/CrystalBlue directory but when i make icewm the files are missing.

**Comment by JC7897** [comment]
I'll check it later but right now there seems to be an issue with CrystalBlue not adding the files i added on icewm-1.7.0.113. I can see the files in the icewm/lib/themes/CrystalBlue directory but when i make icewm the files are missing.

**Comment by JC7897** [comment]
I'll check it later but right now there seems to be an issue with CrystalBlue not adding the files i added on icewm-1.7.0.113. I can see the files in the icewm/lib/themes/CrystalBlue directory but when i make icewm the files are missing.

**Comment by JC7897** [comment]
I'll check it later but right now there seems to be an issue with CrystalBlue not adding the files i added on icewm-1.7.0.113. I can see the files in the icewm/lib/themes/CrystalBlue directory but when i make icewm the files are missing.

**Comment by gijsbers** [comment]
This should be fixed now. The titlebar corners are in some other color and have a hole:
![xterm-titlebar](https://user-images.githubusercontent.com/4169687/89951626-0c39ae80-dc2c-11ea-8f78-383c162ba433.png)
When I set Alpha=1 with compton I get this:
![close-xephyr](https://user-images.githubusercontent.com/4169687/89951693-296e7d00-dc2c-11ea-929b-6f4daca05d82.png)
and this:
![wmdialog](https://user-images.githubusercontent.com/4169687/89951713-312e2180-dc2c-11ea-8fe5-3f7671ef8344.png)
The button pixmaps are too translucent?

**Comment by JC7897** [comment]
This is what i get with alpha = 1 and compton. I can't replicate "The titlebar corners are in some other color and have a hole.".

CrystalBlue + Alpha 1 + Compton
![CB-Alpha-1-Compton](https://user-images.githubusercontent.com/65046150/89971771-a6f5b580-dc4b-11ea-9139-5f05e08603e6.png)


Ater-Ice-Hybird + Alpha 1 + Compton
![Ater-ice-hydrid-Alpha-1-Compton](https://user-images.githubusercontent.com/65046150/89971793-b07f1d80-dc4b-11ea-8053-6da015a4a35d.png)


I don't know why some xpms are transparent while others are solid color. I made the xpms in gimp.

BTW: If i try switch icewm themes with compton on the screen sometimes keeps flickering and will not load the icewm. Not sure if this is related but i did see this in my logs when i hit CTRL+ALT+Backspace.

01:26:16.922: icewm-session: icewm exited with status 1.

https://pastebin.com/1E0Sz8FH

**Comment by JC7897** [comment]
The transparency issue has to do with gradients. I made an issue here about it.

https://github.com/bbidulock/icewm/issues/468

**Comment by JC7897** [comment]
Hey i see a bit of a color issue with the close.xpm. This should fix slightly different color with the close.xpm.

![close](https://user-images.githubusercontent.com/65046150/90208131-681e5600-de2b-11ea-80ec-2f6f75c472c3.png)

[CrystalBlue.zip](https://github.com/bbidulock/icewm/files/5072437/CrystalBlue.zip)
