### ISSUE TITLE
Rename comments from APM monitor options to include the terms "battery" and "power"

### ISSUE THREAD

**Issue by DieSpinne** [bbidulock/icewm#450]
Icewm features this nice and simple battery monitor in the systray. Now, when searching into the `preferences` file for the settings that control the monitor, I guess I am not the only one who misses the settings because they are labeled with `APM`, while I'm searching for `battery` or `power` keywords.

I believe changing the options themselves (e.g., from `ColorApmLine` to `ColorBatteryLine`) may be bad for backwards compatibility, but there should be no drawback in changing the comments, e.g., `#  Color of APM monitor in line mode` to 
`#  Color of APM/ACPI/battery/power monitor in charging mode`. (Also, notice I have proposed changing "line mode" to "charging mode". I, for one, did not know what "line mode" is.)

If the developers agree with that, I could rename those comments, I have already done it for my files. At least that is something I could do. :)

**Comment by gijsbers** [comment]
Most welcome! The best way is to make a pull request with your proposed changes.
If that is too technical for you, a diff (context or unified) could also be posted here.
"Line mode" refers to on line, versus off line. That is, connected to a power line,
versus being disconnected from a charging power. You could clarify that as well.
The files you need to change include
https://github.com/bbidulock/icewm/blob/icewm-1-4-BRANCH/src/themable.h
https://github.com/bbidulock/icewm/blob/icewm-1-4-BRANCH/man/icewm-preferences.pod
and for the manual
https://github.com/ice-wm/manual/blob/master/index.md

I wouldn't write "APM/ACPI/battery/power", but use either "battery" or "power".
APM is outdated, while ACPI is too technical. You can improve readability of
whatever is poorly written or incomplete. Feel free to ask more info.

**Comment by DieSpinne** [comment]
Nice! I will have a look if I can understand a pull request, otherwise I will send the unified diff. I am totally new to this.

If I'm not wrong, this will also need to be changed.
https://raw.githubusercontent.com/bbidulock/icewm/icewm-1-4-BRANCH/src/default.h

Just to confirm it: I should not change the options, just the comments, correct?

**Comment by gijsbers** [comment]
Indeed. The third column which contains the explanation (Bedeutungserklärung).
The program genpref in the src directory uses those to generate a new preferences file.
You can also give genpref a -p option to let it output in .pod-format for the man page.
