### ISSUE TITLE
Thrown into other window when clicking on objects in Google Earth Pro

### ISSUE THREAD

**Issue by jidanni** [bbidulock/icewm#451]
In https://support.google.com/earth/thread/60073209 ,
they say me being thrown into other window when clicking on objects in Google Earth Pro,
is likely a IceWM 1.6.6-1 problem.

**Comment by gijsbers** [comment]
This should be fixed by commit c4d2b6b. You can avoid the problem by placing GEP in a higher window layer. Open the window menu and select Layer and then OnTop.
