### ISSUE TITLE
Restart icewm button jumbles window order

### ISSUE THREAD

**Issue by jidanni** [bbidulock/icewm#452]
"Restart icewm" button should respect the order of our windows.
E.g., if at the bottom of the screen, we have the row of window tabs
A B C D E F G
then that's the order they should be in after icewm restarts. Not
C A B D E F G
etc. 
IceWM 1.6.6

**Comment by gijsbers** [comment]
On restart IceWM chooses to put the focused task button farthest to the right. That has some merit.
IceWM maintains four orders: creation order, focus order, stacking order and systray order.
There exist five techniques to control task button order as listed in issue #337.

**Comment by jidanni** [comment]
That is great. The user has a lot of flexibility in choosing orders.
However compare chromium and firefox.
Do they rearrange the users' tabs upon restart? No.
Sure, one has reasons to restart icewm, but wanting icewm to "please reorder my tabs for me" has never been one.

**Comment by jidanni** [comment]
All that needs to be done is
1. icewm receives a restart notification
2. icewm makes a note of current tab order
1. icewm restarts
2. icewm sorts the tabs in the order that it just saved above.

**Comment by jidanni** [comment]
If systray order means current order,
then systray order should be the default restart order.

**Comment by jidanni** [comment]
Anyway, I can't see how any user could blame icewm for maintaining his current order through restart.
If he is unhappy with his current order and restart the only way to change it,
then there should be a new special option made for users like him.

**Comment by gijsbers** [comment]
There are so many things to do. If you want to compare with chromium and firefox then also compare the number of developers contributing to those projects. You are only contributing very many issues, but did you ever contribute to my donate page?

**Comment by jidanni** [comment]
Perhaps icewm is treating restart and start too much the same, when they should be treated more differently.

**Comment by jidanni** [comment]
Scientists discover icewm users are 99% percent dependent on the position of tabs and not their labels, for recognizing tabs.

Scientists have also linked this to the same mechanism that controls where people's fingers go while typing, no matter what the labels on the keyboard might say. 

Scientists report major distress when one's tabs are jumbled. Equivalent to tension produced in rats when their favorite food is switched.
