### ISSUE TITLE
Collapsing and then expanding adds a whiteline in taskbar 

### ISSUE THREAD

**Issue by JC7897** [bbidulock/icewm#455]
Hi Guys,

Collapsing and then expanding adds a whiteline in taskbar in icewm-1.7.0.86.

![titlebar-whiteline](https://user-images.githubusercontent.com/65046150/89088842-ef7abc80-d389-11ea-85ce-bdb9fe9f1a8a.png)

**Comment by gijsbers** [comment]
I think this is fixed now. BTW, did you notice my new remarks at issue 447?

**Comment by JC7897** [comment]
Yeah it's fixed.

And no i did not see the new marks at issue 447. I will check right now.
