### ISSUE TITLE
Setting taskbarbg.xpm to gradients causes black blocks.

### ISSUE THREAD

**Issue by JC7897** [bbidulock/icewm#457]
On icewm-1.70.98 if i add taskbarbg.xpm to gradients i get black blocks for numbers if the workspacebuttons are also in the gradients section.

![workspacebuttons](https://user-images.githubusercontent.com/65046150/89232834-e0894980-d5d7-11ea-9cfa-937cfdd57632.png)

**Comment by gijsbers** [comment]
I have:

    Gradients="menubg.xpm dialogbg.xpm workspacebuttonbg.xpm workspacebuttonactive.xpm taskbarbg.xpm"

but this works fine. Could this be another Glamor bug, like you reported in #435?

Does it matter if you have PagerShowPreview=1 or 0? And Alpha=1 or 0?

It seems I can just remove the offending function WorkspaceButton::paintBackground.
I'll commit it, so you can test it. Does it help?

**Comment by JC7897** [comment]
No the above commit did not work.  I believe it is the same as issue as #435. I will close this one.

BTW : Setting Alpha to 1 and PagerShowPreview=1 does get rid of the black blocks but the workspace buttons look stretched.
