### ISSUE TITLE
Double clicking the workspace numbers allows renaming button.

### ISSUE THREAD

**Issue by JC7897** [bbidulock/icewm#458]
Double clicking the workspace numbers allows renaming button.

![workspace-rename](https://user-images.githubusercontent.com/65046150/89242549-5b129300-d5f1-11ea-9b97-8f24d24ea357.png)

**Comment by Code7R** [comment]
I think this is a great feature. What is your concern?

**Comment by gijsbers** [comment]
Maybe the documentation is unclear on this? It renames a workspace.
Maybe the new workspace name should be saved to preferences automatically?

**Comment by JC7897** [comment]
Sorry i thought this was a bug.
