### ISSUE TITLE
The bottom of some windows in Firefox hidden below taskbar

### ISSUE THREAD

**Issue by frankzen** [bbidulock/icewm#461]
I just noticed this today. Firefox is 79.0 the latest. Icewm is 1.7.0.98
Regular windows are fine, but when maximizing some, the bottom of these are
hidden below task bar and changing layers doesn't help. The problem
does not exist when I run the Mate desktop. I have attached two screenshots to
illustrate the problem.
![Screenshot at 2020-08-06 16-57-27](https://user-images.githubusercontent.com/717662/89582392-8f12d180-d806-11ea-9d61-55dfc8e05ad1.png)
![Screenshot at 2020-08-06 16-57-47](https://user-images.githubusercontent.com/717662/89582411-9639df80-d806-11ea-8ac8-6ecdaa6fda19.png)

**Comment by gijsbers** [comment]
Hello Frank. I struggle to reproduce this for IceWM 1.7.0.104. Which operating system release version are you using?

**Comment by gijsbers** [comment]
Do other applications exhibit the same behavior?

**Comment by frankzen** [comment]
From the Icewm about:
![Screenshot at 2020-08-07 07-47-36](https://user-images.githubusercontent.com/717662/89642751-64665e80-d882-11ea-96c9-da7359781524.png)
I haven't noticed other applications being affected. And ss I said earlier Mate does not exhibit the same behaviour. The window affected is a tab FF opens to modify settings of extension ublock. I don't see how it could be a theme problem but I'll try changing them.

**Comment by gijsbers** [comment]
Frank what I meant was Linux distribution. This is usually in /etc/os-release.
`cat /etc/os-release` will do.

**Comment by frankzen** [comment]
PRETTY_NAME="Debian GNU/Linux bullseye/sid" 
NAME="Debian GNU/Linux" ID=debian 
HOME_URL="https://www.debian.org/" 
SUPPORT_URL="https://www.debian.org/support" 
BUG_REPORT_URL="https://bugs.debian.org/"


BTW different themes don't make a difference.

**Comment by frankzen** [comment]
The problem has cleared up with subsequent builds. Now running 1.7.0.115 Debian Bullseye.
