### ISSUE TITLE
Alt+Tab focus is broken in recent builds

### ISSUE THREAD

**Issue by mrbrainsample** [bbidulock/icewm#464]
Symptom:

If Window A has focus and you use Alt+Tab (QuickSwitch) to switch to Window B, Window B is raised to the front, but focus is immediately returned to Window A.

This appears to have been introduced between these commits:
acdfa810b16dee6568e0a2a4e8716fafe9330587
and
e39dad310e81076d8895213dcd8cc93399b5c14c

I would narrow it down more if I could, but acdfa8 is where issue #454 started affecting my builds. Commit e39dad fixed it, but exhibits the focus problem.

Let me know if you need more debugging/logs, etc.

**Comment by gijsbers** [comment]
This should be fixed by commit 4083070. Thanks for reporting it!

**Comment by mrbrainsample** [comment]
Yes, that fixed it.

Thank you so much for continuing to improve my favorite window manager!
