### ISSUE TITLE
Is there a way to add shadows to taskbutton text?

### ISSUE THREAD

**Issue by JC7897** [bbidulock/icewm#465]
Titlebar.
![shadows](https://user-images.githubusercontent.com/65046150/89897055-f72e3280-dbcd-11ea-82c8-f94efe0c263b.png)

Taskbar.
![noshadows](https://user-images.githubusercontent.com/65046150/89897074-00b79a80-dbce-11ea-8b82-e2fc50d0a64f.png)

**Comment by gijsbers** [comment]
Afraid not.

**Comment by JC7897** [comment]
Oh that sucks. Thanks though.
