### ISSUE TITLE
compton and switching themes causes segfault on exit.

### ISSUE THREAD

**Issue by JC7897** [bbidulock/icewm#469]
When i try and switch themes with compton on sometimes that screens starts flickering and will not load up icewm. When i hit CTRL+ALT+Backspace it get a segfault.

Backtrace
https://pastebin.com/1E0Sz8FH

**Comment by gijsbers** [comment]
It is a bug in the X11 server. You can report it to X.org or to your Linux distribution.

**Comment by JC7897** [comment]
Ok i will close this then. Thanks.
