### ISSUE TITLE
_NET_CLIENT_LIST_STACKING is not updated when focus is changed

### ISSUE THREAD

**Issue by PetteriAimonen** [bbidulock/icewm#47]
According to http://standards.freedesktop.org/wm-spec/1.3/ar01s03.html the root window property _NET_CLIENT_LIST_STACKING should give a list of the windows in the current stacking order, so that topmost window is last in the list.

Currently icewm only updates this property when new windows are opened, resulting in outdated information and thus inability to query the window stacking order from other applications.

Attached patch fixes this issue, and attached python script can be used to show the _NET_CLIENT_LIST_STACKING value for testing.

[0001-Update-_NET_CLIENT_LIST_STACKING-when-changing-windo.txt](https://github.com/bbidulock/icewm/files/34839/0001-Update-_NET_CLIENT_LIST_STACKING-when-changing-windo.txt)

[list_stacking_order.py.txt](https://github.com/bbidulock/icewm/files/34840/list_stacking_order.py.txt)

**Comment by bbidulock** [comment]
Patch applied.  Thank you!
