### ISSUE TITLE
Can I change the window icon after it has been opened?

### ISSUE THREAD

**Issue by DieSpinne** [bbidulock/icewm#470]
I have assigned a specific icon to `mc` in my `winoptions` file and assigned a key to `xterm -name mc -e mc`, so that when I launch Midnight Commander with that binding, the custom icon is used. However, if I launch it from an interactive shell by typing `mc`, I get no custom icon, but the terminal icon, on that window. I see that is the expected behavior, but can I change the icon somehow in that case?

I thought of `xdotool --icon-name` and `icesh setIconTitle`, but apparently neither do what I expected.

Is that possible at all? I think I will need to alias `mc` to `xterm -name mc -e mc` otherwise, but then I would have to use an speciall case when launching `mc` without an X session...

Thanks all!

**Comment by gijsbers** [comment]
The winoptions icon is determined by the WM_CLASS property of the window. If that is missing then the _NET_WM_ICON property has priority. You could change that one. Icewm watches for changes to it. Would be an interesting experiment.

**Comment by DieSpinne** [comment]
Thanks for your help, gijsbers. With `xterm -name "" -class ""`, I could get `xprop` to report `WM_CLASS(STRING) = "", ""` and `WM_ICON_NAME(STRING) = "mc"` for the window, but the icon is still the terminal icon. I did not find in `icesh` and `xdotool` any way to set `_NET_WM_ICON`... Any idea?

**Comment by gijsbers** [comment]
There is no standard way to do it. You need to search or hack it yourself. Here is:
http://www.leonerd.org.uk/code/xseticon/
or else:
https://stackoverflow.com/questions/10699927/xlib-argb-window-icon

**Comment by DieSpinne** [comment]
Fantastic! `xseticon` did the trick and it was not necessary to mess with `WM_CLASS`. Now I have this in `.bashrc`:
```
mc(){
    [ -n "$WINDOWID" ] && xseticon -id "$WINDOWID" "$mcIcon"
    /usr/local/bin/mc "$@"
    [ -n "$WINDOWID" ] && xseticon -id "$WINDOWID" "$termIcon"
}
```
It changes the icon upon entering `mc` in the terminal, and changes back after quitting MC. (`$mcIcon` and `$termIcon` are the paths to the icons.)
