### ISSUE TITLE
User notification about save-able workspace names

### ISSUE THREAD

**Issue by Code7R** [bbidulock/icewm#472]
While @JC7897 has closed #458 , I think the question raised there is valid. I suggest following:

- When user has edited the workspace name via pager, there shall be a message about the option to store the change permanently.
- The same behavior can also be applied to config changes from the Preferences menu .

Possible way to display prominent information:
call the command:
notify-send "Icewm configuration" "Icewm settings were changed. To store them persistently, please select Start / Preferences / Save Modifications." -i icewm -a icewm -a icewm 
Or implement its D-Bus call but that sounds like lots of code.

To avoid pestering the user too much with that, the bubble should be displayed only one or two times. Once when Workspace name is edited first time, once when some preference was changed first time.

@gijsbers , @JC7897 Does this sound reasonable and worthwhile?

**Comment by gijsbers** [comment]
Are such messages really necessary? I find them obnoxious and disturbing.
At least three users have reported about their inability to change workspace names (#443).
Changing workspace names should become much easier than it currently is.
My preference would be to have a serious GUI to control all preferences,
but lacking that we can just store the new workspace button name to file.
If that is unacceptable, it could also be saved only if you hit Shift+Enter.
We need to add clear documentation on how to change workspace names.

**Comment by JC7897** [comment]
I think it's a good idea if the user renames the button to save it to preferences or the prefoverride.
