### ISSUE TITLE
If you rename workspace buttons they look stretched.

### ISSUE THREAD

**Issue by JC7897** [bbidulock/icewm#476]
If you rename workspace buttons they look stretched. On some themes it's not a problem like nano blu.

NanoBlu
![NanoBlu](https://user-images.githubusercontent.com/65046150/90766638-37f51c80-e32f-11ea-9f8f-9c30907508e2.png)

CrystalBlue however looks like this.
![CrystalBlue](https://user-images.githubusercontent.com/65046150/90766696-4d6a4680-e32f-11ea-826a-5244918fdeba.png)

This what i would like it to look like.
![good](https://user-images.githubusercontent.com/65046150/90766773-7094f600-e32f-11ea-8c82-b75d29e2ec60.png)

You would need to do the same thing you did for the taskbuttons were you don't stretch the first 5 pixals and the last 5 pixals but stretch everything else.

**Comment by gijsbers** [comment]
In #239 we came up with TaskbuttonIconOffset. Does that solution apply here as well for workspace buttons?
Or do you want icewm to detect automatically how much of the gradient pixmap for workspace buttons is meant for the corner, which is to remain unstretched, and how much of the middle part should be stretched?

**Comment by JC7897** [comment]
The TaskbuttonIconOffset shifts the placement of the icon but it does not nothing for stretching problem if i'm not mistaken. Your second solution seems to me the right solution.

EDIT:  This is what TaskbuttoniconOffset = 0
![offset](https://user-images.githubusercontent.com/65046150/90954247-065a8d80-e4b6-11ea-97d4-5c4384b62fb5.png)

The TaskbuttoniconOffset must at least 4 for the button to look properly.  I guess i was mistaken.
