### ISSUE TITLE
Offer way to get out of icehelp to real $BROWSER

### ISSUE THREAD

**Issue by jidanni** [bbidulock/icewm#478]
In the menu choose "Help" and eventually get to this https://github.com/bbidulock/icewm/ .

That is good, but we are still locked inside the "icehelp" browser, with no button at top to break out to go to our real $BROWSER for the current page, nor even a way to copy the current URL so we can paste it into our real $BROWSER.

**Comment by gijsbers** [comment]
That is a correct observation.

**Comment by gijsbers** [comment]
Fixed in 7e4482cd424070efbb5e26eaf79923023696310e.
