### ISSUE TITLE
Avoid ppp* devices, in addition to lo, when monitoring

### ISSUE THREAD

**Issue by jidanni** [bbidulock/icewm#479]
Lately the ppp0 meter ( EN _ [__] __ __ mailbox time)
![5842-0](https://user-images.githubusercontent.com/1230959/91205491-3ca73f80-e738-11ea-80b6-b95bc3e0f119.jpg)
hardly is registering any traffic, even if I am using my maximum ADSL download speed (256 kB/sec.)
Maybe I need a way to tell it what my maximum is, in case it thinks I am on a high speed connection (100 times faster), and thus nothing hardly will show up as it is all too short.

**Comment by jidanni** [comment]
OK, https://www.speedtest.net/ finally made both red (download) and yellow (upload) show up real tall in the graph.
So maybe there should be a way for users to adjust the averaging algorithm used by the NetworkStatusDevice monitor,
to make rapidly fluctuating speeds not become zero.

**Comment by gijsbers** [comment]
#  Delay between Net Monitor samples in ms
    # TaskBarNetDelay=500 # [10-3600000]

**Comment by jidanni** [comment]
It turns out of
```
$ /sbin/ifconfig -s
Iface      MTU    RX-OK RX-ERR RX-DRP RX-OVR    TX-OK TX-ERR TX-DRP TX-OVR Flg
enp1s0    1500    58138      0      0 0         42665      0      0      0 BMRU
lo       65536     8234      0      0 0          8234      0      0      0 LRU
ppp0      1492    10017      0      0 0          8239      0      0      0 MOPRU
```
icewm now always (or sometimes? Last in the list today?) chooses ppp0. But ppp0 is just the virtual device. Thus the user needs to set
```
NetworkStatusDevice="e*"
```
Therefore icewm, in addition to already avoiding **lo**, should also avoid **ppp***, especially if there are other _real_ devices present.

**Comment by gijsbers** [comment]
The default value is:

    # NetworkStatusDevice="[ew]*"

Maybe your preferences is old and needs updating?
