### ISSUE TITLE
Clarify number of pixels per sample

### ISSUE THREAD

**Issue by jidanni** [bbidulock/icewm#480]
In icewm.html
```
  * TaskBarCPUSamples = 20

    Width of CPU Monitor.

  * TaskBarMEMSamples = 20

    Width of Memory Monitor.

  * TaskBarNetSamples = 20

    Width of Net Monitor.
```
"Samples" are perhaps typos for "Width".
Compare e.g.,
```
  * TaskBarApmGraphWidth = 10

    Width of APM Monitor.

  * TaskBarGraphHeight = 20

    Height of taskbar monitoring applets.
```

**Comment by gijsbers** [comment]
Samples is the number of measurements shown in the graph. Makes perfect sense. No typo.

**Comment by jidanni** [comment]
OK. Perhaps add a note like
`(Five pixels per sample.)`
or e.g.,
`(See also: PixelsPerSample.)`

**Comment by gijsbers** [comment]
Currently number of pixels is always equal to the number of samples. Simple as can be.
