### ISSUE TITLE
Wrong font for buttons since 6d557213227ea4952f7fe2f6b547bb26e8e8523c

### ISSUE THREAD

**Issue by targzeta** [bbidulock/icewm#484]
Hi,
I have this prefoverride:
<pre>
ActiveButtonFontNameXft    = "ArcadeAmerica:size=9:bold"
NormalButtonFontNameXft    = "ArcadeAmerica:size=9"
</pre>
Before the commit 6d557213227ea4952f7fe2f6b547bb26e8e8523c my workspace buttons were like that
![bb1ee19a965cf6d271936de7f641b822dbf36760](https://user-images.githubusercontent.com/2431105/91831645-9b8f1c00-ec44-11ea-92a6-aacefa75910d.jpg)
now, instead, are like that:
![6d557213227ea4952f7fe2f6b547bb26e8e8523c](https://user-images.githubusercontent.com/2431105/91831703-afd31900-ec44-11ea-8377-111f713822fe.jpg)

Thank you in advance,
Emanuele

**Comment by gijsbers** [comment]
Yes, if you do:

```
$ grep WorkspaceFontNameXft  preferences
# NormalWorkspaceFontNameXft="sans-serif:size=12"
# ActiveWorkspaceFontNameXft="sans-serif:size=12"
```

You see that that there also exists fonts specially for the workspace buttons.
In issue #475 a theme designer requested that they actually be used.
Commit 80c5b4af3f9d4e3af3600f045d60d9c1dc1fb4d6 implemented that request.
You need to check and possibly define those font names as well.

**Comment by targzeta** [comment]
Hi @gijsbers,
yes, with these settings the buttons are rendered again with the correct fonts.

I haven't told you that my prefoverride also sets:
<pre>
ActiveWorkspaceFontNameXft    = ""
NormalWorkspaceFontNameXft    = ""
</pre>
and the doc says:
<pre>
# Name of the active workspace button font (fallback: ActiveButtonFontName)
# NormalWorkspaceFontNameXft="sans-serif:size=12
</pre>
so, I think that it doesn't do the fallback.

Thank you again,
Emanuele

**Comment by gijsbers** [comment]
You should check if your settings take effect by:
 `icewm --postpreferences | grep -e ButtonFont -e WorkspaceFont`.
If you could read commit 80c5b4af3f9d4e3af3600f045d60d9c1dc1fb4d6
then you should see that it first attempts the workspace font
and if that fails does it attempt the button font. I tested this and it worked.
Maybe you only set the Xft font names, but not the plain font names (without Xft suffix.)

**Comment by targzeta** [comment]
Yes, I have olny the NormalWorkspaceFontNameXft and not the NormalWorkspaceFontName in my prefoverride. It's a little intricate, but it's clear!

Thank you for your works!
Emanuele
