### ISSUE TITLE
menuprogreload bug since 1.8.1

### ISSUE THREAD

**Issue by zaza42** [bbidulock/icewm#487]
I have a small shellscript (from somewhere), which generates sub-menus for every running processes:
```
if [ $# = 1 ]; then
        set `ps -p $1 --no-header -o pid,%cpu,%mem,time`
        echo "prog 'CPU: $2%' - true"
        echo "prog 'MEM: $3%' - true"
        echo "prog 'TIME: $4' - true"
        echo "separator"
        for i in HUP INT KILL TERM STOP CONT; do
                echo "prog $i - kill -$i $1"
        done
else
        ps -aU `id -ru` --no-headers -o '%p|%c' |\
	    grep -v -e iceps.sh$ -e awk$ -e ps$ -e grep$ |\
	while IFS="|" read -r procpid procname; do
		echo menuprogreload \"${procpid#* } $procname\" - 0 $0 $procpid
	done
fi
```
I'm using it as `iceps.sh` in `~/.icewm/menu`:
```
menuprogreload "Running processes" /usr/share/icons/hicolor/16x16/apps/atril.png
 60 /home/DC-1/scripts/iceps.sh 
```

Til version 1.8.0 I've got the right menu entries:
![icewm-1 8 0-processes](https://user-images.githubusercontent.com/16356124/92098818-045bcd00-edda-11ea-8456-5c189c46f305.png)
But version 1.8.1 only shows the first entry:
![icewm-1 8 1-processes](https://user-images.githubusercontent.com/16356124/92098857-1178bc00-edda-11ea-9d4a-06e69700dc64.png)

Was something changed in `menuprogreload` scheme between these version or is it a bug? :-> 

(Debian/sid x86_64)

**Comment by gijsbers** [comment]
b20e3fd9e79ff39a119a202ba1881af10ba762b8

**Comment by gijsbers** [comment]
You can try this. Looks good to me now. Nice script BTW.

**Comment by zaza42** [comment]
Fixed, thanks!
