### ISSUE TITLE
Net monitor no longer works

### ISSUE THREAD

**Issue by frankzen** [bbidulock/icewm#488]
Noticed today that the net monitor no longer works. Version 1.8.1.22  dl'ed and compiled yesterday. According to preferences
this is what is being monitored.

NetworkStatusDevice="[ew]*"

Running Debian Bullseye/Sid

I have no idea what the device is called under my distro.

**Comment by frankzen** [comment]
Just discovered it's called eno1. Put that in preferences but still no monitoring.  Is there anything else which would affect this ?

**Comment by gijsbers** [comment]
The file size of /proc/net/dev was reported as 0 bytes, even though it does have content.
```
ls -l /proc/net/dev
cat /proc/net/dev
```
Should work now.

**Comment by frankzen** [comment]
Fixed. Thank you.
