### ISSUE TITLE
Taskbar autohide again

### ISSUE THREAD

**Issue by LastOfBrunnenG** [bbidulock/icewm#49]
Version 1.3.8 for Vector Linux (Slackware based), as well as 1.3.8 built from source code. Taskbar does not auto hide, once it has been shown. The only way to hide it is to launch an application by choosing it from main menu, which must be activated from 'start' button. The problem has been fixed at least twice in previous releases, I think. Now, it seems to be back again. I switched to 1.3.5 built from source, because it seems to be working there.

Takbar has been set to autohide in preferences file, of course. Making it double height or single height doesn't seem to make a difference.

**Comment by bbidulock** [comment]
Fixed long ago, I believe.  Try the 1.3.11 release available [here](/bbidulock/icewm/releases).

**Comment by LastOfBrunnenG** [comment]
Thanks, I am going to check it out.
