### ISSUE TITLE
icewm panel must get a dock like applet

### ISSUE THREAD

**Issue by zakarriyah** [bbidulock/icewm#490]
I really like icewm but i had to disable the panel since I needed an icon only panel , so i had to use xfce panel with dockbarx plugin , it'd be great if icewm's panel looked like cinnamon de's icon only panel . <img  src ="https://raw.githubusercontent.com/siduck765/icewm-dotfiles/master/fina.png" > , 
<img src ="https://i.redd.it/foyxy2ltayj51.png"> ,

**Comment by gijsbers** [comment]
There are so many TaskBarShow to turn off what you don't want.
Then you can have just a toolbar with your icons, a clock and a tray.

**Comment by zakarriyah** [comment]
> There are so many TaskBarShow to turn off what you don't want.
> Then you can have just a toolbar with your icons, a clock and a tray.

I can remove the text on taskbar? having only icon only tasks?

**Comment by cheapy** [comment]
You mean like this?  You could change preferences from the menu or with an editor, or copy and rename my prefoverride.txt to ~/.icewm/prefoverride file and the screen would look like this:

[prefoverride.txt](https://github.com/bbidulock/icewm/files/5936286/prefoverride.txt)

![screenshot](https://user-images.githubusercontent.com/7473967/107109414-ee798a80-6805-11eb-9352-6803e503a1cb.jpg)
