### ISSUE TITLE
winoption dBorder: 0 leaves black lines as borders [1.8.3]

### ISSUE THREAD

**Issue by zaza42** [bbidulock/icewm#492]
I'm using transparent terminals with some statistics on it. Til version 1.8.2 `dBorder: 0` fully eliminates all borders:
![maim-2020-09-17_11:40:49](https://user-images.githubusercontent.com/16356124/93454617-84eef300-f8db-11ea-8656-bf67a9a41296.png)
Watch bottom right: 3 urxvt terminals.

Then icewm version 1.8.3 did this:
![maim-2020-09-17_11:39:31](https://user-images.githubusercontent.com/16356124/93454708-a2bc5800-f8db-11ea-9134-25c4a7094e87.png)

Relevant part of my `~/.icewm/winoptions`:
```
fsuspend\.urxvtc.layer: Below
fsuspend\.urxvtc.allWorkspaces: 1
fsuspend\.urxvtc.ignoreQuickSwitch: 1 # Don't alt-tab switch
fsuspend\.urxvtc.ignoreWinList: 1 # Don't put in window list
fsuspend\.urxvtc.ignoreTaskBar: 1 # Don't put in task bar
fsuspend\.urxvtc.dTitleBar: 0 # No title bar (close& max. button)
fsuspend\.urxvtc.dBorder: 0
```
`fsuspend.urxvtc` is only a symlink to `/usr/bin/urxvtc`, because I don't want to turn off borders for all terminals. For example the one at top left.
Contents of `fsuspend.dstat`:
```
fsuspend.urxvtc -fade 0 -depth 32 -cr rgba:2600/6200/9400/ffff \
    -bg rgba:2600/6200/9400/ffff \
    -geometry 79x11+1002+750 \
    -fn -gohu-gohufont-medium-r-normal--11-80-100-100-c-60-iso10646-1 \
    -tr -uc -ut -e sh -c "/bin/echo -ne '\033[?25l' ;exec nice -n5 dstat -md -D sda -c --top-bio"
```

Is it a bug or something new value in winoptions which i haven't set?

Debian unstable/sid, x86_64

**Comment by gijsbers** [comment]
No such changes have been made. The dBorder:0 is about the external frame border. What you show is some urxvt border. Could you check with xwininfo? Urxvt has both an external border and an internal border. If I start it like you do then I see this in the logevents output:
```
IceWM: window=0x5200007: create serial=29024 parent=0x13F, (+1002+750 887x237) border_width=0, override_redirect=False
```
This image shows fsuspend.dstat without a border:
![492-d](https://user-images.githubusercontent.com/4169687/93468395-30ee0980-f8ef-11ea-9575-54baade2da0d.png)
Maybe set LogEvents=1 and grep your window id in the output?

**Comment by gijsbers** [comment]
`urxvt -bl` should also work.
Obviates dBorder and dTitleBar.
Since 1.6.6 and a23a3773115f110b9441d4a9b60e5de5e87295f8.
`xwininfo -frame -tree` should show offsets as `+0+0`.

**Comment by zaza42** [comment]
New experience: the black bars instantly disappear when I move the window and they never come back again.
So this bug affects the first position at first run.

With screenshots:
![maim-2020-09-18_12:49:05](https://user-images.githubusercontent.com/16356124/93589962-f7300800-f9ad-11ea-8ecc-79682e2450ed.png)
Look at the top center urxvt. The transparency isn't correct, too. 

Then I move the window to right by some pixels:
![maim-2020-09-18_12:49:13](https://user-images.githubusercontent.com/16356124/93590036-1b8be480-f9ae-11ea-8b78-37366b4274d3.png)
Magically everything is fine.

I think 1.8.2 did one more refresh at first instance, while 1.8.3 is "optimized", and refreshing only when some action happened to the window.

By the way here you are the logevents of fsuspend.dstat with icewm 1.8.3:
```
12:39:45.345: IceWM: window=0x1000060: create serial=135920 parent=0x6D7, (+1002+750 478x125) border_width=0, override_redirect=False
12:39:45.347: IceWM: window=0x1000060: mapRequest serial=135920 parent=0x6D7
12:39:45.348: IceWM: window=0x1000060: reparentNotify serial=135951 event=0x1000060, parent=0xE006AA, (0:0), override_redirect=False
12:39:45.348: IceWM: window=0x1000060: reparentNotify serial=135951 event=0x6D7, parent=0xE006AA, (0:0), override_redirect=False
12:39:45.348: IceWM: window=0x1000060: reparentNotify serial=135951 event=0xE006AA, parent=0xE006AA, (0:0), override_redirect=False
12:39:45.351: IceWM: window=0x1000060: mapNotify serial=136098 event=0x1000060, override_redirect=False
12:39:45.352: IceWM: window=0x1000060: mapNotify serial=136098 event=0xE006AA, override_redirect=False
12:39:59.761: IceWM: window=0xE006AA: EnterNotify serial=137614 root=0x6D7, subwindow=0x1000060, time=1634440698, (200:61 1202:811) mode=Ungrab detail=Virtual same_screen=True, focus=False state=0x0
12:40:00.457: IceWM: window=0xE006AA: LeaveNotify serial=137754 root=0x6D7, subwindow=0x1000060, time=1634441394, (240:-2 1242:748) mode=Normal detail=Virtual same_screen=True, focus=False state=0x0

```

ps. thanx for the tip `urxvt -bl`!!! I'm using this transparent+borderless configuration since IceWM 1.3.x, and I haven't read all changelogs then. :->

**Comment by gijsbers** [comment]
After examining the urxvt code I decided to always send one synthetic ConfigureNotify on startup.
This was an exceptional case, because you used dTitleBar:0 and dBorder:0 in connection with `urxvt -tr`.
Thanks for reporting this issue. I think it is now fixed by b5933ab.

**Comment by zaza42** [comment]
Thx, the new git version has fixed this problem.

**Comment by zaza42** [comment]
New version of rxvt-unicode has arrived: [9.26](http://dist.schmorp.de/rxvt-unicode/), and this bug has also arrived again. :-<
![rxvt-9 26-transparent](https://user-images.githubusercontent.com/16356124/122183689-c8d35080-ce8b-11eb-8f74-e2bfbe1c24a9.png)

IceWM-2.4.0
Debian sid/experimental x86-64

The bug is the same: after I moved the transparent window to 1 pixel to anywhere, then everything is perfect again.

**Comment by gijsbers** [comment]
Is this a bug in icewm or in rxvt-unicode 9.26?

**Comment by zaza42** [comment]
It should be in rxvt-unicode, because the [newer version](https://tracker.debian.org/news/1242867/accepted-rxvt-unicode-926-1-source-amd64-into-experimental/) caused this problem. 
IceWM remained the same.

**Comment by gijsbers** [comment]
If it is in rxvt-unicode, which I think it is, then they need to fix their code and we can close this issue.

**Comment by zaza42** [comment]
Ok. I can report it. 
Rxvt seemed to be an abandoned project last year, because the previous version was released at 2016-11-16.  After 5 years v9.26 has came at 2021-05-14. I hope Schmorp (the developer) can fix it now.

**Comment by gijsbers** [comment]
Maybe test if setting internalBorder and externalBorder to 0 helps or not.

**Comment by zaza42** [comment]
These settings didn't help, but… I've figured out the exact case when this bug appears: `-geometry 80x25+100+100`. The relevant part is the position, not the size. When i add only `-geometry 80x25` it starts without any bug. And I can reproduce the bug with only `-geometry +100+100` parameter.

The full command line for reproducing: `rxvt -bl -tr -geometry +100+100 -e top`
![maim-2021-06-16_12:00:16](https://user-images.githubusercontent.com/16356124/122199585-7a797e00-ce9a-11eb-90d3-afbf1c2198aa.png)


Any idea, or should I finish the report to urxvt?

**Comment by gijsbers** [comment]
It isn't their first bug (see above), so yes, it would be useful
for the future if they become more aware of their slippages.

**Comment by zaza42** [comment]
Ok, i've reported it: http://lists.schmorp.de/pipermail/rxvt-unicode/2021q2/002611.html .
Now waiting… ;->

**Comment by zaza42** [comment]
I've played more with the recent icewm-2.4.0 and urxvt-9.26, and strange effects have come:
~/.icewm/winoptions
rxvt.URxvt.dBorder: 0    + rxvt -tr  --> correct transparency with title bar
rxvt.URxvt.dBorder: 0    + rxvt -tr -bl  --> blackborder + transparency bug
one more line:
rxvt.URxvt.dTitleBar: 0
rxvt.URxvt.dBorder: 0    + rxvt -tr --> the known bugs
Nothing in ~/.icewm/winoptions + rxvt -bl --> no black borders with no transparency!

I've also set up a new user with jwm (joe's window manager) and I can't reproduce this bug.
So I think IceWM wrongly handles transparency when titlebar is also hidden.

**Comment by gijsbers** [comment]
Can you give the exact `configure` statement? It is without the debian modifications?

**Comment by zaza42** [comment]
I'm using the [debian modifications](http://deb.debian.org/debian/pool/main/i/icewm/icewm_2.3.4-1.debian.tar.xz) over source 2.4.0.
But I can reprouce the exactly same with debian [binary package](https://packages.debian.org/experimental/amd64/icewm/download).

**Comment by gijsbers** [comment]
What is the full configure statement in detail?

**Comment by gijsbers** [comment]
No, I mean how is the urxvt configured? Did you include the debian urxvt changes?

**Comment by gijsbers** [comment]
I configured urxvt 9.26 like sid/experimental, but I still can't reproduce your bug.
Could you check with `xwininfo` that the buggy terminal has
```
  Relative upper-left X:  0
  Relative upper-left Y:  0
```
The dimensions should be the same as for `xwininfo -frame`.

**Comment by zaza42** [comment]
Yes, right.
![rxvt-xwininfo2](https://user-images.githubusercontent.com/16356124/122384290-d829cb00-cf6b-11eb-9171-a28705884be9.png)

**Comment by gijsbers** [comment]
Well that is clear. Now my reasoning is this:
Because the client window (rxvt) is precisely above the frame, and
has the same dimensions, the frame can't influence what you see.
Both have a X11 border width of zero pixels, so no influence there.
Hence the black line is solely due to whatever rxvt draws or
doesn't draw. Hence icewm can't influence this.

**Comment by zaza42** [comment]
And what can cause slipped transparency?

**Comment by gijsbers** [comment]
Transparency is handled by the compositor.

**Comment by gijsbers** [comment]
Could it be that you have additional X resources defined for rxvt?
Because sofar it can't be reproduced.

You could also try this:
start a `Xephyr`, start `icewm --logevents -d :1`, start rxvt.
Then, if this issue has any merit, you should be able to see
a non-zero x/y-position for rxvt in configureNotify or
reparentNotify events.

**Comment by zaza42** [comment]
Okey, I've found it: this may be an xorg/feh bug, because the command `feh --no-fehbg --bg-scale /usr/share/wallpapers/debian/debian-blue.png` repairs the wrong transparency instatly.

I still don't understand why this didn't happen with the older IceWM versions, but whatever.
