### ISSUE TITLE
In logout dialog box does not mark the button that fires when the "Enter" key is pressed

### ISSUE THREAD

**Issue by jinn-alt** [bbidulock/icewm#494]
In commit https://github.com/bbidulock/icewm/commit/03d524ffb4672f06d89a38dd1a50bcd7f387da5b was appeared regression, in logout dialog box does not mark the button that fires when the "Enter" key is pressed, due to eroneously deleted call getProtocols(true).
Fix for this issue here https://github.com/jinn-alt/icewm/commit/2310a65ca6530be113e9778101b4aa0918c1c692
Thanks.

**Comment by Code7R** [comment]
Thank you. I wanted to report the lack of focus indicator in the last "Confirm logout" dialog today. I.e. there was no visible Tab pressing response in 1.8.3. This seems to work now so I guess the problems were related?

@jinn-alt Can we close it?

**Comment by jinn-alt** [comment]
Yes. Thanks.
