### ISSUE TITLE
Pager does not correctly display the resizing of the application window

### ISSUE THREAD

**Issue by jinn-alt** [bbidulock/icewm#496]
I looked attentively and discovered the incorrect behavior of the pager.
He does not correctly display the resizing of the application window.
Steps of reproduce:
1. Run an application, for example a terminal emulator. The pager displays its window.
2. Use the "Maximize" button to maximize the window. The pager does not display this action.
3. Make a mouse click anywhere in the taskbar or reduce the size of the window using the "Restore" button.
The pager displays an increased application window.
I found this pager behavior since from commit be3cedd703004f6d15aa95588cf9ed181ffb42b4.

**Comment by gijsbers** [comment]
Thanks for reporting this. There were several cases. Now fixed.

**Comment by jinn-alt** [comment]
I close. Thank you for your work.
