### ISSUE TITLE
Can both row of the dual height taskbar be used for window list display

### ISSUE THREAD

**Issue by QiangF** [bbidulock/icewm#498]
even with this https://github.com/bbidulock/icewm/pull/46
, the top row is still mostly empty, can both row be used for window list display?

**Comment by gijsbers** [comment]
Do you maybe have `TaskBarShowAllWindows=1`?
Maybe you can describe more about your problem situation?
Do you always have so very many windows open?
Maybe you can move some of them to the tray with 
https://ice-wm.org/man/icewm-winoptions#general-options
tray: Minimized or tray: Exclusive?

**Comment by QiangF** [comment]
I have TaskBarShowAllWindows=0.
I mostly use the keyboard, but you have to use the mouse some applications like gimp. So have a autohide taskbar with all spaces utilized is very nice. Maybe we can have taskbar with triple height or even more. But that will make it hard to find the window in the pile. Ahh, I will stick with rofi for the window switching.
Thank you for the suggestions.

**Comment by gijsbers** [comment]
This gives another motivation for #198.
