### ISSUE TITLE
The gettext requirement is too high for most distributions currently

### ISSUE THREAD

**Issue by DeltaResero** [bbidulock/icewm#5]
Priority: High

The latest stable versions of Ubuntu (13.10) and Debian (Wheezy) currently use gettext version 0.18.1 while the requirement here is now 0.18.3.  There are several other distributions which are in a similar situation.  While changing 0.18.3 to 0.18.1 in configure.ac might allow for Ubuntu 13.10 and Debian Wheezy (and newer) to build this, it isn't the proper way to fix it nor am I completely sure that would work.  I don't have time to look into this more right now, so I'm just reporting the issue here.

**Comment by bbidulock** [comment]
Sorry, I use Arch.  It's like Tim Horton's (always fresh).  Need at least 0.18 for [external] option for glibc that includes gettext.

**Comment by DeltaResero** [comment]
This was why I thought more would have to be done other than just changing it to just 0.18: http://lists.gnu.org/archive/html/automake-patches/2013-01/msg00124.html

**Comment by DeltaResero** [comment]
Yeah that's it.  I wasn't sure what the syntax for it would be without having to look through the code and I didn't have time for that yesterday.  I think the use of automake was a huge improvement and with this it should now be possible to build on all current Linux distributions.  I'm closing this issue as it seems to be resolved now.
