### ISSUE TITLE
Logout menu, shutdown and reboot

### ISSUE THREAD

**Issue by LastOfBrunnenG** [bbidulock/icewm#50]
Shutdown and reboot commands don't seem to do anything, no matter how you define them in preferences file. Version 1.3.8, Vector Linux 7.1. 1.3.8 built from source, exactly the same. 

Works flawlessly in 1.3.5. built from source.

**Comment by bbidulock** [comment]
I think that this one was fixed long ago too.  Try the 1.3.11 release available [here](/bbidulock/icewm/releases).
