### ISSUE TITLE
How to prevent black screen on inactivity?

### ISSUE THREAD

**Issue by gelinger777** [bbidulock/icewm#501]
I have installed ICEWM on newest Ubuntu 20.04 . All works perfect, but on inactivity it shuts down the screen . 

I have tried many things like 

```

xset -dpms
xset s off

```

in startup config of the icewm ,

I have uninstalled the power manager of the ubuntu-desktop, i have set in grub acpi=off,apm=off 

But neither of them worked. 

Any idea how to solve the problem? We need that the display constantly works and not goes off...

**Comment by gijsbers** [comment]
IceWM doesn't know or do anything with screen saving or energy.
That is actually a wish: some code to detect if a monitor is turned off.
But how to do that remains a mystery sofar. If you know, please tell us.
Usually the Arch Wiki has good info. Try this:
https://wiki.archlinux.org/index.php/Display_Power_Management_Signaling#xset_screen-saver_control
Good luck!

**Comment by gijsbers** [comment]
xset -dpms s off s noblank s 0 0 s noexpose

```
Add the the following options at the end of your ServerLayout section in /etc/X11/xorg.conf

    Option "BlankTime" "0"
    Option "StandbyTime" "0"
    Option "SuspendTime" "0"
    Option "OffTime" "0"

Like so:

Section "ServerLayout"
    Identifier     "Layout0"
    Screen      0  "Screen0" 0 0
    InputDevice    "Keyboard0" "CoreKeyboard"
    InputDevice    "Mouse0" "CorePointer"
    Option         "Xinerama" "0"
    Option         "BlankTime" "0"
    Option         "StandbyTime" "0"
    Option         "SuspendTime" "0"
    Option         "OffTime" "0"
EndSection
```

**Comment by DieSpinne** [comment]
Is `IdleAction=ignore` in `/etc/systemd/logind.conf`?

**Comment by gelinger777** [comment]
Still didn't had time to try, as I have crashed that PC ... Will test next week and let you guys know. I really appreciate your help!

**Comment by gelinger777** [comment]
@DieSpinne  I have made it IdleAction=ignore , did not helped.

**Comment by gelinger777** [comment]
@gijsbers  i don't have /etc/X11/xorg.conf should I create one? 

Should I put the line 

```
xset -dpms s off s noblank s 0 0 s noexpose
``` 
in the .icewm/startup ? Or ?

**Comment by gijsbers** [comment]
Here we only deal with the window manager IceWM, which is
about positioning application windows and directing input focus.
