### ISSUE TITLE
xnec2c window missing its decorations and taskbar entry

### ISSUE THREAD

**Issue by Code7R** [bbidulock/icewm#503]
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=972498 for details.

Interestingly, the window gets proper behavior when you start another WM like blackbox and then restart icewm.
The obvious difference is that it got _NET_WM_... and _WIN_... properties assigned, see attachment.

However, I checked icewm code (even latest git state) briefly in debugger and it seems to run properly through YFrameWindow::paint,  YFrameWindow::updateTaskBar, etc. and the bitfields in YFrameWindow::getFrameHints  look sane. Strange thing.

The app to test it is xnec2c from https://packages.debian.org/sid/xnec2c .
[information.txt](https://github.com/bbidulock/icewm/files/5402093/information.txt)
[information_after_other_wm.txt](https://github.com/bbidulock/icewm/files/5402096/information_after_other_wm.txt)

**Comment by Code7R** [comment]
Tried winoptions but nothing is effective, like

xnec2c.dBorder: 1
xnec2c.dClose: 1
xnec2c.dTitleBar: 1
xnec2c.ignoreNoFocusHint: 0

**Comment by gijsbers** [comment]
Xnec2c has some strange non-standard behaviors on startup.
Here it goes wrong for ICCCM section "4.1.4. Changing Window State".
Commit 6019c00 introduces a workaround.

**Comment by Code7R** [comment]
Many thanks from the reporting user, fix confirmed.
