### ISSUE TITLE
Taskbar hover peek at window instead of tooltip text?

### ISSUE THREAD

**Issue by cheapy** [bbidulock/icewm#504]
Some MS OS's and Linux XWindow manager panels have the ability to raise the window itself when you hover over its taskbar entry.  

Does IceWM already have a way to do that?  If the ability exists already, please let me know how to configure it.

If not, could I request an enhancement to make it as good or better than the others?

I would prefer it would "peek" (ie temporarily activate the window in hover mode) based on a hover delay over the taskbar entry .  It could be instead of the tool tip popup that appears now.

So if you hover longer than say 250 ms, hover mode is turned on and the window itself activates.  The delay prevents it from activating all of the windows as you move across the taskbar.  

If autohide is on, there needs to be a border a small number of pixels high on outer edge, not sure if the number of pixels needs to be configurable, where it pops up the taskbar, but doesn't turn on hover mode.  

Once in hover mode, if you move off the taskbar entry, it ends hovering and reverts to the layout before you hovered.  
If you left click the icon it ends hovering, and activates the window.  
If you right click the icon it ends hovering reverts to the layout before you hovered and pops up the window options menu same as now.

TaskbarHoverPeek = 0   # 0/1
TaskbarHoverPeekDelay = 250

This is a real nice feature to have when you want to look at other documents while working on a different one.

**Comment by gijsbers** [comment]
Did you first play with all the existing mechanisms? Maybe look at:
```
# KeyWinPrev="Alt+Shift+F6"
# KeyWinNext="Alt+F6"
# KeySysWinNext="Alt+Esc"
# KeyTaskBarSwitchNext=""
# KeyTaskBarSwitchPrev=""
```
You can also cycle over all applications with the mouse wheel when the pointer is over the task buttons.

**Comment by cheapy** [comment]
Yes, I tried each, but they don't fit the workflow.  The closest is to just activate and deactivate the window.  Tint2 has the mouse wheel raise the app if I recall.  I tested using openbox on Bunsen labs which comes with tint2.  It did not cycle through them.  The cycle through via mouse wheel is not something I would use because 99% on the time I am using laptops with a track pads, no mouse wheel and only 2 buttons. That's why the hover feature is so convenient/comfortable to use.

**Comment by gijsbers** [comment]
How would the hover feature combine with the proposed task grouping feature is issue #198?
Maybe this could best be done by using the Alt+Tab quick switch?

**Comment by cheapy** [comment]
Actually, yes, that would be FANTASTIC!  Because not only could you have the basics of hovering to open pager views, but also IceWM has many, many more window options that would be available as a result.

That is the way that they keep the number of taskbar icons reasonable in W10.  They have one icon for a program like Firefox, and if you hover over that icon on the taskbar, it pops up 4 more pager thumbnail views for the 4 windows of that program running (in the Firefox example on #198), with a Tooltip above each saying what is open, and if you hover one of those pager views, it temporarily pops up the real view of it so you can see what is actually in that window itself, and if you click that pager view, it makes the real view active, and if you move off the pager view, it reverts back to the way it was.  If instead you right click the pager view you get the window menu for that window, which in W10 doesn't have much it can do, but in IceWM is super powerful in it's abilities.

**Comment by cheapy** [comment]
Here is a pic from another system.  I have 4 Firefox windows open, but none are visible.  I hover the Firefox icon on the taskbar, and the 4 pager views with tooltips appear.  I hover one of the pager views and that window becomes active temporarily on the screen in the size and position it would normally be.  That is when I took this pic.
![20201029_194057](https://user-images.githubusercontent.com/7473967/97647813-290ea280-1a21-11eb-8a64-1c90c9785f0e.jpg)

**Comment by cheapy** [comment]
Maybe this isn't obvious...  In IceWM as I open more Firefox windows the icons on the taskbar get smaller and I have less clue as to which is which.  The grouping from #198 will reduce the number of icons, and hovering would then give me a pager view of each of the ones in that group.  For it to be really useful day to day, to have get it to pop up by hovering over that pager is needed because many can look similar.  When I see the one I need to read I just read it, and if I need to copy a block of code, text or image from it, I click.

W10 has an alt-tab switch screen that it brings up when there are so many pager views that they won't all fit, and at that point I try to reduce open windows if I can, so I can see again, because it isn't helping me anywhere near as much without those pager views and the ability to see what is inside.

**Comment by gijsbers** [comment]
Those preview windows are yet unavailable to IceWM.
That would require a compositor, which is a substantive addition.
But could we use the Alt+Tab to do it?
Alt+Tab to cycle over your windows, which in turn will be mapped and raised?

**Comment by cheapy** [comment]
I would not want to try to turn a Cheetah into a Sloth, so no, I am trying not to ask for a huge modification.  The taskbar is ok as is if major mods which would make it slower and big would be needed to combine icons into taskbar groups.  

IceWM is my favorite because overall it is the fastest and most efficient (even on old slow hardware) at doing what my fingers expect without me needing to think about it.  I think that is what someone once meant by "feels right".

I am using my trackpad, searching for the right screen in the easiest way possible.  I always have too many workspaces, windows and tabs open.  The tooltips (they have the title value) off the taskbar help a lot at identifying is this the window I want, but it would be nicer if when I am hovering over it and thinking about it, if it would just pop it up for me to help me decide quicker...  I guess I need to click and unclick, but if ever you see a way, it would make for a better workflow if hovering the taskbar icon could be configured to activate the window temporarily.

**Comment by cheapy** [comment]
What if I was to offer a small bribe?  If I was capable of programming this, I would, but I'm not a C++ programmer.  Maybe its just not doable?

**Comment by gijsbers** [comment]
It is not yet clear how to implement this idea neatly.
A feature can't just be added. Its code must also fit in nicely.
Otherwise it becomes a maintenance burden in the long run.
This is currently the case with features like TaskBarAutoHide
and TaskBarFullscreenAutoShow. Their code is problematic.

**Comment by cheapy** [comment]
Yes, I understand that.  Its all the permutations of different setup environments it needs to work correctly in that will cause trouble because it could be affected by anything touching it, or affect anything it touches.
