### ISSUE TITLE
Interacting with Xmgrace frequently crashes Icewm

### ISSUE THREAD

**Issue by DieSpinne** [bbidulock/icewm#506]
[Xmgrace](https://en.wikipedia.org/wiki/Grace_%28plotting_tool%29) crashes Icewm in many cases, and since it is a Motif tool just as Icewm I'm quite surprised. The cases that trigger a crash in Icewm (1.8.3) do not trigger a crash in Mwm.

Example: Just open Xmgrace and a sub-window via `Window > Drawing objects > Elipse props...`. Then Alt-Tab in and out of Xmgrace, and it will eventually crash.

I suspect this report by itself is insufficient, so I apologize in advance and please feel free to point me the steps to provide more relevant information.

**Comment by bbidulock** [comment]
Thank you for the bug report; however, if Xmgrace crashes, how is this an icewm problem?  Is it not an Xmgrace problem?

**Comment by gijsbers** [comment]
It is icewm which crashes if the example is followed.
@DieSpinne You can produce diagnostics with valgrind.
Try either "valgrind icewm" or "icewm-session --valgrind".
Are there more example scenarios?

**Comment by gijsbers** [comment]
Since 3b207539ed1533f8d696d2f5d4d146bd5477a3eb

**Comment by gijsbers** [comment]
The recursion on client leader in YFrameWindow::doRaise() was hopelessly ambitious.
This code from 2009 was never tested against a real client leader.
It could simply be removed! The new code unfolds recursion and enforces termination.
@DieSpinne You can test this. We need a new release.

**Comment by DieSpinne** [comment]
@bbidulock Yes, sorry, I meant Icewm crashes.
@gijsbers Thank you. I have tested it and that particular problem is gone. However, I still can't close any subwindow that Xmgrace generates. The screen blinks and it simply does not go away, the only option is to close Xmgrace main window or to kill Xmgrace. Can you reproduce it?

Here is the Valgrind log, which was generated from `startx /usr/bin/valgrind --log-file=log /usr/bin/icewm-session`:
```
==20623== Memcheck, a memory error detector
==20623== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==20623== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==20623== Command: /usr/bin/icewm-session
==20623== Parent PID: 20613
==20623== 
==20623== 
==20623== HEAP SUMMARY:
==20623==     in use at exit: 0 bytes in 0 blocks
==20623==   total heap usage: 57 allocs, 57 frees, 83,371 bytes allocated
==20623== 
==20623== All heap blocks were freed -- no leaks are possible
==20623== 
==20623== For counts of detected and suppressed errors, rerun with: -v
==20623== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
==20812== 
==20812== HEAP SUMMARY:
==20812==     in use at exit: 65,298 bytes in 37 blocks
==20812==   total heap usage: 897 allocs, 860 frees, 186,296 bytes allocated
==20812== 
==20812== LEAK SUMMARY:
==20812==    definitely lost: 0 bytes in 0 blocks
==20812==    indirectly lost: 0 bytes in 0 blocks
==20812==      possibly lost: 0 bytes in 0 blocks
==20812==    still reachable: 65,298 bytes in 37 blocks
==20812==         suppressed: 0 bytes in 0 blocks
==20812== Rerun with --leak-check=full to see details of leaked memory
==20812== 
==20812== For counts of detected and suppressed errors, rerun with: -v
==20812== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by gijsbers** [comment]
Every subwindow I can close.
Either by the Close button inside a window,
or by the title frame close button, or by Alt+F4.
Do none of these 3 methods work for you?
Maybe you have some particular preferences setting?

**Comment by gijsbers** [comment]
The valgrind is only useful if icewm crashes.
But then you must not use it on icewm-session,
but either "valgrind icewm" or "icewm-session --valgrind".
The valgrind must be on icewm, which icewm-session
can do for you if you use the second form, otherwise
use the first. But only if wish to report a icewm crash.

**Comment by DieSpinne** [comment]
None of those 3 methods worked for me. But that must be because I got confused on how to compile Icewm with the changes (I found no `configure` script in [the latest sources](https://github.com/bbidulock/icewm)), so if all went OK for you, please disconsider it. I have very little familiarity with patches and branches and etc. Thank you for taking the time to teach me the Valgrind.

**Comment by gijsbers** [comment]
To get a configure you need to run the autogen.sh script.
The website explains all the steps how to compile from git in
the section "Install from unreleased development source code".
```
$ git clone https://github.com/bbidulock/icewm
$ cd icewm
$ ./autogen.sh
$ ./configure --enable-gdk-pixbuf --prefix=/usr
$ make
$ sudo make install
```
If you get unclear results like now, sometimes it can help to do a `make clean` before the `make`.

**Comment by DieSpinne** [comment]
Indeed, I have tried that before too, but I get an awkward error, although, as far as I can tell, I have all dependencies installed.
```
$ make -j5
make  all-recursive
make[1]: Entering directory '/home/user/icewm'
Making all in src
make[2]: Entering directory '/home/user/icewm/src'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/user/icewm/src'
Making all in po
make[2]: Entering directory '/home/user/icewm/po'
test ! -f ./icewm.pot || \
  test -z "ar.gmo be.gmo bg.gmo ca.gmo cs.gmo da.gmo de.gmo el.gmo en.gmo es.gmo fi.gmo fr.gmo he.gmo hr.gmo hu.gmo id.gmo it.gmo ja.gmo ko.gmo lt.gmo lv.gmo mk.gmo nb.gm
o nl.gmo no.gmo pl.gmo pt.gmo pt_BR.gmo ro.gmo ru.gmo sk.gmo sl.gmo sv.gmo tr.gmo uk.gmo vi.gmo zh_CN.gmo zh_TW.gmo" || make ar.gmo be.gmo bg.gmo ca.gmo cs.gmo da.gmo de.
gmo el.gmo en.gmo es.gmo fi.gmo fr.gmo he.gmo hr.gmo hu.gmo id.gmo it.gmo ja.gmo ko.gmo lt.gmo lv.gmo mk.gmo nb.gmo nl.gmo no.gmo pl.gmo pt.gmo pt_BR.gmo ro.gmo ru.gmo sk
.gmo sl.gmo sv.gmo tr.gmo uk.gmo vi.gmo zh_CN.gmo zh_TW.gmo
make[3]: Entering directory '/home/user/icewm/po'
rm -f ar.gmo && : -c --statistics --verbose -o ar.gmo ar.po
rm -f be.gmo && : -c --statistics --verbose -o be.gmo be.po
rm -f bg.gmo && : -c --statistics --verbose -o bg.gmo bg.po
mv: cannot stat 't-ar.gmo': No such file or directory
mv: cannot stat 't-be.gmo': No such file or directory
make[3]: *** [Makefile:277: ar.gmo] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [Makefile:277: be.gmo] Error 1
mv: cannot stat 't-bg.gmo': No such file or directory
make[3]: *** [Makefile:277: bg.gmo] Error 1
rm -f cs.gmo && : -c --statistics --verbose -o cs.gmo cs.po
mv: cannot stat 't-cs.gmo': No such file or directory
make[3]: *** [Makefile:277: cs.gmo] Error 1
rm -f ca.gmo && : -c --statistics --verbose -o ca.gmo ca.po
mv: cannot stat 't-ca.gmo': No such file or directory
make[3]: *** [Makefile:277: ca.gmo] Error 1
make[3]: Leaving directory '/home/user/icewm/po'
make[2]: *** [Makefile:315: stamp-po] Error 2
make[2]: Leaving directory '/home/user/icewm/po'
make[1]: *** [Makefile:594: all-recursive] Error 1
make[1]: Leaving directory '/home/user/icewm'
make: *** [Makefile:476: all] Error 2
```

`make clean` didn't help.

**Comment by gijsbers** [comment]
Ah, that is annoying indeed. Those build scripts are unfortunately not so user friendly yet.
You can check that you do have msgfmt installed as `/usr/bin/msgfmt`.
This could be part of the gettext package?
In the mean time just add the `-k` flag to make, like `make -k -j5` and just ignore the warnings.

**Comment by DieSpinne** [comment]
With Gettext I could compile it all, thank you for your patience and guidance. But I confirm that I cannot close any Xmgrace subwindow by any of the three methods.

**Comment by gijsbers** [comment]
Your perseverance as a user is very helpful for us.
I guess the only option left is to try to reproduce your system setup.
What OS and distribution release do you use?
What theme and what focus model do you use?

**Comment by DieSpinne** [comment]
I'm always glad to help this brilliant project, Gijsbers! I repeated the steps once again and the problem has indeed been solved: I can close all Xmgrace subwindows and cannot find any other problem with it. Sorry for my clumsiness and thank you, thank you once again.
