### ISSUE TITLE
Opening and closing sysmenu closes window

### ISSUE THREAD

**Issue by DieSpinne** [bbidulock/icewm#507]
The sysmenu button in the title bar opens a dialog with various window actions (restore, move, maximize, ...). If one clicks that button and then click it again, there is a chance the window will be closed. If not, if the action is repeated, the window is eventually closed.

Can you reproduce it?

**Comment by gijsbers** [comment]
Yes, this is standard IceWM behavior.

**Comment by DieSpinne** [comment]
Ah, I see, it is documented in [Mwm manual](https://linux.die.net/man/1/mwm) under Window Menu Button. Is it documented in Icewm too? I failed to find it, at least under "window menu" and "sysmenu" keywords.

**Comment by gijsbers** [comment]
The feature may indeed be inspired by Mwm. This may not be documented yet. Feel free to improve.
