### ISSUE TITLE
1.9.0: Task bar stays hidden when AutoHideDelay <= 1.

### ISSUE THREAD

**Issue by Spyros-2501** [bbidulock/icewm#508]
Task bar does NOT stay hidden when AutoHideDelay is set to 2 or more.

**Comment by gijsbers** [comment]
Indeed. The time is in milliseconds. We could enforce a minimum value of 2 milliseconds for you?

**Comment by Spyros-2501** [comment]
No need. I'd like to disable it, but setting it to 0 does not work.

**Comment by gijsbers** [comment]
You want to disable the delay on auto hiding? 2 ms should be fine then? Can you feel that 2 ms is too much??

**Comment by Spyros-2501** [comment]
No, of course not :D. The problem remains at 0ms though, since the task bar is no longer visible.

**Comment by gijsbers** [comment]
Why would you want to modify the delay, if all you want is to control the visibility. That seems so strange.

**Comment by Spyros-2501** [comment]
I do want the transition to be immediate but with the latest update it stopped working. I do not want to modify the delay, but i limited the problem's occurence to 2+ ms.
