### ISSUE TITLE
Penguin Subtitle Player

### ISSUE THREAD

**Issue by LastOfBrunnenG** [bbidulock/icewm#51]
Penguin Subtitle Player creates a window with subtitles which is on top of the other window. It is a Qt5 application with statically linked Qt5 libs. It seems to be working with JWM and Xfce4 on the same machine. With Icewm  there seems to be something missing. It hides as soon as user activates program options which bring up additional dialog windows, like 'preferences' and 'file open'. Then main window stays hidden and can't be accessed any more. The process i still running in the background. With icewm-session it places itself into tray and clicking on it makes no difference.

I feel tat it might be a minor issue which could be solved, but I don't know where to start.

I am running IceWM 1.3.5 built from source, because I have other issues with 1.3.8, which I reported here, too.

**Comment by bbidulock** [comment]
I don't remember this on specifically; however, a significant amount of EWMH/NetWM support and corrections were made since the 1.3.8 release.  Try the 1.3.11 release available [here](/bbidulock/icewm/releases) and see if all of your problems go away.

**Comment by LastOfBrunnenG** [comment]
Everything works in 1.3.11. 

There is no mention of it on icewm.org... 1.3.8 is the latest there. I understand this is a fork, but nevertheless. What is going on with Marko Macek ? Has he given up or something ? It has been a long, long time since IceWM got started, I know. Also, my impression is that I am not the only one who didn't know about this.
