### ISSUE TITLE
Huge window of Motif application

### ISSUE THREAD

**Issue by HJarausch** [bbidulock/icewm#510]
I am a fan of the "NEdit" editor which is Motif based.
This worked just fine until release 1.8.3.
But now with release 1.9.0 the initial window is huge (unusable). It looks as if window size requirements are ignored.
Am I missing a new setting/preference or is it a bug.
Thanks for a hint,
Helmut

**Comment by targzeta** [comment]
Hi,
I have the same problem with IntelliJ. In addition, I have the problem that when I have two instance of Intellij, changing the working space and then going back, the focus is randomly on one of these.

For me, this problem is also with the 1.8.3. Currently I use the 1.8.2.

Emanuele

**Comment by gijsbers** [comment]
NEdit I can reproduce and I have a fix. The problem was that NEdit requests to be mapped with only
a minimal WM_NORMAL_HINTS and then after the mapping updates this with large increment values.
NEdit should have provided the complete WM_NORMAL_HINTS settings before the map request.

IntelliJ is fine here. You get a very large window? What specific version details of IDEA?

Two instances is two different processes, or just two project windows? Works fine here too.

**Comment by HJarausch** [comment]
Hi Gisjbers,
I need a help hand. What has to be changed in NEdit's source or in .Xdefaults or what ever to fix this WM_NORMAL_HINTS?
Many thanks,
Helmut

**Comment by gijsbers** [comment]
You could apply this patch to source/window.c:

```
diff --git a/source/window.c b/source/window.c
index 634b084..f6423c3 100644
--- a/source/window.c
+++ b/source/window.c
@@ -773,6 +773,12 @@ WindowInfo *CreateWindow(const char *name, char *geometry, int iconic)
     	    window->showStats)
         XtManageChild(statsAreaForm);
     
+    /* Realize the widget in unmapped state */
+    XtRealizeWidget(winShell);
+
+    /* Make window resizing work in nice character heights */
+    UpdateWMSizeHints(window);
+
     /* realize all of the widgets in the new window */
     RealizeWithoutForcingPosition(winShell);
     XmProcessTraversal(text, XmTRAVERSE_CURRENT);
@@ -780,9 +786,6 @@ WindowInfo *CreateWindow(const char *name, char *geometry, int iconic)
     /* Make close command in window menu gracefully prompt for close */
     AddMotifCloseCallback(winShell, (XtCallbackProc)closeCB, window);
     
-    /* Make window resizing work in nice character heights */
-    UpdateWMSizeHints(window);
-    
     /* Set the minimum pane height for the initial text pane */
     UpdateMinPaneHeights(window);
     
```

[nedit.diff.txt](https://github.com/bbidulock/icewm/files/5467605/nedit.diff.txt)

**Comment by HJarausch** [comment]
Many thanks Gijsbers,
I have applied your recent 3 patches to IceWM on Github, and I have applied the patch to NEdit.
Now it works just fine!.
By the way, if you like NEdit as I do, do you known the "clone" patch? It provides a unique feature which I haven't found on any other editor: you can open several windows connected to the same file. And of course, if one changes something in one window,  this change is shown immediately in all other windows connected to the same file.
E.g. if editing a C/C++ source file, the definitions are open at the beginning of the file but one uses these at other places which can't be displayed in a single window. Just leave me a notice if you'd like to get these patches.
Helmut

**Comment by targzeta** [comment]
With latest commit (560cbbd) all seems to work also for me. Thank you!

Emanuele
