### ISSUE TITLE
Chromium issue actually due to icewm?

### ISSUE THREAD

**Issue by jidanni** [bbidulock/icewm#511]
In https://bugs.chromium.org/p/chromium/issues/detail?id=1140762#c8
icewm was implicated in a suspected chromium issue...

**Comment by gijsbers** [comment]
You could make a nice readable story about what is the matter. That would save us time.

**Comment by rubyFeedback** [comment]
I downvoted this by jidanni for a single reason: it links to an external source,
which is not good for tracking your own issue at a project, IMO.

Specifically my odd browser ( palemoon ) does not even display anything
there; and I think it is REALLY bad style to require of people to go to an 
external site.

jidanni - If you do not even have an interest to invest time into describing 
it (the issue) here, other than just pasting URLs and expecting others to
invest their time, then what is the net use for the project?

**Comment by jidanni** [comment]
I will need a few days to figure it out.

**Comment by jidanni** [comment]
Ah, it turns out they were mentioning something good about icewm, not something bad.
(OK, next time, even though it will add five days, I will first fully investigate what is being said ☻)
