### ISSUE TITLE
problem in window list window

### ISSUE THREAD

**Issue by denispr** [bbidulock/icewm#514]
In window list window, when icon size is increased through SmallIconSize option in preferences file, icon image and window description text overlap (see attached file, with SmallIconSize=25).

![Capture d’écran_2020-11-12_09-07-54](https://user-images.githubusercontent.com/4786274/98913110-3dde4200-24c7-11eb-835c-f4fbcd98861d.png)

**Comment by gijsbers** [comment]
Should be fixed now.

**Comment by denispr** [comment]
Great, thanks !
