### ISSUE TITLE
Some windows like xfce4-terminal have gap when maximized

### ISSUE THREAD

**Issue by linwaytin** [bbidulock/icewm#515]
Some windows like xfce4-terminal and Emacs can only be resized by the size of a character.
This is fine when the window is not maximized.
When the window is maximized, usually the size cannot fit the screen, like [this](https://i.imgur.com/GmS4Dua.png).
That makes a gap around the window. 

Is there a way to force those windows maximized to the size of screen exactly?

**Comment by gijsbers** [comment]
Yes. This is becoming a popular question. See issue #413.

**Comment by linwaytin** [comment]
Thanks a lot. 
I didn't understand the description of `ConsiderSizeHintsMaximized`,
but it works!
