### ISSUE TITLE
proposal to remove the _WIN_PROTOCOL properties for 2.0

### ISSUE THREAD

**Issue by gijsbers** [bbidulock/icewm#518]
Somewhere after 1.9 comes 2.0, which gives us the option of a slight incompatibility.
Can we use this to drop support for the old GNOME 1 WinWM properties from IceWM?
IceWM is one of the very few window managers which still carry these around.
Since about the year 2000, all X11 applications use EWMH properties
to communicate with the window manager. Removing support for WinWM
would make IceWM a little lighter, smaller and easier to maintain.
But if there are still applications which rely on WinWM then we can keep them as is.

**Comment by Code7R** [comment]
Question: what's the best way to detect it in application source? Grep for "_WIN_PROTOCOLS" ?

AFAICS the number of such applications is negligible.

https://codesearch.debian.net/search?literal=1&perpkg=1&q=_WIN_PROTOCOLS&page=0

**Comment by gijsbers** [comment]
Ideally, applications first check _WIN_PROTOCOLS on the root window.
In theory, any property you see when you do `xprop -root | grep _WIN_` is relevant.
However, they may also just check any _WIN_* property on their application window.
`xprop | grep _WIN_` will show this if you click on a window.
These are: _WIN_STATE, _WIN_WORKSPACE, _WIN_LAYER.
It is not a problem if an application uses _WIN_STATE, if it also considers _NET_WM_STATE.
The latter is preferable.
It is also not a problem if it uses _WIN_WORKSPACE, if it also considers _NET_WM_DESKTOP.
The only unique feature of _WIN_PROTOCOLS is the _WIN_LAYER property.
If there exists applications which rely on this in a way which cannot be realised by
using the _NET_WM_STATE_ABOVE and _NET_WM_STATE_BELOW flags of _NET_WM_STATE
then we may consider only supporting _WIN_LAYER.

**Comment by gijsbers** [comment]
This was implemented by commit 39775ce30d47a13cff922cdc75c9140fd3bed925.
