### ISSUE TITLE
unicode characters in a latin1 locale

### ISSUE THREAD

**Issue by gprints** [bbidulock/icewm#519]
I'm running a de_DE.ISO8859-1 locale and icewm 1.9.2 is ignoring that and outputting unicode character sequences, e.g. in the Preferences Menu, it says "Aâ| - Lâ|" instead of "A... - L..." and a quick look into the source code reveals only a check of the font contains unicode characters, but no check for the locale. Do we really need unicode instead of just using three ASCII dots?

**Comment by Code7R** [comment]
Unicode ellipsis takes less space and also looks better, IMHO. Anyway, that situation can be solved by throwing an additional nl_langinfo check on it.

**Comment by gijsbers** [comment]
The de_DE.ISO8859-1 locale looks fine to me. Is this still a concern?

**Comment by gprints** [comment]
While the incorrect display got fiexed, I still wonder if a single unicode character is worth having a dependency to another library.

**Comment by gijsbers** [comment]
Maybe not? How can I check this? Which library?

**Comment by gprints** [comment]
Sorry, I was wrong. libiconv isn't being used for "...", it's hardcoded as
#define utf8ellipsis "\xe2\x80\xa6"
const unsigned utf32ellipsis = 0x2026;

But as far as the original bug is concearned, it got fixed.
