### ISSUE TITLE
Window snapped on top gets resized when trying to move it

### ISSUE THREAD

**Issue by gprints** [bbidulock/icewm#520]
Sorry for the bad title, but it's kind of hard to give a short description of what's happening.
To reproduce it, move a window to the top of the screen until the window borders are off-screen. Then move your mouse into the top position of the title bar of that window. Notice the mouse cursor not changing to the resize cusor. Try to drag the window to a lower position and it gets resized instead of being moved.
icewm 1.9.2.

**Comment by gijsbers** [comment]
Should be fixed now.
