### ISSUE TITLE
Extending to Brazillian Portugese these two translations icewm-session.desktop and icewm.desktop

### ISSUE THREAD

**Issue by claudiosa** [bbidulock/icewm#521]
Hi

I am fully new here. I fixes in icewm/lib/ these two files  icewm-session.desktop and icewm.desktop
to support pt_BR. A minor correction was done also.

Really, I am not sure the steps for Pull Request here. I did a fork but I am not sure.
I tried 
git push origin master and 
git push origin main
but an error: 
error: failed to push some refs to 'https://github.com/claudiosa/icewm'

**Comment by claudiosa** [comment]
I am not sure if these two files follow attach

**Comment by gijsbers** [comment]
This merged via #522.
