### ISSUE TITLE
Unwanted space with separator in taskbar

### ISSUE THREAD

**Issue by qsmodo** [bbidulock/icewm#524]
This is a very minor issue. I have neither the start menu nor toolbar buttons. This causes a weird extra space with a vertical separator line in the left part of the taskbar:
![05-21:02:49](https://user-images.githubusercontent.com/75080827/101267994-5d226500-373d-11eb-9e17-d27500318c2d.png)
I believe it should not be there but could not find any mention to such separator in the preferences file.

**Comment by gijsbers** [comment]
Should be fixed now.
