### ISSUE TITLE
Left mouse button down on titlebar rolls down window

### ISSUE THREAD

**Issue by hnridder** [bbidulock/icewm#525]
Icewm 1.8.3 and 1.9.2 on gentoo.
I have set

    TitleBarMaximizeButton=2
    TitleBarRollupButton=1

When left double clicking the titlebar, the window gets rolled up, as expected.
But pressing down (so not even a single click yet!) the left mouse button on the rolled up window immediately rolls down the window.

Expected behaviour: Roll down is only executed when _double_ clicking the titlebar.

The current behaviour is a) unexpected and b) makes it impossible to move rolled up windows around.
Versions <=1.7.0 did not have this behaviour for as far back as I can remember.
Possibly related: #446

**Comment by gijsbers** [comment]
Thanks for reporting this. Should be fixed now.

**Comment by hnridder** [comment]
Fixed in 2.0.0
