### ISSUE TITLE
Maybe a problem with my locale ?

### ISSUE THREAD

**Issue by frankzen** [bbidulock/icewm#526]
I have been getting these warnings in .xsession-errors for a while.

IceWM: Warning: Invalid multibyte string "Opinion | Pat Toomey reveals just how deranged many Republicans have become - The Washington Post â Mozilla Firefox": Invalid or incomplete multibyte or wide character

Running 1.9.2.48 under Debian Sid.

**Comment by gprints** [comment]
Probably du to a Firefox bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1678975

**Comment by frankzen** [comment]
You may be right, We'll see what happens.
