### ISSUE TITLE
Worksapce buttons stay "pressed" when you move a pixel (or more) while holding down the mouse button

### ISSUE THREAD

**Issue by gprints** [bbidulock/icewm#527]
I don't think it's supposed to be like that:
If you click on a workspace button, but move tha mouse at least one pixel before releasing the button, you don't switch the workspace, the button stays "pressed" until you click it again.
I'd expect the workspaces to be switched and the wrkspace button to be released.

icewm 1.9.2

**Comment by gijsbers** [comment]
In 2.0.0.16, if I press a workspace button and move one or more pixels, then nothing happens.
The previous workspace button of the current workspace remains pressed down.
Is it perhaps some pref setting?

**Comment by gprints** [comment]
Tried 2.0.1 now, still happens to me.
Preferences are
TaskBarShowAPMAuto=0 # 0/1
TaskBarShowMailboxStatus=0 # 0/1
TaskBarShowWindowListMenu=0 # 0/1
TaskBarShowCPUStatus=0 # 0/1
TaskBarShowMEMStatus=0 # 0/1
TaskBarShowCollapseButton=1 # 0/1
PagerShowPreview=0 # 0/1
ShowThemesMenu=0 # 0/1
WorkspaceNames=" 1 ", " 2 ", " 3 ", " 4 "
Theme="/usr/local/share/icewm/themes/win95/default.theme"

**Comment by gijsbers** [comment]
`PagerShowPreview=0` suffices to reproduce it.
The toolbar buttons also have it.

**Comment by Polynomial-C** [comment]
After this fix has been included into the `2.1.0` release, I now have the issue that the application menu won't stay open when I click on it. I have to keep the mouse button depressed. Is that now intended behavior?

**Comment by gijsbers** [comment]
Thanks for testing this so quickly. We need a new release. Wait for 2.1.1.

**Comment by Polynomial-C** [comment]
And that patch fixes it for me. Thank you.

**Comment by gprints** [comment]
fixed in 2.1.1
