### ISSUE TITLE
Feature Request Stretch Image.

### ISSUE THREAD

**Issue by SolisX** [bbidulock/icewm#53]
Hello Brain,

It would be nice if the icewm background manager had the ability to stretch the image.

**Comment by bbidulock** [comment]
I was rather disappointed with background setting in various lightweight window managers, so I wrote the xde-setbg program that is part of the [xde-ctools](/bbidulock/xde-ctools) repository.  It has the ability to stretch or apply other hsetroot type backgrounds on a per-desktop basis for any window managers that is EWMH/NetWM or GNOME/WMH compliant (which is quite a few of them).  It works nicely with about 20 or so lightweight window managers.

IceWM background manager has other problems.  It relies on temporary pixmap resources that can go away at any time and it errors out (X protocol error) if you use some background setters (like hsetroot) to set the background while it is running.  The ice-session is pretty crude too.

Nevertheless, I don't think that it would take too much to get it to stretch the image.  I'll take a look.

**Comment by bbidulock** [comment]
Hmmm.  Are you sure it doesn't work?  Looks to me as though if you set DesktopBackgroundScaled to 1 and DesktopBackgroundCenter to 0 the image will be stretched without repecting the aspect ratio of the image.

**Comment by SolisX** [comment]
Hello bbidulock,

Sorry i must have made a mistake when trying to strecth the image.
