### ISSUE TITLE
Return from fullscreen forgets maximized state

### ISSUE THREAD

**Issue by marcelkorpel** [bbidulock/icewm#533]
The last few months I noticed that when *any* window goes fullscreen and back, the maximized state is forgotton and the window size and position is restored to 'normal'.

To reproduce, open a browser like Chrome or Firefox, maximize it, press F11 to go to fullscreen mode, press F11 to go back. The same happens with other applications I put fullscreen, whether it is using an application's function to put everything fullscreen (like F11 in a browser of `f` in mpv), or when I use IceWM's Alt-F11.

This might be related to (the fix of) #491, as it could be since then that this issue popped up (I'm not sure, though).

Using 2.0.0 on Arch Linux.

**Comment by gijsbers** [comment]
Yes, this is intentional. If you want to go from fullscreen to maximized
then you can just hit the maximize key combination.
To restore now really means to go back to normal.

**Comment by marcelkorpel** [comment]
I understand. The only thing is I remember it was different before, and I preferred it.

If this is (still) intentional, please close this issue.

**Comment by gijsbers** [comment]
Yes, 2.0.0 is different and therefore some users will experience a period of adaptation.
I believe the new behavior is more what other WMs do and also more EWMH compliant.
The spec doesn't discuss what it means that a window is both fullscreen and maximized.
It does say: "Additionally the Window Manager is responsible for restoring the 
original geometry after a switch from fullscreen back to normal window."
You can see this by executing `icesh -f spy` and then toggle fullscreen / maximized
and observe the _NET_WM_STATE flags. Pre-2.0.0 it was possible to be in fullscreen,
then toggle maximized, with unclear effects, also when restoring to normal.
As mentioned, you can still go from fullscreen to maximized by hitting the maximize hotkey.
