### ISSUE TITLE
When maintaining preferences via menu, after saving, the "=" after the setting name has been omitted

### ISSUE THREAD

**Issue by cheapy** [bbidulock/icewm#535]
This is on 2.0.0 up to date on antiX19.3

ShowRun0

another example: ShowFocusModeMenu0 # 0/1

**Comment by cheapy** [comment]
from a friend, skidoo at antiX, I'm not a C++ programmer:

the seemingly relavent code was introduced way back in 2018, and has not been modified since
https://github.com/ice-wm/icewm/commit/16b8d71492d128a09a33765adddc3d736ea0d09a

wmprog.cc::updateOption()
   [..]
   char* s = text;
   regmatch_t m = {};
   while (0 == regexec(&pat, s, 1, &m, 0)) {
      s += m.rm_eo;
      s[-1] = '0' + o->boolval();
      s = replaceComment(s, "# 0/1");
   }
   [..]
}

s[-1] = ‘0’ + o->boolval();
but at that point, s is just a character array.
Positioning to “-1” seems to wrongly presume the need to backtrack past the nullbyte of a null-terminated string
(so winds up overwriting the equalsign character)

Untested, I reckon the fix would be

   while (0 == regexec(&pat, s, 1, &m, 0)) {
      s += m.rm_eo;
   }
   s += '\0';
   s[-1] = '0' + o->boolval();
   s = replaceComment(s, "# 0/1");

**Comment by frankzen** [comment]
Same problem on 2.0.0.9.
Turning off (0) in ShowRun preferences worked, but in both cases after saving turning it back on (1) was missing the =.
Turning off ShowTaskBar left the 1 in place but after saving the = was missing.

**Comment by cheapy** [comment]
antiX 19.3 stable has now been updated to 2.0.1 and I can confirm that the issue has been fixed.  Thanks much for your speedy help.
