### ISSUE TITLE
On dual LCD setup maximized window is stretched to the second monitor

### ISSUE THREAD

**Issue by logout128** [bbidulock/icewm#536]
![fullscreen_bug](https://user-images.githubusercontent.com/14232260/103930911-c2dc8500-511f-11eb-9bc7-777ff5d3e0fd.png)

I just built IceWM 2.0.1 on Slackware current and discovered that if I maximize window, it's stretched to the second monitor. It doesn't matter whether the maximized window is on primary or on secondary LCD, it always is has few pixels on the other one. It almost seems like it's one of the window borders, while the three other are not visible in maximized state. Can this be anyhow avoided? I went through issues list here on github, through the manual and through the config files but didn't find any setting that would modify this. Thank you!

**Comment by gijsbers** [comment]
Are you sure about "fullscreen"? This looks like it is maximized.
You can try if setting `HideBordersMaximized=1` helps.

**Comment by logout128** [comment]
Thanks for the reply and for correcting my misuse of terminology. I changed the title and the description to avoid more confusion. 
So what I described is desired state? If I don't have borders hidden in maximized state, they're are supposed to overlap to another screen? Thanks!

**Comment by gijsbers** [comment]
Dunno if it is desired or supposed to. I guess it has been like this for ages.
You may be the first to dislike it? It could be changed, I guess.
Are Fullscreen or HideBordersMaximized=1 unsatisfactory?

**Comment by Code7R** [comment]
He is not the first, it has bothered me for ages as well, just not hard enough to start digging for a solution.

Edited: if HideBordersMaximized=1 was supposed to fix it then it does not work. I see a maximized window on the other screen covering the edge of the fullscreen window.

Edit2: I stand corrected, the option works but it does not cooperate well with reality. Which is: certain applications like Firefox do restore their windows after start in a fake maximized mode. The window has the previous size where it originally was (in maximized state) but the window state is not maximized.

Can we add some heuristic for this case? Maybe interpret window position (edge matching screen edge) just the same way as maximized with HideBordersMaximized option?

**Comment by logout128** [comment]
If I maybe so bold as a original reporter, the option HideBordersMaximized=1 fixes what I meant by my report and what's visible in the screenshot. I just didn't think that borders of maximized window overlapping to another screen could be a feature, because I don't see any use of such feature. Mea culpa.

**Comment by gijsbers** [comment]
It's not your fault. IceWM is 24 years old. It grew as technology and standards developed. Hence, over time many extensions came into existence with their own options. Those options would not have existed if IceWM were redeveloped from scratch in one go. Here you may consider that back then it was not customary to have more than one monitor and so the frame of a maximized windows wasn't seen as a problem. In fact, all the many options now unexpectedly allow new tricks, if you find the right combination. Her you could set LimitSize=0, LimitPosition=0, SizeMaximized=1 and then resize a maximized window.

**Comment by logout128** [comment]
> It's not your fault. IceWM is 24 years old. (...) Here you may consider that back then it was not customary to have more than one monitor and so the frame of a maximized windows wasn't seen as a problem.

Indeed, I used IceWM briefly around 2001/2002 and was perfectly happy with one screen back then. I just recently rediscovered it and grew quite fond of it.
