### ISSUE TITLE
What is the new equivalent of icesh setTrayOption since 2.0.0?

### ISSUE THREAD

**Issue by zaza42** [bbidulock/icewm#537]
I used to use icesh setTrayOption often, but I've experienced [this](https://github.com/bbidulock/icewm/commit/39775ce30d47a13cff922cdc75c9140fd3bed925) commit, which removed setTrayOption completely. How can I put window to systemtray from commandline since then?

**Comment by gijsbers** [comment]
Only via https://ice-wm.org/man/icewm-winoptions or https://ice-wm.org/man/icewmhint, sorry.

**Comment by zaza42** [comment]
So, put an already running program to systemtray is impossible now? ;-<
Can you recommend any dirty hack solution?

**Comment by gijsbers** [comment]
No, because the _WIN_TRAY message handler and property event handler are no longer there, sorry.
The only obscure way that remains is to use https://en.wikipedia.org/wiki/Xnee, quite a challenge.

**Comment by zaza42** [comment]
```
IFS="+x" read _ _ _ _ _ wx wy <<<$(icesh -f list)
xdotool mousemove --sync $((wx)) $((wy-5)) click --clearmodifiers 1 \
    mousemove_relative --sync 0 200  click --clearmodifiers 1

```
Okey, this works, but... What can I do when an application is in fullscreen?

**Comment by gijsbers** [comment]
Temporarily maximize it, then post the menu, do your thing, re-fullscreen it.

**Comment by zaza42** [comment]
Let me describe exactly what my problem is: i use devilspie2 to stick and tray every window which is on the second head (on a projector). Various programs, various keycombos to exit and enter fullscreen, so...
```
x, y, width, height = get_window_geometry();
if (x > 1599) and (x < 9999) then
    wid = get_window_xid()
    path = [[/usr/bin/icesh -window ]] .. wid .. [[ setTrayOption 2]]
    os.execute(path)
    pin_window()
end
```
Can we have an option in icewmhint or winoptions which matches the windowgeometry (position) not the class?

**Comment by gijsbers** [comment]
Couldn't icewmhint do the thing for you?
Do these apps support the WM_WINDOW_ROLE property?
Could `alltray` be of help?

**Comment by zaza42** [comment]
I couldn't find what `alltray` is.

**Comment by gijsbers** [comment]
https://launchpad.net/alltray
https://github.com/mbt/alltray

**Comment by zaza42** [comment]
Ohh, I thought this is an `icesh` or `icewmhint` parameter, or it has something to do with icewm.
No, `alltray` does a totally different thing than my goal, even  `icewmhint` is more suitable.

Can't we get back that setTrayOption feature? It has the power among other wms.

**Comment by gijsbers** [comment]
Yeah, I was already thinking in that direction. If we just restore message event handler
for the _WIN_TRAY message, but not yet the property(??).

**Comment by zaza42** [comment]
THANX for v2.1.0!
