### ISSUE TITLE
Fedora 32 freeze on icewm logout

### ISSUE THREAD

**Issue by boycottsystemd** [bbidulock/icewm#539]
Some artifact has appeared in left upper corner of the screen on logout. Screen then went black and system got frozen. Power button was needed to press to stop system.

icewm-2.0.1-1.fc32

journalctl -r
Jan 12 13:01:12 fedora kernel: sysrq: Emergency Sync
Jan 12 13:01:11 fedora kernel: sysrq: This sysrq operation is disabled.
Jan 12 13:01:10 fedora kernel: sysrq: This sysrq operation is disabled.
Jan 12 13:01:08 fedora kernel: sysrq: This sysrq operation is disabled.
Jan 12 12:55:58 fedora gsd-power[8219]: Error setting property 'PowerSaveMode' on interface org.gnome.Mutter.DisplayConfig: Timeout was reached (g->
Jan 12 12:55:38 fedora kernel: ACPI: \_SB_.PCI0.PEG0.PEGP: failed to evaluate _DSM
Jan 12 12:55:33 fedora systemd[8411]: pulseaudio.service: Consumed 6min 38.412s CPU time.
Jan 12 12:55:33 fedora systemd[8411]: pulseaudio.service: Succeeded.
Jan 12 12:55:33 fedora systemd-logind[920]: Session 2 logged out. Waiting for processes to exit.
Jan 12 12:55:33 fedora systemd[1]: home-u1.mount: Succeeded.
Jan 12 12:55:33 fedora systemd[8411]: home-u1.mount: Succeeded.
Jan 12 12:55:34 fedora /usr/libexec/gdm-x-session[7912]: (II) systemd-logind: got resume for 226:1
Jan 12 12:55:33 fedora systemd[7833]: home-u1.mount: Succeeded.
Jan 12 12:55:33 fedora audit[8401]: CRED_DISP pid=8401 uid=0 auid=1000 ses=2 msg='op=PAM:setcred grantors=pam_unix,pam_gnome_keyring,pam_ecryptfs a>
Jan 12 12:55:33 fedora audit[8401]: USER_LOGOUT pid=8401 uid=0 auid=1000 ses=2 msg='uid=1000 exe="/usr/libexec/gdm-session-worker" hostname=? addr=>
Jan 12 12:55:33 fedora audit[8401]: USER_END pid=8401 uid=0 auid=1000 ses=2 msg='op=PAM:session_close grantors=pam_selinux,pam_loginuid,pam_selinux>
Jan 12 12:55:33 fedora kernel: rfkill: input handler disabled
Jan 12 12:55:33 fedora gdm-password][8401]: pam_unix(gdm-password:session): session closed for user u1
Jan 12 12:55:33 fedora gdm-x-session[8460]: GLib: Source ID 2 was not found when attempting to remove it
Jan 12 12:55:32 fedora /usr/libexec/gdm-x-session[8462]: (II) Server terminated successfully (0). Closing log file.
Jan 12 12:55:32 fedora /usr/libexec/gdm-x-session[93895]: icewmbg: Can't open display: <none>. X must be running and $DISPLAY set.
Jan 12 12:55:31 fedora systemd[8411]: dbus-:1.23-org.a11y.atspi.Registry@0.service: Consumed 2.932s CPU time.
Jan 12 12:55:31 fedora systemd[8411]: dbus-:1.23-org.a11y.atspi.Registry@0.service: Succeeded.
Jan 12 12:55:31 fedora systemd[8411]: xdg-desktop-portal-gtk.service: Failed with result 'exit-code'.
Jan 12 12:55:32 fedora /usr/libexec/gdm-x-session[8462]: (II) systemd-logind: releasing fd for 13:66
Jan 12 12:55:32 fedora /usr/libexec/gdm-x-session[8462]: (II) UnloadModule: "libinput"
Jan 12 12:55:32 fedora /usr/libexec/gdm-x-session[8462]: (II) systemd-logind: releasing fd for 13:71
Jan 12 12:55:32 fedora /usr/libexec/gdm-x-session[8462]: (II) UnloadModule: "libinput"
Jan 12 12:55:32 fedora /usr/libexec/gdm-x-session[8462]: (II) systemd-logind: releasing fd for 13:70
Jan 12 12:55:32 fedora /usr/libexec/gdm-x-session[8462]: (II) UnloadModule: "libinput"
Jan 12 12:55:32 fedora /usr/libexec/gdm-x-session[8462]: (II) systemd-logind: releasing fd for 13:65
Jan 12 12:55:32 fedora /usr/libexec/gdm-x-session[8462]: (II) UnloadModule: "libinput"
Jan 12 12:55:32 fedora /usr/libexec/gdm-x-session[8462]: (II) systemd-logind: releasing fd for 13:68
Jan 12 12:55:32 fedora /usr/libexec/gdm-x-session[8462]: (II) UnloadModule: "libinput"
Jan 12 12:55:32 fedora /usr/libexec/gdm-x-session[8462]: (II) systemd-logind: releasing fd for 13:67
Jan 12 12:55:32 fedora /usr/libexec/gdm-x-session[8462]: (II) UnloadModule: "libinput"
Jan 12 12:55:32 fedora /usr/libexec/gdm-x-session[8462]: (II) systemd-logind: releasing fd for 13:69
Jan 12 12:55:32 fedora /usr/libexec/gdm-x-session[8462]: (II) UnloadModule: "libinput"
Jan 12 12:55:32 fedora /usr/libexec/gdm-x-session[8462]: (II) systemd-logind: releasing fd for 13:73
Jan 12 12:55:32 fedora /usr/libexec/gdm-x-session[8462]: (II) UnloadModule: "libinput"
Jan 12 12:55:31 fedora systemd[8411]: xdg-desktop-portal-gtk.service: Main process exited, code=exited, status=1/FAILURE
Jan 12 12:55:31 fedora /usr/libexec/gdm-x-session[8462]: (II) event9  - MSI WMI hotkeys: device removed
Jan 12 12:55:31 fedora /usr/libexec/gdm-x-session[8462]: (**) Option "fd" "39"
Jan 12 12:55:31 fedora /usr/libexec/gdm-x-session[8462]: (II) event5  - ETPS/2 Elantech Touchpad: device removed
Jan 12 12:55:31 fedora /usr/libexec/gdm-x-session[8462]: (**) Option "fd" "38"
Jan 12 12:55:31 fedora /usr/libexec/gdm-x-session[8462]: (II) event3  - AT Translated Set 2 keyboard: device removed
Jan 12 12:55:31 fedora /usr/libexec/gdm-x-session[8462]: (**) Option "fd" "37"
Jan 12 12:55:31 fedora /usr/libexec/gdm-x-session[8462]: (II) event4  - Logitech USB-PS/2 Optical Mouse: device removed
Jan 12 12:55:31 fedora /usr/libexec/gdm-x-session[8462]: (**) Option "fd" "36"
Jan 12 12:55:31 fedora /usr/libexec/gdm-x-session[8462]: (II) event1  - Power Button: device removed
Jan 12 12:55:31 fedora /usr/libexec/gdm-x-session[8462]: (**) Option "fd" "35"
Jan 12 12:55:31 fedora /usr/libexec/gdm-x-session[8462]: (II) event6  - Video Bus: device removed
Jan 12 12:55:31 fedora /usr/libexec/gdm-x-session[8462]: (**) Option "fd" "34"
Jan 12 12:55:31 fedora /usr/libexec/gdm-x-session[8462]: (II) event7  - Video Bus: device removed
Jan 12 12:55:31 fedora /usr/libexec/gdm-x-session[8462]: (**) Option "fd" "33"
Jan 12 12:55:31 fedora /usr/libexec/gdm-x-session[8462]: (II) event2  - Power Button: device removed
Jan 12 12:55:31 fedora /usr/libexec/gdm-x-session[8462]: (**) Option "fd" "30"
Jan 12 12:55:31 fedora unknown[18481]: xdg-desktop-portal-gtk: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
Jan 12 12:55:31 fedora at-spi2-registryd[8737]: X connection to :1 broken (explicit kill or server shutdown).
Jan 12 12:55:31 fedora /usr/libexec/gdm-x-session[8729]: conky: X Error: Display 561334257e60
Jan 12 12:55:31 fedora unknown[8704]: volumeicon: Fatal IO error 11 (Ressource temporairement non disponible) on X server :1.
Jan 12 12:55:31 fedora /usr/libexec/gdm-x-session[8700]: X connection to :1 broken (explicit kill or server shutdown).
Jan 12 12:55:29 fedora /usr/libexec/gdm-x-session[8701]: IceWM: Attention : 'icewm-menu-fdo' timed out!

**Comment by gijsbers** [comment]
There is no clear hint here that this may be due to IceWM. 
IceWM doesn't draw random artifacts or blank the screen.
It also doesn't have the capability to freeze the system, even if it wanted to (which it doesn't).
If icewm exited with a non-zero exit code, then icewm-session would have reported that.
Therefore, some other forum is more appropriate to raise this issue, like Fedora's.

**Comment by bedna-KU** [comment]
Fedora uses Wayland by default.
