### ISSUE TITLE
Tktray icons sometimes not fully visible

### ISSUE THREAD

**Issue by Code7R** [bbidulock/icewm#54]
Hello Brian, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=807408 .

The oldest version I could compile in the bisect run had this issue already, most didn't even compile.  Last Marco version didn't have the problem.

Maybe you have a quick idea, otherwise I will go on with debugging it later this week.

**Comment by bbidulock** [comment]
The couple of commits that changed tray icon sizing were 12ee299937de29b09b49a9b874c792333d28bdce and a55789a557d47dd3f2e22940c3e3b60a611811ce; perhaps one of those is at fault.  Those two are my best guess.

**Comment by Code7R** [comment]
I could narrow this down to ywindow.cc (used YXTrayEmbedder in yxtray.cc). The reported window size is really 1x1, and this value comes straight from XGetWindowAttributes (yxwindow.cc:330), although other values there look sane.

But the catch is, when I add a break of a couple of seconds before this is called (sleep(2); in yxtray.cc:188 ) then it works just fine.

Not sure what we are seing here, some kind of race? Maybe tktray is modifying the window after creation? Can anyone imagine a reason why XGetWindowAttributes reports nonsense?
