### ISSUE TITLE
IceWM produces non-textured/black background on the taskbar when IceWM starts.

### ISSUE THREAD

**Issue by mikedebian** [bbidulock/icewm#542]
![2021-01-23-155904_2560x1440_scrot](https://user-images.githubusercontent.com/3228644/105597182-30c9b300-5d94-11eb-816d-1feef2bfe480.png)

See picture.

Starting applications or right clicking the menu to get index menu up, will texture that area with the black background (not wallpaper).
This happens with all themes.

![2021-01-23-160131_2560x1440_scrot](https://user-images.githubusercontent.com/3228644/105597607-4dfe8180-5d94-11eb-98da-9daa39a6f548.png)

Here I've already opened up and closed some applications, and I've right clicked the taskbar to get index menu up, clicked on the desktop to close it, and then it has been textured.

I've had this issue on several install. Not using a composoting manager. Standard icewm install under arch linux, using XDM as display manager, amdgpu.

Thank you. Sorry if it has been posted before, I tried going through the issues.

IceWM 2.0.1, Copyright 1997-2012 Marko Macek, 2001 Mathias Hasselmann.

**Comment by mikedebian** [comment]
[preferences.txt](https://github.com/bbidulock/icewm/files/5860376/preferences.txt)

Here is my preferences file, uploaded as TXT only for github.

**Comment by gijsbers** [comment]
The combination of TaskBarDoubleHeight=1 and TaskBarShowWorkspaces=0 was unexpected.

**Comment by mikedebian** [comment]
Well, changed TaskBarShowWorkspaces=1 and no more black bakground.
Tried two resets, works as it should.
I've just not had the need for extra workspaces, thus I disabled it :)
Come to think of it, always have and this has always been an issue for me.
Guess since I saw no other reports that I must be the single one that disables it and enables double height.
