### ISSUE TITLE
Question: Way to access the Focus, Themes, Preferences menus other than from the main menu?

### ISSUE THREAD

**Issue by cheapy** [bbidulock/icewm#543]
We are trying to reduce the main menu items to ones people use all the time.  It is great that everything is so flexible, but people generally don't change their IceWM settings often once they have them set up comfortably.
 
We would still want to have access to the "IceWM settings" menu options, but either from a submenu or from separate .desktop menu options.

I don't know what options might already exist.  Any suggestions?

**Comment by gijsbers** [comment]
Do you mean just: Help, Focus, Preferences, Themes? Or more? Otherwise detail examples.

**Comment by cheapy** [comment]
Yes, you are correct.  Help was not visible because I had ShowHelp=0.  That one would also be nice to have available,  but currently we have the IceWM Manual and FAQ on another Help menu, and that's why it was turned off.

With ShowHelp turned on they would take 4 slots on the main menu.   They would fit in well on the menu as an IceWM Settings sub-menu under Preferences, normally I would think, or if we had a way to call them directly, we could put them in our control center, or people would have the flexibility to add them to their personal menu or toolbar if they wanted to.  The menu options I'm referring to specifically are:

#  Show settings submenu in the program menu
ShowSettingsMenu=1 # 0/1
#  Show focus mode submenu in the program menu
ShowFocusModeMenu=1 # 0/1 
#  Show themes submenu in the program menu
ShowThemesMenu=1 # 0/1
#  Show the help menu item in the program menu
ShowHelp=1 # 0/1

**Comment by gijsbers** [comment]
1.3.8 had a Settings submenu like this:
![138](https://user-images.githubusercontent.com/4169687/105639316-d144d380-5e77-11eb-9167-1c4949a0b0e9.png)
Is that better?

**Comment by cheapy** [comment]
Yes, we used to use that feature.  That would help, yes.

**Comment by gijsbers** [comment]
We can move all four (Help, Focus, Preferences, Themes) to a single
"Settings" submenu, like in 1.3.8, no problem, I'm fine with that.
Then the current preference `ShowSettingsMenu` could either
mean to show this submenu, or to show the Preferences submenu.
What do you think?

**Comment by cheapy** [comment]
Thanks, that would be great. That will help trim it down nicely.

**Comment by gijsbers** [comment]
Commit bc0ddd726342a9068edfa7c1405936c6c6014831 introduces 
a Settings submenu for Help/Focus/Pref/Themes.
It looks like this:
![543](https://user-images.githubusercontent.com/4169687/105707189-d9058600-5f12-11eb-97b6-7127bf8dfbbe.png)

**Comment by cheapy** [comment]
That looks great, thanks.   

I will see if I can test it tonight

Thanks again for your speedy assist

**Comment by cheapy** [comment]
I wasn't able to build/compile due to missing "imlib2", so I forwarded your message to anti (the distro's author).  I'm sure he will know how.

**Comment by gijsbers** [comment]
Since 2.0.0 we have an extra image module which uses imlib2.
The previous one gdk-pixbuf-xlib is still available, if you
select it with --enable-gdk-pixbuf, if you use configure.
To get the missing imlib2 dependency, install `libimlib2-dev` for Debian.
You can also use the os-depends.sh script from the website.

**Comment by cheapy** [comment]
@gijsbers Your solution for the compile worked, and I got it compiled and installed.  I installed it wrong at first, but then I did it again correctly, and now its working.

Thanks Much!

**Comment by cheapy** [comment]
Here is the result, much cleaner...
![screenshot_5](https://user-images.githubusercontent.com/7473967/105989557-eaf83d80-6066-11eb-9e1e-c168af9a05a8.jpg)

**Comment by cheapy** [comment]
No problems found.  closing issue, thanks again.
