### ISSUE TITLE
Panic when screen becomes multiple

### ISSUE THREAD

**Issue by jidanni** [bbidulock/icewm#545]
Today somehow I hit RET on something, and my screen split into...
![20210202T080818](https://user-images.githubusercontent.com/1230959/106533980-1202b380-652e-11eb-90b4-aa6876b1aa8d.jpg)
OK, by double clicking on the top bars of one of them, I was finally able to recover. (Actually needed on each of the windows.)
But before that no poking in the menus etc. revealed how to get out.
Yes, at the lower left of the screen, there was a new `田` icon. But clicking that didn't help.
Anyway, just wanted to let you know.

**Comment by gijsbers** [comment]
Note that IceWM is jamp-packed with features. You likely hit one of the many you still don't know about. Like:
```
       KeySysTileVertical="Alt+Shift+F2"
       KeySysTileHorizontal="Alt+Shift+F3"
       KeySysCascade="Alt+Shift+F4"
       KeySysArrange="Alt+Shift+F5"
       KeySysUndoArrange="Alt+Shift+F7"
```
The man pages can enlighten you.
