### ISSUE TITLE
icewm-menu-fdo fails on broken .desktop symlink, with fix

### ISSUE THREAD

**Issue by floofywolf** [bbidulock/icewm#546]
Debian/KDE seems to like leaving dangling symlinks on upgrades.  icewm-menu-fdo stops processing .desktop files when it finds one, rather than just skipping it and continuing like it does for other bad .desktop files.

My fix:
fdomenu.cc, at line 565:
        if (g_stat(szFullName, &buf))
            return;
Change to:
        if (g_stat(szFullName, &buf))
            continue;
(sorry, I don't remember how to generate a proper patch, and it's just one line...)

It continues on other issues, and I can't think of any reason not to do the same when it can't stat the .desktop file.

Thanks for the great wm!

**Comment by Code7R** [comment]
This was rolled out to Debian Testing (Frozen) now, can you confirm the fix? Thanks.

**Comment by Code7R** [comment]
IMHO this ticket should be force-closed when next Debian major version is released. I could reproduce it before and never again since the fix.  https://wiki.debian.org/DebianReleases

**Comment by floofywolf** [comment]
Sorry, I haven't been doing any coding-related things lately  - too busy with work.  I haven't installed the debian package, but the commit looks like it does the same thing I did to my copy, so I can't imagine it not fixing it.  Thanks!
