### ISSUE TITLE
gap in taskbar after fullscreen

### ISSUE THREAD

**Issue by zaza42** [bbidulock/icewm#548]
A dummy gap left on the taskbar, if an app was closed while other was in fullscreen.
![icewm-2 1 1-missingtitleontaskbar](https://user-images.githubusercontent.com/16356124/106824245-bbf35480-6682-11eb-8631-9effc84ea1f4.png)

I can replay it with: `sleep 5;exit` in terminal, run mpv in fullscreen for more than 5 seconds, then switch from fullscreen to windowed mode, then a gap appears in place of the closed app.
When I change task, the gap immediately disappears.

**Comment by Code7R** [comment]
Wait, why? I thought it was a feature and I liked it!
