### ISSUE TITLE
Preserve taskbar layout while closing windows with meta-middle-clicking

### ISSUE THREAD

**Issue by Code7R** [bbidulock/icewm#549]
That idea came as a side effect of issue #548. It's slightly inconvenient when you attempt to close windows with mouse but the taskbar keeps relayouting entries all the time so you might mistarget when using gamer's muscle memory.

There should be an option to keep the layout as long as the meta (Alt) key is held pushed.

**Comment by zaza42** [comment]
Could there be an option for this in the preferences file?

I'm using Alt+[key] combos for switching between workspaces, and I really miss being able to see on the taskbar what is running on a workspace. Especially if there are a lot of windows overlapping - then I can only see from the taskbar if I'm on the right workspace.

**Comment by danfe** [comment]
> I'm using Alt+[key] combos for switching between workspaces, and I really miss being able to see on the taskbar what is running on a workspace.

I use Ctrl+Alt+_arrows_ to cycle through the workspaces and also just found that task bar is not updated in 3.2.2, which is quite annoying.

**Comment by zaza42** [comment]
> I use Ctrl+Alt+_arrows_ to cycle through the workspaces and also just found that task bar is not updated in 3.2.2, which is quite annoying.

Commit https://github.com/bbidulock/icewm/commit/f074fb0cf405b9ec5191cd942c52c334c5ca1970 was fixed this issue.
