### ISSUE TITLE
icesound and icewmhint missing setlocale() call

### ISSUE THREAD

**Issue by danfe** [bbidulock/icewm#553]
I've noticed that `icesound -h` and `icewmhint -h` do not display translated help strings properly for non-English locales (they appear as a series of question marks).

Looks like it's because of the missing call to `setlocale(LC_ALL, "")` before `bindtextdomain()` in those programs' `main()` function; note that other programs might be affected as well.  Interestingly, e.g. `icehelp -h` does not suffer from this, apparently due to `YLocale locale`.

**Comment by danfe** [comment]
Not sure what "verification-pending label" means, but both utilities display translated strings now.

**Comment by gijsbers** [comment]
Thanks for lifting the pending status of the verification. ;-)
