### ISSUE TITLE
Alt-Tabbing over fullscreen window causes it to steal focus

### ISSUE THREAD

**Issue by qsmodo** [bbidulock/icewm#558]
Open some windows A, B and F and make F fullscreen. Focus window A. Using Alt-Tab, cycle over the windows.

Expected behavior: The Alt-Tab menu shows up, but A retains focus until the menu is dismissed by releasing Alt.

Observed behavior: The Alt-Tab menu shows up, but as soon as F is selected — and thus before releasing Alt — it claims focus until the menu is dismissed.

**Comment by Code7R** [comment]
Cannot reproduce. Please report your "icewm -p" output.

And what do you mean with "make F fullscreen"? Maximize it, or true full-screen mode without decoration? Please explain what you **actually** use.

**Comment by qsmodo** [comment]
True fullscreen mode, such as clicking the title bar with the right-mouse button and selecting "fullscreen". Below are my relevant settings, but note I can reproduce it on a non-customized Icewm (more precisely, after `mv .icewm .icewm.bak`).

```
QuickSwitch=1
QuickSwitchToMinimized=1
QuickSwitchToHidden=1
QuickSwitchToUrgent=1
QuickSwitchToAllWorkspaces=0
QuickSwitchGroupWorkspaces=1
QuickSwitchAllIcons=1
QuickSwitchTextFirst=0
QuickSwitchSmallWindow=0
QuickSwitchMaxWidth=1
QuickSwitchVertical=1
QuickSwitchHugeIcon=0
QuickSwitchFillSelection=0
TaskBarFullscreenAutoShow=0
AllowFullscreen=1
FullscreenUseAllMonitors=0
KeyWinFullscreen="Ctrl+Shift+Alt+F11"
```

Latest Icewm release too.

**Comment by gijsbers** [comment]
When this command is run in all three windows:
```
xprop -root -spy _NET_ACTIVE_WINDOW
```
then it shows that each Alt+Tab brings focus to the next window.

**Comment by qsmodo** [comment]
I can reproduce it, Gijbsers. I may be using the wrong terminology, then. What I mean is that the fullscreened window "comes to the front" of all others as soon as it is selected in the Alt+Tab menu. This, however, does not happen when a non-fullscreened window is selected until the menu is dismissed. Can you reproduce that?

**Comment by gijsbers** [comment]
Yes, I can reproduce that. With your settings, the QuickSwitch is broken if there is a fullscreen window.

**Comment by gijsbers** [comment]
Could you test if this fixes your problem?

**Comment by qsmodo** [comment]
Thank you, but I fear not. According to my tests, now each Tab press in the quick switch causes the next window to be raised instead of only raising the selected window when the quick swtich is dismissed.

**Comment by gijsbers** [comment]
Yes, that is due to a request from #564. You can find the updated manpage here https://github.com/bbidulock/icewm/blob/icewm-1-4-BRANCH/man/icewm.pod#quick-switch. You can update again and evaluate the new features, before they are released.

**Comment by qsmodo** [comment]
Thanks. So actually the commit goes in the opposite direction of what I consider the expected behavior, right?
At least I don't see any mention of configurability in [that section](https://github.com/bbidulock/icewm/blob/icewm-1-4-BRANCH/man/icewm.pod#quick-switch). The input focus section does not mention any effect on the quick swtich either. And it really shouldn't because, if I understand right, the correct terminology is that the all windows are now *raised* (and not *focused*) when alt-tabbing, while the problem I reported originally was that fullscreened windows would be raised when alt-tabbing over them.

**Comment by gijsbers** [comment]
When you Tab to a window, then it is raised and focused. If you then Tab again, the previous window will be put in its original stacking order and not have focus anymore. I don't understand the basis of 'now raised (and not focused) '.
You need to use the xprop command I gave you above, or use `icesh spy`, to prove what you say about focus.
The problem you raised in this issues was that a fullscreen window remained raised, disrupting the intended behavior of the QuickSwitch. That seems solved now. It should, because the new code avoids the conditions required for it.
You can still comment on how it now works, or what should be better explained in the documentation, and so on.

**Comment by qsmodo** [comment]
I am failing to convey my message, my bad. Now that I grasp the terminology, let's start from scratch, may we?

The original behavior, namely of not raising windows before the alt-tab dialog was dismissed, was good for me. The reason I opened this issue was that the fullscreen window, differently from others, would be raised and remain raised. Now it does not remain raised, but on the other hand it is raised as are all the other windows. I would like to only raise a window when I dismissed the alt-tab dialog.

I hope the whole issue hasn't become too contrived. Let me know if it is better to close this and open a clean, new one. And thank you for your support.

**Comment by gijsbers** [comment]
Okay, you don't appreciate the new feature, which is fair. We could make it a preference.

**Comment by qsmodo** [comment]
I would highly appreciate it, Gijsbers, though I believe a [standalone Alttab](https://github.com/sagb/alttab) would also do the trick.

**Comment by qsmodo** [comment]
Many thanks for addressing the issue, which I tested and is working great.

**Comment by qsmodo** [comment]
Closing.
