### ISSUE TITLE
Issues with the new task bar grouping

### ISSUE THREAD

**Issue by exebook** [bbidulock/icewm#560]
First, thank you very much for enabling this, it is super cool!

Grouping works as expected, it groups firefox, xterm, thunar, putty, chromium, vscode, mpv, inkscape, kitty, terminator. That's  all I tried.

Here are some minor issues I found so far:

Icon badge counter looks weird, overlapping text:

![Selection_074](https://user-images.githubusercontent.com/3821217/111627423-9cbf1980-8821-11eb-9432-74a7f36654d8.png)

I do not have a great solution for that, but here is for example what Firefox does for badge coutners:

![Selection_078](https://user-images.githubusercontent.com/3821217/111628404-c462b180-8822-11eb-815f-105c9610801d.png)

Shutter's idea of adding `[1]` to the title is also lovely:

![-home-ya-Selection_078 png - Shutter_080](https://user-images.githubusercontent.com/3821217/111631930-8d8e9a80-8826-11eb-9350-b5b83cb720c3.png)

Other issue is that my task bar is at the top of the screen and drop down menu aligns to the top of the taskbar even though it should be at the bottom for me:

![Selection_077](https://user-images.githubusercontent.com/3821217/111628230-93827c80-8822-11eb-9eae-2f7587b6b51b.png)

Also menu behaves inconsistently with the "Start" menu, i.e. for the start menu I do:
-mouse down
-mouse up
-move mouse to select an item
-mouse down
-mouse up

But for the task group menu I do:
-mouse down
-move the mouse to select an item
-mouse up

I prefer the first way (like in windows 95) so maybe I have this option in the preferences file, do not remember, if there is such option it should probably be consistent for both types of menu, the start and the group selection, if there is no such option, then they just should be the same probably, just thinking. Probably no reason to have two settings, because users probably want all menus working the same way.

**Comment by exebook** [comment]
Another one: moving task bar items left and right with `Control` down does not work for the grouped items, although it works for others.

**Comment by gijsbers** [comment]
Your feedback was incorporated. Please try again.

**Comment by exebook** [comment]
It is almost perfect now. Although the badge counter still seems a bit off for me. And it's padding is nearly zero btw.

One problem though is that when I tried to move the taskbar to the bottom with ALT+drag the menu was popping aligned wrongly to the bottom. I thought maybe that's because I moved it with ALT and not with the preferences setting, so I reached to the Start menu where I have a link to Geany to open Preferences, but it did not work. So start menu  opens but selecting items does nothing, all menu items are in place but do not work. I had to `git checkout HEAD~` and recompile to get the menu back.

**Comment by danfe** [comment]
Thanks, this is a nice feature indeed.  However, I'm a bit surprised that when I enable it, it groups *all* windows across all worskspaces, not just those which belong to the current one.  Is there a way to control this?

Second, the window counter looks a bit ugly sometimes, e.g. look at the attached screenshot.  Would it be possible to move it all the way to the right or somehow otherwise avoid interference (overlap) with the icon and title?

![14xterms](https://user-images.githubusercontent.com/1132291/113472882-8effca00-9498-11eb-8515-21825b55ca7c.png)

**Comment by gijsbers** [comment]
Maybe this the drawing from #565 is better? You could help evaluate #565 (and improve?).
How many windows do you have per workspace and totally?

**Comment by danfe** [comment]
> You could help evaluate #565 (and improve?)

Thanks for the hint, I'll take a look!

> How many windows do you have per workspace and totally?

I have four workspaces with 4~12 xterm windows on each (plus windows for other programs, of course, but those usually do not require grouping and are per-workspace anyway).

**Comment by danfe** [comment]
> I'm a bit surprised that when I enable it, it groups all windows across _all_ worskspaces, not just those which belong to the current one. Is there a way to control this?

Gentle nag to (re)consider making this per-workspace or configurable. :-)

**Comment by danfe** [comment]
Feel kind of bad about nagging you again, but did you have a chance to think about making this configurable or maybe aligned with the _TaskBarShowAllWindows_ setting?  Global grouping by default essentially deprives me from using the taskbar for switching between my dozen xterm's while I'd gladly use it if grouping were per-workspace.  Perhaps attached screenshot would be more convincing.

![screenshot](https://user-images.githubusercontent.com/1132291/174049283-34d93f22-e6a7-41f7-97f8-a692aa5cb6ff.png)

Another problem with global grouping is that selecting a window from the group might switch the current workspace, which can be confusing to the user (unless _TaskBarShowAllWindows_ is enabled; +1 reason to make it aligned with that setting, if not configurable).

**Comment by danfe** [comment]
Another problem with global grouping is that selecting a window from the group might switch the current workspace, which can be confusing to the user (unless _TaskBarShowAllWindows_ is enabled; +1 reason to make it aligned with that setting, if not configurable).

**Comment by danfe** [comment]
> Let _TaskBarShowAllWindows_ influence _TaskBarTaskGrouping_

Oh this is so much better now, can't thank you enough! :-)
