### ISSUE TITLE
Fill the gaps of windows whose dimensions are measured in characters

### ISSUE THREAD

**Issue by qsmodo** [bbidulock/icewm#561]
Disclaimer: I know Icewm is a stacking WM and this is more of a feature
for a tiling WM and may be hard to do in Icewm, 
so I understand if this is rejected right away.

I have set the following in my `keys` file for the occasions when I need
to have two windows side-by-side:
```
key Super+Left      icesh -focus restore sizeto 50% 100% left
key Super+Right     icesh -focus restore sizeto 50% 100% right
```
It does the job, but when one of the windows sets its dimensions
based on character cells rather than pixels — that is mainly old school
programs, such as Xterm —, then small gaps are left behind.

It would be great if Icewm could fill that extra part of the window, maybe
in a manner similar to `ConsiderSizeHintsMaximized` for maximized windows,
such that the gaps went away, each window occupying *exactly* 50% of the
available screen width and 100% of the height. Maybe some kind of flag
would need to be set with `icesh` on the desired windows, or a `preferences`
setting, if this is possible at all.

**Comment by gijsbers** [comment]
Usually you can just get by with `xprop -remove WM_NORMAL_HINTS`.
Or in this case `xprop -id $(icesh -f id) -remove WM_NORMAL_HINTS`.

**Comment by qsmodo** [comment]
Fantastic! Many thanks for your helping hand, Gijsbers!
