### ISSUE TITLE
Switching workspaces is impossible while in Alt-Tab mode

### ISSUE THREAD

**Issue by danfe** [bbidulock/icewm#563]
I frequently find myself in situation when I've pressed Alt-Tab to switch to a particular window, but then realise it's on another workspace, which I normally navigate around with Ctrl-Alt-arrows, however, workspace switching does not work while Alt-Tab mode is active.  This is quite annoying and contrary to e.g. Openbox, which does not block workspace switching in the window cycle mode and updates the window list accordingly.

**Comment by gijsbers** [comment]
Can you evaluate these two commits?

**Comment by danfe** [comment]
Hmm, I've applied them over 2.2.1 and it does not work as expected, e.g. if I open two windows on workspace one, and four on the second, then I expect Alt-Tab window size to get changed accordingly when I switch between them, but it stays the same.  Window list gets updated properly, though, but there would be either empty slots (when going from four to two windows) or not all windows would be listed (it is still possible to switch between them, though).

**Comment by gijsbers** [comment]
I deduced you were using vertical mode. Please try again.

**Comment by danfe** [comment]
> I deduced you were using vertical mode.

Isn't it the default one? :-)

> Please try again.

Thanks, now it matches Openbox behavior and that's exactly what I've asked for.

**Comment by gijsbers** [comment]
You're right, vertical is the default, since 2007.
Thanks for suggesting this feature.
It seems so natural and indispensible, now that we have it.

**Comment by danfe** [comment]
> It seems so natural and indispensible, now that we have it.

Enjoying it for over a year and just noticed this issue is still open.  Closing as fixed.
