### ISSUE TITLE
Allow more space for taskbar button icons

### ISSUE THREAD

**Issue by qsmodo** [bbidulock/icewm#566]
Apparently, taskbar button icons are constrained into some sort of inner vertical margin (3 or 4 pixels wide according to my calculations) inside the button. For small taskbar sizes, that can force the icon to be quite small. This is in opposition to systray icons, which are allowed to occupy the whole taskbar height. The pictures below show the taskbar icon for a `SmallIconSize=16` and `20`, and the last one shows a couple of systray icons.

![16Sized](https://user-images.githubusercontent.com/75080827/112202542-690d3680-8c09-11eb-9f7d-80bb860c29f5.png)
![20Sized](https://user-images.githubusercontent.com/75080827/112202546-6ad6fa00-8c09-11eb-8d7a-8e6731a811b0.png)
![Tray](https://user-images.githubusercontent.com/75080827/112202554-6ca0bd80-8c09-11eb-9bc9-0802646e8ebe.png)

All the pictures are alligned to the screen at the bottom. (Also excuse me for the theme breakage at the second picture.)

I think it would be useful if the user could allow more space, say via a setting. There is `TaskbuttonIconOffset` but that only controls the inner left margin, according to my tests.

Here are some settings in case it is relevant:
```
TaskBarShowWindowIcons=1
TaskbuttonIconOffset=2
TrayIconMaxWidth=32
TrayIconMaxHeight=24
MenuIconSize=28
SmallIconSize=16
LargeIconSize=28
HugeIconSize=48
```

**Comment by gijsbers** [comment]
What theme?

**Comment by qsmodo** [comment]
It's a custom theme with only pixmaps for taskbar buttons. `default.theme` contains
```
Look=flat
TaskbuttonIconOffset=2
```
Anyway, reconsidering this issue now I think it is too minor to warrant bothering the mantainers with it, so I'm closing it. If you find it worth pursuing, I'll be happy to provide any more details or clarification if needed.
