### ISSUE TITLE
Toggle system tray and monitor widgets for space in the taskbar

### ISSUE THREAD

**Issue by qsmodo** [bbidulock/icewm#568]
When there are too many windows open or/and the tray is taking up too much space, I find it useful to toggle all the tray (including monitor widgets). So I made this script to do it:

```
#!/bin/sh
file=$HOME/.icewm/preferences
mv "$file" "$file".bak
sed '
/^TaskBarShowTray=/y/01/10/
/^TaskBarShowWorkspaces=/y/10/01/
/^TaskBarEnableSystemTray=/y/01/10/
/^TaskBarShowAPMStatus=/y/10/01/
/^TaskBarShowCPUStatus=/y/10/01/
/^TaskBarShowMEMStatus=/y/10/01/
/^TaskBarShowNetStatus=/y/10/01/
/^TaskBarShowClock=/y/10/01/
' "$file".bak > "$file"
icewm --restart
```

It works but there is flickering because it has to restart Icewm. I believe it would be an useful addition if that could somehow be accomplished on the fly, maybe via an `icesh` or `icewmtray` command?

**Comment by gijsbers** [comment]
Consider setting TaskBarShowAllWindows=1, otherwise TaskBarTaskGrouping=1.

**Comment by qsmodo** [comment]
I could not find TaskBarTaskGrouping in the [preferences manual](https://ice-wm.org/man/icewm-preferences.html), maybe there is a typo in your comment?

**Comment by gijsbers** [comment]
Try Github search.
