### ISSUE TITLE
Need a theme question answered

### ISSUE THREAD

**Issue by frankzen** [bbidulock/icewm#570]
Can someone tell me what keyword in the theme file changes the colours of the text and background of the box which pops up
when "About" is right-clicked on the taskbar??? Driving me nuts!!

**Comment by Code7R** [comment]
Just for the record, one of the worst kind of support requests is the one where the requester closes the ticket/topic/thread with "nevermind solved it" or no helpful comment at all :1st_place_medal: .

For the average Joe who was searching for similar keywords and found his way here, that drives HIM nuts.
