### ISSUE TITLE
Regression between 2.2.1 and 2.3.0

### ISSUE THREAD

**Issue by danfe** [bbidulock/icewm#572]
Something got broken with recent changes, I can no longer switch themes with either keyboard or mouse via the context menu on the desktop, if they do not appear exactly on the level after "Settings -> Themes".

For example, I have [icewm-extra-themes](https://github.com/bbidulock/icewm-extra-themes) package installed, and most themes are grouped under their starting letter (e.g., Settings -> Themes -> **C** -> **C**rystalBlue), except three (_18k_, _Helix_, and _OpenLook-shaped_) which are uncategorized.  With 2.2.1, I could switch to any theme, but with 2.3.0 only to those three.

**Comment by Code7R** [comment]
I can reproduce it. Can be bisected down to this commit:

32fd056a759b7181b79c69fe7af3b3acf9eb8451 is the first bad commit
commit 32fd056a759b7181b79c69fe7af3b3acf9eb8451
Author: Bert Gijsbers <gijsbers@science.uva.nl>
Date:   Fri Mar 19 00:09:35 2021 +0100

    Remove the actionPerformed callback from menu items.

 src/objmenu.h    |  2 +-
 src/wmmgr.h      |  7 ++++++-
 src/wmprog.cc    | 12 +++++-------
 src/wmwinmenu.cc | 46 ++++++++++++++++++++--------------------------
 src/ymenu.cc     |  8 +++-----
 src/ymenuitem.cc |  5 -----
 src/ymenuitem.h  |  2 --
 src/ypopup.cc    |  6 +++---
 8 files changed, 38 insertions(+), 50 deletions(-)

**Comment by danfe** [comment]
With 2.3.1, the bug is no longer there, closing.
