### ISSUE TITLE
Regression from 2.2.1 - Lost menu icons in 2.3.0

### ISSUE THREAD

**Issue by anticapitalista** [bbidulock/icewm#573]
Running antiX and 2.3.0 version loses icons in main menu and Application section of antiX menu.
All ok with 2.2.1 version

**Comment by gijsbers** [comment]
Fixed by commit 79616ed36e05b8ae56eb1acc0afca5d9df68affb. Thanks!

**Comment by danfe** [comment]
Just for the record, it got broken with 656cbff while trying to fix #562.

**Comment by anticapitalista** [comment]
Excellent - and fast! 2.3.1 fixes the problem. Thanks
