### ISSUE TITLE
Buttons not clicked when moving mouse a little

### ISSUE THREAD

**Issue by gprints** [bbidulock/icewm#575]
This probably is related to the already solved #527, the behaviour of icewm has changed vom 1.3 to 2 and is now different from what other applications do. If you click a Workspace button, but move the mouse one pixel before releaseing the button, this is not being considered as a click on the button. IMO this is a bug.

**Comment by gijsbers** [comment]
Your ... doesn't look like normal, so it's weird and you must fix it... ;-) IMVHO.

**Comment by gijsbers** [comment]
In addition there is this to tweak:
```
#  Pointer motion distance before click gets interpreted as drag.
# ClickMotionDistance=4 # [0-32]

#  Delay in ms before click gets interpreted as drag.
# ClickMotionDelay=200 # [0-2000]
```
