### ISSUE TITLE
Moved window buttons stay pressed after releasing the mouse button

### ISSUE THREAD

**Issue by gprints** [bbidulock/icewm#576]
When you have more than one window open, drag its "button" on the icewm bar to another position by clicking on it, holding the mouse button, moving it left or right and releasing the mouse button. It looks like you never released the mouse button, you can switch workspaces, click on other stuff, but as soon as you only hover the mouse over this window's button again, it looks like if you were still clicking on it. When you do click on it, the curse is gone.

**Comment by gprints** [comment]
Forgot to mention that it's version 2.1.1.

**Comment by gijsbers** [comment]
Fixed.
