### ISSUE TITLE
Emacs' toggle-frame-fullscreen doesn't toggle back off

### ISSUE THREAD

**Issue by jidanni** [bbidulock/icewm#578]
$ emacs -Q
Alt+F10 (icewm's) OK, now it is maximized.
Now in emacs do
F11: runs the command toggle-frame-fullscreen
OK, now do it again.
It was supposed to be a toggle.
But it doesn't toggle back off!

May be already fixed. All I know is I am using
emacs:all/unstable 1:27.1+1-3.1
icewm:amd64/unstable 2.1.2-1

**Comment by gijsbers** [comment]
Alt+F11 still works to toggle fullscreen.
F11 is a request to emacs to toggle fullscreen.
Emacs ignores this when it is both maximized and fullscreen.
Alt+F11 is a request to icewm to toggle fullscreen the focused application window.
Icewm handles it just fine. So no problem with icewm.

**Comment by jidanni** [comment]
OK can you send a report to bug-gnu-emacs@gnu.org . Thanks.

**Comment by gijsbers** [comment]
You can compare this to Firefox, which still has a usable F11 key after Alt+F10.

**Comment by jidanni** [comment]
OK please tell the responsible parties. All this is over my head. Thanks.
