### ISSUE TITLE
There is no 'icesh toggleState' any more? What to replace it with?

### ISSUE THREAD

**Issue by arsonoff** [bbidulock/icewm#580]
I had the button on the panel, ~/.icewm/toolbar:
```
...
prog xvkbd input-keyboard.png icesh -class xvkbd toggleState Minimized
...
```
Now it does not work.
Replaced with ```wmctrl -r xvkbd -b toggle,hidden```

icesh it can be made?

**Comment by gijsbers** [comment]
`icesh -c xvkbd -N HIDDEN restore || icesh -c xvkbd hide`

**Comment by arsonoff** [comment]
OK
