### ISSUE TITLE
Modify default winoptions value

### ISSUE THREAD

**Issue by qsmodo** [bbidulock/icewm#582]
Say I want all windows with `tray: Exclusive` and `startMaximized: 1` options. Being those non-default values, AFAIK the only way is to exhaustively set them to all the possible class/instance windows in `winoptions`. It would be so much more convenient if there were some way to modify the default values.

My suggestion is to allow for a wildcard value that would apply to all windows, e.g.
```
*.tray: Exclusive
*.startMaximized: 1
```

**Comment by gijsbers** [comment]
You only need to remove the stars.
