### ISSUE TITLE
Configure script lacks --disable-rsvg switch

### ISSUE THREAD

**Issue by danfe** [bbidulock/icewm#587]
It would be nice to have `--disable-rsvg` configure script switch to disable librsvg2 detection similarly to imlib2/fribidi/nls, so downstream packagers and end-users could explicitly control which features and libraries IceWM should use and link against, regardless of their presence in the system (that is, prevent silent dependency injection).

**Comment by gijsbers** [comment]
Like this?

**Comment by danfe** [comment]
> Like this?

Yes, this works, thank you!
