### ISSUE TITLE
Screen distorted after monitor suspended

### ISSUE THREAD

**Issue by marcelkorpel** [bbidulock/icewm#588]
I highly doubt that this is an IceWM issue, but just in case, since the issue changed since I installed 2.3.4.

Until then, after the monitor goes in suspension mode and back on, large parts of the screen started flickering, turning black and back on. When I move the mouse over a certain window, that one will flicker more frequently, but when changing windows, causing a repaint, that part of the screen restores to normal. Even GUI parts, like in the taskbar, can be forced to repaint and those parts will be fine again. Consequently, after letting everything repaint by switching a window to full screen and back, everything is normal again.

Since the update, more or less the same behaviour can be observed, but after switching the monitor on a distortion can be seen, instead of black parts:

![distortions](https://user-images.githubusercontent.com/367181/117888812-e6bcfc80-b2b2-11eb-8ada-c8a13c8a9cce.png)

(the only thing I redacted in this screenshot was my email address in the taskbar, the button of Thunderbird mysteriously appeared normal; distortions can be seen in taskbar button icons, though).

Is there anything changed in IceWM that could have caused this change in the issue? For the record, I'm using Arch Linux and Picom 8.2 as a compositor, and xorg-server 1.20.11.

**Comment by gijsbers** [comment]
This is a bug in the X server. You may want to report this to your distro's support site.
They may want to examine your /var/log/Xorg.0.log. I have seen a number of bugs
related to the new GLAMOR driver. It can be interesting to try X without it.
https://wiki.raptorcs.com/wiki/Troubleshooting/GPU#Xorg_crashes_or_is_laggy_with_the_AST_VGA_GPU

**Comment by marcelkorpel** [comment]
Thank for pointing me in the right direction! I'll report it there.
