### ISSUE TITLE
taskbar dropped graphics

### ISSUE THREAD

**Issue by ithgub** [bbidulock/icewm#590]
![scrot 2020-11-19T11:56:31,281638071+02:00](https://user-images.githubusercontent.com/75799052/119175397-4c4e7d00-ba59-11eb-894a-e37d1fd96bb7.png)
then it healed itself a bit but still background suffers: 
![scrot 2020-11-23T12:59:52,366901666+02:00](https://user-images.githubusercontent.com/75799052/119175421-57091200-ba59-11eb-9ff9-dd6e35b3342a.png)

Did nothing special or stressful, just a regular workflow 
Running IceWM of antiX Linux 
Theme — Icequinox Dawn 
The issue happened November 2020. I was too lazy to report in a timely fashion, sorry

**Comment by gijsbers** [comment]
Hello, thanks for reporting. Which version is this? Does it also happen with latest?
Do you run a compositor like picom or compton?

**Comment by ithgub** [comment]
This happened only once, in November 2020

The IceWM version was of antiX' repo in November 2020 
antiX probably has a tweaked IceWM, judging by version string (this is my current, not the version of the date of the issue, but the word "antix" was there either): 
```
> apt show icewm 
Package: icewm 
Version: 2.2.1-1.0antix1 
```

I must have generally run picom compositor at the time, but I am not 100% sure whether it was actually running at the moment of the issue.

Notice the favicon of https://apkpure.com/ (that green capital "A") in place of taskbar background. Multiple tabs with the website were opened in https://qutebrowser.org/ . Websites' favicons normally never get into IceWM taskbar afaik, so I wonder how...

I had had nouveau driver then, but Qt apps hadn't worked OK (qbittorrent regularly crashed whereas anki wouldn't start at all). Since I installed Nvidia driver, the aforementioned couple runs smoothly. 
qutebrowser is a Qt app too, but unlike qbittorrent and anki it did work fine on nouveau. 
I speculate, if Qt fails witn nouveau on my NVIDIA G98M [GeForce 9300M GS], then other GUIs might either, including IceWM.

I have insufficient RAM of 3 GB, and swap is used routinely. The total memory load was heavy at the moment of the issue (as always — web browsers are hogs, you know). 

I recall that taskbar dropping graphics happened on window switching, probably on Alt+Tab.

**Comment by gijsbers** [comment]
If it only happened once, and hasn't for half a year, then we may assume it was due to providing insufficient memory for your applications to run. We can safely discard this issue. This is a more a bug for the X server.
