### ISSUE TITLE
Net Monitor disappears from taskbar

### ISSUE THREAD

**Issue by Veraellyunjie** [bbidulock/icewm#591]
The taskbar-built-in Net Monitor worked fine until recently. A month ago I switched from mobile internet (external modem plugged via USB) to a speedier cable internet (plugged via LAN port). 
Now, the Net Monitor starts as usual with IceWM and the taskbar, works for a while, and then disappears. It is the same way like when an application crashes and its button disappears from the task bar. 
The issue happens repeatedly. The network connection itself continues to work. Other taskbar-built-in monitors (battery, memory and CPU) work fine.  
I can't blame it certainly on the internet connection change but it does correlate in time.

Restarting IceWM does not help to bring the Net Monitor back to the taskbar.
Rebooting does help.
Logging out and then back in — didn't try.

IceWM version is 2.2.1-1.0antix1

**Comment by gijsbers** [comment]
You need to check if your LAN device appears correctly in the Linux
 kernel file `/proc/net/dev`. See `man 5 proc` for details.
If it disappears after a while, and a restart of icewm doesn't help,
then there is some interfacing problem somewhere.
In icewm releases after 2.2.1 improvements to reading this file were made.
The AntiX release 19.4 has this.

**Comment by cheapy** [comment]
If this is still occurring, you should try it on the same machine with the most current up to date standard full version of antiX you can run and if still happening, try a few different kernel versions to see if any of them cause the issue to go away.  If still occuring, then also try another distro like Debian with IceWM and see if it occurs there, too.  If it only occurs with all antiX permutations, it's likely an antiX issue, and should be brought up on the antiX forum.  I never have seen this on any of my antiX machines or versions.

**Comment by Veraellyunjie** [comment]
I've switched to another machine and only rarely use the topic one  
so can't report whether the issue is still occurring,  
and with the announced elogind-free antiX-22 I think we'd better wait for the new version.  
Thank you for your attention and effort, nonetheless
