### ISSUE TITLE
manpage BUGS section "no known bugs"

### ISSUE THREAD

**Issue by ithgub** [bbidulock/icewm#592]
man icewm on antiX 19 (Debian 10):
```
BUGS
       icewm had no known bugs at the time of release.  Please report bugs for current versions to the source code repository at <https://github.com/bbidulock/icewm/issues>.
```
"no known bugs" is misinformation

**Comment by gijsbers** [comment]
Why is that `misinformation`? Now it is like saying `fakenews`, without elucidating us with the subtle and valuable line of reasoning which leads you to protest against this apparently misleading statement.

**Comment by ithgub** [comment]
Being neither misbehaving nor misty person, I elucidate:

I see that our use of language misalign. 
I feel you think I mischaracterized the issue. 
I believe my comment was misconstrued. 
I don't believe I misworded or misapplied it. 
I do believe that it is your misassumption of the word 'misinformation', mister/Ms. gijsbers. 
No misblame for you, since fake-news-makers do their misservice to the language and people's minds and miscellanea and now we mislabel things. What a misfortune! I miss plain English usage. 
Please pardon me my linguistic misbalance.

I like your bile-laden comment. No mismatch with your predator kitty avatar. Thank you.

BTW JFY a non-mis-definition: 
Disinformation — a type of misinformation that is intentionally false and intended to deceive or mislead. 
Misinformation — false or out-of-context information that is presented as fact regardless of an intent to deceive.

**Comment by ithgub** [comment]
Being neither misbehaving nor misty person, I elucidate:

I see that our use of language misalign. 
I feel you think I mischaracterized the issue. 
I believe my comment was misconstrued. 
I don't believe I misworded or misapplied it. 
I do believe that it is your misassumption of the word 'misinformation', mister/Ms. gijsbers. 
No misblame for you, since fakenews-makers do their misservice to the language and people's minds and miscellanea and now we mislabel things. What a misfortune! I miss plain English usage. 
Please pardon me my linguistic misbalance.

I like your bile-laden comment. No mismatch with your predator kitty avatar. Thank you.

BTW JFY a non-mis-definition: 
Disinformation — a type of misinformation that is intentionally false and intended to deceive or mislead. 
Misinformation — false or out-of-context information that is presented as fact regardless of an intent to deceive.

Seriously, 
https://github.com/bbidulock/icewm/issues?q=is%3Aissue+is%3Aopen+label%3Abug
lists 10 open, the newest from November 2019. There is actually more: 
https://github.com/bbidulock/icewm/issues
lists 102 open. Not all of them are bugs, but there are more bugs than labeled as such, aren't there?

**Comment by gijsbers** [comment]
From this explanation I understand that you conclude "misinformation", because there are still open issues and open bugs. I never appreciated the "no known bugs" line either, because it fails to define "bugs", or the "who" to which it is known. It is also unrealistic for a project with the history, design and complexity of icewm. There are still long standing irritating bugs with focus and the handling of taskbar in fullscreen mode, etc. So we may both agree to the conclusion, but for somewhat different reasons.

**Comment by gijsbers** [comment]
Fixed.

**Comment by bbidulock** [comment]
I wrote it to say that because I used to never release with known bugs.  I take it that has changed...
