### ISSUE TITLE
show desktop → keyboard not responding

### ISSUE THREAD

**Issue by Veraellyunjie** [bbidulock/icewm#593]
It has been happening for a year (and I didn't use IceWM earlier), 
with both TaskBarShowShowDesktopButton and KeySysShowDesktop, 
in a small percentage of uses (not each time), but already many-many times.

Upon minimizing all windows, keypresses stop working. Neither Alt+Tab, nor Alt+Ctrl+h (KeySysCollapseTaskBar), nor Alt+F2 (gexec run command), nor F1 (tilda drop-down terminal), nor any other — nothing. 
Mouse clicking still works, and upon raising any window, keyboard becomes functional again. 

Running IceWM of antiX Linux

**Comment by gijsbers** [comment]
You can test if this helps.

**Comment by rubyFeedback** [comment]
I haven't run into this error yet. Wonder why that is triggered only sometimes.

**Comment by gijsbers** [comment]
Me neither. Maybe depends on the exact platform details and/or the applications he uses?
