### ISSUE TITLE
Enhancement request: Optional log output of programs run from the menu or toolbar

### ISSUE THREAD

**Issue by cheapy** [bbidulock/icewm#594]
The details needed would be date/timestamp, program name shown on menu or toolbar, and if possible, the command line.  

The reason for the request is because programs called by IceWM don't appear via acct or zietgeist logging, and I would use the information as the primary input to generating a file of the most commonly used menu options in menu/toolbar format.

If you know of a better way to find out which programs are run from IceWM most often, please advise.

**Comment by gijsbers** [comment]
The programs started via menu or toolbar are shown by acct, but they have to terminate first.

**Comment by cheapy** [comment]
It's not worth the effort to try to do it from what the system generates.  I was hoping to be able to have a semi dynamic toolbar that would automatically add programs used frequently, and remove ones that were considered optional if not used often, thus allowing the user to find all the things they normally used on the toolbar, accessible with one click.  From the logs the system generates, it isn't obvious or easily determined what menu option was run.

**Comment by gijsbers** [comment]
@cheapy May I suggest [my AntiX 19.4 review](https://github.com/bbidulock/icewm/issues/188#issuecomment-850907780)?
Also, it would be nice if AntiX would upgrade its old roxterm 2.9.5
to version 3.11.1 from https://github.com/realh/roxterm/.
