### ISSUE TITLE
How to keep preferences files in sync

### ISSUE THREAD

**Issue by frankzen** [bbidulock/icewm#599]
Whenever I compile and install a new version I don't know how to ensure any   new keys are in my local preferences file. Is there a relatively easy way to do this? I have a lot of modified preferences in my local version. Thanks

**Comment by gijsbers** [comment]
`icewm --rewrite-preferences`

Keep a backup of what you had, so you can compare and decide if you like the result.

**Comment by frankzen** [comment]
That works! Thanka
