### ISSUE TITLE
No rule for icewm.lsm

### ISSUE THREAD

**Issue by onli** [bbidulock/icewm#6]
On Ubuntu 14.04, the current HEAD does not compile with the command in the README. It leads to this error in the first make step:

```
make[2]: *** Keine Regel vorhanden, um das Target »icewm.lsm«, 
  benötigt von »all-am«, zu erstellen.  Schluss.
```

which translates to the usual no rule available error I'm sure you know.

Solution was for me to remove the icewm.lsm from the Makefile.

**Comment by bbidulock** [comment]
Sorry, the README was not updated after providnig a full automake build system.  I just committed a change to the README that fixes that.
