### ISSUE TITLE
i cant using Alt+Tab if i want drag and drop something

### ISSUE THREAD

**Issue by mantarimay** [bbidulock/icewm#619]
For example i want drag n drop file from thunar to chrome and change window using Alt+Tab but i cant change window thunar to chrome.

**Comment by gijsbers** [comment]
Yes, you are right, but this can't be remedied. What you can do is to hover the drag over the workspace button of your destination workspace. Then icewm will change to that workspace and you can drop the drag onto chrome. Isn't that magical?
