### ISSUE TITLE
[Feature proposal] In the main context menu for icewm (the one you get via right-mouse click button), add an entry for user input to start as if one would have hit alt+F2 key

### ISSUE THREAD

**Issue by rubyFeedback** [bbidulock/icewm#623]
Hey there Brian and everyone else,

I'll first describe the proposal. Adjust and adapt as it may fit (or not fit) please.

- It is herein proposed to add a user-input entry when the context menu appears. This user-input entry is
for user input. Upon hitting the "enter" key, the command that is input by the user is executed, if possible.

A typical and simple example for this is the following:

    xterm

So, the user would start xterm (if it is installed and works that is; if not found then perhaps some popup
or some other simple notification could show that it was not found or something, but this is secondary to
the feature proposal. For lazinzess we can always skip that, as long as the primary user input "start
this program" works).

In other WMs, such as fluxbox, I remember I could use "alt+F2" I think. I just tried via icewm but this does
not work. Perhaps my brain mixes up stuff. But I was also thinking that it might be better to add some
way from the context menu itself to start a command as such. That way more advanced users can just
type as-is without needing to navigate.

Where should this user-input entry be placed? Well, perhaps between the top list, and the horizontal
separator. It's hard to describe but if you open the context menu via the right mouse button then the
horizontal separator can be seen, so below or above is fine IMO.

Alternatively if you do not want to put it in the main context menu, then perhaps it could be added
at some of the other settings as such, like "Settings" or somewhere. Not sure where to best put
it, but IMO the feature decision yes/no to this suggestion is more important anyway; I think 
placement and such is secondary and can be decided upon either way if the feature has been
given the thumbs up (or thumbs down).

Background: So this may be a bit boring, but I just installed devuan. It came with cinnamon but
cinnamon was buggy. I am reinstalling tons of things. So right now I am on icewm already as-is,
and setting things up (kde konsole does not work right now so I use xterm, until I compile 
mate-terminal in a bit, which should work better than xterm.)

So, being able to do more stuff from the context menu would be great, including changing things
such as background image, number of workspaces, and so on and so forth. Perhaps this is 
all possible as-is; we should perhaps go through the menu at one point in time and make it
a bit cleaner (and perhaps also wider ... or my eyesight is getting bad too quickly, but I digress).

Anyway as always please be free to disregard in any way - it's just a small possible improvement.
Not sure how simple it is to do user-input entries; in HTML/CSS these are quite simple and
in gtk, qt, libui and other toolkits it's also quite simple. Looking at icewm right now in the context
menu I don't seem to find an example for being able to type something. In for instance KDE
plasma desktop you have a "search" functionality that allows for users to type something.
(I don't quite propose a search functionality; just an input entry to execute commands from
the context menu. I sometimes manage to break terminals such as xterm, so it would be
nice to be able to just type the commands as-is without having to remember the shortcut
for starting it. I am quite sure there was one, in fluxbox it is alt+f2, but I'll look it up after 
writing this issue request because otherwise I'd forget it quickly again ...  :D.)

**Comment by danfe** [comment]
This imposes the same problem I've mentioned in the issue #644: having a text input field would mean that IceWM not only manages windows, but does what's typically a widget toolkit's work.  While IceWM does provide couple of ancillary things like the taskbar, status bar, and context menu, none of those requires managing user's input other than mouse clicks and navigation/select keys.

There are plenty of third-party launchers that offer command typing with intelligent completion, suggest candidates to run, etc., from [dmenu](https://tools.suckless.org/dmenu/) to [Ulauncher](https://ulauncher.io/).  Have you tried any of them yet?

**Comment by gijsbers** [comment]
"Alt+Ctrl+Space" gives you the address bar.
