### ISSUE TITLE
systray background glitch

### ISSUE THREAD

**Issue by zaza42** [bbidulock/icewm#626]
The background of system tray icons go glitched sometimes after `icewm -r`, like:
![icewm-29-toolbar-colorbug3](https://user-images.githubusercontent.com/16356124/145218119-96fd411e-aeb7-4b9c-a113-2f33811e1a99.png)
![icewm-29-toolbar-colorbug2](https://user-images.githubusercontent.com/16356124/145218121-6f7ee5f1-6662-4292-8a54-324994447b10.png)
![icewm-29-toolbar-colorbug](https://user-images.githubusercontent.com/16356124/145218122-056db8ed-9628-4b4d-93d0-2b695597afdc.png)

The top and bottom of the background fade are reversed. I can't reproduce it, but it occured a many times. A repeated `icewm -r` usually solves this problems. I encounter this from version 2.9.0 only.

**Comment by gijsbers** [comment]
Is this still your mix of jim-mac and ElbergGreen?
I have seen such a glitch before, but fail to reproduce it since 2.9.2.
Check this hypothesis: "To reproduce, the theme must have a
taskbar/taskbarbg.xpm, which isn't part of Gradients."
Then the fillPixmap function will be used, which looks buggy to me.
I partially fixed it a bit in commit 7db6efc83d94cba8811b8c11ae8b84f6069ab6a5.

**Comment by zaza42** [comment]
Ohh, it was before 2.9.2 - I've just realized this new release now. I'll keep an eye on it from now on to see if it improves.

(Don't sit back, I'll show you other small bugs soon. ;-> )

**Comment by gijsbers** [comment]
This must be it. I couldn't reproduce it initially, because I had Alpha=1.
The glitch was probably due to commit 96d6feec365e55c78e3b815dd32fc2f4792b4ee4,
which includes an optimization to reduce the number of taskbar relayouts on startup.

**Comment by zaza42** [comment]
IceWM 2.9.2 now ;-< 
![icewm-29-toolbar-292-colorbug4](https://user-images.githubusercontent.com/16356124/145433142-78d41786-f2dd-4be5-a310-37eda500f2c9.png)

**Comment by gijsbers** [comment]
Looks better, right?

**Comment by zaza42** [comment]
Still flipped gradient on pasystray and audacious icons. :-<

**Comment by gijsbers** [comment]
More rigorous fix. Try again.

**Comment by zaza42** [comment]
The latest git version seems to have fixed this bug.
Thanx!

**Comment by gijsbers** [comment]
Thanks for letting us know!
