### ISSUE TITLE
Window resize borders are too thin

### ISSUE THREAD

**Issue by Vrihub** [bbidulock/icewm#628]
I find it difficult to resize windows, when moving the mouse pointer onto the border window one has to be very precise, the "active area" (where the pointer enters "resize mode") is only some pixels wide, too thin.

Is there a way to enlarge that area? I tried changing `BorderSizeX` and `BorderSizeY`  but it seems they have no effect.

**Comment by gijsbers** [comment]
How and where did you define BorderSizeX?  Which places of definition did you consider? Why not more?

**Comment by gijsbers** [comment]
Themes with wide borders include Sky, NanoBlue, Illuminate-ice, Aalglatt, DC-macdebian, xfvwm, CoolSteel.

**Comment by Vrihub** [comment]
> How and where did you define BorderSizeX?

I found it in the ~/.icewm/preferences file

> Themes with wide borders include Sky, NanoBlue, Illuminate-ice, Aalglatt, DC-macdebian, xfvwm, CoolSteel.

Uhm, I didn't noticed they were part of the `Themable preferences` section, so I have to put them in `~/.icewm/prefoverride`. Ok.

The problem with these is that they also draw a visible thicker border around the window, changing the window position/size which is bad for some of my applications, leaving the actual visible border unchanged.

I think there should be a way to configure only the "logical" area that activates the window resizing feature.

**Comment by gijsbers** [comment]
You could also use `KeyWinSize` and `MouseWinSize`. They work very well, but take a little getting use to.

We can't add a logical area, because applications use those mouse events too.
