### ISSUE TITLE
"Hot" sorted on top of QuickSwitch list, hard to reach

### ISSUE THREAD

**Issue by Code7R** [bbidulock/icewm#631]
Repro:
- Have a few windows, the one in foreground maximized
- make a window sends notifications (for example, use HexChat and send a message from another PC to trigger hexchat's taskbar notification) while this window is in background
- Use Alt-Tab to get to that window

Problem:
in the quickswitch, the hot window is the first one. But the first press of Alt-Tab already moved the cursor to the second entry, which is your currently active window! (unlike the regular behavior where the cursor points to the next option)
And how to get to the blinking window's entry?
Either keep alt-tabing through the whole list, or break your fingers by using alt-shift-tab, or use other input (mouse). All very inconvenient options.

Expectation:
the hot window should be the second in the list, which is focused by alt-tab right in the beginning.

**Comment by gijsbers** [comment]
Can you test this?

**Comment by Code7R** [comment]
Looks better, thanks.
