### ISSUE TITLE
Geometry displayed when moving windows vs. icesh

### ISSUE THREAD

**Issue by gprints** [bbidulock/icewm#636]
I'm not sure if this is a bug or if it's supposed to be that way, but when I move a window to the upper left corner, icewm displays a geometry of axb+0+0 with a and b being the size of the window. When I run icesh getGeometry, it's at +6+26. When I run setGeometry with a +0+0, the title bar and the borders are off-screen. I'm still running 2.9.4.

**Comment by gijsbers** [comment]
That seems to be correct. If you want to know more you can read the ICCCM.
Specifically, 4.1.2.3. WM_NORMAL_HINTS Property and the win_gravity.
