### ISSUE TITLE
Add option for ToolbarIconZoomSize to control a larger icon and program title when a toolbar icon is hovered.  [Enhancement idea]

### ISSUE THREAD

**Issue by cheapy** [bbidulock/icewm#637]
The idea is that when you hover over a toolbar icon currently, it displays the program title text overlaying the taskbar icon below.  

This action would remain the same if ToolbarIconZoomSize=0 which would be the default value.

If ToolbarIconZoomSize=64 then it would display a zoomed to 64x64 sized icon and title text above (if toolbar at bottom) or below the toolbar icon area, similar to how the Network and CPU monitors display the tip text in a popup window above or below the tray area. 

I will try to photoshop a pic of what it would look like.

**Comment by rubyFeedback** [comment]
I like all ideas related to "better introspection" so +1.

Image may be helpful to more easily indicate how this should be positioned.

**Comment by cheapy** [comment]
Here is a pic of close to what it would look like if I hover over the smaller Synaptic icon on the toolbar.  I arbitrarily decided to make the hover icon 64x64 instead of 32x32.  so the larger hover icon is placed on the toolbar at the same vertical position, and the larger icon centered over the position of the smaller icon, and then the description centered above it.   There should be a border on the sides of the icon the same size as it would normally be.   Limit the horizontal position to positions on the screen.  Yes, when hovering over an icon, the icons on either side will be partially or completely blocked from view, depending on the size chosen for the hover icon.  This is to keep it efficient and simpler to implement.  If the toolbar is at the top of the screen, the hover icon extends lower than the toolbar icon line, and the description goes under the hover icon.  The pic below shows what it looks like now when hovering. 
![screenshot-2022Feb06_050640](https://user-images.githubusercontent.com/7473967/152678633-d0826ec1-14e7-4133-a751-b9342de18c50.jpg)

![screenshot-2022Feb06_044232](https://user-images.githubusercontent.com/7473967/152678843-ac30e9a0-be1d-4d68-b742-25d0dceb8e5d.jpg)

**Comment by cheapy** [comment]
For an efficient workflow (as compared to using menus, which are fine for programs I rarely use, but want available), I add a launcher icon to the toolbar for every application that I use even once a week or once a month.  My icons need to be small to fit them all, so having them zoom when I hover will make them easier to see and get the right one.

**Comment by gijsbers** [comment]
Is this OK? It doesn't need an option.

**Comment by cheapy** [comment]
That works great, Thanks :)

**Comment by cheapy** [comment]
@gijsbers I'm sorry, I should have thought of this, but what looks and feels great to me is not always right for everyone.  For me the icons are beautiful, but to some others they are distracting because they pop up.  

Would it be possible to make a preferences/prefoverride option to turn them on/off? 

# TaskBarShowToolTipIcon=0/1

PS: I am suggesting on/off because the question to others seems to be should it pop up rather than how big should it be, and also I was looking at your naming convention, and it seems TaskBarShow is a better place for it.

**Comment by cheapy** [comment]
as a temporary workaround for those who didn't like it, I figured out that resizing the huge icons would minimize the issue.

HugeIconSize - If you set it to 8 in ~/.icewm/prefoverride you may be happy again, that is until you find whatever else huge icons get used for…

# Dimension of the large icons
HugeIconSize=8 # [8-128]

**Comment by cheapy** [comment]
The workaround didn't work well enough and the Devs reverted the code back to before the larger icon when hovered.  

The large icons were great on my 1080p laptop (1920x1080) and 4k big screen (3840x2160).

**Comment by cheapy** [comment]
Works great, everyone is happy :)
