### ISSUE TITLE
Building without documentation [asciidoc]

### ISSUE THREAD

**Issue by exebook** [bbidulock/icewm#638]
Hi I am trying to build `icewm` on a newly installed Ubuntu, but I cannot seem to find an option to build without documentation. I think I knew how to do this long ago, but forgot. `configure --help` did not help me. I know I need asciidoc but when I typed apt get asciidoc it said 

```
After this operation, 903 MB of additional disk space will be used.
```
I do not think I need another 903M of stuff to get a feature I never really use, I read all docs online.

**Comment by gijsbers** [comment]
You don't tell us if you build from git repository, but if you use the `.tar.lz` to build from, as the website explains, then you shouldn't need asciidoc.

**Comment by exebook** [comment]
Yes, from  git. This replaced 903M for me:

```
sudo cp /bin/echo /bin/asciidoc
touch ./doc/icewm.html
sudo make install
```

**Comment by exebook** [comment]
This brings another interesting question though, why git usage also forces documentation? Is it like git is for maintainers only, users should use zipped releases? But modern users tend to `git clone` `make install` instead.

**Comment by gijsbers** [comment]
A release is convenient for users.
The git repository is convenient for developers.
Developers own beefy hardware.
If you want to impersonate as a developer then muscle your stuff.
