### ISSUE TITLE
Feature Request: Mouse Wheel Workspace Switching

### ISSUE THREAD

**Issue by prg318** [bbidulock/icewm#640]
It would be great if there was an option to use the mouse wheel on the desktop to change desktop workspaces.  This should probably not be enabled by default, but it would make icewm more flexible if it was an option.  Openbox and other *box WMs do this behavior by default, so I'm sure many people are accustomed to this behavior.

For example:  If the user is on desktop 1 and the mouse cursor is not over a window and the user scrolls down, the desktop could be switched to Desktop 2 if this feature was enabled.  If the user is on desktop 2 and the mouse cursor is not over a window and the user scrolls up, the desktop could be switched to Desktop 1.

Let me know if there is any additional information I can provide.  Thank you for your hard work and contributions to this awesome window manager!

**Comment by gijsbers** [comment]
This already works if the mouse pointer is over the workspace list in the taskbar.
In addition, you can use edge switching. Search for `EdgeSwitch` in [preferences](https://ice-wm.org/man/icewm-preferences).
You can define it in keys like:

    key "Pointer_Button4"   icesh goto prev
    key "Pointer_Button5"   icesh goto next

But the current release of icesh doesn't yet support `prev` and `next`.

**Comment by prg318** [comment]
Thanks for the information!  The `key` bindings work great with the latest version of icesh from git.

Thanks a lot for the heads up and all your efforts on the icewm project
