### ISSUE TITLE
Feature Request:  Allow multiple binds to same function in preferences

### ISSUE THREAD

**Issue by prg318** [bbidulock/icewm#642]
Hello!  First of all, I apologize if this is already possible to do in icewm, but I wasn't able to find out how in the documentation.  It would be useful to be able to use multiple keybinds for a single function in preferences.

For example, let's say a user would like to use both "Alt+F4" and "CTRL+SHIFT+Q" for KeyWinClose:

KeyWinClose="Alt+F4"
KeyWinClose=Ctrl+Shift+q"

Icewm will only use one of the above entries in the preferences configuration file.  Perhaps a separator (maybe "|" pipe?) could be used to allow for multiple binds to be registered like this:

KeyWinClose="Alt+F4|Ctrl+Shift+q"

There is an available workaround for this:  in order to bind two keys to KeyWinClose, one can set one keybind in icewm, and then use xmodmap or another program to send the close key combination when another key combination is pressed.  However, it would be useful to be able to define this in the icewm configuration directly.

Let me know if I'm missing some existing functionality in icewm or if there is any additional information i can provide that would be helpful.

Thank you again for all your hard work on the awesome icewm project!

**Comment by gijsbers** [comment]
It's not supported. You can't use `icesh` in `keys`?
Otherwise  see the discussion in https://github.com/bbidulock/icewm/issues/584#issuecomment-839831988.

**Comment by prg318** [comment]
Thanks for the heads up!  I'll admit - I had not read over everything that `icesh` can do in its man page until now and I see that most everything in `preferences` that I would want to bind can be accomplished with `icesh` binds in `keys`.  Thank you for letting me know and sorry about the noise!  Hopefully someone else that didn't yet read the icewm man page might come across this closed issue and find it helpful.

Thanks for the quick response @gijsbers - I'll be updating my config shortly.  Take care!
