### ISSUE TITLE
Only startup.wav works with icewm-session --sound (icesound)

### ISSUE THREAD

**Issue by ghost** [bbidulock/icewm#643]
Hello,

I've been doing a lot of tweaking with my favorite window manager today. I only recently found out there is a sound theme system (icesound) and I've enabled it via .xinitrc when launching my icewm-session with the --sound flag:

`exec dbus-launch --exit-with-session icewm-session --sound --nobg
`
^ My .xsession & .xinitrc

I downloaded the "warp" theme from the icewm website and managed to get it semi-working by extracting all the sounds to $HOME/.icewm/sounds. I say semi-working because only the "startup.wav" works when there are all sorts of other sounds that came with it.

This is icewm 2.9.4 on FreeBSD 13.0-RELEASE. Any help or clarity is appreciated. :-)

**Comment by gijsbers** [comment]
What sound interface?

    icesound --list-interfaces

Does this work?

    for f in $(icesound --list-sounds) ; do if test -f ~/.icewm/sounds/$f ; then echo "Playing $f"; icesound -p $f; else echo "Skipping $f"; fi ; done

**Comment by ghost** [comment]
> What sound interface?
OSS.

> Does this work?
Says "illegal variable name"

**Comment by gijsbers** [comment]
What shell do you use?

**Comment by ghost** [comment]
> What shell do you use?

It's tcsh. I just ran the command in a terminal emulator because I assumed that's what you meant.

**Comment by gijsbers** [comment]
It is a `bash` script. Can you start bash and run it?

**Comment by ghost** [comment]
It works. It played all of the sounds.

**Comment by gijsbers** [comment]
Good. Monitor sound events with `icesh guievents`. For each line icesound should play a sound.
