### ISSUE TITLE
Feature request: allow changing window title manually

### ISSUE THREAD

**Issue by Vrihub** [bbidulock/icewm#644]
How about adding a "Rename" command to the window menu (alt-space, or right-click on taskbar window item), to be able to type in the new window title manually? At the moment I'm using a custom script to do that. Would it be difficult to implement?

**Comment by danfe** [comment]
> to be able to type in the new window title manually

This implies that IceWM would need to grow a pair of _widget toolkit_ features, like text input and buttons.  While some window managers might offer that, IMHO this is anti-Unix in its nature and not a window manager's job.

> At the moment I'm using a custom script to do that.

That's exactly the right, Unix-style approach.

**Comment by gijsbers** [comment]
IceWM already includes widgets for text input and buttons.

**Comment by gijsbers** [comment]
"Rename" is in 3.2.2.
