### ISSUE TITLE
Focus problems in 2.9.6.6

### ISSUE THREAD

**Issue by frankzen** [bbidulock/icewm#650]
Actually for the last few versions I am having focus problems but only on my Fedora 36 installation.  No matter how I set focus in the settings menu, Icewm acts like I have set expilcit mouse focus. I also run the Mate desktop on this partition...could focus settings there be interacting?  I have focus under IceWm set to "click to focus" but if I have two windows up, moving the mouse from one to the other brings up the item under the mouse. I don't have this problem under Debian. Any help appreciated.

**Comment by gijsbers** [comment]
Check if your AutoRaise is 1. Should be 0.
Otherwise give us: `icewm -p | grep Raise`.

**Comment by frankzen** [comment]
It was. Changed to 0  and works as expected.
Thank you for the quick fix.

For completeness :

[frank@fedora-36 ~]$ icewm -p | grep Raise
FocusOnAppRaise=1
RequestFocusOnAppRaise=1
RaiseOnFocus=1
RaiseOnClickClient=1
RaiseOnClickTitleBar=0
RaiseOnClickButton=0
RaiseOnClickFrame=0
LowerOnClickWhenRaised=0
AutoRaise=0
QuickSwitchRaiseCandidate=0
AutoRaiseDelay=400
ButtonRaiseMask=1
MouseWinRaise=Ctrl+Alt+Pointer_Button1
KeyWinRaise=Alt+F1
IceWM: A window manager is already running, use --replace to replace it
[frank@fedora-36 ~]$
