### ISSUE TITLE
undo key capturing

### ISSUE THREAD

**Issue by HJarausch** [bbidulock/icewm#651]
Sorry, this is probably no bug.
I've just install IceWm on a Ubuntu system. I'v copied the .icewm folder from my Gentoo system.
Now, I IceWm captures **Ctrl**+f and opens a new xterm. I have no idea why.
Since **Ctrl+f** is used in browser and editors for searching a string, this makes IceWm nearly unusable.

Where could this key binding be defined (I have searched all files in the folder .icewm and  
/usr/share/icewm - there is no /etc/icewm)
How can I stop IceWm from grabbing **Ctrl+f**

Many thanks for a hint,
Helmut

**Comment by gijsbers** [comment]
What Ubuntu version? Which icewm?
What gives `apt list --installed | grep ice`?
Run icewm with `--trace=conf,prog` or `Trace=conf,prog`.
The output shows which files it opens or runs.

**Comment by HJarausch** [comment]
Sorry for the noise. I had **xbindkeys -p** in the **startup** file, which caused this problem
Helmut

**Comment by gijsbers** [comment]
I suspected something like that.
You can still close this issue and donate! :)

**Comment by zaza42** [comment]
Please someone close this issue!
