### ISSUE TITLE
ACPI temperature in status bar has a trailing period

### ISSUE THREAD

**Issue by lathanasiadis** [bbidulock/icewm#652]
When the preference `CPUStatusShowAcpiTemp` is set to `1`, the temperature shown ends with a period, e.g "33." instead of "33" or "33.0".
I tried changing the width of the monitor with `TaskBarCPUSamples` to see if a decimal place is being cut off, but it turns out that this isn't the case.
My IceWM version is 2.9.6 running on Fedora 35.

Also, a small feature request: It'd be nice to show "°C" in the end of the temperature string so that what's being displayed is more clear.

**Comment by gijsbers** [comment]
Thanks for reporting this. Can you test the solution?

**Comment by lathanasiadis** [comment]
Just tested it and it works fine, thanks for the quick fix!
