### ISSUE TITLE
[Enhancement] Allow TaskBarGraphHeight= to be defined in theme file

### ISSUE THREAD

**Issue by cheapy** [bbidulock/icewm#659]
Currently, in order to support themes to fit different monitor resolutions and sizes, I need to put an entry into prefoverride or change the main preferences value which would affect all themes on all screen types.   Otherwise the taskbar/toolbar icon and monitor heights might not be reasonable for the screen.  

Following what seems to be a normal convention, I've created theme variants to fit general ranges of screen sizes, and it would make be better if the theme itself could provide a value that overrides the default value in preferences, and which the user could optionally override themselves in prefoverride if needed.

**Comment by gijsbers** [comment]
Did this help you?

**Comment by cheapy** [comment]
Thanks much!  Sorry, I didn't notice a notification before. I will give it a try tomorrow night.

**Comment by cheapy** [comment]
Yes, it worked perfectly, tested as follows:
Default from preferences
override possible by theme
override over theme value by prefoverride

**Comment by cheapy** [comment]
Thanks again!

**Comment by gijsbers** [comment]
Is this sufficient, or do you need/prefer a release?

**Comment by cheapy** [comment]
If you could just include it in the next release, please, that would be great.  When I see it's working I'll add it to the themes.

Thanks again :)

**Comment by gijsbers** [comment]
It's in the new 2.9.8 release.
