### ISSUE TITLE
Window title not updating within QuickSwitch (alt+tab) dialog for some otherwise normal looking programs

### ISSUE THREAD

**Issue by celeron55** [bbidulock/icewm#663]
In #612 there's a mention of this really good and important feature of IceWM:

"If a theme specified different color for active window title, then yes, you'd see the candidate window title drawn as active while cycling through them."

There appear to be some programs where this does not work. In the non-working program(s), the window title does not change color when cycling through windows using alt+tab.

Not working: arduino (1.8.19)

(Working: rxvt-unicode, firefox, google-chrome, pluma, dolphin and various other programs)

To me other non-working programs are currently unknown.

I will describe the exact behavior by using this example:
- You have 2 windows from "working" programs and 2 windows from "non-working" programs
- The last used window order is: working 1, non-working 1, non-working 2, working 2
- The window currently active is "working 1".

Interacting with this example gives a result as follows:
1. On the first alt+tab press, the selection switches to "non-working 1", but the window title of "working 1" stays active and the window title of "non-working 1" does not activate or change in any way.
2. Continuing pressing alt and pressing tab again, the selection switches to "non-working 2" but the window title of "working 1" still stays active and the window title of "non-working 2" does not activate or change in any way.
3. Continuing pressing alt and pressing tab again, the selection switches to "working 2", and now the window title of "working 2" changes to the active color and the window title of "working 1" changes to the inactive color.
4. Continuing pressing alt and pressing tab again, the selection switches to "working 1", and now the window title of "working 1" changes to the active color and the window title of "working 2" changes to the inactive color.
5. Continuing pressing alt and pressing tab again restarts the cycle from step 1.

If you release tab at any point, the selected window is activated and the window title colors then update, regardless of whether the window was a working or non-working one.

I'm using IceWM 2.9.9 as packaged by Fedora.

Wait... that one is from another branch compared to this repo, but it has some of the same relatively new features? Ok now I'll have to go hunting for all the repos first...

**Comment by gijsbers** [comment]
If arduino is the only program, maybe it has something peculiar?
Could you do `xprop | grep -e '[:=]'` on its window? It has only one window?
Also try `icesh spy` and see if anything is different when you cycle.

**Comment by gijsbers** [comment]
3.2.0 has changes which may fix this. If this still occurs, examine the output of `icesh -a list focusmodel` and report the focusmodel of the failing applications.

**Comment by celeron55** [comment]
I now have IceWM 3.6.0 as packaged by Fedora, and the problem still occurs.

I'm not sure what the output of `icesh -a list focusmodel` means and which rows are important, but here's what I think relates to the Arduino window:

```
$ icesh -a list focusmodel | grep 0x600000c
0x600000c   2 1388778 "vcu1 | Arduino 1.8.19": (sun-awt-X11-XFramePeer.processing-app-Base) 1369x1221+8+44
0x600000c  focusmodel Globally
```

Here's, for comparison, Firefox:

```
$ icesh -a list focusmodel | grep 0x70007a8
0x70007a8   2 806564 "ui8dhw2.0_schematic.pdf — Mozilla Firefox": (Navigator.firefox)  3840x2111+0+0
0x70007a8  focusmodel Locally
```

Arduino seems to be only window for me with `focusmodel Globally.`

**Comment by gijsbers** [comment]
Indeed. Applications which use the Focusmodel Globally can be a bit problematic in accepting focus.

I can verify that Arduino 1.8.19 behaves as you say, but arduino-ide_2.3.6 seems to work fine. Can you verify this?

To me this issue seems of minor importance, as we can still select and properly activate the application. It is unrealistic to expect IceWM to workaround every application bug.

**Comment by celeron55** [comment]
Sure, stating that Arduino 1.x has a bug which is not worth working around is a reasonable conclusion to this PR.

I don't like Arduino 2.x and don't have that installed, so I don't really even care about finding out. I think they rewrote the entire thing so it probably has an entirely new set of bugs and none of the old ones.
