### ISSUE TITLE
Tabbed Windows: Tabs are not shown

### ISSUE THREAD

**Issue by fladd** [bbidulock/icewm#673]
When using the new tabbed windows feature as advertised, the titlebar is blinking when dragging a second window over it, as per documentation, but when I release the dragged window, there are no tabs. The titlebar just gets replaced with the new window. I tried different themes (including the default one), but none of them shows any tabs.

Another issue is that while Alt+Tab works for switching to these invisible tabs, reaching the last one of them kind of interrupts the Alt+Tab cycle, such that one needs to press it Alt+Tab twice to continue.

**Comment by gijsbers** [comment]
1. todo
2. done

**Comment by gijsbers** [comment]
1. In 3.1.0 there are small tab indicators. Is this sufficient?

**Comment by fladd** [comment]
1. Mmh, I am still not seeing any actual tabs, just a "...".
2. The Alt+Tab behaviour also still doesn't do what I would expect, or at least I don't understand what the switch order/logic is. It always toggles between the first tab and whatever is currently visible (unless the first one is visible in which case it toggles to the second). But when I am on the second, and then Alt+Tab to the third, another Alt+Tab should bring it back to the second (because that was the last one I looked at before), but it does not, it just brings me back to the first tab. Things become even more confusing when another window is present on the desktop, because it seems that tabs from the current window always have precedence over other windows, even if the last thing you looked at before was another window. It seems that the Alt+Tab mechanisms somehow doesn't consider at all what the window viewing history was.

**Comment by gijsbers** [comment]
All tabs are ordered within their frame from left to right.
Here left also means preceding and right means successive.
The "... |" on the left side of the title indicates `KeyWinPrev`
will bring you to the preceding tab. The "| ..." on the right
says that `KeyWinNext` will go to the next tab in the same frame.
The Alt+Tab shows the tabs from left to right, except for
the currently focused tab, which is always shown first.
So there is no history of what you viewed, just a fixed ordering.
An Alt+Tab viewing history would be a new feature.

**Comment by gijsbers** [comment]
This implements your idea of the Alt+Tab having a history.
This needs to be tested to see if it all still makes sense.

**Comment by zaza42** [comment]
Unfortunately the 30 seconds history is also applied to KeySysSwitchClass, which I don't think it should.

**Comment by fladd** [comment]
> This implements your idea of the Alt+Tab having a history. This needs to be tested to see if it all still makes sense.

I will test it soon. However, I don't understand why a 30 sec history is needed when in principle just one single state needs to be saved (the previous window). What happens if I am 31 sec on a window, will it then not go back to the last one?

So basically, the behaviour I am after is that if you have n>2 windows/tabs, repeated alt-tab (with releasing alt in between!) will toggle between 2 windows only (the current one and the last one), instead of cycling through all of them.

**Comment by gijsbers** [comment]
In 3.2.1 you can set [QuickSwitchPersistence](https://ice-wm.org/man/icewm-preferences#quick-switch).

**Comment by fladd** [comment]
To which value do I need to set `QuickSwithPersistence` to get the behaviour I am after (i.e. the default behaviour of all other window managers; see also https://github.com/bbidulock/icewm/issues/683, https://github.com/bbidulock/icewm/issues/579, https://github.com/bbidulock/icewm/issues/685)?

**Comment by gijsbers** [comment]
Try `1`.
