### ISSUE TITLE
can't move window outside of the work area since 3.0.0

### ISSUE THREAD

**Issue by zaza42** [bbidulock/icewm#678]
I encounter the same bug since 3.0.0 that I've written about here: https://github.com/bbidulock/icewm/issues/550#issuecomment-778242461

Reproduce: `icesh -window focus move -42 -42`

**Comment by gijsbers** [comment]
Works fine here, but I have `LimitPosition=0`.

**Comment by zaza42** [comment]
Thanx, this was the solution.
