### ISSUE TITLE
Minor Issue with tray icon bg

### ISSUE THREAD

**Issue by SolisX** [bbidulock/icewm#68]
Hello bbidulock,

It would be nice if the icons the are not handled by icewm tray like nmapplet would match the taskbarbg.xpm. It's an eye sore to have the taskbarbg not match. 

http://s8.postimg.org/6zsr86hpw/icewm.jpg

Also this might be asking to much but it would a if the icewm menu could be made to look like
the whisker menu.

**Comment by bbidulock** [comment]
Please check to see if commit 2686986 fixes the tray icon background issue.

**Comment by SolisX** [comment]
Hello bbiulock,

No it does not fix tray icons not matching the taskbarbg.xpm.

**Comment by SolisX** [comment]
Hello Bbiulock,

http://s33.postimg.org/pksmn8zqn/screen06.png

Although this is not exactly the same  issue it's similar. The apps that you tray with icewm
when using the flat look don't match. The same is true with taskbutton-active, taskbutton-minimized.
Although you can set them as gradients in the default.theme it does look correct. I think i would be
better to have a separate trayiconbg.xpm, trayiconactive.xpm, trayiconminimized.xpm taskbuttonbegin.xpm, taskbuttonend.xpm, clockbegin.xpm and clockend.xpm.

**Comment by gijsbers** [comment]
@SolisX is this still an issue or has this been resolved by commit 374d553147999fa2a6298bf8507f50a27135330e which added the `TrayIconMaxWidth` and `TrayIconMaxHeight` options?

**Comment by bbidulock** [comment]
I think this is fixed.  Now windows are transparent all the way down to the taskbar.  Task bar pixmaps and gradients show under the icons.   See attached with cbaticon and pasystray.

![tray](https://user-images.githubusercontent.com/5490751/31607188-ae2cb344-b228-11e7-8bb8-4f99e0f82f8d.png)

**Comment by bbidulock** [comment]
Please give it a shot and see if we are done with this one.

**Comment by SolisX** [comment]
Sorry for the late reply.  I will try the newest version of icewm to see if its fixed.

**Comment by SolisX** [comment]
Yes this  issue is fixed in icewm 1.4.2.583.

**Comment by SolisX** [comment]
HelloEveryone,

With the flat look themes it's drawing the  black border around the tray icons. 

See the screenshot.
https://s1.postimg.org/60b8iwa09b/screen01.png

**Comment by bbidulock** [comment]
You know that you can upload the file rather than positing it somewhere, right?  Like this:
![screen01](https://user-images.githubusercontent.com/5490751/31680479-a5730492-b331-11e7-8723-b0505d9f8074.png)

**Comment by bbidulock** [comment]
Works for me with flat look themes.  When running the new icewm to test you must also make sure that you are running the new icewmtray.

**Comment by SolisX** [comment]
Hello Bbidulock,

You need to start icewm with Dark-Ice theme then switch to a flat look theme. It will keep the
borders from the other theme. Also notice that if i start icewm with flat look when switch to a pixmap look it will not draw the border. So icewm is keeping what ever style you started it with
for the tray icons when switching themes.

Also about uploading files. I tried to drag and drop the screenshot to cilpboard but it keeps
saying there is a problem with the upload.

**Comment by SolisX** [comment]
Wicd tray icon corrupts when using the flat look.
![screen02](https://user-images.githubusercontent.com/15175058/31688356-1a98b226-b35a-11e7-839d-80c3b695fee7.png)

Also i have conky running and when icewm starts up now the taskbutton for conky show up which does not happen on the previous version of icewm.

**Comment by bbidulock** [comment]
I don't have a Dark-Ice theme.

**Comment by SolisX** [comment]
Here is the Dark-Ice theme.
[Dark-Ice.zip](https://github.com/bbidulock/icewm/files/1392652/Dark-Ice.zip)

**Comment by bbidulock** [comment]
I just ran through every theme that come with icewm as well as those in icewm-extra-themes one after the other and they all render correctly.

**Comment by bbidulock** [comment]
Different problem.  When one starts with Dark-Ice (the only theme that has TrayDrawBevel=1), the geometry of the tray is being calculated to exclude the bevel.  When the theme changes (to one with TrayDrawBevel=0), the geometries are not being recalculated so there is a gap where the bevel would be.

**Comment by SolisX** [comment]
Oh glad you figured out what is causing the issue. So i will make a new issue and close this one.
