### ISSUE TITLE
IceWM: preferences option "restore defaults"?

### ISSUE THREAD

**Issue by rubyFeedback** [bbidulock/icewm#680]
I accidentally clicked something and the bottom bar of IceWM vanished. I was working in
KDE konsole. I had no idea how to restore it. I could still open the IceWM menu
via the windows key, but I had no idea what to choose.

I solved it by killing xorg and then simply re-starting icewm so it was not a big deal. I also
have some ruby scripts to help me, so "books --open" will open and restore my open .pdf
files, so it was not a big deal. I did not lose anything, only a bit of time.

But I think it would be nice if the preferences entry would have an additional "restore 
default values" or something like that, without having to restart icewm. Perhaps this
option already exists, but my intuition was to go to settings-preference first. So perhaps
it could be put there. Or a "subdirectory" there, such as "misc" or something like that.

It's probably not commonly needed, but a lesser needed option, so not sure if it is
worth to add it actually. I'll report it here anyway as a suggestion - who knows, perhaps
others may also find that useful. Thank you for reading.

**Comment by gijsbers** [comment]
When something like that happens, could you make a screendump of the affected area?
