### ISSUE TITLE
With edgeswitch on, I want to move a window to the next workspace by dragging it with my mouse 

### ISSUE THREAD

**Issue by cheapy** [bbidulock/icewm#681]
I can get to the next workspace by moving my mouse pointer and holding it at the edge, but I can't do that while moving/dragging a window.

Is it possible I have something configured wrong?

**Comment by gijsbers** [comment]
It seems edge switching is not supported when moving a window. Would be a valid feature request.

**Comment by gijsbers** [comment]
You can try and see if this is what you meant.

**Comment by cheapy** [comment]
Thanks much for the speedy response, I will give it a try today.

I have had Edge switching on for a couple of days now, and have increased the delay to 2000 ms, which is working, but I have my screen set at 1920x1080, so the arrow indicator that shows its going to switch is very small and when I'm on the browser scroll bar I end up switching by accident quite often.  I was able to increase the font size on the Workspace status to 18, and the time on it to 3000 ms, so I definitely know what workspace I'm on after it switches, but what would really help would be if the Arrow was also displayed in a much larger size so I would be sure to notice it before it switches accidentally.  Is there some way I could adjust the Arrow size also?

The settings I changed for the workspace were
WorkspaceStatusTime=3000
StatusFontNameXft="monospace:size=18:bold"

**Comment by gijsbers** [comment]
You can define your own cursors in `~/.icewm/cursors/`.
The format is explained in: https://ice-wm.org/themes/#cursors
The edge switching uses the scroll cursors.
Themes that define their own cursors include:

    Aalglatt
    aeteria
    cj
    CoolSteel
    FrostyG
    IceCrack2
    InfadelOS
    K-ath-Leen
    LunaDotHome
    pkde2
    tin
    Urbicande

**Comment by cheapy** [comment]
I never knew that, thanks.  

I was able to get the Left.xpm from K-ath-Leen to work as scrollL.xpm, and able to make it much larger.
For some strange reason I can't get a large Right arrow to work.  I took the larger left scrollL.xpm and used convert on it.
convert -flop scrollL.xpm scrollR.xpm

It looks like it created it ok, but doesn't appear on the right side of the screen.  Its almost as though its off the screen. 

[scrollLR.xpm.zip](https://github.com/bbidulock/icewm/files/9896897/scrollLR.xpm.zip)

**Comment by gijsbers** [comment]
It appears on the right side of the screen, because the hotspot isn't defined, as explained in the link I gave above near "Remember to define the [cursor hotspot](https://en.wikipedia.org/wiki/X_PixMap#XPM3)." By default the cursor hotspot is in the top left corner. Most cursors need it someplace else. I now see that the icewm manpage lacks a section on cursors. It is a good idea to examine the cursors of a theme. You can view the XPM files in a text editor to examine its header.

**Comment by cheapy** [comment]
Oh my!  Add that to the things I didn't know list.  I will need to work on it a lot more.  

Thanks for knowing and sharing your knowledge.

**Comment by cheapy** [comment]
Dragging a window across edges is working, and thanks to your help, the larger cursor before edge switching to the next workspace are looking good.  I don't see the arrows when dragging the window, so there is my delay before it moves, but the act of dragging it is very deliberate anyway, so you know you are dragging it and it will just be a second or 2.

I think its pretty slick :)  Great job.

![edgeswitch-arrow](https://user-images.githubusercontent.com/7473967/198937093-c6c003bb-ea59-4f0f-8488-f8ee81815a37.png)
