### ISSUE TITLE
VerticalEdgeSwitch down increases the workspace number, up decreases the workspace number

### ISSUE THREAD

**Issue by cheapy** [bbidulock/icewm#682]
VerticalEdgeSwitch=1

I move the mouse to the bottom of the screen, the down arrow appears, after a short delay the workspace switches up to the next one
 
This seems backwards.

Do I have something configured wrong?

**Comment by gijsbers** [comment]
All of the workspaces are organized in a grid. By default icewm uses 20 workspaces per row. The vertical edge switching goes from one row to the next (or previous) row. Hence by steps of 20. You can change this setup:

    xprop -root -f _NET_DESKTOP_LAYOUT 32cccc -set _NET_DESKTOP_LAYOUT 0,5,7,0

will give you a workspace grid layout of 7 rows of 5 columns. I'm not aware of any handy utility for this.

Such a statement could be added to your `~/.icewm/startup`.

**Comment by gijsbers** [comment]
@cheapy Could you try if you like the new Alt+Tab with history?

**Comment by cheapy** [comment]
I am still running the version from a few days ago with the enhancement to drag windows across the edges to the next or previous workspace.

I'm not sure what to test, but I'm on lunch from work, so will update code to current and recompile, and then check back here to see what you need me to try

**Comment by cheapy** [comment]
I have current code compiled and running
Let me know how I should test.  I saw issue 673 but not really understanding what I should be testing

**Comment by cheapy** [comment]
Ok, I figured it out.
I combined 2 windows into one.
If I have that window active and Alt+Tab, I can see both listed, and can make the other one active instead.
But what I don't see is on the title bar, I would expect to see the title of the active tab, and another inactive tab on the titlebar with the 2nd window that is hiding behind it.

**Comment by cheapy** [comment]
I thought you might like to see this...

Thanks for all your help!
![edgeswitch-arrow](https://user-images.githubusercontent.com/7473967/199319647-791ad0eb-60ca-44ca-a990-38c6e18d66af.png)

**Comment by gijsbers** [comment]
I see you have become a master in the art of cursor hotspot definitions!

**Comment by cheapy** [comment]
Yes, I got that working.  It was actually not too hard once I saw it was really just a text file.  Maybe that is also how to solve the bad colors of the arrows?  I was hoping to make them black, white and transparent in the middle.

**Comment by gijsbers** [comment]
You could also try a utility to do this. After `pixmap -in move.xpm` you can tweak colors and define the hotspot.
