### ISSUE TITLE
Alt-Tab regression while switching workspaces

### ISSUE THREAD

**Issue by danfe** [bbidulock/icewm#683]
I very much rely on the ability to press Alt-Tab and then switch workspaces, selecting the needed window as described in issue #563.  Unfortunately, commit 6502c0a, which made it into freshly released 3.2.0, had broken it: window list now stays the same, i.e. does not change to match particular (active) workspace.  In version 3.1.0 it behaves correctly.  This is quite frustrating and severely cripples the ability to select windows while cycling through workspaces.

**Comment by gijsbers** [comment]
My guess is you set `QuickSwitchToAllWorkspaces=0`, right? Can you get by for the moment with `=1`?

**Comment by danfe** [comment]
> My guess is you set `QuickSwitchToAllWorkspaces=0`, right?

Yes, of course.

> Can you get by for the moment with `=1`?

Now it shows all windows across all workspaces, only their order changes when I switch workspaces.  Looks like I can select any window and it would switch to it (and the workspace, if the window is not on the current one), but personally I find this mode quite unusable.  For example, if there are two windows on the workspace, I expect Alt-Tab would switch to another one, but most likely it would throw me to another workspace.  Second, now selecting the desired window takes a lot longer because of the sheer number of items on the window list one has to cycle through.

**Comment by gijsbers** [comment]
Thanks for the detailed explanation! You can try if this commit helps you.

**Comment by danfe** [comment]
> You can try if this commit helps you.

Yes, it does, thank you Bert!

**Comment by danfe** [comment]
There's another regression (tell me if you prefer a separate issue): previously, pressing Alt-Tab separately (releasing the keys) but continuously (again and again) would toggle between two windows, which was very convenient and matches behavior in other window managers and operating systems.  Now it selects every other window in turn.  I've downgraded to version 3.1.0 and must say that Alt-Tab window switching feels better there (not sure if just because of this bug or for other reasons I might not be able to formulate yet).

I see this in release notes: **The next Alt+Tab will continue where the previous one left off.**  IMHO this is counterintuitive and goes against what most people expect or got used to.

**Comment by gijsbers** [comment]
1. what is the usefulness of toggling between two windows, when you can also cycle over a larger group?
2. to toggle between two windows icewm already has the keybinding `KeySysWinPrev="Alt+Shift+Esc"`.
3. why is matching behavior of other window managers desirable?
4. which window managers, btw?
5. any attempt to improve the status quo is wrong?
6. what is intuitive or feels better is personal and conditioned. the reason for this feature is #673 point 2.

**Comment by danfe** [comment]
> 1. what is the usefulness of toggling between two windows, when you can also cycle over a larger group?

These are different usecases: cycling over a larger group happens when you press _and hold_ Alt while pressing Tab multiple times.  Isolated Alt-Tab's toggle between two windows idempotently.  It's very useful when you have e.g. a document you read in one window and writing something based on it in another.  Being able to easily switch between the two is instrumental in this case.

> 3. why is matching behavior of other window managers desirable?

  Short answer is [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

> 4. which window managers, btw?

Openbox, Windows Explorer, macOS Finder?  Admittedly, I can't recall where it's different. :-)

> 2. to toggle between two windows icewm already has the keybinding `KeySysWinPrev="Alt+Shift+Esc"`.

Just tried it on 3.1.0, it didn't toggle between two windows.  Also, it's considerably harder combination to use, finger-wise.

> 5. any attempt to improve the status quo is wrong?

No.  Improving is one thing, this looks more like a regression.

> 6. the reason for this feature is [Tabbed Windows: Tabs are not shown #673](https://github.com/bbidulock/icewm/issues/673) point 2.

I understand there must be a reason, since it's mentioned in the release notes.  I don't use tabbed windows, but often oscillate between two windows which is now harder to do.

**Comment by Vrihub** [comment]
Yes, please do not break the feature "consecutive alt-tab -> toggle between two windows"!
Icewm has always behaved like that and there's no reason to disrupt this useful feature!

**Comment by gijsbers** [comment]
Thanks for the feedback!
