### ISSUE TITLE
Alt+Tab broken - cannot alternate between 2 terminal windows using single Alt+Tab

### ISSUE THREAD

**Issue by brebs-gh** [bbidulock/icewm#685]
If I open terminal 1, then open terminal 2, I expect to be able to simply press Alt+Tab once to quickly switch between them. This has worked in the vast majority of previous icewm versions.

Using icewm 3.2.1, pressing Alt+Tab once, switches instead to a different (unwanted) window.

Seems a similar bug to https://github.com/bbidulock/icewm/issues/579

**Comment by gijsbers** [comment]
Thanks for reporting this. Should be fixed now.

**Comment by brebs-gh** [comment]
Thanks, this is fixed in icewm 3.2.2
