### ISSUE TITLE
Alt+Tab: color of the active menu item

### ISSUE THREAD

**Issue by zaza42** [bbidulock/icewm#687]
Since there is so much development going on in the Alt-Tab menu…

Could we have a theme option to specify the color (or xpm) of the active menu item in Alt+Tab menu? My theme uses a green bar for every active menu except the alt-tab. (`menusel.xpm` and `taskbar/taskbuttonactive.xpm`)

![menu-active](https://user-images.githubusercontent.com/16356124/201776479-6450b6e0-eef9-4b3e-9c68-f73d6bd04afe.png)
![menubar](https://user-images.githubusercontent.com/16356124/201775080-04552f2b-1838-44be-99f4-fa82c5fab8dd.png)

![alttab-active](https://user-images.githubusercontent.com/16356124/201775082-3adbaa04-cb18-46ff-b302-2504edbd4008.png)
This color is specified by `ColorNormalMenu` in `default.theme`, and it is also the background of the (ctr+esc) menu.

I would like something like this:
![alttab-active-zold](https://user-images.githubusercontent.com/16356124/201776100-86524912-cd4c-4dc8-9f18-4ba27cd2414a.png)

**Comment by zpct** [comment]
Isn't `ColorQuickSwitchActive` what you're looking for?

I notice there's in fact no option for `ColorQuickSwitchActiveText`. Instead, text for `ColorQuickSwitchActive` relies on `ColorActiveTitleBarText`. An option for `ColorQuickSwitchActiveText` will give a bit more flexibility to make themes.

**Comment by zaza42** [comment]
Wow, thanx! That was it.

Sorry for bothering and I that I didn't look into it further.
