### ISSUE TITLE
`icesh goto 4` is equivalent to `icesh goto 5`

### ISSUE THREAD

**Issue by zaza42** [bbidulock/icewm#688]
For the first 5 workspace the numbering is: 0,1,2,3,4. For the rest are 6,7,8,…. So the 1st workspace is 0, but the 6th workspace is numbered as 6.

**Comment by gijsbers** [comment]
Really? What gives `icesh listWorkspaces`?

**Comment by zaza42** [comment]
Strange… It works perfectly now. I don't know what happened to it then.

At that time I was dynamically adding and deleting workspaces, and maybe that's what caused a bug.
