### ISSUE TITLE
Switchable Toolbars enhancement idea

### ISSUE THREAD

**Issue by cheapy** [bbidulock/icewm#689]
The distro typically provides a "Standard" toolbar, but the users want varied applications add, some in common, others not.   What if there were multiple toolbars.  I would call them named toolbars.  I could make 2 or 3 different groups of icons available from my toolbar by adding an icon and toolbar-type file for each Or maybe I could switch toolbars by pressing a key or button for next_toolbar or prev_toolbar?

For syntax, in toolbar-type files we could allow for syntax like

toolbar "title" icon_name toolbar_filename

So I would create a Favorites toolbar file with prog entries

And add a line to my ~/.icewm/ toolbar file

toolbar "Favorites" toolbar_icon.png Favorites

And then if I click that icon, my Favorites toolbar pops up (it pops up on its own line above it if toolbar at bottom), and I can click an icon from my Favorites toolbar to run it, or do something (press Esc maybe or click on main toolbar) to make my Favorites toolbar disappear and get back to my regular toolbar.

I don't know any WM that has anything like this, but it would provide quick application access costing minimal memory or screen space, and giving people plenty of flexibility because its basically just another instance of a toolbar.

**Comment by gijsbers** [comment]
I'm not sure I understand. Is this similar to [include or menu](https://ice-wm.org/man/icewm-programs)?

**Comment by cheapy** [comment]
I am suggesting that we be able to have multiple toolbars, and be able to add those toolbar icons onto the system toolbar.  Its like a menu displayed in a toolbar format.  I can create a pretend example if you like?

It would be a feature unique to IceWM.  

For antiX, I would start by making the user's personal menu instead a personal toolbar icon they could click on the system toolbar instead of a menu, making it much easier and quicker to use.  I'm also thinking there could be another toolbar of Frequently used applications, thus giving the user quick access to the things they want it for and at the same time keeping the main system toolbar from getting cluttered and bloated.

**Comment by gijsbers** [comment]
Why isn't the `menu` capability of the toolbar sufficient? It has similar capabilities.
