### ISSUE TITLE
Pressing Alt+Tab then Alt+Tab does not return to the original window

### ISSUE THREAD

**Issue by covex** [bbidulock/icewm#690]
I am somewhat confused. It seems to me, that the behavior of Alt+Tab somehow changed in icewm lately. I am used to switch between two windows forth and back just by pressing Alt+Tab, but it seems in 3.2.0 versions of icewm this goes thru the whole list of windows in the window list.

Example:
1. window browser (active)
2. window terminal
3. window pdf viewer

Pressing Alt+Tab switches to 2 (terminal), after some work in terminal, pressing Alt+Tab used to switch to 1 browser back, but now it switches to 3 pdf viewer. I have all the QuickSwitch options on default.

**Comment by gijsbers** [comment]
Is this a duplicate of #685?

**Comment by covex** [comment]
Yes, this is a dupe, I am on 3.2.1 now. I was searching thru the bugs, but it showed only open ones. My bad, sorry.
