### ISSUE TITLE
No utf8 chars in titlebar etc. with non-defaut font settings

### ISSUE THREAD

**Issue by covex** [bbidulock/icewm#693]
For some time (maybe #26) I do have issue with utf8 in TitleFontNameXft etc. If I remove this definition from my theme definition then the strings display correctly, but as soon as I change them it seems to stick to iso8859-1 or something. I thought this could be a wrong font selection, but even when I do
TitleFontNameXft           =    ":size=10"
the font size is correct, but the strings are only displaying certain letters. This happened in dark ages when you e.g. used a latin1 (iso8859-1) to display latin2 (iso8859-2) strings. The _NET_WM properties are OK.

**Comment by gijsbers** [comment]
With `TitleFontNameXft="DejaVu Sans:size=12"` it works fine here.
Which letters aren't displayed correctly? What is your locale?

**Comment by covex** [comment]
Interesting, I tried several fonts and still letters like "ř,ž,š" were missing. With default font (i.e. no definitions like TitleFontNameXft) this worked OK. With this "DejaVu Sans:size=12" it works too, but with ":size=12" it does not. I.e. specifing just a size uses a different font compared to no existing definition. My locale is set everywhere to en_US.utf8.

**Comment by gijsbers** [comment]
A font designer is certainly not obliged to provide letters for every code point. Of course, because there over one million of valid ones. Hence, one needs to choose a font which does have the code points of interest.

**Comment by covex** [comment]
No argue with that, but why is default icewm font OK but when only font size is changed, then the font is not OK?

**Comment by gijsbers** [comment]
No idea. Did you try `Trace=font`? Also note there is `TitleFontNameXft` and `TitleFontName`. The latter may be used if Xft is unset.

**Comment by covex** [comment]
TitleFontName is not used - at least I did not found it to be used anywhere. Trace= is new to me:

This is with definition of all *FontNameXft using DejaVu Sans (+lucida):
14:55:16.895: IceWM: font open: DejaVu Sans:size=10 ascent=13,descent=4
14:55:17.194: IceWM: font open: lucida:size=14:boldi:bold ascent=18,descent=5
14:55:17.208: IceWM: font open: DejaVu Sans:size=12 ascent=15,descent=4
14:55:17.210: IceWM: font open: DejaVu Sans:size=12:bold ascent=15,descent=4
14:55:17.214: IceWM: font open: DejaVu Sans:size=10:bold ascent=13,descent=4

This one without any definition (thus default):
#TitleFontNameXft           =    "DejaVu Sans:size=10"
#MenuFontNameXft            =    "DejaVu Sans:size=10"
#MinimizedWindowFontNameXft =    "DejaVu Sans:size=10"
#ActiveButtonFontNameXft    =    "DejaVu Sans:size=10:bold"
#NormalButtonFontNameXft    =    "DejaVu Sans:size=10"
#QuickSwitchFontNameXft     =    "DejaVu Sans:size=10"
#ListBoxFontNameXft         =    "DejaVu Sans:size=10"
#StatusFontNameXft          =    "DejaVu Sans:size=10"
#ToolTipFontNameXft         =    "DejaVu Sans:size=10"
#ActiveTaskBarFontNameXft   =    "DejaVu Sans:size=10:bold"
#NormalTaskBarFontNameXft   =    "DejaVu Sans:size=10"
#ClockFontNameXft           =    "lucida:size=14:bold:bold"
#ApmFontNameXft             =    "lucida:size=14:boldi:bold"

14:50:05.873: IceWM: font open: DejaVu Sans:size=12 ascent=15,descent=4
14:50:05.875: IceWM: font open: DejaVu Sans:size=10:bold ascent=13,descent=4
14:50:06.201: IceWM: font open: DejaVu Sans Mono:monospace:size=12 ascent=15,descent=4
14:50:06.214: IceWM: font open: DejaVu Sans:size=12:bold ascent=15,descent=4

This is with size only re-definition:
TitleFontNameXft           =    ":size=10"
MenuFontNameXft            =    ":size=10"
MinimizedWindowFontNameXft =    ":size=10"
ActiveButtonFontNameXft    =    ":size=10:bold"
NormalButtonFontNameXft    =    ":size=10"
QuickSwitchFontNameXft     =    ":size=10"
ListBoxFontNameXft         =    ":size=10"
StatusFontNameXft          =    ":size=10"
ToolTipFontNameXft         =    ":size=10"
ActiveTaskBarFontNameXft   =    ":size=10:bold"
NormalTaskBarFontNameXft   =    ":size=10"
ClockFontNameXft           =    "lucida:size=14:bold:bold"
ApmFontNameXft             =    "lucida:size=14:boldi:bold"

14:57:50.811: IceWM: font open: :size=10 ascent=13,descent=4
14:57:51.107: IceWM: font open: lucida:size=14:boldi:bold ascent=18,descent=5
14:57:51.114: IceWM: font open: DejaVu Sans:size=12 ascent=15,descent=4
14:57:51.117: IceWM: font open: DejaVu Sans:size=12:bold ascent=15,descent=4
14:57:51.121: IceWM: font open: :size=10:bold ascent=13,descent=4

did not help much - is the ":size=10" a valid syntax? It changes the size, this works, but it is still not obvious which font is taken in that case. I'd expect the default "DejaVu Sans" should be used as in case there is no definition, but maybe this is beoynd IceWM and up to Xft which font is used in that case?

**Comment by gijsbers** [comment]
This is ideed very much beyond IceWM. You could look at font-config and fc-match for a start. Become an expert and teach us and update the user documentation.

**Comment by covex** [comment]
You are right. Probably not anything to teach
$ fc-match ":size=10"
Vera.ttf: "Bitstream Vera Sans" "Regular"

Not sure which doc is now maintained or which should be used for that, there is somehow more repos including my old theme howto. Here is a commit to man/icewm-preferences 
https://github.com/covex/icewm/commit/e999f4df6414f15bdbf9ffac3a4cb41d94bedd02
