### ISSUE TITLE
[request] non-gnome SVG loader

### ISSUE THREAD

**Issue by Tcll** [bbidulock/icewm#695]
Gnome libraries often prove to be problematic and often tend to break or have various incomprehensible issues

such as gdk-pixbuf failing to find it's loaders, and refusing to register it's loader modules

so this request is to replace librsvg and remove the need for gdk-pixbuf completely :)

perhaps something like nanosvg might work: :)
https://github.com/memononen/nanosvg
(you may need to fork it if you want to maintain it though)

**Comment by gijsbers** [comment]
This is a great idea to reduce the dependencies on other packages.
Can you test this implementation (and also the new focus behavior)?
Use `configure --disable-rsvg --enable-nanosvg`. Thanks!

**Comment by Tcll** [comment]
well, I personally can't test after breaking gcc somehow (I'm considering just removing it along with pacman)
though what I'd like to do is build portable environments with tcc instead rather than have everything in `/usr/...`
but I'm not ready for that just yet (too much on my plate as is)

I just hope to inspire and eventually see change ;)

but I hope someone else more capable can actually test :D
(I'll report any issues that trickle down to the Artix repos)

or if you're willing to build an AppDir (like I've done with fvwm3), I could download and test that for you sooner ;)
but you'll have to provide the AppDir.tar.gz on the website since github doesn't load release assets due to blocked malware
(posting issues barely works for me as is, thank you Microsoft)

I'm willing to work with you, just everything's up in the air with me atm, so yeah, technicalities galore... x.x

**Comment by gijsbers** [comment]
Implemented by commits 598b7e1297d181719f89aae99202e6d78a6e8c8a and c7986036100457845465300a607c25b56236fc28.
