### ISSUE TITLE
configure does not report selected audio support

### ISSUE THREAD

**Issue by danfe** [bbidulock/icewm#699]
In the summary after the `./configure` run, **Audio support** line is always empty.  The following patch fixes it for me (now correctly reports "oss" in my case):
```patch
-  { $as_echo "$as_me:${as_lineno-$LINENO}: result: Audio support: $ice_value" >&5
-$as_echo "Audio support: $ice_value" >&6; }
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: Audio support: $iface" >&5
+$as_echo "Audio support: $iface" >&6; }
```

**Comment by gijsbers** [comment]
`iface` is incorrect since it is also reported if that interface is unavailable. Edit `configure.ac`. Thanks!
