### ISSUE TITLE
utf in menu broken

### ISSUE THREAD

**Issue by ivan1986** [bbidulock/icewm#7]
Hello
i try update debian package from 1.3.7 to latest git

for now new version correct build, but in new version i have new bugs
- broken unicode symbols in menu, 
- not fix old - unicode names in window titles

https://launchpad.net/~ivan1986/+archive/ppa

can you look on this package, it may be useful after i found way to fix bugs

**Comment by bbidulock** [comment]
I didn't really change anything there, but I noticed that icewm doesn't handle utf8 well at all.  Well, I fixed a memory leak in some iconv functions.  When I get some time I will look at what windowmaker and blackbox do (both handle utf8 well in the menu at least).

**Comment by ivan1986** [comment]
I check in vagtant - build from source - same bug
but in debian in menu utf is correct show
in new version i turn off many debian patches - they may fix this

**Comment by bbidulock** [comment]
It looks like commit 04dc06efa3699c90f88c37f7290eb6ebe16bc730 may have fixed this issue as well.  Please check if UTF-8 is rendered properly in the menu now.

**Comment by ivan1986** [comment]
yes, all correct

**Comment by bbidulock** [comment]
Closed then...
