### ISSUE TITLE
Windows do not render when rolledup

### ISSUE THREAD

**Issue by ResidentSpaceDragon** [bbidulock/icewm#703]
Coming from fluxbox, you could 'shade' a window,which is similar to rolledup and the program would just be a titlebar. However with icewm if you try to record that rolled up window with OBS for example, the window does not render and only shows a black spot in its place.
Is there a way to replicate this behavior in icewm so that rolledup windows may be recorded?

**Comment by gijsbers** [comment]
IceWM unmaps a shaded client window, while fluxbox doesn't. Both are acceptable options for a window manager. You can hack the source code, of course, but  it would be more logical to report this as a bug to OBS. You should at least be given the option to record the frame, which contains the titlebar of the shaded client window.

**Comment by ResidentSpaceDragon** [comment]
@gijsbers 
Just having the title bar isnt what is expected, bothering obs seems a big much for just a title bar when the rest of the program wouldnt even be loaded for the work

Can this be turned in to a preference? I'm not a developer.

**Comment by gijsbers** [comment]
No!
