### ISSUE TITLE
 iceWM does not show VirtualBox's minibar

### ISSUE THREAD

**Issue by remyhorton** [bbidulock/icewm#707]
When using VirtualBox in fullscreen mode the minibar does not show, regardless of the settings that control its visibility. It does however flash up very briefly when switching a VM from from windowed to fullscreen mode. This seems to be an iceWM bug because it does appear if Xfce is used on the same system (see screenshot below).

This is on Slackware 15.0 with a tarball build of 3.3.1 ([config.log](https://github.com/bbidulock/icewm/files/10527751/config.log) attached)

![vbox-guest-ctrlbar](https://user-images.githubusercontent.com/65685616/215278172-c7a5b4ed-8444-4c80-b0e5-14cc876810f6.png)

**Comment by gijsbers** [comment]
IceWM is a _layering_ window manager. It supports 16 different layers. You can see them in the output of `icewm symbols` and in the window menu. Fullscreen is layer number 14, while the mini-toolbar advertises itself with a window type of NORMAL, which by default ends up in layer 4. See the output of `xprop`. To force the mini-toolbar above the Fullscreen layer, add this line to your `winoptions`:

```
VirtualBoxVM.VirtualBoxVM.layer:   AboveAll
```

Then do `icesh winoptions`. Now when a new mini-toolbar is created, it should be positioned above the fullscreen window. Check this with `icesh -a list getLayer`. You could also do:

```
icesh -c VirtualBoxVM.VirtualBoxVM setLayer 15
```

Icesh doesn't yet know the names for Fullscreen and AboveAll.

If VirtualBox would have set the window type to TOOLTIP or DND then this problem wouldn't have occurred.

**Comment by remyhorton** [comment]
Yep that did the trick. :) Closing ticket..
