### ISSUE TITLE
System Tray popups

### ISSUE THREAD

**Issue by shlozm** [bbidulock/icewm#709]
After a lot of searching I can't figure this out.
I have 2 system tray icons; gxkb and cbatticon, they both have poups, gxkb for the current layout and cbatticon for the battery info.
They both popup towards the bottom instead of towards the top, the only way I can see them is if I place the taskbar on the top! Is there any way to fix this?
Thanks

**Comment by gijsbers** [comment]
Yes, ask the developers of those applications to make their applications work with icewm. In general icewm is not involved with menu popups, because those are created with the [override_redirect](https://tronche.com/gui/x/xlib/window/attributes/override-redirect.html) flag set to true.

**Comment by gijsbers** [comment]
Another option is to use the `ignoreOverrideRedirect` winoption and set the geometry explicitly, but tricks like that require problem solving skills.

**Comment by shlozm** [comment]
Thanks gijsbers. If you can give me an example of setting the geometry in winoptions I would definitely try to see if I can get it right. I appreciate everything you do for us in maintaining Icewm, and understand if it's too much trouble...

**Comment by shlozm** [comment]
I used the ignoreOverrideRedirect winoption without setting the geometry and I'm getting the popup in the top left corner of the display. At least I can read it!

**Comment by gijsbers** [comment]
I regret having mentioned that option. Please ask the developers of those applications.

**Comment by shlozm** [comment]
It turns out the taskbar height was the problem. I had my taskbar set too high in my theme.
