### ISSUE TITLE
Compton Issue

### ISSUE THREAD

**Issue by SolisX** [bbidulock/icewm#71]
Hello Everyone,

When i start compton the terminal loses transparency.

With compton.
http://s16.postimg.org/fjjpovyer/screen19.png

Without using compton.
http://s29.postimg.org/3vculcjxh/screen18.png

**Comment by bbidulock** [comment]
The only way a terminal can "lose" transparency when you start compton is if it is set for pseudo-transparency.  Pseudo-transparency and true transparency are incompatible.  Has nothing to do with the window manager.

**Comment by SolisX** [comment]
Hello Bbidulock,

Ok thanks for the info.
