### ISSUE TITLE
pycharm - Lose Focus after Switching Workspace

### ISSUE THREAD

**Issue by targzeta** [bbidulock/icewm#710]
Hi,
I have the same problem [discussed here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360001411659-Lose-Focus-after-Switching-Workspace-in-i3wm) but with IceWM.

Do you have any suggestion?
Emanuele

**Comment by targzeta** [comment]
Hi, why do you consider this an invalid issue? You can install the free edition of any JetBrains products to see this problem by yourself. Simply switching between workspaces.

Best regards,
Emanuele

**Comment by gijsbers** [comment]
Did you expect to investigate bugs in commercial software for free?

**Comment by targzeta** [comment]
So, do you think that is a PyCharm problem? Ok, I'm sorry but I don't know how the app interacts with the windows manager.
I noticed that if I set the ignoreNoFocusHint property, the focus is not lost, but I still don't have any cursor. I try to ask on the JetBrains forum.

Thanks anyway,
Emanuele

**Comment by gijsbers** [comment]
Please don't bother me again.
