### ISSUE TITLE
icewm toolbar and background don't update when resolution changes.

### ISSUE THREAD

**Issue by Parakleta** [bbidulock/icewm#713]
The workspace switcher (in the taskbar) and background image, and maybe other things too, don't detect when my screen resolution changes.  I have confirmed with `xev` that I am getting `RRScreenChangeNotify` events when the resolution changes.  If I use `icewm -r` and `icewmbg -r` after changing the screen resolution the sizes update properly.

I am running icewm 3.3.1 on FreeBSD 13.1 under TurboVNC, and icewm 3.3.2 on FreeBSD 13.1 under VirtualBox and both situations exhibit the same problem.

I am happy to do some further testing if needed, but I'm not sure how to expose any logging behaviour in icewm so some pointers in this regard would be appreciated.

Thanks.

**Comment by gijsbers** [comment]
This should fix the workspace button dimensions. Icewmbg works for me. Do you have special settings for that which I missed?  DesktopBackgroundMultihead DesktopBackgroundCenter SupportSemitransparency DesktopBackgroundScaled DesktopBackgroundImage DesktopBackgroundColor DesktopTransparencyImage DesktopTransparencyColor ShuffleBackgroundImages CycleBackgroundsPeriod?

For detailed logging, `configure --enable-logevents` and `pkill -x -USR2 icewm` or `icewmbg`. Don't see how that could help in this case.

**Comment by Parakleta** [comment]
The background options enabled are `...Center=1`, `...Scaled=1`, and `...Image="wallpaper.jpg"`.  Everything else is default.

**Comment by Parakleta** [comment]
![image](https://user-images.githubusercontent.com/11205202/228122604-da4eb41b-b1ed-424b-ab9b-af5094b1b498.png)

**Comment by gijsbers** [comment]
I still can't reproduce it.
Try the `--verbose` option to icewmbg.
Also try if setting `Center=0` helps.
Then try if this commit helps.

**Comment by Parakleta** [comment]
I'll have to set up a test system to build this into on the weekend, I'll get back to you with how I go.

Thanks.

**Comment by gijsbers** [comment]
Any luck?

**Comment by Parakleta** [comment]
Sorry, time got away from me with other commitments, it will be quite a while before I get another opportunity to test it.  If you prefer I can open a new ticket once I get a chance to test it further.

**Comment by gijsbers** [comment]
OK. It is in 3.3.3 which is already in [FreeBSD freshports](https://www.freshports.org/x11-wm/icewm).
