### ISSUE TITLE
Desktop background can't be changed

### ISSUE THREAD

**Issue by rwb196884** [bbidulock/icewm#717]
How do I get rid of this?
![image](https://user-images.githubusercontent.com/12090617/234545665-c0ec8732-a8a5-4fb5-8f06-3c8d72e86b66.png)

I've set
```
DesktopBackgroundColor="#444444"
DesktopBackgroundImage=""
```
in `~/.icewm/preferences` and these are commented out in `/usr/share/icewm/preferences` but it's still there.
(I would have expected user settings to override system settings.)

**Comment by gijsbers** [comment]
https://ice-wm.org/man/icewm-prefoverride
