### ISSUE TITLE
changing keyboard layouts working poorly.

### ISSUE THREAD

**Issue by jakoprd** [bbidulock/icewm#721]
If i use more than two keyboard layouts then switch using hotkey working bad. I want press both shift keys for that.

> KeyboardLayouts="us,cz,ru"
KeySysKeyboardNext="Shift_L+Shift_R"

this is not work

> KeyboardLayouts=us,cz,ru
KeySysKeyboardNext="Shift+Alt"

this is not work too but i can click by mouse for change layout. Keyboard layouts must be unquoted?

> KeyboardLayouts=us,cz,ru
KeySysKeyboardNext="Alt+Shift+k"

this is work, but when i reach last layout in list, hotkey cant jump back to first.

`setxkbmap -layout us,cz,ru -option grp:shifts_toggle,caps:none`
in ~/.xinitrc works, but here is no visual indication in icewm tray.

**Comment by gijsbers** [comment]
Traditionally icewm only supports key bindings like "Shift+k", not modifier-only bindings like "Shift_L+Shift_R".
The manpage is very clear about how  to specify the KeyboardLayouts:
https://ice-wm.org/man/icewm#keyboard-layout-switching
Please read the manpage first before asking questions.

**Comment by jakoprd** [comment]
Oh its my bad. I forgot that there is no latin k letter on the russian keyboard. set the keyboard shortcut to Ctrl+Scroll_Lock and the layout cycling works.
