### ISSUE TITLE
Question: system dialog command 

### ISSUE THREAD

**Issue by shlozm** [bbidulock/icewm#724]
Is there a command I can use in the terminal or a script to invoke the IceWM system dialog? The dialog that opens when pressing ctrl+alt+del or whatever is configured as KeySysDialog…

Searched all over and can’t seem to find what the command for that would be.

Thanks

**Comment by gijsbers** [comment]
xdotool key Ctrl+Alt+Delete

**Comment by shlozm** [comment]
OK thanks. I guess not. xdotool will do.

**Comment by cheapy** [comment]
shlozm, The time the Developers spend answering questions that were already answered is less time the have to fix bugs or develop new features.  

You asked the same question on the antiX forum and the first answer there was to try xdotool.  You might have searched for xdotool with your browser for xdotool examples and found out how to use it.

**Comment by shlozm** [comment]
I knew about xdotool, I always used that. However, the converted Chromebook I'm using now does nothing with xdotool key  Ctrl+Alt+Delete, I think because the layout is chromebook and there's no delete key on a chromebook. Pressing ctrl+alt+backspace does bring up the dialog but xdotool wont even with xdotool key Control+Alt+Backspace.
As a work around I ser KeySysDialog to Alt+Ctrl+x and xdotool key Control+Alt+x works, but I would rather still use Control+Alt+Backspace which is consistent with my muscle memory. Hence my question. All I wanted to know is if xdotool is the only way. If there's a command using icesh I figured someone here would know...
