### ISSUE TITLE
Startup script not executing brightnessctl

### ISSUE THREAD

**Issue by shlozm** [bbidulock/icewm#725]
I'm trying to set my initial screen brightness using brightnessctl
'brightnessctl set 80%' works fine in terminal (without root, my user has permission...)
I tried above command, sleep 20 &&, above command, exec above command, calling a script that executes above command, no luck. What am I doing wrong?

**Comment by gijsbers** [comment]
I can't help you, because I only do `icewm`. For problems with your system, contact your OS-provider.
```
set -x
brightnessctl set 80% &>>~/brightnessctl.output
echo "exit code of brightnessctl is $?." &>>~/brightnessctl.output
```

**Comment by shlozm** [comment]
Thanks. Your code made no difference, but I moved my original code (brightnessctl set 80% &) up in the script (I had it at the end before) and now it works! I don't know why that would be but I'm happy that it's now working. Thank you for your help and time, as always.
Shlozm
