### ISSUE TITLE
Start menu can't open by keyboard shortcut Ctrl+Esc

### ISSUE THREAD

**Issue by jinn-alt** [bbidulock/icewm#726]
When trying to open the start menu using the keyboard shortcut "Ctrl+Esc" no actions can be done with it, because when release it closes. If keep holding these keys, the menu starts flashing. It began in the  Icewm version 3.3.3.

**Comment by gijsbers** [comment]
Thanks. As a workaround one can undefine `KeySysWinMenu` and set `KeySysMenu=Shift+Esc`.

**Comment by jinn-alt** [comment]
It so works as planned. Thank you very much.

**Comment by jinn-alt** [comment]
Fixed. Thanks again.
