### ISSUE TITLE
Bug by closing the window of window list by "Alt+Ctrl+Esc"

### ISSUE THREAD

**Issue by jinn-alt** [bbidulock/icewm#727]
If try open the window of window list by keyboard shortcut "Alt+Ctrl+Esc" and after this action accidentally another press these keys, then this window is closed, but neither this keys combination, not "Ctrl+Esc" can't be works, until be mouse click on start menu button. This bug is older than the previous, but noticed only now.

**Comment by gijsbers** [comment]
If I understand you correctly, then this is the same bug as #726, and hence is fixed by commit fd02e72.

**Comment by jinn-alt** [comment]
No, that's another bug.
If to open the window of window list by "Alt+Ctrl+Esc", and after this to close his also by "Alt+Ctrl+Esc", then all keyboard shortcuts stop working.
In my opinion, it is related with loss the focus at close window, i.e. the window is closed, but the focus stayed with him. If to make a mouse click on TaskBar or on another open window, the keyboard shortcuts start working again.
In my opinion again, this window should not be closed by "Alt+Ctrl+Esc".

**Comment by gijsbers** [comment]
After commit fd02e72, compiling, installing and restarting, if I  open the window list by "Alt+Ctrl+Esc", and close it by "Alt+Ctrl+Esc", then all keyboard shortcuts are still working normally.

**Comment by jinn-alt** [comment]
It works for me as I described.
Well, I'll leave it until the time when I can check on another computer.
Thanks.

**Comment by jinn-alt** [comment]
I found the commit, after which this bug appeared. This is commit f05c2fe5026af0d74a6590adf6bb39a39f84aa47.
The bug manifests itself in either "Click to focus" or "Explicit focus" focus mode.
This bug has nothing to do with the bug #726.

**Comment by gijsbers** [comment]
OK, I could now properly reproduce it, thanks to your investigation. This fixes it.

**Comment by jinn-alt** [comment]
Thank you very much.
