### ISSUE TITLE
Icewm sometimes crashes when a window doesn't respond to close request

### ISSUE THREAD

**Issue by plomari** [bbidulock/icewm#729]
When a windows doesn't respond to being closed (like clicking on the X in the window decorations), icewm shows a message and offers you to kill it. I think this is a relatively recently added feature.

The problem is that sometimes, when the application doesn't respond and other circumstances I do not know, icewm crashes. (I was pleased to see that icewm is just restarted and even keeps the window locations, although they were shifted by the window decoration's size.) I get applications not responding relatively often. They're only temporarily frozen, but long enough to trigger Icewm's timeout. It doesn't always crash. Maybe it has to do with the application terminating while icewm still displays the message. Hard to reproduce.

I don't know if this is fixed in newer icewm releases.

**Comment by gijsbers** [comment]
Check if the client has a non-zero WM_CLASS property.

**Comment by gijsbers** [comment]
Before the crash, you do or don't see a popup with the messages
`Client with PID fails to respond. Do you wish to terminate this client?`.

**Comment by plomari** [comment]
In at least one case the WM_CLASS property was set. It was a Qt application. I can check for the exact message next time it happens.

**Comment by plomari** [comment]
> Before the crash, you do or don't see a popup with the messages `Client with PID fails to respond. Do you wish to terminate this client?`.

Yes, this exact message. I'm still using an older icewm release (3.3.3), but lately this situation didn't happen. It only happened once just now, but icewm didn't crash.

**Comment by gijsbers** [comment]
Maybe increasing the value for `# PingTimeout=3 # [0-86400]` avoids this problem.

**Comment by plomari** [comment]
I get the dialog occasionally, but it never crashed again.

**Comment by gijsbers** [comment]
That confirms the fix. Thanks.
