### ISSUE TITLE
Bug QuickSwitch

### ISSUE THREAD

**Issue by arsonoff** [bbidulock/icewm#73]
~/.icewm/winoptions:
xvkbd.ignoreQuickSwitch: 1
xvkbd.appTakesFocus: 1

~/.icewm/startup (or .xinitrc):
xvkbd >& /dev/null &

Immediately after running the IceWM, the xvkbd it is visible in the QuickSwitch (the first three press "Alt+TAB").
Without options "appTakesFocus" everything is fine, but then does not work autofocus in xvkbd :(

**Comment by bbidulock** [comment]
The option "ignoreQuickSwitch" was deprecated in 2003 with the conversion to the 1.2 branch.  So, not a bug, do not use that option.

With regard to appTakesFocus: I have no idea why you are trying to set this: xvkbd does not take focus and says so using ICCCM 2.0 compliant WM_HINTS.  You cannot make an application take focus when it refuses to accept it.

**Comment by arsonoff** [comment]
> The option "ignoreQuickSwitch" was deprecated

How then do to the application is not visible in the QuickSwitch?!

> xvkbd does not take focus

The problem is that I have the opposite. Without this option xvkbd receives focus.

**Comment by bbidulock** [comment]
xvkbd uses some EWMH properties.  It should set _NET_WM_STATE_SKIP_TASKBAR.
The other (giving focus) is incorrect and a bug.

**Comment by arsonoff** [comment]
> It should set _NET_WM_STATE_SKIP_TASKBAR

wmctrl -r xvkbd -b add,skip_taskbar
This can replace: "xvkbd.ignoreTaskBar: 1"
But one can not replace: "xvkbd.ignoreWinList: 1", "xvkbd.ignoreQuickSwitch: 1"

> The option "ignoreQuickSwitch" was deprecated in 2003

Don't delete an option (feature request :)

**Comment by arsonoff** [comment]
> fix focus issue

As before, xvkbd works correctly only with option "xvkbd.appTakesFocus: 1", xvkbd it is visible in the QuickSwitch (now only the first pressing "Alt + TAB")

**Comment by bbidulock** [comment]
Try eekboard: it looks much nicer...

![eekboard](https://cloud.githubusercontent.com/assets/5490751/16024489/83364a2c-317f-11e6-8c72-198edf4fa0a0.jpg)

and works better.
