### ISSUE TITLE
[Feature request] Mouse scrollwheel on root window to scroll through workspaces

### ISSUE THREAD

**Issue by bananaliker** [bbidulock/icewm#730]
This is a feature I'm very used to in XFCE, FVWM, Openbox and Sawfish. It's quite useful if you're using the mouse to do something and want to quickly switch workspaces. Currently in icewm you can achieve a similar affect by scrolling over the taskbar's pager itself, but it's not _quite_ as convenient as having the entire root window accept the input, since you have to aim it. 

Would this be difficult to implement as a toggle-able feature?

**Comment by gijsbers** [comment]
https://ice-wm.org/man/icewm-keys#examples

**Comment by bananaliker** [comment]
Welp, don't know how I missed that for so long. Thanks!

**Comment by gijsbers** [comment]
#640
