### ISSUE TITLE
Themes with names in upper and lower case

### ISSUE THREAD

**Issue by francescoinblack** [bbidulock/icewm#731]
Hello to all.
I don’t know if this is a bug, but since a few days I have discovered that some themes with the same names with the difference of a few uppercase or lowercase letters, icewm cancels the display of one and makes only one activatable.
Let me give an example of a couple of themes I have in the themes folder:
slashdot and Slashdot.
Both names are the same but one has s in lowercase and the other has s in uppercase; in this case icewm sees only one of the 2 themes.
I don’t know if this is a bug but in order to view all 2 themes I had to rename one of them in Slashdot02.
If this is not a bug I hope this post will help others rename some themes with the same name.
Bye
Francesco bat

**Comment by gijsbers** [comment]
It appears to be that this was done intentionally by the programmer. So it is a feature.
In general, if two theme names differ only in case, are they the same, similar or unrelated?

**Comment by francescoinblack** [comment]
Either way.
The important thing was to know so that to use them all just rename them as I did a few days ago in 01 02 etc..
Bye
Francesco bat
