### ISSUE TITLE
Some translations are missing from `.tar.lz` tarball?

### ISSUE THREAD

**Issue by danfe** [bbidulock/icewm#735]
So I read there should be new Georgian translation included in the 3.4.0 release as `po/ka.po`, but I don't see it in the tarball:

```
$ tar tf icewm-3.4.0.tar.lz | grep po/k
icewm-3.4.0/po/ko.gmo
icewm-3.4.0/po/ko.po
```

When looking at the tagged [tree](https://github.com/ice-wm/icewm/tree/3.4.0/po), it should be there together with Kazakh translation `po/kk.po` which is also missing from the release tarball.

**Comment by gijsbers** [comment]
New release tar file includes all languages.
shasum icewm-3.4.0.tar.lz   85cda505315cfacfc4642ff08a7e9e2b5ea99fb8

**Comment by danfe** [comment]
Thanks for the quick fix!  Looks like we've been missing some for a while.  Out of curiosity, why they were not included before?

**Comment by gijsbers** [comment]
They were apparently not included automatically. Some scripts are so complicated that I fail to understand them.
