### ISSUE TITLE
Add feature to force enable window decorations for GTK applications

### ISSUE THREAD

**Issue by plomari** [bbidulock/icewm#738]
Unfortunately GNOME continues their anti-user war, and unfortunately, many programs still use GTK.

Anyway, one of the problems with GTK is that more and more GTK applications seem to disable native window decorations. They use something that appears to be hardcoded for the GNOME desktop instead.  I suspect it happens when applications call gtk_window_set_titlebar().

Would it be possible to detect GTK applications and disable the request to remove window borders automatically? Alternatively, a mechanism for winoptions to force decorations, or a window menu command to do that would help.

**Comment by gijsbers** [comment]
Why on earth did you think this isn't already possible with icewm?

```
gedit.dBorder:  1
gedit.dResize: 1
gedit.dTitleBar:  1
```

Why on earth do I have to document and explain everything thrice?

**Comment by plomari** [comment]
Sorry. I even looked at https://ice-wm.org/man/icewm-winoptions (but somehow overlooked it). It works, thank you very much!

**Comment by gijsbers** [comment]
Supported since 0.8.6 (1997). Duplicate of #227.
