### ISSUE TITLE
loginctl usage

### ISSUE THREAD

**Issue by Code7R** [bbidulock/icewm#739]
I saw something odd while integrating tag 3.4.1. into Debian package:

XSV(const char *, hibernateCommand,             "test -e /run/systemd/system && systemctl hibernate || loginctl suspend")

What is this? Loginctl is NOT "user's systemctl". It does not take random systemctl commands, at least not in our version (you might have a patched one, who knows, but if so, then this should be documented).

Actually, the only sensible feature (for icewm) in loginctl is probably the lock-session command, to do the screensaver lock (without checking which screensaver is currently installed).

**Comment by gijsbers** [comment]
Github search is amazing in its ease of use:
https://github.com/bbidulock/icewm/issues?q=loginctl

So is `git blame default.h | grep loginctl` and follow the commit message to the pull request.
