### ISSUE TITLE
Not scaled CPUStatus, NetStatus, etc.

### ISSUE THREAD

**Issue by arsonoff** [bbidulock/icewm#74]
After scaling "~/.icewm/themes/theme/taskbar/start.xpm":
taskbar - scaled; CPUStatus, NetStatus - not scaled. It looks not nice.

**Comment by bbidulock** [comment]
Well, no other element scales itself either?  Is this a feature request?

**Comment by arsonoff** [comment]
> Well, no other element scales itself either?

Well yes. On HiDPI display all you need to increase: taskbar, fonts, buttons, etc. But the size of CPUStatus, NetStatus hard coded in the program.

> Is this a feature request?

It should be written to the next section (Pull requests)?

**Comment by gijsbers** [comment]
I have a patch for this ready.

**Comment by arsonoff** [comment]
Excellently. How to test?

**Comment by gijsbers** [comment]
it's all just committed. lemmeknow if it works.

**Comment by arsonoff** [comment]
No. Doesn't work.
Release 1.4.2, clean profile, has increased x2 themes/Infadel2/taskbar/start.xpm, CPUStatus hasn't changed.
[![icewm.png](https://s11.postimg.org/4cld1srmr/icewm.png)](https://postimg.org/image/vn6o9pujj/)
Current branch 523b8ad, isn't compiled:
```
wmmgr.cc: In member function 'bool YWindowManager::handleWMKey(const XKeyEvent&, KeySym, unsigned int, unsigned int)':
wmmgr.cc:301:9: error: 'wmapp' was not declared in this scope
     if (wmapp->getSwitchWindow() != 0) {
         ^
wmmgr.cc:327:13: error: 'wmapp' was not declared in this scope
         if (wmapp->getCtrlAltDelete()) {
             ^
wmmgr.cc: In member function 'void YWindowManager::restackWindows(YFrameWindow*)':
wmmgr.cc:1869:9: error: 'wmapp' was not declared in this scope
     if (wmapp->hasCtrlAltDelete()) {
         ^
wmmgr.cc:1930:9: error: 'wmapp' was not declared in this scope
     if (wmapp->hasCtrlAltDelete()) {
         ^
make[2]: *** [wmmgr.o] Error 1
```

**Comment by gijsbers** [comment]
I understand that you didn't configure with --enable-guievents ? 
That is of course a valid thing to do. It just exposes that wmapp is only defined if GUIEVENTS are enabled. I committed a small fix to always define wmapp, regardless of the GUIEVENTS setting. Just do a git pull and see wmapp.h being updated.

As to why your start.xpm has a double height I'm baffled. 
I can't understand or reproduce this. 
If I move away my configuration:

    mv ~/.icewm ~/dot-icewm
    mv ~/.config/icewm ~/con-icewm

I should have a clean slate. If I then select the Infadel2 theme everything looks normal to me.

**Comment by arsonoff** [comment]
>As to why your start.xpm has a double height I'm baffled.

Because I enlarged the image twice :)
The question consists in the following: I have small HiDPI the screen and I need to increase all elements on the screen. I can increase taskbar (having increased start.xpm), I can increase icons, fonts, but CPUStatus, NetStatus and so forth remain strictly given size.

**Comment by gijsbers** [comment]
Ah okay, well that explains it :)
To answer your question:
now there is a preferences option `TaskBarGraphHeight` to set the height of all applets.
The CPUStatus width is set by `TaskBarCPUSamples`.
The NETStatus width is set by `TaskBarNetSamples`.
etc.
You need to set them to the appropriate values.
Does that help you to achieve your goals for your HiDPI screen?
If you could git pull once more you should be able to compile without problems.

**Comment by arsonoff** [comment]
>TaskBarGraphHeight
Yes! Is what is necessary.
