### ISSUE TITLE
QUESTION  - Persistent Wallpaper When Restarting IceWM/Rebooting System/Changing Styles

### ISSUE THREAD

**Issue by VoxAndrews** [bbidulock/icewm#743]
I was wondering if there is a way to have a wallpaper stay persistent on the system when rebooting the system, restarting IceWM or changing styles. I use Nitrogen to set my wallpaper and have got it so when IceWM starts up it will run a Nitrogen command to reapply my selected background, however, if I change styles or restart IceWM, the background reverts back to the style default. I'd like to make it so I can use this command still either when switching styles or restarting IceWM through the Logout submenu. Any info would be greatly appreciated!

**Comment by gijsbers** [comment]
If you use icewmbg as part of your icewm setup, which is the default if you start it with icewm-session, then you can add your desktop settings to your ~/.icewm/prefoverride. See https://ice-wm.org/man/icewm-prefoverride and https://ice-wm.org/man/icewmbg.

If you don't want use icewmbg for background settings, then you can add your startup commands to ~/.icewm/startup. See https://ice-wm.org/man/icewm-startup.

You need to study the documentation carefully, otherwise you will be asking too many questions... ;-)

**Comment by VoxAndrews** [comment]
> If you use icewmbg as part of your icewm setup, which is the default if you start it with icewm-session, then you can you desktop settings to your ~/.icewm/prefoverride. See https://ice-wm.org/man/icewm-prefoverride and https://ice-wm.org/man/icewmbg.
> 
> If you don't want use icewmbg for background settings, then you can add your startup commands to ~/.icewm/startup. See https://ice-wm.org/man/icewm-startup.
> 
> You need to study the documentation carefully, otherwise you will be asking too many question... ;-)

Haha, that is true, thanks for pointing me in a direction to start off with, bit new to IceWM so I'm still learning the ins and outs, really interesting so far. Funnily enough, I have placed my command into ~/.icewm/startup (nitrogen --restore &) and it works great for when IceWM starts up either from turning on or logging out and logging back in. But if I select 'Logout...->Restart Icewm' it doesn't seem to run the command anymore, so I assumed that maybe 'Restart Icewm' either didn't have a file to runs commands since it seems to be seperate from startup, or perhaps there was another file

**Comment by zaza42** [comment]
You can watch restarting via a simple shellscript:
```
icesh guievents| while read a; do
   if [ "$a" = "startup" ] || [ "$a" = "restart" ]; then
      nitrogen --restore &
   fi
done
```

**Comment by gijsbers** [comment]
Or shorter: `icesh guievents | awk '/startup|restart/ { system("nitrogen --restore &") }'`
