### ISSUE TITLE
Option to remove 2 pixel margin around start.xpm

### ISSUE THREAD

**Issue by fladd** [bbidulock/icewm#744]
Currently, it seems that there is always a 2 pixel margin around start.xpm, such that it is not possible to have start.xpm fill the entire taskbar vertically.

![image](https://github.com/bbidulock/icewm/assets/2971539/2a621ed6-96a4-4b72-9a31-357963cc56d6)

If you make start.xpm larger by e.g. one pixel, than instead of minimizing the remaining margin, the taskbar gets one pixel larger as well, and the 2 pixels of margin are still there.

**Comment by gijsbers** [comment]
That start button looks too large to me and also out of tone with the rest. Hence I don't understand what justifies a new option. The code that controls the current margin stems from 2004 and is quite hairy. Another reason to be cautious.

**Comment by fladd** [comment]
Not sure I understand, but how would I make that start button (irrespective
of its tone, this is just an example) actually hit the border of the taskar?

**Comment by gijsbers** [comment]
That seems impossible. Worse, that margin can be 2 or 3 and is caused by different sections of code.
