### ISSUE TITLE
spacing when cascading windows

### ISSUE THREAD

**Issue by gsabdiv** [bbidulock/icewm#747]
It's probably more a feature request than a bug. When cascading windows, the positions are being calculated on the title bar size, ignoring the border size. When having big borders because  of a small, but hi-res screen, it would be nice to have cascading postitions by adding title bar and border size - or maybe have a configuration option for extra spacing.

**Comment by gijsbers** [comment]
Sounds reasonable. Is it easy to add a screen dump? Just the area where it looks wrong.
What DPI means `hi-res`?

**Comment by gsabdiv** [comment]
Physically, the resolution is 180 DPI, but X11 is set to 96 and no scaling applies. I just increased the border size from the default of 6 to 10, so it's easier to grab. Here's what I get when I cascade xterms (Ctrl+Alt+Esc, select windows, right click, cascade) with the default border size of 6 and the default title bar height of 20:
![cascade_default_border](https://github.com/bbidulock/icewm/assets/145005878/64d9ad53-84bc-409d-bc3d-21a30631226a)

But with a border size of 10, the title is partly hidden after cascading (xterm does have a different font size here):
![cascade_border_10](https://github.com/bbidulock/icewm/assets/145005878/06a0fd13-8dfa-418a-924f-602c9c9d8916)

**Comment by gijsbers** [comment]
If you like, you can test if this suits you.

**Comment by gsabdiv** [comment]
Looks good to me, Ticket resolved.
