### ISSUE TITLE
Suggestion how to handle processes not responding better

### ISSUE THREAD

**Issue by plomari** [bbidulock/icewm#749]
The dialog complaining about clients not responding appears too often and and situations when the clients are responding properly. (Example: claws-mail, click Compose, write some text, close editor window, it asks you whether to discard or save the mail, and after a while the icewm dialog pops up for no reason.)

I suggest one or both the following:
- show the dialog only when clicking the window close button a second time and nothing else was clicked
- offer killing the process or the client in the window menu

**Comment by gijsbers** [comment]
When you press the close button, icewm sends a ping and a close request. Your client _should_ then either close the window or reply to the ping request. Apparently this client doesn't do that. Annoying, but as long as it is unclear why, i see no reason to change anything. Claws-mail offers to close its compose window either via its menu or via its hotkey `Ctrl+W`. If you use those, you'll circumvent this case.

**Comment by plomari** [comment]
It happens with other clients too, though I don't remember which ones exactly. (I can post them when I encounter them again.)

**Comment by gijsbers** [comment]
OK,  but anything non-reproducable has little value.

BTW, you can already immediately kill a client via the WindowList. Right click over the app.

Your "second time" suggestion is too complicated and non-intuitive and violates POLA.
