### ISSUE TITLE
Can we find themes from ~/.config/icewm/themes dir?

### ISSUE THREAD

**Issue by tumashu** [bbidulock/icewm#752]
At the moment, we can find themes from ~/.icewm/themes, can we find themes from ~/.config/icewm/themes ?

**Comment by gijsbers** [comment]
You need to study the manpages, otherwise you will be asking too many questions and you didn't pay for a support contract:
https://ice-wm.org/man/icewm#configuration-directories

and:
https://ice-wm.org/man/icewm#environment-variables
