### ISSUE TITLE
When a window is in fullscreen, the notification popup is not on top of the fullscreen window

### ISSUE THREAD

**Issue by allencch** [bbidulock/icewm#753]
OS: Arch Linux
icewm 3.4.4
libnotify 0.8.3
xfce4-notifyd 0.9.3

When a window is in fullscreen mode, such as web browser, xfce4-terminal, etc, and if there is a notification, the notification is below (behind) the fullscreen window. This makes the notification unnoticeable.

Is there any solution for this?

P/S: I tried to add `xfce4-notifyd.Xfce4-notifyd.layer: AboveAll` to `winoptions`, but it doesn't solve.

**Comment by zaza42** [comment]
"/compat/use-override-redirect-windows (boolean): this defaults to false. If your window manager displays notification windows in a strange way (gives it borders or a titlebar, doesn't allow it above fullscreen windows, etc.), you can try setting this to true. Be aware, though, that notifications may end up being displayed above your screen saver / screen locker, which you might consider an unacceptable security risk." - https://gitlab.xfce.org/apps/xfce4-notifyd/-/blob/master/README.md#hidden-settings

**Comment by allencch** [comment]
Thank you @zaza42 , the above solution solved my issue.
Just wondering, why Openbox doesn't have this issue during full screen?
