### ISSUE TITLE
Strange preference menu display

### ISSUE THREAD

**Issue by frankzen** [bbidulock/icewm#757]
Running IceWm 3.4.4 on OpenSuse Tumbleweed. Noticed today wile making some minor changes of the the options has a strange mis-spelling. 
![Screenshot at 2023-12-02 11-40-36](https://github.com/bbidulock/icewm/assets/717662/30389459-593f-4422-ab25-b7f804345145)

When you change the option and save it, the mis-spellng of taskbarshowshowdesktopbutton is saved to the preference file.  If you correct the spelling in the preferences file, then re-display it in IceWm it's back to being mis-spelled.

**Comment by gijsbers** [comment]
I tried to reproduce this, but could not.
Is this consistent and only with TaskBarTaskGrouping?
Can you try `icewm --rewrite-preferences` first and then retry this?
Please give the exact verbatim copy of the misspelling.

**Comment by frankzen** [comment]
I did the --rewrite-preferences, but there was no change. I have since discovered if that preference (TaskbarShowDesktopButton) is un-commented in the preference file, changes made using the settings do not save the misspelled preference to the preferences file, but it still displays  as TaskbarShowShowDesktopButton. It also happens under all themes I have tried.  I have uploaded my preferences file.
[preferences.txt](https://github.com/bbidulock/icewm/files/13539045/preferences.txt)

**Comment by gijsbers** [comment]
There is a button called "ShowDesktopButton". To enable something on the taskbar there is a "TaskbarShow" preference. Hence "TaskbarShow" + "ShowDesktopButton"  gives "TaskBarShowShowDesktopButton" with a double "Show".

**Comment by frankzen** [comment]
I don't understand what you are saying here.
For me it's just a cosmetic issue. But at the same time I don't understand
why I'm the only one seeing this.

**Comment by gijsbers** [comment]
There is no misspelling!
