### ISSUE TITLE
Ugly popups in Google Chrome

### ISSUE THREAD

**Issue by gensenio** [bbidulock/icewm#758]
With the latest version of google chrome (Version 120.0.6099.109 (Official Build) (64-bit))  the popup menus are badly rendered:

![image](https://github.com/bbidulock/icewm/assets/3276068/77245614-9af4-4cb6-bc28-2f18716ac16d)

This is not happening when if i use a compositor like picom.

**Comment by gijsbers** [comment]
Please report your google chrome problems at the google chrome website. We know google chrome has lots of problems and google chrome needs to fix them, but google chrome can only do that if you talk to the google chrome folks at the google chrome website.
