### ISSUE TITLE
commit fb939b6

### ISSUE THREAD

**Issue by mozai1** [bbidulock/icewm#76]
commit fb939b6: add new default theme and background
surly this commit breaks too much to be useful?

**Comment by bbidulock** [comment]
What in particular does it break?

**Comment by mozai1** [comment]
the titlebar image and buttons appear corrupted for me.

**Comment by SolisX** [comment]
Hello Everyone,

Feel free to use one my themes if you like for a default theme. The default themes that you currently have look very dated.

You can find my themes here

http://box-look.org/usermanager/search.php?username=Solisx7&action=contents

**Comment by mozai1** [comment]
I've been using this theme for 15+ years so yeah its dated :) I will be changing it when i get my first direct neural interface link. I don't see why breaking loads of old themes is a good thing. But hey its no biggie i can just use older version.

**Comment by bbidulock** [comment]
Which themes are broken and how?

**Comment by mozai1** [comment]
well the one i'm using is icedesert.  The (window titlebar) image and buttons appear as corrupted images.

**Comment by bbidulock** [comment]
I don't have any problems with icedesert....
![snapshot](https://cloud.githubusercontent.com/assets/5490751/16024349/a66a87a2-317e-11e6-86ce-51223425679f.jpg)
