### ISSUE TITLE
Problem with pulldown menus on websites

### ISSUE THREAD

**Issue by char11** [bbidulock/icewm#760]
I have a problem with pulldown menus on many pages opened in firefox. e.g. https://blog.mozilla.org/en/. After clicking, the menu hides without opening the link. Sometimes it works fine. The problem also occurs on Chrome. I also have a problem with vscodium - scrollbars in the editor window often do not work. When you hover over them, the cursor changes but you cannot move them. None of these problems occur on e.g. xfce.
Log from icesh spy (two first clicks fail):
17:44.434: 0x1c0002c: Enter Ungrab Ancestor Focus
17:46.058: 0x1c0002c: Leave Grab Ancestor Focus
17:46.058: 0x1c0002c: Enter Ungrab Ancestor Focus
17:47.849: 0x1c0002c: Leave Grab Ancestor Focus
17:47.850: 0x1c0002c: Enter Ungrab Ancestor Focus
17:48.360: 0x1c0002c: _NET_WM_NAME = Mozilla Firefox
17:48.361: 0x1c0002c: WM_NAME = Mozilla Firefox
17:48.362: 0x1c0002c: _NET_WM_ICON_NAME = Mozilla Firefox
17:48.362: 0x1c0002c: WM_ICON_NAME = Mozilla Firefox
17:48.362: 0x1c0002c: _NET_WM_VISIBLE_NAME = Mozilla Firefox
17:48.362: 0x1c0002c: _NET_WM_VISIBLE_ICON_NAME = Mozilla Firefox
17:48.376: 0x1c0002c: _NET_WM_NAME = Interviews - The Mozilla Blog ... Mozilla Firefox
17:48.377: 0x1c0002c: WM_NAME = Interviews - The Mozilla Blog .%G....%@ Mozilla Firefox
17:48.377: 0x1c0002c: _NET_WM_ICON_NAME = Interviews - The Mozilla Blog ... Mozilla Firefox
17:48.377: 0x1c0002c: WM_ICON_NAME = Interviews - The Mozilla Blog .%G....%@ Mozilla Firefox
17:48.377: 0x1c0002c: _NET_WM_VISIBLE_NAME = Interviews - The Mozilla Blog ... Mozilla Firefox
17:48.377: 0x1c0002c: _NET_WM_VISIBLE_ICON_NAME = Interviews - The Mozilla Blog ... Mozilla Firefox

**Comment by gijsbers** [comment]
Try 3.4.5.
