### ISSUE TITLE
Support shutdown/reboot/sleep on FreeBSD

### ISSUE THREAD

**Issue by danfe** [bbidulock/icewm#761]
Consider the following patch I've been running with for a while, works just fine:
```patch
--- src/default.h.orig	2023-12-28 18:29:47 UTC
+++ src/default.h
@@ -193,6 +193,11 @@ XSV(const char *, shutdownCommand,              "test 
 XSV(const char *, rebootCommand,                "test -e /run/systemd/system && systemctl reboot || loginctl reboot")
 XSV(const char *, suspendCommand,               "test -e /run/systemd/system && systemctl suspend || loginctl suspend")
 XSV(const char *, hibernateCommand,             "test -e /run/systemd/system && systemctl hibernate || loginctl hibernate")
+#elif __FreeBSD__
+XSV(const char *, shutdownCommand,              "shutdown -p now")
+XSV(const char *, rebootCommand,                "shutdown -r now")
+XSV(const char *, suspendCommand,               "zzz")
+XSV(const char *, hibernateCommand,             0)
 #else
 XSV(const char *, shutdownCommand,              0)
 XSV(const char *, rebootCommand,                0)
```
Hibernate (suspend to disk, S4) is not supported on FreeBSD.

**Comment by gijsbers** [comment]
Would it be OK to use "poweroff" and "reboot" instead?

**Comment by danfe** [comment]
> Would it be OK to use "poweroff"

Yes, it would: per the manpage, calling `poweroff` is equivalent to `shutdown -p now`.  However,

> and "reboot" instead?

This one is different: `reboot` merely flushes the file system cache to disk, sends all running processes a SIGTERM (and subsequently a SIGKILL) signal, and restarts the system; it short-circuits the normal shutdown process by not going through all of the RC and other bookkeeping of stopping processes and logging actions properly before killing the OS.  You may want to check out [this forum thread](https://forums.freebsd.org/threads/how-to-shutdown-reboot-the-cleanest-possible-way.64197/).  Thus, for consistency's sake, I've opted for _shutdown(8)_ in both cases.
