### ISSUE TITLE
[Feature request] Could it be made easier to change the font size and task bar width and height?

### ISSUE THREAD

**Issue by rubyFeedback** [bbidulock/icewm#767]
I start icewm via oldschool "startx".

However had as I get older, my eye sight also got worse, and I have difficulties with small fonts and small icons.

I'd kind of like something that would easily increase icewm's scaling factor, say, by +20% or +25% or so. Something
simple.

Would it be possible to add some kind of "scaler" we could use and apply while icewm is running? If that is not
possible, perhaps a simple "scaler" that could be used, then we close Xorg, then "startx" again with the increased
font size?

I also mean the lower bottom pane, that task bar - would be nice if font size can be increased AND the individual
windows as well as the icons. So really say +25% would scale all of that by 25% including height.

Something like "Preferences", put it on the left bottom area, and an option such as "scaling". And tooltips for that
or tooltip-like explanations.

icewm is great, super-fast and convenient. It's almost a DE rather than a WM. It could be made a little bit more convenient though; ideally the user could modify everything without having to modify text files.

**Comment by cheapy** [comment]
In antiX there is a script that sets the DPI of the screen called set-dpi.  Another possibility would be to use a screen resolution more to your liking by running a program called arandr, or xrandr if arandr isn't available.

**Comment by gijsbers** [comment]
Ne Hercules quidem adversus duos.
