### ISSUE TITLE
Translation reference

### ISSUE THREAD

**Issue by GreenLunar** [bbidulock/icewm#77]
Please add reference to where contributors can translate IceWM.  I did not see IceWM at https://hosted.weblate.org/ nor did I find a reference to the Weblate instance with which IceWM is being translated.

There is an Hebrew translation available at https://sourceforge.net/p/icewm/mailman/message/30447527/

**Comment by bbidulock** [comment]
Added in commit 9a6d374e6d4a6db977e799a0b9807d99d42be377

Unfortunately, it is not very complete, but maybe someone will update it.

With regard to weblate, you can still submit po files, patches to po files, or pull requests on po files directly.

You will find icewm weblate at https://l10n.opensuse.org/

**Comment by GreenLunar** [comment]
I am not able to register.  I have sent over 60 suggestions in Hebrew translation.

**Comment by bbidulock** [comment]
You can use poedit tool and give me a link to resulting he.po file or generate pull request if that would work better.

**Comment by GreenLunar** [comment]
I should have notify you before I have made the suggestions at the Weblate instance, which I have not saved.  Please accept all suggestions of Hebrew translation, and I will continue by pull requests.

**Comment by bbidulock** [comment]
I couldn't really figure out how to use weblate to commit the suggestions!

**Comment by GreenLunar** [comment]
Just accept the suggestions, one by one.  I will try again to register an account.

**Comment by bbidulock** [comment]
I didn't see an accept button!

**Comment by GreenLunar** [comment]
You should see it under each string that received a suggestion.  Try to reach these entries by pressing the blue bar (strings with suggestions).

**Comment by GreenLunar** [comment]
I am failing to send a feedback from form https://www2.suse.com/nl-nl/common/inc/feedback_overlay.html

**Feedback over URL:** https://www.suse.com/selfreg/jsp/createAccount.jsp
**Op- en aanmerkingen *:** Unable to register an account https://www.suse.com/selfreg/jsp/createAccount.jsp for translating at https://l10n.opensuse.org/projects/icewm/icewm-1-3-branch/he/
**E-mailadres (als u een antwoord wilt ontvangen):** email@address
**E-mailadres bevestigen:** email@address

@opensuse-i18n @openSUSE @SUSE please help us.

**Comment by stanislav-brabec** [comment]
I am an admin of http://l10n.opensuse.org/ . I just approved all your suggestions except one, where two different suggestions exist.

However the registration server is not maintained by me, but by a Microfocus infrastructure team. I just sent your issue to our helpdesk.

Here is what I am seeing:
- Click Register in http://l10n.opensuse.org/
- After few redirects, I got into https://login.microfocus.com/nidp/idff/sso?id=6&sid=2&option=credential&sid=2&target=https://esp.microfocus.com/LAGBroker?%22https://www.opensuse.org/openid/secureprovider%22
- Clicked Create Account
- Got into https://www.suse.com/selfreg/jsp/createAccount.jsp?target=https://www.opensuse.org/openid/secureprovider
- Now I am on a page, where I should create the account.
- Did not test to enter some data and click Create Login.

Are you experiencing the same in https://bugzilla.opensuse.org/ ?

When you will succeed, you can authorize your translation by:
Go to the last suggestion. Pick the incorrect one and click Edit. Then Save. Reject the remaining one. You will become Last Translator, as long as somebody else makes an edit.

**Comment by bbidulock** [comment]
Can this be closed now?

**Comment by stanislav-brabec** [comment]
Just a hint: I never experienced this in Weblate, but sometimes similar problem appears in Bugzilla, when cookies and server status go out of sync. When it happens, removal of cookies helps. (In this case it the broken cookie be *.opensuse.org, *.novell.com and *.microfocus.com.)
