### ISSUE TITLE
Need a little help

### ISSUE THREAD

**Issue by frankzen** [bbidulock/icewm#770]
Can someone tell me which parts of the preferences file control  the background and text colors of the box that the "About" item pops up? I am using a theme which has bizarre color selections for that box.

Thanks

**Comment by gijsbers** [comment]
What theme? Screenshot of the problem?

**Comment by frankzen** [comment]
The theme under Debian Trixie is Ark-Dark.
![Screenshot from 2024-03-28 14-18-36](https://github.com/bbidulock/icewm/assets/717662/8801bf6a-5835-466e-82ae-3f4b5c82d679)

**Comment by gijsbers** [comment]
```
ColorDialog="#b4b2b4"
ColorLabel="#b4b2b4"
ColorLabelText="#000000"
```

How do you get the Ark-Dark theme? I can't find it.

**Comment by frankzen** [comment]
This is the original theme: https://github.com/Aethusx/icewm-arc-dark
I then found a "fixed" version: https://github.com/Brottweiler/Arc-Dark
Your additions fixed the version I had (the original).

Thanks
