### ISSUE TITLE
Certain window items are unclickable on Firefox under IceWM

### ISSUE THREAD

**Issue by dagelf** [bbidulock/icewm#771]
Easily reproducable. Just watch any video on Firefox and try to click the window pop-out floater (or whatever they call it). Doesn't work half the time. Works after minimization and restoral, the first time, every time, and randomly other times. I have no idea yet where to start looking, or what could cause this. 

I didn't know that this could be caused by the Window Manager - and judging by some of these issues, it's not just IceWM: https://bugzilla.mozilla.org/buglist.cgi?quicksearch=can%27t+click - I'm sure because this never happens on any other window manager that I've used. I keep coming back to IceWM for its insane snappiness, and I've just discovered the command line automation tools. Anyways huge thanks to everyone who built and are maintaining IceWM!!!

**Comment by dagelf** [comment]
Sorry, I'm a fool. Obviously using the Debian packaged version from Ubuntu here. Can't remember if this ever happened if I compiled from source. Let me see if I can update the Debian package...

**Comment by dagelf** [comment]
In case its still present in the latest version, a note to self to search https://github.com/search?q=org%3Amozilla+_NET_WM_&type=code

**Comment by dagelf** [comment]
Unsurprisingly, new version hasn't done this yet. Bad version still in Debian/Ubuntu is `icewm          2.9.6-1 `

**Comment by gijsbers** [comment]
The issues here are not to be used as a blog about attempts to produce an issue. Next time think first, do your examinations in private and reach a level of actuality, certainty and conciseness before you ask others to wake up and spend valuable time reading whatever your fingers produce on the keyboard. Thanks so much.
