### ISSUE TITLE
lxterminal, xterm windows sporadically flash on task bar without reason

### ISSUE THREAD

**Issue by JanD1234** [bbidulock/icewm#772]
Hello.

I'm observing strange behavior of icewm and at least 2 terminals emulator I'm using - lxterminal and xterm. Sporadically it happens, that terminal windows start to flash on task bar every time the focus is changed from or to terminal window. The only way, how put the terminal window back to normal state is to use 'icesh urgent' command on the terminal window. This command, after initial flash, clears urgent flag from the window and it behaves normally afterwards.
I'm aware about this issue for some time, but I was not able to reproduce it reliably. Today I accidentally found out, that issue happens always, when I restart icewm with terminal windows opened. Download following recording for more information:
https://mail.upjs.sk/20240423_212449.mp4

Also terminals from other virtual desktop appears on task bar and flash after the restart. I set icewm to only show windows from the current virtual desktop on the task bar. This led me to believe, that the urgent flag is set for these windows.

icewm version: icewm-3.4.7
terminal emulators: lxterminal-0.4.0-bp154.1.86, xterm-330-150200.11.12.1
OS: OpenSuSE Leap 15.4
How to reproduce: see video in the link or description above
Note: I'm using focus follow mouse mode.

**Comment by gijsbers** [comment]
The video doesn't show properly. Can you make a screencast?

What focus model do you use? Does it work with Quiet Sloppy?

This is with `TaskBarShowAllWindows=1`? Can you try with the default preferences?

**Comment by JanD1234** [comment]
Hello.

TaksBarShowAllWindows has default value 0.
Below is the preferences file I use. Let me know, what you want to change for retest.

ManualPlacement=1
UseMouseWheel=1
Win95Keys = 0
ModSuperIsCtrlAlt = 0
ClickToFocus = 0
FocusOnAppRaise = 1
RequestFocusOnAppRaise = 1
RaiseOnFocus = 1
RaiseOnClickClient = 1
PassFirstClickToClient = 0 # 0/1
FocusChangesWorkspace = 1
FocusOnMap = 1
FocusOnMapTransient = 1
FocusOnMapTransientActive = 1
MapInactiveOnTop = 1
PointerFocusDelay = 500
AutoRaiseDelay = 400
FocusRequestFlashTime=10 # [0-86400]

TaskBarAutoHide = 0
TaskBarShowMailboxStatus = 0
TimeFormat = "%a %d %b %R"
TaskBarShowCPUStatus = 0
TaskBarShowNetStatus = 0
TaskBarShowMEMStatus = 0

TerminalCommand = xterm.moj
LockCommand='xlock -nice 19 -mode blank'
ClockCommand = 'xclock -digital -padding 2 -twentyfour -strftime "%a %d %b %Y %H:%M" -face "*-8"'
SuspendCommand= 'test -e /run/systemd/system && syssuspend || loginctl suspend'
HibernateCommand= 'test -e /run/systemd/system && syshibernate || loginctl hibernate'

In addition, the focus_mode file:
#Focus mode (0=custom, 1=click, 2=sloppy, 3=explicit, 4=strict, 5=quiet)

FocusMode=0
#FocusMode=2
#FocusMode=0
#FocusMode=2
#FocusMode=0
#FocusMode=2

**Comment by gijsbers** [comment]
Using all your settings, I can't reproduce it! Nothing ever flashes...

You can set the `ignoreUrgentHint` winoption for xterm and lxterminal.

**Comment by JanD1234** [comment]
Hello.

It is strange. But you can see on video, that it is happening. And for me, every time when I restart icewm.

I added 
lxterminal.Lxterminal.ignoreUrgentHint: 1

to the winoptions file in ~/.icewm and restarted icewm, but no change. The same behavior as before. I tried also icesh winoptions, but the same result.

Update: There is a change. Now I cannot use icesh urgent command to stop flashing. I'm going to revert this option back, as it makes issue worse. :(

**Comment by JanD1234** [comment]
I can create MS Teams meeting for debugging the issue if you give me e-mail address to invite.

**Comment by gijsbers** [comment]
Try `icesh restore` instead of `icesh urgent`. The former turns it off, the latter on.

Check `FocusRequestFlashInterval` and `FocusRequestFlashTime`.
`icewm -p | grep RequestFlash`. Set the latter to 0.

Run `xprop WM_HINTS` on the window that flashes.

**Comment by gijsbers** [comment]
Also set `FocusOnAppRaise = 0`.

**Comment by JanD1234** [comment]
Hello.

The FlashTime is set 10 seconds as you can see from the preferences file I shared.
The FlashInterval is 250.

I set FlashTime to zero and result is that flashing is now indefinite and cannot be stopped with icesh restore|urgent.

> xprop WM_HINTS
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x1a00007
		bitmap id # of mask for icon: 0x1a00012
		window id # of group leader: 0x1a00001
		The urgency hint bit is set

icesh restore cannot stop flashing, only urgent works.

**Comment by JanD1234** [comment]
With FocusOnAppRaise=0 no change.

**Comment by gijsbers** [comment]
Can you start from the default configuration?
If you use `~/.icewm`, then just rename it to `~/icewm-backup`.

**Comment by gijsbers** [comment]
> The urgency hint bit is set

What sets that bit?

**Comment by JanD1234** [comment]
This is good question. These terminals are open for approximately 2-3 days. I just tried to open the new one and it is without urgency bit set. And also does not flash after icewm restart. This is reason, why you cannot reproduce the issue.

So the question is how it happened, that these 3 terminals have this bit set? And how to clear it?

So it looks, that flashing after restart is only secondary reaction. The root cause is somewhere else.

**Comment by JanD1234** [comment]
And why only terminals? Why I have not observed this with firefox, thunderbird or pavucontrol, which are permanently running on my desktop?

**Comment by JanD1234** [comment]
Maybe I have an idea. Lxterminal has an option for visual bell. This is used in case, that PC does not have beeper. With lxterminal, the visual bell is translated to flashing of icon in task bar. Here is a proof. The new lxterminal window:
> xprop WM_HINTS
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x1a59a2e
		bitmap id # of mask for icon: 0x1a59a34
		window id # of group leader: 0x1a00001

The same lxterminal window, after visual bell was used:
> xprop WM_HINTS
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x1a59a2e
		bitmap id # of mask for icon: 0x1a59a34
		window id # of group leader: 0x1a00001
		The urgency hint bit is set

So it looks, that urgency flag is not cleared after it is used for visual bell. Is clearing of urgent flag responsibility of WM or application?

**Comment by gijsbers** [comment]
It is the responsibility of the application according to section 4.1.2.4 of http://www.x.org/docs/ICCCM/icccm.pdf:
`Clients must provide some means by which the user can cause the UrgencyHint flag to be set to zero or the window to be withdrawn. The user’s action can either mitigate the actual condition that made the window urgent, or it can merely shut off the alarm.`

**Comment by gijsbers** [comment]
Lxterminal never turns the urgency flag off. That is clearly a bug in lxterminal.

**Comment by gijsbers** [comment]
Changes 2dadb9b3388078c6c38a0d2968d615f9a6e20948 and f59682cc732c4060811175c9191b11e36e4cc3d4 let icesh and icewm increase control of the urgency flag.

**Comment by JanD1234** [comment]
Hello.

I can confirm, that after applying patches, icesh urgent and restore commands clear urgency hint.
After the visual bell is used in lxterminal window, the urgency hint stays set on this window.
After restart of the icewm, the urgency bit is cleared from the lxterminals after they flash.

**Comment by gijsbers** [comment]
The question now is, is this a desirable feature or not? Nowhere in the ICCCM spec does it say that a WM should clear this flag. Lxterminal may be the only application which has this bug. If you want all WMs to support this erratic behavior, you have to inform all [367 WMs out there](https://www.gilesorr.com/wm/table.html) and update the spec. We may just as well remove this new code from IceWM and let lxterminal users suffer a bit until they report the bug to the lxterminal developers.

**Comment by JanD1234** [comment]
Hello.

I have created a ticket for lxterminal. Let us wait for lxde developers reaction.
https://sourceforge.net/p/lxde/bugs/969/

**Comment by gijsbers** [comment]
Thanks! Urxvt has this cool option, which is spot on!

```
   urgentOnBell: boolean
       True: set the urgency hint for the wm on receipt of a bell
       character.  False: do not set the urgency hint [default].

       urxvt resets the urgency hint on every focus change.
```

Sakura and XTerm also work correctly. So does xfce4-terminal.

**Comment by JanD1234** [comment]
I tried Sakura, it works in the same way as lxterminal.
New Sakura window:
> xprop WM_HINTS
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		window id # of group leader: 0x1200001

The same window after visual bell (called urgency bell in Sakura):
> xprop WM_HINTS
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		window id # of group leader: 0x1200001
		The urgency hint bit is set

It does not help, when I change focus, the urgency hint is still active.

And after icewm restart, also the Sakura icon blinks, until icewm clears the urgency hint.

**Comment by gijsbers** [comment]
What version of sakura is that?
My tests went fine and the source code of sakura looks good too.

**Comment by JanD1234** [comment]
This one:

Information for package sakura:
-------------------------------
Repository     : openSUSE-Leap-15.4-1
Name           : sakura
Version        : 3.8.2-bp154.1.77
Arch           : x86_64
