### ISSUE TITLE
Graphical applications cannot be started after changing the hostname

### ISSUE THREAD

**Issue by alexanderzhirov** [bbidulock/icewm#773]
After the `hostname` has been changed in the running `icewm-session`, the applications refuse to start. The following messages appear in the logs:

```
Authorization required, but no authorization protocol specified
xterm: Xt error: Can't open display: :0
Authorization required, but no authorization protocol specified
qt.qpa.xcb: could not connect to display :0
```

Works after the icewm session is restarted.

GUI windows do not open after calling `hostnamectl set-hostname <name>`.

**Comment by gijsbers** [comment]
Icewm doesn't concern itself with authorization. That is the responsibility of the X11 server, which we don't do. Icewm is an application itself.

Please don't submit the same issue twice!

**Comment by alexanderzhirov** [comment]
@gijsbers If this is not an icewm problem, then what could it be related to? It is strange that changing the hostname affects the operation of the icewm session.
