### ISSUE TITLE
Dragging on titlebars on GTK4 apps makes PC unresponsive

### ISSUE THREAD

**Issue by MANICX100** [bbidulock/icewm#778]
Launch any GTK4 app
Hold down mouse and drag on the title bar
PC now unresponsive

### Current behaviour
PC becomes unresponsive beyond rapid right clicking or hover effects

I have reported this to GTK devs but they say its an issue with Icewm

**Comment by gijsbers** [comment]
What are GTK4 apps? I never used them before.
If they say it is icewm, then they must be able to give a reason, which would help a lot.

**Comment by gijsbers** [comment]
The only app on my system which links to libgtk-4 is gnome-chess and it doesn't exhibit any erratic behavior when I drag it on the title bar, hence your assumption has been proven wrong.

**Comment by gijsbers** [comment]
I compiled the GTK4 example from https://docs.gtk.org/gtk4/getting_started.html and dragging the title bar works flawlessly. What are you doing wrong? Apart from writing an issue which is lacking all kinds of required information?

**Comment by MANICX100** [comment]
That is surprising, For further info here is my GTK bug report:

[Gitlab report](https://gitlab.gnome.org/GNOME/gtk/-/issues/6779
)

I can replicate the behaviour in for instance:
[Fotema](https://flathub.org/apps/app.fotema.Fotema)

I am running Ubuntu 24.04 with Icewm 3.5.1 compiled from the source repo

**Comment by gijsbers** [comment]
What do you mean exactly in detail when you say `lock up`?

Can you switch workspaces?
Can you open menu's?
Can you click on the taskbar buttons / icons / workspaces?

Are there GTK4 applications that work fine?
You gave only one example application, but I want a dozen, preferably which are on the Ubuntu distribution.

The video is unclear. Can you give a step by step recipe?

**Comment by MANICX100** [comment]
Can you switch workspaces?
I can load another tty and then pkill icewm which is what I do when I forget this is a thing.

Can you open menu's?
No, although I can open menus on the titlebar until the bug is triggered

Can you click on the taskbar buttons / icons / workspaces?
No, although I can use icons on the titlebar until the bug is triggered

Other Example Applications
Decibels
Flatseal
Warehouse

**Comment by MANICX100** [comment]
If you move mouse to the top of the window and then hold down the left mouse button to drag the window you will encounter the bug.

**Comment by gijsbers** [comment]
I was able to reproduce this bug in Ubuntu 24.04. An icewm event log shows the following:

```
41.995: IceWM: window=0x1600004: ClientMessage _NET_WM_STATE 32 data=REMOVE,_NET_WM_STATE_HIDDEN,
41.997: IceWM: window=0x1600004: ClientMessage _NET_WM_STATE 32 data=REMOVE,_NET_WM_STATE_FULLSCREEN,
41.998: IceWM: window=0x1600004: ClientMessage _NET_WM_MOVERESIZE fmt=32 data=1519,0x1D,0x8
42.002: IceWM: window=0x1600004: ClientMessage _NET_WM_STATE 32 data=REMOVE,_NET_WM_STATE_HIDDEN,
42.028: IceWM: window=0x1600004: ClientMessage _NET_WM_STATE 32 data=REMOVE,_NET_WM_STATE_FULLSCREEN,
42.028: IceWM: window=0x1600004: ClientMessage _NET_WM_MOVERESIZE fmt=32 data=1519,0x1D,0x8
```

Time is in seconds with millisecond resolution. When I try to move the application window, GTK-4 issues two _NET_WM_MOVERESIZE requests within 30 milliseconds where one is enough. Icewm chokes on the second request. Commit 90439526 fixes this.

**Comment by gijsbers** [comment]
Notable also is that GTK-4 requests to remove the HIDDEN flag and the FULLSCREEN flag from _NET_WM_STATE, even though the application wasn't HIDDEN and wasn't FULLSCREEN. This superfluous request is also repeated.

**Comment by MANICX100** [comment]
Thank you so much. It is fixed
