### ISSUE TITLE
Remember window order on restarts

### ISSUE THREAD

**Issue by plomari** [bbidulock/icewm#782]
When I click the "Restart Icewm" menu item, windows mostly keep their position and workspace, but the order on the taskbar is shuffled.
Would it be possible to keep the order in the taskbar as well across restarts?

**Comment by plomari** [comment]
Alternatively: maybe there's a better way to reload the configuration for often-changed config files like winoptions?

**Comment by gijsbers** [comment]
You have a bit of a habit to ask questions which (1) have been answered before in this forum or (2) which you can easily lookup in the manpages yourself.
