### ISSUE TITLE
Icesh exit status 1 on manager  actions 

### ISSUE THREAD

**Issue by Vrihub** [bbidulock/icewm#789]
Looks like icesh exits with status 1 on "manager" actions (I haven't tested them all).

Expected result: it should exit with 1 only on _unsuccessful_ (window or manager) actions, and with 0 on successful ones.

Not a big deal but it could break shell scripts using icesh.

**Comment by gijsbers** [comment]
You didn't provide a concrete reproducable scenario. Also unclear is the version.

**Comment by Vrihub** [comment]
> You didn't provide a concrete reproducable scenario. Also unclear is the version.

Version 3.3.1.

To reproduce: run some of the icesh commands listed under MANAGER ACTIONS in the icesh manual page that do not involve windows and check the exit status.
e.g. `icesh keys` exits with 1 even if the keys file is reloaded successfully.

Interestingly, the few manager actions that involve windows (e.g. `icesh windows`) exit with 0 or 1 depending on the command result (e.g. if window are listed in the output).

It seems that currently the exit status of all icesh commands only depends on the fact that any windows are produced the command output. The problem is that most  MANAGER ACTIONS don't involve windows at all, so they always exit with 1 even when they run successfully (and one would expect a 0 exit status).

**Comment by gijsbers** [comment]
Thanks! I asked because in 3.6.0 `icesh about` exits with `0`. Thanks for providing the version number. I can now verify that you are correct. It must have been fixed sometime ago.

I urge everyone to always provide the version number as this would save a lot of time! Also provide a `concrete` example.

**Comment by gijsbers** [comment]
It was fixed by commit a7f12c37.

**Comment by Vrihub** [comment]
Ok sorry, unfortunately I couldn't try the latest release on my system and I searched only in the github issues page, not the whole repository.

So I'm going to close this "bug" (the best kind of bugs, already fixed bugs).
