### ISSUE TITLE
Conky crashes when used in startup file.

### ISSUE THREAD

**Issue by SolisX** [bbidulock/icewm#79]
Hello Bbidulock,

Hey conky crashes when i use it in the startup file when i right click over conky.

conky -c /opt/conky/conkytheme &

X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  25 (X_SendEvent)
  Resource id in failed request:  0xe00001
  Serial number of failed request:  4335
  Current serial number in output stream:  4338

**Comment by bbidulock** [comment]
Don't know how this is icewm's problem.  Try running conky with and without its own window (in configuration file).
