### ISSUE TITLE
broken localisation

### ISSUE THREAD

**Issue by ivan1986** [bbidulock/icewm#8]
in last version show only english texts - some happens whis translations
in https://packages.qa.debian.org/i/icewm.html - correct
in clean build - only eng

**Comment by bbidulock** [comment]
i18n turned back on by default in configure.  This should fix it.  I get French in menus and diagnostic messages when I run LANG=fr_FR.UTF-8 icewm.   The .po files for your languages probably need some updating, I would appreciate if you could provide updated translations for a language or two.

**Comment by ivan1986** [comment]
yes commit 04dc06efa3699c90f88c37f7290eb6ebe16bc730 also fix locales

**Comment by bbidulock** [comment]
Well, I think this is closed then...
