### ISSUE TITLE
Can't bind XF86Tools

### ISSUE THREAD

**Issue by melobiy** [bbidulock/icewm#83]
Can't bind XF86Tools key (keysym 0x1008ff81).

IceWM 1.3.8, Debian.

**Comment by bbidulock** [comment]
Not really an error, is it?  Just telling you that your keyboard does not support that key...

**Comment by melobiy** [comment]
Other keys work fine (like XF86Launch6, etc).

xev output:
KeyRelease event, serial 41, synthetic NO, window 0x2800001,
    root 0x255, subw 0x0, time 2629021542, (62,-11), root:(848,677),
    state 0x0, keycode 191 (keysym 0x1008ff81, XF86Tools), same_screen YES,
    XKeysymToKeycode returns keycode: 179
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

In xbindkeys doesn't work too.
Yeah. The problem lies somewhere else.
I'm sorry to trouble you.
