### ISSUE TITLE
Missing xpm when using double height.

### ISSUE THREAD

**Issue by SolisX** [bbidulock/icewm#87]
Hello Bbidulock,

Hey i noticed that if i am using double height and have the taskbarbg.xpm as a gradient in
the default.theme when i use double height the top bar does not use the taskbarbg.xpm.

Tested with my illuminate icewm theme found here.
https://www.box-look.org/p/1018158/

**Comment by gijsbers** [comment]
Seems to work fine for me. Is this still a problem for you? Could you post a screendump?

**Comment by SolisX** [comment]
I removed the taskbarbg.xpm from the gradients section on the theme so if you download it
it looks fine. However if you add taskbarbg.xpm to the gradients section it will look like the
Bad Taskbar screenshot.

Bad Taskbar
https://postimg.org/image/m0pl279i7/
Good Taskbar
https://postimg.org/image/qd38qzxrz/

**Comment by gijsbers** [comment]
That is very helpful! What version do you use? (icewm -V) Github clone or a release?

**Comment by SolisX** [comment]
Hello Gijsbers,

I believe it was from the git clone icewm 1.3.12. However i compiled the current icewm git clone. It does seems to fix this issue but there is another issue. I will make a issue for that one.
