### ISSUE TITLE
Should use g_type_init() in src/yimage_gdk.cc

### ISSUE THREAD

**Issue by roms2000** [bbidulock/icewm#93]
If I compile and use IceWM with Thinstation (glib v2.23), IceWM does not launch.
Error is : GLib-GObject-CRITICAL *\* gtype.c 2720: You forgot to call g_type_init()

If we add g_type_init() to function image_init() in src/yimage_gdk.cc : 
`void image_init() {`
`g_type_init();`
`xlib_rgb_init(xapp->display(), ScreenOfDisplay(xapp->display(), xapp->screen()));`
`gdk_pixbuf_xlib_init(xapp->display(), xapp->screen());`
`}`

Everything is Ok and IceWM is running.
See [RedHat Bug 1031459 and comment #14](https://bugzilla.redhat.com/show_bug.cgi?id=1031459#c14) may help.

Any way, function  image_init() could be like this :
`void image_init() {`
`#if (GLIB_MAJOR_VERSION <= 2 && GLIB_MINOR_VERSION < 36 && GLIB_MICRO_VERSION <= 0)`
`g_type_init();`
`#endif`
`xlib_rgb_init(xapp->display(), ScreenOfDisplay(xapp->display(), xapp->screen()));`
`gdk_pixbuf_xlib_init(xapp->display(), xapp->screen());`
`}`

This help using IceWM with older version of glib and may be run older platform too.

**Comment by bbidulock** [comment]
Thank you!
