### ISSUE TITLE
gentoo: 1.3.11..GIT startup hangout

### ISSUE THREAD

**Issue by vpil** [bbidulock/icewm#96]
Hi everybody,

I was running successfully all your main versions up to 1.3.12 on Gentoo 64bit (mostly stable packages) without problems. After recent system-wide package upgrade, icewm freezes during startup: Just black screen with cursor, X process is highly loaded and Xorg.0.log is being filled with infinite repeating of EDID detections:
```
  2619.077] (II) RADEON(0): EDID vendor "GSM", prod id 30186
[  2619.077] (II) RADEON(0): Printing DDC gathered Modelines:
[  2619.077] (II) RADEON(0): Modeline "1280x800"x0.0   71.00  1280 1328 1360 1440  800 803 809 823 +hsync -vsync (49.3 kHz e)
[  2619.077] (II) RADEON(0): Modeline "2560x1600"x0.0  268.00  2560 2608 2640 2720  1600 1603 1609 1646 +hsync -vsync (98.5 kHz e)
[  2619.337] (II) RADEON(0): EDID vendor "GSM", prod id 30186
[  2619.337] (II) RADEON(0): Printing DDC gathered Modelines:
[  2619.337] (II) RADEON(0): Modeline "1280x800"x0.0   71.00  1280 1328 1360 1440  800 803 809 823 +hsync -vsync (49.3 kHz e)
[  2619.337] (II) RADEON(0): Modeline "2560x1600"x0.0  268.00  2560 2608 2640 2720  1600 1603 1609 1646 +hsync -vsync (98.5 kHz e)
[  2619.607] (II) RADEON(0): EDID vendor "GSM", prod id 30186
[  2619.607] (II) RADEON(0): Printing DDC gathered Modelines:
[  2619.607] (II) RADEON(0): Modeline "1280x800"x0.0   71.00  1280 1328 1360 1440  800 803 809 823 +hsync -vsync (49.3 kHz e)
[  2619.607] (II) RADEON(0): Modeline "2560x1600"x0.0  268.00  2560 2608 2640 2720  1600 1603 1609 1646 +hsync -vsync (98.5 kHz e)
```
So I tried downgrade to 1.3.11, upgrade to latest GIT sources or even latest kernel 3.9.0. Nothing helped. Then I downgraded to older 1.3.8 and it works normally.

Any ideas? What else should I test? Thank you.

**Comment by bbidulock** [comment]
Can't help you: not running Gentoo; running Arch.  Sounds like the radeon driver's fault.  Recent versions of icewm use proper Xrandr and Xinerama calls whereas older versions did not.  That's the only clue I can give you.

**Comment by bbidulock** [comment]
Did you reboot the box after the upgrade?

**Comment by vpil** [comment]
I tested xf86-video-ati-7.7.0 (stable) and xf86-video-ati-7.8.0 (latest). No change. Indeed, I rebooted many times (kernel change...). The strange is, latest icewm is the only found sw with this bug. I tested other WM, or startx with direct X app execution and everything else works.

**Comment by vpil** [comment]
I tried to compile 1.3.12 without xinerama support and to downgrade libXrandr from 1.5.1 to 1.5.0 (from the time icewm worked)... and no change :-(

**Comment by bbidulock** [comment]
I run under xf86-video-intel and have no problems.

**Comment by Cynede** [comment]
@vpil strange, same version works fine for me on Gentoo

**Comment by bbidulock** [comment]
@vpil  Can we close this now?

**Comment by vpil** [comment]
Indeed, as you wish. Thanks for all ideas, hopefully I will find the reason for my trouble some day.
