### ISSUE TITLE
unclosable black window periodically appears and eat tray icons

### ISSUE THREAD

**Issue by Cynede** [bbidulock/icewm#97]
version 1.3.12, gentoo amd64

can 100% reproduce running steam, or clicking on transmission tray icon

I don't have `.icewm/startup`

If I will add
`
xscreensaver -nosplash &
xscreensaver-command --lock
`

to `.icewm/startup` then I will get lock screen when I previously had black window, after unlocking I will still have this black window.

preferences: https://github.com/Heather/home/blob/home/.icewm/preferences

**Comment by gijsbers** [comment]
Could you maybe add a screendump of what it looks like?
To make a screendump while icem is running put something like this in your .icewm/keys:
key "Print"      xv -startgrab
If you go to a console (like with Ctrl+Alt F1) and do a process listing can you spot any suspicious processes which may produce a black window?

**Comment by Cynede** [comment]
sorry but for now I've switched wm and hardly will be able to provide feedback about that issue, so I'm closing it for now (have no time either)
