### ISSUE TITLE
compile fails on X86_64 linux 4.4.30

### ISSUE THREAD

**Issue by volumetricsteve** [bbidulock/icewm#99]
Should I expect this to compile as root?  I got the same error with a user level account too.

./genpref >preferences
make[2]: Leaving directory '/root/sources/icewm-icewm-1-3-BRANCH/src'
Making all in po
make[2]: Entering directory '/root/sources/icewm-icewm-1-3-BRANCH/po'
test ! -f ./icewm.pot || \
  test -z "ar.gmo be.gmo bg.gmo ca.gmo cs.gmo da.gmo de.gmo el.gmo en.gmo es.gmo fi.gmo fr.gmo he.gmo hr.gmo hu.gmo id.gmo it.gmo ja.gmo ko.gmo lt.gmo lv.gmo mk.gmo nb.gmo nl.gmo no.gmo pl.gmo pt_BR.gmo ro.gmo ru.gmo sk.gmo sl.gmo sv.gmo tr.gmo uk.gmo vi.gmo zh_CN.gmo zh_TW.gmo" || make ar.gmo be.gmo bg.gmo ca.gmo cs.gmo da.gmo de.gmo el.gmo en.gmo es.gmo fi.gmo fr.gmo he.gmo hr.gmo hu.gmo id.gmo it.gmo ja.gmo ko.gmo lt.gmo lv.gmo mk.gmo nb.gmo nl.gmo no.gmo pl.gmo pt_BR.gmo ro.gmo ru.gmo sk.gmo sl.gmo sv.gmo tr.gmo uk.gmo vi.gmo zh_CN.gmo zh_TW.gmo
make[3]: Entering directory '/root/sources/icewm-icewm-1-3-BRANCH/po'
make[3]: 'ar.gmo' is up to date.
make[3]: 'be.gmo' is up to date.
make[3]: 'bg.gmo' is up to date.
make[3]: 'ca.gmo' is up to date.
make[3]: 'cs.gmo' is up to date.
make[3]: 'da.gmo' is up to date.
make[3]: 'de.gmo' is up to date.
rm -f el.gmo && /usr/bin/msgfmt -c --statistics --verbose -o el.gmo el.po
el.po:317: 'msgstr' is not a valid C format string, unlike 'msgid'. Reason: In the directive number 2, the character ' ' is not a valid conversion specifier.
/usr/bin/msgfmt: found 1 fatal error
el.po: 206 translated messages, 46 fuzzy translations, 6 untranslated messages.
make[3]: *** [Makefile:280: el.gmo] Error 1
make[3]: Leaving directory '/root/sources/icewm-icewm-1-3-BRANCH/po'
make[2]: *** [Makefile:318: stamp-po] Error 2
make[2]: Leaving directory '/root/sources/icewm-icewm-1-3-BRANCH/po'
make[1]: *** [Makefile:573: all-recursive] Error 1
make[1]: Leaving directory '/root/sources/icewm-icewm-1-3-BRANCH'
make: *** [Makefile:455: all] Error 2

**Comment by bbidulock** [comment]
This is fixed.  Thank you for the bug report!

**Comment by volumetricsteve** [comment]
Fingers crossed!  I'll give it another try when I get home.  Thanks for your help.  Semi-related, I thought IceWM was c/c++ based, what does the python code do?

**Comment by bbidulock** [comment]
What python code?

**Comment by volumetricsteve** [comment]
Oh....huh, I saw "po" and thought "python object" and....I guess it means Polish.

**Comment by bbidulock** [comment]
No, po files are used to generate i18n message catalogs.

**Comment by volumetricsteve** [comment]
Wow, so I'm just...all the way off track!  Thanks for clearing that up.
